// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package operator

import (
	"context"

	"github.com/carson-networks/budget-server/internal/storage"
	mock "github.com/stretchr/testify/mock"
)

// NewMockIStorage creates a new instance of MockIStorage. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockIStorage(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockIStorage {
	if helper, ok := t.(interface{ Helper() }); ok {
		helper.Helper()
	}

	mock := &MockIStorage{}
	mock.Mock.Test(t)

	t.Cleanup(func() {
		if helper, ok := t.(interface{ Helper() }); ok {
			helper.Helper()
		}
		mock.AssertExpectations(t)
	})

	return mock
}

// MockIStorage is an autogenerated mock type for the IStorage type
type MockIStorage struct {
	mock.Mock
}

type MockIStorage_Expecter struct {
	mock *mock.Mock
}

func (_m *MockIStorage) EXPECT() *MockIStorage_Expecter {
	return &MockIStorage_Expecter{mock: &_m.Mock}
}

// Write provides a mock function for the type MockIStorage
func (_mock *MockIStorage) Write(ctx context.Context) (*storage.Writer, error) {
	ret := _mock.Called(ctx)

	if len(ret) == 0 {
		panic("no return value specified for Write")
	}

	var r0 *storage.Writer
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context) (*storage.Writer, error)); ok {
		return returnFunc(ctx)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context) *storage.Writer); ok {
		r0 = returnFunc(ctx)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*storage.Writer)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context) error); ok {
		r1 = returnFunc(ctx)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockIStorage_Write_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Write'
type MockIStorage_Write_Call struct {
	*mock.Call
}

// Write is a helper method to define mock.On call
//   - ctx context.Context
func (_e *MockIStorage_Expecter) Write(ctx any) *MockIStorage_Write_Call {
	return &MockIStorage_Write_Call{Call: _e.mock.On("Write", ctx)}
}

func (_c *MockIStorage_Write_Call) Run(run func(ctx context.Context)) *MockIStorage_Write_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockIStorage_Write_Call) Return(writer *storage.Writer, err error) *MockIStorage_Write_Call {
	_c.Call.Return(writer, err)
	return _c
}

func (_c *MockIStorage_Write_Call) RunAndReturn(run func(ctx context.Context) (*storage.Writer, error)) *MockIStorage_Write_Call {
	_c.Call.Return(run)
	return _c
}
