// Code generated by mockery v2.53.6. DO NOT EDIT.

package operator

import (
	context "context"

	storage "github.com/carson-networks/budget-server/internal/storage"
	mock "github.com/stretchr/testify/mock"
)

// MockIStorage is an autogenerated mock type for the IStorage type
type MockIStorage struct {
	mock.Mock
}

type MockIStorage_Expecter struct {
	mock *mock.Mock
}

func (_m *MockIStorage) EXPECT() *MockIStorage_Expecter {
	return &MockIStorage_Expecter{mock: &_m.Mock}
}

// Write provides a mock function with given fields: ctx
func (_m *MockIStorage) Write(ctx context.Context) (*storage.Writer, error) {
	ret := _m.Called(ctx)

	if len(ret) == 0 {
		panic("no return value specified for Write")
	}

	var r0 *storage.Writer
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context) (*storage.Writer, error)); ok {
		return rf(ctx)
	}
	if rf, ok := ret.Get(0).(func(context.Context) *storage.Writer); ok {
		r0 = rf(ctx)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*storage.Writer)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context) error); ok {
		r1 = rf(ctx)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockIStorage_Write_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Write'
type MockIStorage_Write_Call struct {
	*mock.Call
}

// Write is a helper method to define mock.On call
//   - ctx context.Context
func (_e *MockIStorage_Expecter) Write(ctx interface{}) *MockIStorage_Write_Call {
	return &MockIStorage_Write_Call{Call: _e.mock.On("Write", ctx)}
}

func (_c *MockIStorage_Write_Call) Run(run func(ctx context.Context)) *MockIStorage_Write_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context))
	})
	return _c
}

func (_c *MockIStorage_Write_Call) Return(_a0 *storage.Writer, _a1 error) *MockIStorage_Write_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockIStorage_Write_Call) RunAndReturn(run func(context.Context) (*storage.Writer, error)) *MockIStorage_Write_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockIStorage creates a new instance of MockIStorage. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockIStorage(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockIStorage {
	mock := &MockIStorage{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
