dir: "{{.InterfaceDir}}"
filename: "mock_{{.InterfaceName}}.go"
structname: "Mock{{.InterfaceName}}"
template: testify
template-data:
  unroll-variadic: true
packages:
  github.com/carson-networks/budget-server/internal/storage:
    interfaces:
      IAccountWriter:
      ITransactionWriter:
      ICategoryWriter:
      IBudgetWriter:
      IPlaidWriter:
      ISyncWriter:
  github.com/carson-networks/budget-server/internal/operator:
    interfaces:
      IStorage:
      IProcessor:
  github.com/carson-networks/budget-server/internal/operator/actions:
    interfaces:
      IAction:
  github.com/carson-networks/budget-server/internal/storage/account:
    interfaces:
      IAccountTable:
  github.com/carson-networks/budget-server/internal/storage/transaction:
    interfaces:
      ITransactionTable:
