with-expecter: true
filename: "mock_{{.InterfaceName}}.go"
mockname: "Mock{{.InterfaceName}}"
inpackage: true
dir: "{{.InterfaceDir}}"
packages:
  github.com/carson-networks/budget-server/internal/storage:
    interfaces:
      IAccountWriter:
      ITransactionWriter:
  github.com/carson-networks/budget-server/internal/operator:
    interfaces:
      IStorage:
  github.com/carson-networks/budget-server/internal/operator/actions:
    interfaces:
      IAction:
