with-expecter: true
filename: "mock_{{.InterfaceName}}.go"
mockname: "Mock{{.InterfaceName}}"
inpackage: true
dir: "{{.InterfaceDir}}"
packages:
  github.com/carson-networks/budget-server/internal/storage/sqlconfig:
    interfaces:
      IAccountTable:
  github.com/carson-networks/budget-server/internal/storage/transaction:
    interfaces:
      ITransactionTable:
  github.com/carson-networks/budget-server/internal/storage:
    interfaces:
      TransactionStore:
