// Code generated by mockery v2.53.6. DO NOT EDIT.

package storage

import (
	context "context"

	transaction "github.com/carson-networks/budget-server/internal/storage/transaction"
	mock "github.com/stretchr/testify/mock"

	uuid "github.com/gofrs/uuid/v5"
)

// MockITransactionWriter is an autogenerated mock type for the ITransactionWriter type
type MockITransactionWriter struct {
	mock.Mock
}

type MockITransactionWriter_Expecter struct {
	mock *mock.Mock
}

func (_m *MockITransactionWriter) EXPECT() *MockITransactionWriter_Expecter {
	return &MockITransactionWriter_Expecter{mock: &_m.Mock}
}

// Insert provides a mock function with given fields: ctx, create
func (_m *MockITransactionWriter) Insert(ctx context.Context, create *transaction.TransactionCreate) (uuid.UUID, error) {
	ret := _m.Called(ctx, create)

	if len(ret) == 0 {
		panic("no return value specified for Insert")
	}

	var r0 uuid.UUID
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, *transaction.TransactionCreate) (uuid.UUID, error)); ok {
		return rf(ctx, create)
	}
	if rf, ok := ret.Get(0).(func(context.Context, *transaction.TransactionCreate) uuid.UUID); ok {
		r0 = rf(ctx, create)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(uuid.UUID)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, *transaction.TransactionCreate) error); ok {
		r1 = rf(ctx, create)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockITransactionWriter_Insert_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Insert'
type MockITransactionWriter_Insert_Call struct {
	*mock.Call
}

// Insert is a helper method to define mock.On call
//   - ctx context.Context
//   - create *transaction.TransactionCreate
func (_e *MockITransactionWriter_Expecter) Insert(ctx interface{}, create interface{}) *MockITransactionWriter_Insert_Call {
	return &MockITransactionWriter_Insert_Call{Call: _e.mock.On("Insert", ctx, create)}
}

func (_c *MockITransactionWriter_Insert_Call) Run(run func(ctx context.Context, create *transaction.TransactionCreate)) *MockITransactionWriter_Insert_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(*transaction.TransactionCreate))
	})
	return _c
}

func (_c *MockITransactionWriter_Insert_Call) Return(_a0 uuid.UUID, _a1 error) *MockITransactionWriter_Insert_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockITransactionWriter_Insert_Call) RunAndReturn(run func(context.Context, *transaction.TransactionCreate) (uuid.UUID, error)) *MockITransactionWriter_Insert_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockITransactionWriter creates a new instance of MockITransactionWriter. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockITransactionWriter(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockITransactionWriter {
	mock := &MockITransactionWriter{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
