// Code generated by mockery v2.53.6. DO NOT EDIT.

package storage

import (
	context "context"

	budget "github.com/carson-networks/budget-server/internal/storage/budget"

	mock "github.com/stretchr/testify/mock"

	time "time"

	uuid "github.com/gofrs/uuid/v5"
)

// MockIBudgetWriter is an autogenerated mock type for the IBudgetWriter type
type MockIBudgetWriter struct {
	mock.Mock
}

type MockIBudgetWriter_Expecter struct {
	mock *mock.Mock
}

func (_m *MockIBudgetWriter) EXPECT() *MockIBudgetWriter_Expecter {
	return &MockIBudgetWriter_Expecter{mock: &_m.Mock}
}

// DeleteByCategoryAndMonthsAfter provides a mock function with given fields: ctx, categoryID, month
func (_m *MockIBudgetWriter) DeleteByCategoryAndMonthsAfter(ctx context.Context, categoryID uuid.UUID, month time.Time) error {
	ret := _m.Called(ctx, categoryID, month)

	if len(ret) == 0 {
		panic("no return value specified for DeleteByCategoryAndMonthsAfter")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID, time.Time) error); ok {
		r0 = rf(ctx, categoryID, month)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockIBudgetWriter_DeleteByCategoryAndMonthsAfter_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'DeleteByCategoryAndMonthsAfter'
type MockIBudgetWriter_DeleteByCategoryAndMonthsAfter_Call struct {
	*mock.Call
}

// DeleteByCategoryAndMonthsAfter is a helper method to define mock.On call
//   - ctx context.Context
//   - categoryID uuid.UUID
//   - month time.Time
func (_e *MockIBudgetWriter_Expecter) DeleteByCategoryAndMonthsAfter(ctx interface{}, categoryID interface{}, month interface{}) *MockIBudgetWriter_DeleteByCategoryAndMonthsAfter_Call {
	return &MockIBudgetWriter_DeleteByCategoryAndMonthsAfter_Call{Call: _e.mock.On("DeleteByCategoryAndMonthsAfter", ctx, categoryID, month)}
}

func (_c *MockIBudgetWriter_DeleteByCategoryAndMonthsAfter_Call) Run(run func(ctx context.Context, categoryID uuid.UUID, month time.Time)) *MockIBudgetWriter_DeleteByCategoryAndMonthsAfter_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(uuid.UUID), args[2].(time.Time))
	})
	return _c
}

func (_c *MockIBudgetWriter_DeleteByCategoryAndMonthsAfter_Call) Return(_a0 error) *MockIBudgetWriter_DeleteByCategoryAndMonthsAfter_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockIBudgetWriter_DeleteByCategoryAndMonthsAfter_Call) RunAndReturn(run func(context.Context, uuid.UUID, time.Time) error) *MockIBudgetWriter_DeleteByCategoryAndMonthsAfter_Call {
	_c.Call.Return(run)
	return _c
}

// Set provides a mock function with given fields: ctx, set
func (_m *MockIBudgetWriter) Set(ctx context.Context, set *budget.BudgetSet) error {
	ret := _m.Called(ctx, set)

	if len(ret) == 0 {
		panic("no return value specified for Set")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, *budget.BudgetSet) error); ok {
		r0 = rf(ctx, set)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockIBudgetWriter_Set_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Set'
type MockIBudgetWriter_Set_Call struct {
	*mock.Call
}

// Set is a helper method to define mock.On call
//   - ctx context.Context
//   - set *budget.BudgetSet
func (_e *MockIBudgetWriter_Expecter) Set(ctx interface{}, set interface{}) *MockIBudgetWriter_Set_Call {
	return &MockIBudgetWriter_Set_Call{Call: _e.mock.On("Set", ctx, set)}
}

func (_c *MockIBudgetWriter_Set_Call) Run(run func(ctx context.Context, set *budget.BudgetSet)) *MockIBudgetWriter_Set_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(*budget.BudgetSet))
	})
	return _c
}

func (_c *MockIBudgetWriter_Set_Call) Return(_a0 error) *MockIBudgetWriter_Set_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockIBudgetWriter_Set_Call) RunAndReturn(run func(context.Context, *budget.BudgetSet) error) *MockIBudgetWriter_Set_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockIBudgetWriter creates a new instance of MockIBudgetWriter. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockIBudgetWriter(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockIBudgetWriter {
	mock := &MockIBudgetWriter{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
