// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package storage

import (
	"context"

	"github.com/carson-networks/budget-server/internal/storage/category"
	"github.com/gofrs/uuid/v5"
	mock "github.com/stretchr/testify/mock"
)

// NewMockICategoryWriter creates a new instance of MockICategoryWriter. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockICategoryWriter(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockICategoryWriter {
	if helper, ok := t.(interface{ Helper() }); ok {
		helper.Helper()
	}

	mock := &MockICategoryWriter{}
	mock.Mock.Test(t)

	t.Cleanup(func() {
		if helper, ok := t.(interface{ Helper() }); ok {
			helper.Helper()
		}
		mock.AssertExpectations(t)
	})

	return mock
}

// MockICategoryWriter is an autogenerated mock type for the ICategoryWriter type
type MockICategoryWriter struct {
	mock.Mock
}

type MockICategoryWriter_Expecter struct {
	mock *mock.Mock
}

func (_m *MockICategoryWriter) EXPECT() *MockICategoryWriter_Expecter {
	return &MockICategoryWriter_Expecter{mock: &_m.Mock}
}

// Create provides a mock function for the type MockICategoryWriter
func (_mock *MockICategoryWriter) Create(ctx context.Context, create *category.CategoryCreate) error {
	ret := _mock.Called(ctx, create)

	if len(ret) == 0 {
		panic("no return value specified for Create")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, *category.CategoryCreate) error); ok {
		r0 = returnFunc(ctx, create)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockICategoryWriter_Create_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Create'
type MockICategoryWriter_Create_Call struct {
	*mock.Call
}

// Create is a helper method to define mock.On call
//   - ctx context.Context
//   - create *category.CategoryCreate
func (_e *MockICategoryWriter_Expecter) Create(ctx any, create any) *MockICategoryWriter_Create_Call {
	return &MockICategoryWriter_Create_Call{Call: _e.mock.On("Create", ctx, create)}
}

func (_c *MockICategoryWriter_Create_Call) Run(run func(ctx context.Context, create *category.CategoryCreate)) *MockICategoryWriter_Create_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 *category.CategoryCreate
		if args[1] != nil {
			arg1 = args[1].(*category.CategoryCreate)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockICategoryWriter_Create_Call) Return(err error) *MockICategoryWriter_Create_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockICategoryWriter_Create_Call) RunAndReturn(run func(ctx context.Context, create *category.CategoryCreate) error) *MockICategoryWriter_Create_Call {
	_c.Call.Return(run)
	return _c
}

// GetByID provides a mock function for the type MockICategoryWriter
func (_mock *MockICategoryWriter) GetByID(ctx context.Context, id uuid.UUID) (*category.Category, error) {
	ret := _mock.Called(ctx, id)

	if len(ret) == 0 {
		panic("no return value specified for GetByID")
	}

	var r0 *category.Category
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, uuid.UUID) (*category.Category, error)); ok {
		return returnFunc(ctx, id)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, uuid.UUID) *category.Category); ok {
		r0 = returnFunc(ctx, id)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*category.Category)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, uuid.UUID) error); ok {
		r1 = returnFunc(ctx, id)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockICategoryWriter_GetByID_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetByID'
type MockICategoryWriter_GetByID_Call struct {
	*mock.Call
}

// GetByID is a helper method to define mock.On call
//   - ctx context.Context
//   - id uuid.UUID
func (_e *MockICategoryWriter_Expecter) GetByID(ctx any, id any) *MockICategoryWriter_GetByID_Call {
	return &MockICategoryWriter_GetByID_Call{Call: _e.mock.On("GetByID", ctx, id)}
}

func (_c *MockICategoryWriter_GetByID_Call) Run(run func(ctx context.Context, id uuid.UUID)) *MockICategoryWriter_GetByID_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 uuid.UUID
		if args[1] != nil {
			arg1 = args[1].(uuid.UUID)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockICategoryWriter_GetByID_Call) Return(category1 *category.Category, err error) *MockICategoryWriter_GetByID_Call {
	_c.Call.Return(category1, err)
	return _c
}

func (_c *MockICategoryWriter_GetByID_Call) RunAndReturn(run func(ctx context.Context, id uuid.UUID) (*category.Category, error)) *MockICategoryWriter_GetByID_Call {
	_c.Call.Return(run)
	return _c
}

// Update provides a mock function for the type MockICategoryWriter
func (_mock *MockICategoryWriter) Update(ctx context.Context, id uuid.UUID, update *category.CategoryUpdate) error {
	ret := _mock.Called(ctx, id, update)

	if len(ret) == 0 {
		panic("no return value specified for Update")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, uuid.UUID, *category.CategoryUpdate) error); ok {
		r0 = returnFunc(ctx, id, update)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockICategoryWriter_Update_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Update'
type MockICategoryWriter_Update_Call struct {
	*mock.Call
}

// Update is a helper method to define mock.On call
//   - ctx context.Context
//   - id uuid.UUID
//   - update *category.CategoryUpdate
func (_e *MockICategoryWriter_Expecter) Update(ctx any, id any, update any) *MockICategoryWriter_Update_Call {
	return &MockICategoryWriter_Update_Call{Call: _e.mock.On("Update", ctx, id, update)}
}

func (_c *MockICategoryWriter_Update_Call) Run(run func(ctx context.Context, id uuid.UUID, update *category.CategoryUpdate)) *MockICategoryWriter_Update_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 uuid.UUID
		if args[1] != nil {
			arg1 = args[1].(uuid.UUID)
		}
		var arg2 *category.CategoryUpdate
		if args[2] != nil {
			arg2 = args[2].(*category.CategoryUpdate)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *MockICategoryWriter_Update_Call) Return(err error) *MockICategoryWriter_Update_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockICategoryWriter_Update_Call) RunAndReturn(run func(ctx context.Context, id uuid.UUID, update *category.CategoryUpdate) error) *MockICategoryWriter_Update_Call {
	_c.Call.Return(run)
	return _c
}
