// Code generated by mockery v2.53.6. DO NOT EDIT.

package storage

import (
	context "context"

	plaid "github.com/carson-networks/budget-server/internal/storage/plaid"
	mock "github.com/stretchr/testify/mock"

	uuid "github.com/gofrs/uuid/v5"
)

// MockIPlaidWriter is an autogenerated mock type for the IPlaidWriter type
type MockIPlaidWriter struct {
	mock.Mock
}

type MockIPlaidWriter_Expecter struct {
	mock *mock.Mock
}

func (_m *MockIPlaidWriter) EXPECT() *MockIPlaidWriter_Expecter {
	return &MockIPlaidWriter_Expecter{mock: &_m.Mock}
}

// CreateAccountLink provides a mock function with given fields: ctx, link
func (_m *MockIPlaidWriter) CreateAccountLink(ctx context.Context, link *plaid.AccountLink) error {
	ret := _m.Called(ctx, link)

	if len(ret) == 0 {
		panic("no return value specified for CreateAccountLink")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, *plaid.AccountLink) error); ok {
		r0 = rf(ctx, link)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockIPlaidWriter_CreateAccountLink_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CreateAccountLink'
type MockIPlaidWriter_CreateAccountLink_Call struct {
	*mock.Call
}

// CreateAccountLink is a helper method to define mock.On call
//   - ctx context.Context
//   - link *plaid.AccountLink
func (_e *MockIPlaidWriter_Expecter) CreateAccountLink(ctx interface{}, link interface{}) *MockIPlaidWriter_CreateAccountLink_Call {
	return &MockIPlaidWriter_CreateAccountLink_Call{Call: _e.mock.On("CreateAccountLink", ctx, link)}
}

func (_c *MockIPlaidWriter_CreateAccountLink_Call) Run(run func(ctx context.Context, link *plaid.AccountLink)) *MockIPlaidWriter_CreateAccountLink_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(*plaid.AccountLink))
	})
	return _c
}

func (_c *MockIPlaidWriter_CreateAccountLink_Call) Return(_a0 error) *MockIPlaidWriter_CreateAccountLink_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockIPlaidWriter_CreateAccountLink_Call) RunAndReturn(run func(context.Context, *plaid.AccountLink) error) *MockIPlaidWriter_CreateAccountLink_Call {
	_c.Call.Return(run)
	return _c
}

// CreateItem provides a mock function with given fields: ctx, create
func (_m *MockIPlaidWriter) CreateItem(ctx context.Context, create *plaid.PlaidItemCreate) (uuid.UUID, error) {
	ret := _m.Called(ctx, create)

	if len(ret) == 0 {
		panic("no return value specified for CreateItem")
	}

	var r0 uuid.UUID
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, *plaid.PlaidItemCreate) (uuid.UUID, error)); ok {
		return rf(ctx, create)
	}
	if rf, ok := ret.Get(0).(func(context.Context, *plaid.PlaidItemCreate) uuid.UUID); ok {
		r0 = rf(ctx, create)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(uuid.UUID)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, *plaid.PlaidItemCreate) error); ok {
		r1 = rf(ctx, create)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockIPlaidWriter_CreateItem_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CreateItem'
type MockIPlaidWriter_CreateItem_Call struct {
	*mock.Call
}

// CreateItem is a helper method to define mock.On call
//   - ctx context.Context
//   - create *plaid.PlaidItemCreate
func (_e *MockIPlaidWriter_Expecter) CreateItem(ctx interface{}, create interface{}) *MockIPlaidWriter_CreateItem_Call {
	return &MockIPlaidWriter_CreateItem_Call{Call: _e.mock.On("CreateItem", ctx, create)}
}

func (_c *MockIPlaidWriter_CreateItem_Call) Run(run func(ctx context.Context, create *plaid.PlaidItemCreate)) *MockIPlaidWriter_CreateItem_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(*plaid.PlaidItemCreate))
	})
	return _c
}

func (_c *MockIPlaidWriter_CreateItem_Call) Return(_a0 uuid.UUID, _a1 error) *MockIPlaidWriter_CreateItem_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockIPlaidWriter_CreateItem_Call) RunAndReturn(run func(context.Context, *plaid.PlaidItemCreate) (uuid.UUID, error)) *MockIPlaidWriter_CreateItem_Call {
	_c.Call.Return(run)
	return _c
}

// CreateTransactionLink provides a mock function with given fields: ctx, link
func (_m *MockIPlaidWriter) CreateTransactionLink(ctx context.Context, link *plaid.TransactionLink) error {
	ret := _m.Called(ctx, link)

	if len(ret) == 0 {
		panic("no return value specified for CreateTransactionLink")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, *plaid.TransactionLink) error); ok {
		r0 = rf(ctx, link)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockIPlaidWriter_CreateTransactionLink_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CreateTransactionLink'
type MockIPlaidWriter_CreateTransactionLink_Call struct {
	*mock.Call
}

// CreateTransactionLink is a helper method to define mock.On call
//   - ctx context.Context
//   - link *plaid.TransactionLink
func (_e *MockIPlaidWriter_Expecter) CreateTransactionLink(ctx interface{}, link interface{}) *MockIPlaidWriter_CreateTransactionLink_Call {
	return &MockIPlaidWriter_CreateTransactionLink_Call{Call: _e.mock.On("CreateTransactionLink", ctx, link)}
}

func (_c *MockIPlaidWriter_CreateTransactionLink_Call) Run(run func(ctx context.Context, link *plaid.TransactionLink)) *MockIPlaidWriter_CreateTransactionLink_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(*plaid.TransactionLink))
	})
	return _c
}

func (_c *MockIPlaidWriter_CreateTransactionLink_Call) Return(_a0 error) *MockIPlaidWriter_CreateTransactionLink_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockIPlaidWriter_CreateTransactionLink_Call) RunAndReturn(run func(context.Context, *plaid.TransactionLink) error) *MockIPlaidWriter_CreateTransactionLink_Call {
	_c.Call.Return(run)
	return _c
}

// DeleteTransactionLink provides a mock function with given fields: ctx, plaidTxnID
func (_m *MockIPlaidWriter) DeleteTransactionLink(ctx context.Context, plaidTxnID string) error {
	ret := _m.Called(ctx, plaidTxnID)

	if len(ret) == 0 {
		panic("no return value specified for DeleteTransactionLink")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, string) error); ok {
		r0 = rf(ctx, plaidTxnID)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockIPlaidWriter_DeleteTransactionLink_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'DeleteTransactionLink'
type MockIPlaidWriter_DeleteTransactionLink_Call struct {
	*mock.Call
}

// DeleteTransactionLink is a helper method to define mock.On call
//   - ctx context.Context
//   - plaidTxnID string
func (_e *MockIPlaidWriter_Expecter) DeleteTransactionLink(ctx interface{}, plaidTxnID interface{}) *MockIPlaidWriter_DeleteTransactionLink_Call {
	return &MockIPlaidWriter_DeleteTransactionLink_Call{Call: _e.mock.On("DeleteTransactionLink", ctx, plaidTxnID)}
}

func (_c *MockIPlaidWriter_DeleteTransactionLink_Call) Run(run func(ctx context.Context, plaidTxnID string)) *MockIPlaidWriter_DeleteTransactionLink_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string))
	})
	return _c
}

func (_c *MockIPlaidWriter_DeleteTransactionLink_Call) Return(_a0 error) *MockIPlaidWriter_DeleteTransactionLink_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockIPlaidWriter_DeleteTransactionLink_Call) RunAndReturn(run func(context.Context, string) error) *MockIPlaidWriter_DeleteTransactionLink_Call {
	_c.Call.Return(run)
	return _c
}

// FindTransactionLink provides a mock function with given fields: ctx, plaidTxnID
func (_m *MockIPlaidWriter) FindTransactionLink(ctx context.Context, plaidTxnID string) (*plaid.TransactionLink, error) {
	ret := _m.Called(ctx, plaidTxnID)

	if len(ret) == 0 {
		panic("no return value specified for FindTransactionLink")
	}

	var r0 *plaid.TransactionLink
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string) (*plaid.TransactionLink, error)); ok {
		return rf(ctx, plaidTxnID)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string) *plaid.TransactionLink); ok {
		r0 = rf(ctx, plaidTxnID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*plaid.TransactionLink)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = rf(ctx, plaidTxnID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockIPlaidWriter_FindTransactionLink_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'FindTransactionLink'
type MockIPlaidWriter_FindTransactionLink_Call struct {
	*mock.Call
}

// FindTransactionLink is a helper method to define mock.On call
//   - ctx context.Context
//   - plaidTxnID string
func (_e *MockIPlaidWriter_Expecter) FindTransactionLink(ctx interface{}, plaidTxnID interface{}) *MockIPlaidWriter_FindTransactionLink_Call {
	return &MockIPlaidWriter_FindTransactionLink_Call{Call: _e.mock.On("FindTransactionLink", ctx, plaidTxnID)}
}

func (_c *MockIPlaidWriter_FindTransactionLink_Call) Run(run func(ctx context.Context, plaidTxnID string)) *MockIPlaidWriter_FindTransactionLink_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string))
	})
	return _c
}

func (_c *MockIPlaidWriter_FindTransactionLink_Call) Return(_a0 *plaid.TransactionLink, _a1 error) *MockIPlaidWriter_FindTransactionLink_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockIPlaidWriter_FindTransactionLink_Call) RunAndReturn(run func(context.Context, string) (*plaid.TransactionLink, error)) *MockIPlaidWriter_FindTransactionLink_Call {
	_c.Call.Return(run)
	return _c
}

// ListAccountLinksByItemID provides a mock function with given fields: ctx, itemID
func (_m *MockIPlaidWriter) ListAccountLinksByItemID(ctx context.Context, itemID uuid.UUID) ([]*plaid.AccountLink, error) {
	ret := _m.Called(ctx, itemID)

	if len(ret) == 0 {
		panic("no return value specified for ListAccountLinksByItemID")
	}

	var r0 []*plaid.AccountLink
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID) ([]*plaid.AccountLink, error)); ok {
		return rf(ctx, itemID)
	}
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID) []*plaid.AccountLink); ok {
		r0 = rf(ctx, itemID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]*plaid.AccountLink)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, uuid.UUID) error); ok {
		r1 = rf(ctx, itemID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockIPlaidWriter_ListAccountLinksByItemID_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ListAccountLinksByItemID'
type MockIPlaidWriter_ListAccountLinksByItemID_Call struct {
	*mock.Call
}

// ListAccountLinksByItemID is a helper method to define mock.On call
//   - ctx context.Context
//   - itemID uuid.UUID
func (_e *MockIPlaidWriter_Expecter) ListAccountLinksByItemID(ctx interface{}, itemID interface{}) *MockIPlaidWriter_ListAccountLinksByItemID_Call {
	return &MockIPlaidWriter_ListAccountLinksByItemID_Call{Call: _e.mock.On("ListAccountLinksByItemID", ctx, itemID)}
}

func (_c *MockIPlaidWriter_ListAccountLinksByItemID_Call) Run(run func(ctx context.Context, itemID uuid.UUID)) *MockIPlaidWriter_ListAccountLinksByItemID_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(uuid.UUID))
	})
	return _c
}

func (_c *MockIPlaidWriter_ListAccountLinksByItemID_Call) Return(_a0 []*plaid.AccountLink, _a1 error) *MockIPlaidWriter_ListAccountLinksByItemID_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockIPlaidWriter_ListAccountLinksByItemID_Call) RunAndReturn(run func(context.Context, uuid.UUID) ([]*plaid.AccountLink, error)) *MockIPlaidWriter_ListAccountLinksByItemID_Call {
	_c.Call.Return(run)
	return _c
}

// UpdateCursor provides a mock function with given fields: ctx, itemID, cursor
func (_m *MockIPlaidWriter) UpdateCursor(ctx context.Context, itemID uuid.UUID, cursor string) error {
	ret := _m.Called(ctx, itemID, cursor)

	if len(ret) == 0 {
		panic("no return value specified for UpdateCursor")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID, string) error); ok {
		r0 = rf(ctx, itemID, cursor)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockIPlaidWriter_UpdateCursor_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'UpdateCursor'
type MockIPlaidWriter_UpdateCursor_Call struct {
	*mock.Call
}

// UpdateCursor is a helper method to define mock.On call
//   - ctx context.Context
//   - itemID uuid.UUID
//   - cursor string
func (_e *MockIPlaidWriter_Expecter) UpdateCursor(ctx interface{}, itemID interface{}, cursor interface{}) *MockIPlaidWriter_UpdateCursor_Call {
	return &MockIPlaidWriter_UpdateCursor_Call{Call: _e.mock.On("UpdateCursor", ctx, itemID, cursor)}
}

func (_c *MockIPlaidWriter_UpdateCursor_Call) Run(run func(ctx context.Context, itemID uuid.UUID, cursor string)) *MockIPlaidWriter_UpdateCursor_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(uuid.UUID), args[2].(string))
	})
	return _c
}

func (_c *MockIPlaidWriter_UpdateCursor_Call) Return(_a0 error) *MockIPlaidWriter_UpdateCursor_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockIPlaidWriter_UpdateCursor_Call) RunAndReturn(run func(context.Context, uuid.UUID, string) error) *MockIPlaidWriter_UpdateCursor_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockIPlaidWriter creates a new instance of MockIPlaidWriter. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockIPlaidWriter(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockIPlaidWriter {
	mock := &MockIPlaidWriter{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
