// Code generated by mockery v2.53.6. DO NOT EDIT.

package storage

import (
	context "context"

	sync "github.com/carson-networks/budget-server/internal/storage/sync"
	mock "github.com/stretchr/testify/mock"

	uuid "github.com/gofrs/uuid/v5"
)

// MockISyncWriter is an autogenerated mock type for the ISyncWriter type
type MockISyncWriter struct {
	mock.Mock
}

type MockISyncWriter_Expecter struct {
	mock *mock.Mock
}

func (_m *MockISyncWriter) EXPECT() *MockISyncWriter_Expecter {
	return &MockISyncWriter_Expecter{mock: &_m.Mock}
}

// Create provides a mock function with given fields: ctx, accountID, syncType
func (_m *MockISyncWriter) Create(ctx context.Context, accountID uuid.UUID, syncType sync.SyncType) error {
	ret := _m.Called(ctx, accountID, syncType)

	if len(ret) == 0 {
		panic("no return value specified for Create")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID, sync.SyncType) error); ok {
		r0 = rf(ctx, accountID, syncType)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockISyncWriter_Create_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Create'
type MockISyncWriter_Create_Call struct {
	*mock.Call
}

// Create is a helper method to define mock.On call
//   - ctx context.Context
//   - accountID uuid.UUID
//   - syncType sync.SyncType
func (_e *MockISyncWriter_Expecter) Create(ctx interface{}, accountID interface{}, syncType interface{}) *MockISyncWriter_Create_Call {
	return &MockISyncWriter_Create_Call{Call: _e.mock.On("Create", ctx, accountID, syncType)}
}

func (_c *MockISyncWriter_Create_Call) Run(run func(ctx context.Context, accountID uuid.UUID, syncType sync.SyncType)) *MockISyncWriter_Create_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(uuid.UUID), args[2].(sync.SyncType))
	})
	return _c
}

func (_c *MockISyncWriter_Create_Call) Return(_a0 error) *MockISyncWriter_Create_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockISyncWriter_Create_Call) RunAndReturn(run func(context.Context, uuid.UUID, sync.SyncType) error) *MockISyncWriter_Create_Call {
	_c.Call.Return(run)
	return _c
}

// Delete provides a mock function with given fields: ctx, accountID
func (_m *MockISyncWriter) Delete(ctx context.Context, accountID uuid.UUID) error {
	ret := _m.Called(ctx, accountID)

	if len(ret) == 0 {
		panic("no return value specified for Delete")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID) error); ok {
		r0 = rf(ctx, accountID)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockISyncWriter_Delete_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Delete'
type MockISyncWriter_Delete_Call struct {
	*mock.Call
}

// Delete is a helper method to define mock.On call
//   - ctx context.Context
//   - accountID uuid.UUID
func (_e *MockISyncWriter_Expecter) Delete(ctx interface{}, accountID interface{}) *MockISyncWriter_Delete_Call {
	return &MockISyncWriter_Delete_Call{Call: _e.mock.On("Delete", ctx, accountID)}
}

func (_c *MockISyncWriter_Delete_Call) Run(run func(ctx context.Context, accountID uuid.UUID)) *MockISyncWriter_Delete_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(uuid.UUID))
	})
	return _c
}

func (_c *MockISyncWriter_Delete_Call) Return(_a0 error) *MockISyncWriter_Delete_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockISyncWriter_Delete_Call) RunAndReturn(run func(context.Context, uuid.UUID) error) *MockISyncWriter_Delete_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockISyncWriter creates a new instance of MockISyncWriter. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockISyncWriter(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockISyncWriter {
	mock := &MockISyncWriter{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
