// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package storage

import (
	"context"

	"github.com/carson-networks/budget-server/internal/storage/account"
	"github.com/gofrs/uuid/v5"
	"github.com/shopspring/decimal"
	mock "github.com/stretchr/testify/mock"
)

// NewMockIAccountWriter creates a new instance of MockIAccountWriter. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockIAccountWriter(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockIAccountWriter {
	if helper, ok := t.(interface{ Helper() }); ok {
		helper.Helper()
	}

	mock := &MockIAccountWriter{}
	mock.Mock.Test(t)

	t.Cleanup(func() {
		if helper, ok := t.(interface{ Helper() }); ok {
			helper.Helper()
		}
		mock.AssertExpectations(t)
	})

	return mock
}

// MockIAccountWriter is an autogenerated mock type for the IAccountWriter type
type MockIAccountWriter struct {
	mock.Mock
}

type MockIAccountWriter_Expecter struct {
	mock *mock.Mock
}

func (_m *MockIAccountWriter) EXPECT() *MockIAccountWriter_Expecter {
	return &MockIAccountWriter_Expecter{mock: &_m.Mock}
}

// Create provides a mock function for the type MockIAccountWriter
func (_mock *MockIAccountWriter) Create(ctx context.Context, name string, accountType account.AccountType, accountSubType string, startingBalance decimal.Decimal) (uuid.UUID, error) {
	ret := _mock.Called(ctx, name, accountType, accountSubType, startingBalance)

	if len(ret) == 0 {
		panic("no return value specified for Create")
	}

	var r0 uuid.UUID
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, account.AccountType, string, decimal.Decimal) (uuid.UUID, error)); ok {
		return returnFunc(ctx, name, accountType, accountSubType, startingBalance)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, account.AccountType, string, decimal.Decimal) uuid.UUID); ok {
		r0 = returnFunc(ctx, name, accountType, accountSubType, startingBalance)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(uuid.UUID)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string, account.AccountType, string, decimal.Decimal) error); ok {
		r1 = returnFunc(ctx, name, accountType, accountSubType, startingBalance)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockIAccountWriter_Create_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Create'
type MockIAccountWriter_Create_Call struct {
	*mock.Call
}

// Create is a helper method to define mock.On call
//   - ctx context.Context
//   - name string
//   - accountType account.AccountType
//   - accountSubType string
//   - startingBalance decimal.Decimal
func (_e *MockIAccountWriter_Expecter) Create(ctx any, name any, accountType any, accountSubType any, startingBalance any) *MockIAccountWriter_Create_Call {
	return &MockIAccountWriter_Create_Call{Call: _e.mock.On("Create", ctx, name, accountType, accountSubType, startingBalance)}
}

func (_c *MockIAccountWriter_Create_Call) Run(run func(ctx context.Context, name string, accountType account.AccountType, accountSubType string, startingBalance decimal.Decimal)) *MockIAccountWriter_Create_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 account.AccountType
		if args[2] != nil {
			arg2 = args[2].(account.AccountType)
		}
		var arg3 string
		if args[3] != nil {
			arg3 = args[3].(string)
		}
		var arg4 decimal.Decimal
		if args[4] != nil {
			arg4 = args[4].(decimal.Decimal)
		}
		run(
			arg0,
			arg1,
			arg2,
			arg3,
			arg4,
		)
	})
	return _c
}

func (_c *MockIAccountWriter_Create_Call) Return(uUID uuid.UUID, err error) *MockIAccountWriter_Create_Call {
	_c.Call.Return(uUID, err)
	return _c
}

func (_c *MockIAccountWriter_Create_Call) RunAndReturn(run func(ctx context.Context, name string, accountType account.AccountType, accountSubType string, startingBalance decimal.Decimal) (uuid.UUID, error)) *MockIAccountWriter_Create_Call {
	_c.Call.Return(run)
	return _c
}

// FindByIDForUpdate provides a mock function for the type MockIAccountWriter
func (_mock *MockIAccountWriter) FindByIDForUpdate(ctx context.Context, id uuid.UUID) (*account.Account, error) {
	ret := _mock.Called(ctx, id)

	if len(ret) == 0 {
		panic("no return value specified for FindByIDForUpdate")
	}

	var r0 *account.Account
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, uuid.UUID) (*account.Account, error)); ok {
		return returnFunc(ctx, id)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, uuid.UUID) *account.Account); ok {
		r0 = returnFunc(ctx, id)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*account.Account)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, uuid.UUID) error); ok {
		r1 = returnFunc(ctx, id)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockIAccountWriter_FindByIDForUpdate_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'FindByIDForUpdate'
type MockIAccountWriter_FindByIDForUpdate_Call struct {
	*mock.Call
}

// FindByIDForUpdate is a helper method to define mock.On call
//   - ctx context.Context
//   - id uuid.UUID
func (_e *MockIAccountWriter_Expecter) FindByIDForUpdate(ctx any, id any) *MockIAccountWriter_FindByIDForUpdate_Call {
	return &MockIAccountWriter_FindByIDForUpdate_Call{Call: _e.mock.On("FindByIDForUpdate", ctx, id)}
}

func (_c *MockIAccountWriter_FindByIDForUpdate_Call) Run(run func(ctx context.Context, id uuid.UUID)) *MockIAccountWriter_FindByIDForUpdate_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 uuid.UUID
		if args[1] != nil {
			arg1 = args[1].(uuid.UUID)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockIAccountWriter_FindByIDForUpdate_Call) Return(account1 *account.Account, err error) *MockIAccountWriter_FindByIDForUpdate_Call {
	_c.Call.Return(account1, err)
	return _c
}

func (_c *MockIAccountWriter_FindByIDForUpdate_Call) RunAndReturn(run func(ctx context.Context, id uuid.UUID) (*account.Account, error)) *MockIAccountWriter_FindByIDForUpdate_Call {
	_c.Call.Return(run)
	return _c
}

// Update provides a mock function for the type MockIAccountWriter
func (_mock *MockIAccountWriter) Update(ctx context.Context, id uuid.UUID, update *account.AccountUpdate) error {
	ret := _mock.Called(ctx, id, update)

	if len(ret) == 0 {
		panic("no return value specified for Update")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, uuid.UUID, *account.AccountUpdate) error); ok {
		r0 = returnFunc(ctx, id, update)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockIAccountWriter_Update_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Update'
type MockIAccountWriter_Update_Call struct {
	*mock.Call
}

// Update is a helper method to define mock.On call
//   - ctx context.Context
//   - id uuid.UUID
//   - update *account.AccountUpdate
func (_e *MockIAccountWriter_Expecter) Update(ctx any, id any, update any) *MockIAccountWriter_Update_Call {
	return &MockIAccountWriter_Update_Call{Call: _e.mock.On("Update", ctx, id, update)}
}

func (_c *MockIAccountWriter_Update_Call) Run(run func(ctx context.Context, id uuid.UUID, update *account.AccountUpdate)) *MockIAccountWriter_Update_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 uuid.UUID
		if args[1] != nil {
			arg1 = args[1].(uuid.UUID)
		}
		var arg2 *account.AccountUpdate
		if args[2] != nil {
			arg2 = args[2].(*account.AccountUpdate)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *MockIAccountWriter_Update_Call) Return(err error) *MockIAccountWriter_Update_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockIAccountWriter_Update_Call) RunAndReturn(run func(ctx context.Context, id uuid.UUID, update *account.AccountUpdate) error) *MockIAccountWriter_Update_Call {
	_c.Call.Return(run)
	return _c
}

// UpdateBalance provides a mock function for the type MockIAccountWriter
func (_mock *MockIAccountWriter) UpdateBalance(ctx context.Context, id uuid.UUID, balance decimal.Decimal) error {
	ret := _mock.Called(ctx, id, balance)

	if len(ret) == 0 {
		panic("no return value specified for UpdateBalance")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, uuid.UUID, decimal.Decimal) error); ok {
		r0 = returnFunc(ctx, id, balance)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockIAccountWriter_UpdateBalance_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'UpdateBalance'
type MockIAccountWriter_UpdateBalance_Call struct {
	*mock.Call
}

// UpdateBalance is a helper method to define mock.On call
//   - ctx context.Context
//   - id uuid.UUID
//   - balance decimal.Decimal
func (_e *MockIAccountWriter_Expecter) UpdateBalance(ctx any, id any, balance any) *MockIAccountWriter_UpdateBalance_Call {
	return &MockIAccountWriter_UpdateBalance_Call{Call: _e.mock.On("UpdateBalance", ctx, id, balance)}
}

func (_c *MockIAccountWriter_UpdateBalance_Call) Run(run func(ctx context.Context, id uuid.UUID, balance decimal.Decimal)) *MockIAccountWriter_UpdateBalance_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 uuid.UUID
		if args[1] != nil {
			arg1 = args[1].(uuid.UUID)
		}
		var arg2 decimal.Decimal
		if args[2] != nil {
			arg2 = args[2].(decimal.Decimal)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *MockIAccountWriter_UpdateBalance_Call) Return(err error) *MockIAccountWriter_UpdateBalance_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockIAccountWriter_UpdateBalance_Call) RunAndReturn(run func(ctx context.Context, id uuid.UUID, balance decimal.Decimal) error) *MockIAccountWriter_UpdateBalance_Call {
	_c.Call.Return(run)
	return _c
}

// Delete provides a mock function for the type MockIAccountWriter
func (_mock *MockIAccountWriter) Delete(ctx context.Context, id uuid.UUID) error {
	ret := _mock.Called(ctx, id)

	if len(ret) == 0 {
		panic("no return value specified for Delete")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, uuid.UUID) error); ok {
		r0 = returnFunc(ctx, id)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockIAccountWriter_Delete_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Delete'
type MockIAccountWriter_Delete_Call struct {
	*mock.Call
}

// Delete is a helper method to define mock.On call
//   - ctx context.Context
//   - id uuid.UUID
func (_e *MockIAccountWriter_Expecter) Delete(ctx any, id any) *MockIAccountWriter_Delete_Call {
	return &MockIAccountWriter_Delete_Call{Call: _e.mock.On("Delete", ctx, id)}
}

func (_c *MockIAccountWriter_Delete_Call) Run(run func(ctx context.Context, id uuid.UUID)) *MockIAccountWriter_Delete_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 uuid.UUID
		if args[1] != nil {
			arg1 = args[1].(uuid.UUID)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockIAccountWriter_Delete_Call) Return(err error) *MockIAccountWriter_Delete_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockIAccountWriter_Delete_Call) RunAndReturn(run func(ctx context.Context, id uuid.UUID) error) *MockIAccountWriter_Delete_Call {
	_c.Call.Return(run)
	return _c
}
