// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package storage

import (
	"context"

	"github.com/carson-networks/budget-server/internal/storage/transaction"
	"github.com/gofrs/uuid/v5"
	mock "github.com/stretchr/testify/mock"
)

// NewMockITransactionWriter creates a new instance of MockITransactionWriter. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockITransactionWriter(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockITransactionWriter {
	if helper, ok := t.(interface{ Helper() }); ok {
		helper.Helper()
	}

	mock := &MockITransactionWriter{}
	mock.Mock.Test(t)

	t.Cleanup(func() {
		if helper, ok := t.(interface{ Helper() }); ok {
			helper.Helper()
		}
		mock.AssertExpectations(t)
	})

	return mock
}

// MockITransactionWriter is an autogenerated mock type for the ITransactionWriter type
type MockITransactionWriter struct {
	mock.Mock
}

type MockITransactionWriter_Expecter struct {
	mock *mock.Mock
}

func (_m *MockITransactionWriter) EXPECT() *MockITransactionWriter_Expecter {
	return &MockITransactionWriter_Expecter{mock: &_m.Mock}
}

// Delete provides a mock function for the type MockITransactionWriter
func (_mock *MockITransactionWriter) Delete(ctx context.Context, id uuid.UUID) (*transaction.Transaction, error) {
	ret := _mock.Called(ctx, id)

	if len(ret) == 0 {
		panic("no return value specified for Delete")
	}

	var r0 *transaction.Transaction
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, uuid.UUID) (*transaction.Transaction, error)); ok {
		return returnFunc(ctx, id)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, uuid.UUID) *transaction.Transaction); ok {
		r0 = returnFunc(ctx, id)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*transaction.Transaction)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, uuid.UUID) error); ok {
		r1 = returnFunc(ctx, id)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockITransactionWriter_Delete_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Delete'
type MockITransactionWriter_Delete_Call struct {
	*mock.Call
}

// Delete is a helper method to define mock.On call
//   - ctx context.Context
//   - id uuid.UUID
func (_e *MockITransactionWriter_Expecter) Delete(ctx any, id any) *MockITransactionWriter_Delete_Call {
	return &MockITransactionWriter_Delete_Call{Call: _e.mock.On("Delete", ctx, id)}
}

func (_c *MockITransactionWriter_Delete_Call) Run(run func(ctx context.Context, id uuid.UUID)) *MockITransactionWriter_Delete_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 uuid.UUID
		if args[1] != nil {
			arg1 = args[1].(uuid.UUID)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockITransactionWriter_Delete_Call) Return(transaction1 *transaction.Transaction, err error) *MockITransactionWriter_Delete_Call {
	_c.Call.Return(transaction1, err)
	return _c
}

func (_c *MockITransactionWriter_Delete_Call) RunAndReturn(run func(ctx context.Context, id uuid.UUID) (*transaction.Transaction, error)) *MockITransactionWriter_Delete_Call {
	_c.Call.Return(run)
	return _c
}

// DeleteByAccountID provides a mock function for the type MockITransactionWriter
func (_mock *MockITransactionWriter) DeleteByAccountID(ctx context.Context, accountID uuid.UUID) error {
	ret := _mock.Called(ctx, accountID)

	if len(ret) == 0 {
		panic("no return value specified for DeleteByAccountID")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, uuid.UUID) error); ok {
		r0 = returnFunc(ctx, accountID)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockITransactionWriter_DeleteByAccountID_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'DeleteByAccountID'
type MockITransactionWriter_DeleteByAccountID_Call struct {
	*mock.Call
}

// DeleteByAccountID is a helper method to define mock.On call
//   - ctx context.Context
//   - accountID uuid.UUID
func (_e *MockITransactionWriter_Expecter) DeleteByAccountID(ctx any, accountID any) *MockITransactionWriter_DeleteByAccountID_Call {
	return &MockITransactionWriter_DeleteByAccountID_Call{Call: _e.mock.On("DeleteByAccountID", ctx, accountID)}
}

func (_c *MockITransactionWriter_DeleteByAccountID_Call) Run(run func(ctx context.Context, accountID uuid.UUID)) *MockITransactionWriter_DeleteByAccountID_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 uuid.UUID
		if args[1] != nil {
			arg1 = args[1].(uuid.UUID)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockITransactionWriter_DeleteByAccountID_Call) Return(err error) *MockITransactionWriter_DeleteByAccountID_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockITransactionWriter_DeleteByAccountID_Call) RunAndReturn(run func(ctx context.Context, accountID uuid.UUID) error) *MockITransactionWriter_DeleteByAccountID_Call {
	_c.Call.Return(run)
	return _c
}

// FindByID provides a mock function for the type MockITransactionWriter
func (_mock *MockITransactionWriter) FindByID(ctx context.Context, id uuid.UUID) (*transaction.Transaction, error) {
	ret := _mock.Called(ctx, id)

	if len(ret) == 0 {
		panic("no return value specified for FindByID")
	}

	var r0 *transaction.Transaction
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, uuid.UUID) (*transaction.Transaction, error)); ok {
		return returnFunc(ctx, id)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, uuid.UUID) *transaction.Transaction); ok {
		r0 = returnFunc(ctx, id)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*transaction.Transaction)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, uuid.UUID) error); ok {
		r1 = returnFunc(ctx, id)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockITransactionWriter_FindByID_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'FindByID'
type MockITransactionWriter_FindByID_Call struct {
	*mock.Call
}

// FindByID is a helper method to define mock.On call
//   - ctx context.Context
//   - id uuid.UUID
func (_e *MockITransactionWriter_Expecter) FindByID(ctx any, id any) *MockITransactionWriter_FindByID_Call {
	return &MockITransactionWriter_FindByID_Call{Call: _e.mock.On("FindByID", ctx, id)}
}

func (_c *MockITransactionWriter_FindByID_Call) Run(run func(ctx context.Context, id uuid.UUID)) *MockITransactionWriter_FindByID_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 uuid.UUID
		if args[1] != nil {
			arg1 = args[1].(uuid.UUID)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockITransactionWriter_FindByID_Call) Return(transaction1 *transaction.Transaction, err error) *MockITransactionWriter_FindByID_Call {
	_c.Call.Return(transaction1, err)
	return _c
}

func (_c *MockITransactionWriter_FindByID_Call) RunAndReturn(run func(ctx context.Context, id uuid.UUID) (*transaction.Transaction, error)) *MockITransactionWriter_FindByID_Call {
	_c.Call.Return(run)
	return _c
}

// Insert provides a mock function for the type MockITransactionWriter
func (_mock *MockITransactionWriter) Insert(ctx context.Context, create *transaction.TransactionCreate) (uuid.UUID, error) {
	ret := _mock.Called(ctx, create)

	if len(ret) == 0 {
		panic("no return value specified for Insert")
	}

	var r0 uuid.UUID
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, *transaction.TransactionCreate) (uuid.UUID, error)); ok {
		return returnFunc(ctx, create)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, *transaction.TransactionCreate) uuid.UUID); ok {
		r0 = returnFunc(ctx, create)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(uuid.UUID)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, *transaction.TransactionCreate) error); ok {
		r1 = returnFunc(ctx, create)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockITransactionWriter_Insert_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Insert'
type MockITransactionWriter_Insert_Call struct {
	*mock.Call
}

// Insert is a helper method to define mock.On call
//   - ctx context.Context
//   - create *transaction.TransactionCreate
func (_e *MockITransactionWriter_Expecter) Insert(ctx any, create any) *MockITransactionWriter_Insert_Call {
	return &MockITransactionWriter_Insert_Call{Call: _e.mock.On("Insert", ctx, create)}
}

func (_c *MockITransactionWriter_Insert_Call) Run(run func(ctx context.Context, create *transaction.TransactionCreate)) *MockITransactionWriter_Insert_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 *transaction.TransactionCreate
		if args[1] != nil {
			arg1 = args[1].(*transaction.TransactionCreate)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockITransactionWriter_Insert_Call) Return(uUID uuid.UUID, err error) *MockITransactionWriter_Insert_Call {
	_c.Call.Return(uUID, err)
	return _c
}

func (_c *MockITransactionWriter_Insert_Call) RunAndReturn(run func(ctx context.Context, create *transaction.TransactionCreate) (uuid.UUID, error)) *MockITransactionWriter_Insert_Call {
	_c.Call.Return(run)
	return _c
}

// Update provides a mock function for the type MockITransactionWriter
func (_mock *MockITransactionWriter) Update(ctx context.Context, id uuid.UUID, update *transaction.TransactionUpdate) error {
	ret := _mock.Called(ctx, id, update)

	if len(ret) == 0 {
		panic("no return value specified for Update")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, uuid.UUID, *transaction.TransactionUpdate) error); ok {
		r0 = returnFunc(ctx, id, update)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockITransactionWriter_Update_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Update'
type MockITransactionWriter_Update_Call struct {
	*mock.Call
}

// Update is a helper method to define mock.On call
//   - ctx context.Context
//   - id uuid.UUID
//   - update *transaction.TransactionUpdate
func (_e *MockITransactionWriter_Expecter) Update(ctx any, id any, update any) *MockITransactionWriter_Update_Call {
	return &MockITransactionWriter_Update_Call{Call: _e.mock.On("Update", ctx, id, update)}
}

func (_c *MockITransactionWriter_Update_Call) Run(run func(ctx context.Context, id uuid.UUID, update *transaction.TransactionUpdate)) *MockITransactionWriter_Update_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 uuid.UUID
		if args[1] != nil {
			arg1 = args[1].(uuid.UUID)
		}
		var arg2 *transaction.TransactionUpdate
		if args[2] != nil {
			arg2 = args[2].(*transaction.TransactionUpdate)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *MockITransactionWriter_Update_Call) Return(err error) *MockITransactionWriter_Update_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockITransactionWriter_Update_Call) RunAndReturn(run func(ctx context.Context, id uuid.UUID, update *transaction.TransactionUpdate) error) *MockITransactionWriter_Update_Call {
	_c.Call.Return(run)
	return _c
}
