// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package account

import (
	"context"

	"github.com/gofrs/uuid/v5"
	"github.com/shopspring/decimal"
	mock "github.com/stretchr/testify/mock"
)

// NewMockIAccountTable creates a new instance of MockIAccountTable. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockIAccountTable(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockIAccountTable {
	if helper, ok := t.(interface{ Helper() }); ok {
		helper.Helper()
	}

	mock := &MockIAccountTable{}
	mock.Mock.Test(t)

	t.Cleanup(func() {
		if helper, ok := t.(interface{ Helper() }); ok {
			helper.Helper()
		}
		mock.AssertExpectations(t)
	})

	return mock
}

// MockIAccountTable is an autogenerated mock type for the IAccountTable type
type MockIAccountTable struct {
	mock.Mock
}

type MockIAccountTable_Expecter struct {
	mock *mock.Mock
}

func (_m *MockIAccountTable) EXPECT() *MockIAccountTable_Expecter {
	return &MockIAccountTable_Expecter{mock: &_m.Mock}
}

// FindByID provides a mock function for the type MockIAccountTable
func (_mock *MockIAccountTable) FindByID(ctx context.Context, id uuid.UUID, forUpdate bool) (*Account, error) {
	ret := _mock.Called(ctx, id, forUpdate)

	if len(ret) == 0 {
		panic("no return value specified for FindByID")
	}

	var r0 *Account
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, uuid.UUID, bool) (*Account, error)); ok {
		return returnFunc(ctx, id, forUpdate)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, uuid.UUID, bool) *Account); ok {
		r0 = returnFunc(ctx, id, forUpdate)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*Account)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, uuid.UUID, bool) error); ok {
		r1 = returnFunc(ctx, id, forUpdate)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockIAccountTable_FindByID_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'FindByID'
type MockIAccountTable_FindByID_Call struct {
	*mock.Call
}

// FindByID is a helper method to define mock.On call
//   - ctx context.Context
//   - id uuid.UUID
//   - forUpdate bool
func (_e *MockIAccountTable_Expecter) FindByID(ctx any, id any, forUpdate any) *MockIAccountTable_FindByID_Call {
	return &MockIAccountTable_FindByID_Call{Call: _e.mock.On("FindByID", ctx, id, forUpdate)}
}

func (_c *MockIAccountTable_FindByID_Call) Run(run func(ctx context.Context, id uuid.UUID, forUpdate bool)) *MockIAccountTable_FindByID_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 uuid.UUID
		if args[1] != nil {
			arg1 = args[1].(uuid.UUID)
		}
		var arg2 bool
		if args[2] != nil {
			arg2 = args[2].(bool)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *MockIAccountTable_FindByID_Call) Return(account *Account, err error) *MockIAccountTable_FindByID_Call {
	_c.Call.Return(account, err)
	return _c
}

func (_c *MockIAccountTable_FindByID_Call) RunAndReturn(run func(ctx context.Context, id uuid.UUID, forUpdate bool) (*Account, error)) *MockIAccountTable_FindByID_Call {
	_c.Call.Return(run)
	return _c
}

// Insert provides a mock function for the type MockIAccountTable
func (_mock *MockIAccountTable) Insert(ctx context.Context, create *AccountCreate) (uuid.UUID, error) {
	ret := _mock.Called(ctx, create)

	if len(ret) == 0 {
		panic("no return value specified for Insert")
	}

	var r0 uuid.UUID
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, *AccountCreate) (uuid.UUID, error)); ok {
		return returnFunc(ctx, create)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, *AccountCreate) uuid.UUID); ok {
		r0 = returnFunc(ctx, create)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(uuid.UUID)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, *AccountCreate) error); ok {
		r1 = returnFunc(ctx, create)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockIAccountTable_Insert_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Insert'
type MockIAccountTable_Insert_Call struct {
	*mock.Call
}

// Insert is a helper method to define mock.On call
//   - ctx context.Context
//   - create *AccountCreate
func (_e *MockIAccountTable_Expecter) Insert(ctx any, create any) *MockIAccountTable_Insert_Call {
	return &MockIAccountTable_Insert_Call{Call: _e.mock.On("Insert", ctx, create)}
}

func (_c *MockIAccountTable_Insert_Call) Run(run func(ctx context.Context, create *AccountCreate)) *MockIAccountTable_Insert_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 *AccountCreate
		if args[1] != nil {
			arg1 = args[1].(*AccountCreate)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockIAccountTable_Insert_Call) Return(uUID uuid.UUID, err error) *MockIAccountTable_Insert_Call {
	_c.Call.Return(uUID, err)
	return _c
}

func (_c *MockIAccountTable_Insert_Call) RunAndReturn(run func(ctx context.Context, create *AccountCreate) (uuid.UUID, error)) *MockIAccountTable_Insert_Call {
	_c.Call.Return(run)
	return _c
}

// List provides a mock function for the type MockIAccountTable
func (_mock *MockIAccountTable) List(ctx context.Context, filter *AccountFilter) ([]*Account, error) {
	ret := _mock.Called(ctx, filter)

	if len(ret) == 0 {
		panic("no return value specified for List")
	}

	var r0 []*Account
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, *AccountFilter) ([]*Account, error)); ok {
		return returnFunc(ctx, filter)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, *AccountFilter) []*Account); ok {
		r0 = returnFunc(ctx, filter)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]*Account)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, *AccountFilter) error); ok {
		r1 = returnFunc(ctx, filter)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockIAccountTable_List_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'List'
type MockIAccountTable_List_Call struct {
	*mock.Call
}

// List is a helper method to define mock.On call
//   - ctx context.Context
//   - filter *AccountFilter
func (_e *MockIAccountTable_Expecter) List(ctx any, filter any) *MockIAccountTable_List_Call {
	return &MockIAccountTable_List_Call{Call: _e.mock.On("List", ctx, filter)}
}

func (_c *MockIAccountTable_List_Call) Run(run func(ctx context.Context, filter *AccountFilter)) *MockIAccountTable_List_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 *AccountFilter
		if args[1] != nil {
			arg1 = args[1].(*AccountFilter)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockIAccountTable_List_Call) Return(accounts []*Account, err error) *MockIAccountTable_List_Call {
	_c.Call.Return(accounts, err)
	return _c
}

func (_c *MockIAccountTable_List_Call) RunAndReturn(run func(ctx context.Context, filter *AccountFilter) ([]*Account, error)) *MockIAccountTable_List_Call {
	_c.Call.Return(run)
	return _c
}

// UpdateBalance provides a mock function for the type MockIAccountTable
func (_mock *MockIAccountTable) UpdateBalance(ctx context.Context, id uuid.UUID, balance decimal.Decimal) error {
	ret := _mock.Called(ctx, id, balance)

	if len(ret) == 0 {
		panic("no return value specified for UpdateBalance")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, uuid.UUID, decimal.Decimal) error); ok {
		r0 = returnFunc(ctx, id, balance)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockIAccountTable_UpdateBalance_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'UpdateBalance'
type MockIAccountTable_UpdateBalance_Call struct {
	*mock.Call
}

// UpdateBalance is a helper method to define mock.On call
//   - ctx context.Context
//   - id uuid.UUID
//   - balance decimal.Decimal
func (_e *MockIAccountTable_Expecter) UpdateBalance(ctx any, id any, balance any) *MockIAccountTable_UpdateBalance_Call {
	return &MockIAccountTable_UpdateBalance_Call{Call: _e.mock.On("UpdateBalance", ctx, id, balance)}
}

func (_c *MockIAccountTable_UpdateBalance_Call) Run(run func(ctx context.Context, id uuid.UUID, balance decimal.Decimal)) *MockIAccountTable_UpdateBalance_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 uuid.UUID
		if args[1] != nil {
			arg1 = args[1].(uuid.UUID)
		}
		var arg2 decimal.Decimal
		if args[2] != nil {
			arg2 = args[2].(decimal.Decimal)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *MockIAccountTable_UpdateBalance_Call) Return(err error) *MockIAccountTable_UpdateBalance_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockIAccountTable_UpdateBalance_Call) RunAndReturn(run func(ctx context.Context, id uuid.UUID, balance decimal.Decimal) error) *MockIAccountTable_UpdateBalance_Call {
	_c.Call.Return(run)
	return _c
}
