// Code generated by BobGen psql v0.42.0. DO NOT EDIT.
// This file is meant to be re-generated in place and/or deleted at any time.

package dberrors

var CategoryErrors = &categoryErrors{
	ErrUniqueCategoriesPkey: &UniqueConstraintError{
		schema:  "",
		table:   "categories",
		columns: []string{"id"},
		s:       "categories_pkey",
	},
}

type categoryErrors struct {
	ErrUniqueCategoriesPkey *UniqueConstraintError
}
