// Code generated by BobGen psql v0.42.0. DO NOT EDIT.
// This file is meant to be re-generated in place and/or deleted at any time.

package dberrors

var PlaidAccountLinkErrors = &plaidAccountLinkErrors{
	ErrUniquePlaidAccountLinksPkey: &UniqueConstraintError{
		schema:  "",
		table:   "plaid_account_links",
		columns: []string{"plaid_account_id"},
		s:       "plaid_account_links_pkey",
	},
}

type plaidAccountLinkErrors struct {
	ErrUniquePlaidAccountLinksPkey *UniqueConstraintError
}
