// Code generated by BobGen psql v0.42.0. DO NOT EDIT.
// This file is meant to be re-generated in place and/or deleted at any time.

package dberrors

var PlaidItemErrors = &plaidItemErrors{
	ErrUniquePlaidItemsPkey: &UniqueConstraintError{
		schema:  "",
		table:   "plaid_items",
		columns: []string{"id"},
		s:       "plaid_items_pkey",
	},

	ErrUniquePlaidItemsPlaidItemIdKey: &UniqueConstraintError{
		schema:  "",
		table:   "plaid_items",
		columns: []string{"plaid_item_id"},
		s:       "plaid_items_plaid_item_id_key",
	},
}

type plaidItemErrors struct {
	ErrUniquePlaidItemsPkey *UniqueConstraintError

	ErrUniquePlaidItemsPlaidItemIdKey *UniqueConstraintError
}
