// Code generated by BobGen psql v0.42.0. DO NOT EDIT.
// This file is meant to be re-generated in place and/or deleted at any time.

package dberrors

var PlaidTransactionLinkErrors = &plaidTransactionLinkErrors{
	ErrUniquePlaidTransactionLinksPkey: &UniqueConstraintError{
		schema:  "",
		table:   "plaid_transaction_links",
		columns: []string{"plaid_transaction_id"},
		s:       "plaid_transaction_links_pkey",
	},
}

type plaidTransactionLinkErrors struct {
	ErrUniquePlaidTransactionLinksPkey *UniqueConstraintError
}
