// Code generated by BobGen psql v0.50.0. DO NOT EDIT.
// This file is meant to be re-generated in place and/or deleted at any time.

package bobgen

import (
	"context"
	"fmt"
	"io"
	"strings"
	"time"

	"github.com/aarondl/opt/null"
	"github.com/aarondl/opt/omit"
	"github.com/gofrs/uuid/v5"
	"github.com/shopspring/decimal"
	"github.com/stephenafamo/bob"
	"github.com/stephenafamo/bob/dialect/psql"
	"github.com/stephenafamo/bob/dialect/psql/dialect"
	"github.com/stephenafamo/bob/dialect/psql/dm"
	"github.com/stephenafamo/bob/dialect/psql/sm"
	"github.com/stephenafamo/bob/dialect/psql/um"
	"github.com/stephenafamo/bob/expr"
	"github.com/stephenafamo/bob/mods"
	"github.com/stephenafamo/bob/orm"
	"github.com/stephenafamo/bob/types/pgtypes"
	"github.com/stephenafamo/scan"
)

// Account is an object representing the database table.
type Account struct {
	ID              uuid.UUID       `db:"id,pk" `
	Name            string          `db:"name" `
	Type            int16           `db:"type" `
	SubType         string          `db:"sub_type" `
	Balance         decimal.Decimal `db:"balance" `
	StartingBalance decimal.Decimal `db:"starting_balance" `
	CreatedAt       time.Time       `db:"created_at" `

	R accountR `db:"-" `

	C accountC `db:"-" `
}

// AccountSlice is an alias for a slice of pointers to Account.
// This should almost always be used instead of []*Account.
type AccountSlice []*Account

// Accounts contains methods to work with the accounts table
var Accounts = psql.NewTablex[*Account, AccountSlice, *AccountSetter]("", "accounts", buildAccountColumns("accounts"), accountScanMapper)

// AccountsQuery is a query on the accounts table
type AccountsQuery = *psql.ViewQuery[*Account, AccountSlice]

// accountR is where relationships are stored.
type accountR struct {
	PlaidAccountLinks PlaidAccountLinkSlice // plaid_account_links.plaid_account_links_account_id_fkey
	Sync              *Sync                 // syncs.syncs_account_id_fkey
	// Loaded reports whether each relationship has been loaded.
	// A relationship's bool is set by Load*, Preload, ThenLoad, factory builds,
	// and to-one Attach/Insert operations. To-many Attach/Insert operations leave it unchanged.
	Loaded accountRLoaded `db:"-" `
}

// accountRLoaded tracks which relationships on Account have been loaded.
type accountRLoaded struct {
	PlaidAccountLinks bool // plaid_account_links.plaid_account_links_account_id_fkey
	Sync              bool // syncs.syncs_account_id_fkey
}

func buildAccountColumns(tableName string) accountColumns {
	columnsExpr := expr.NewColumnsExpr(
		"id", "name", "type", "sub_type", "balance", "starting_balance", "created_at",
	)

	if tableName != "" {
		columnsExpr = columnsExpr.WithParent(tableName)
	}

	return accountColumns{
		ColumnsExpr:     columnsExpr,
		tableAlias:      tableName,
		ID:              buildAccountColumn(tableName, "id"),
		Name:            buildAccountColumn(tableName, "name"),
		Type:            buildAccountColumn(tableName, "type"),
		SubType:         buildAccountColumn(tableName, "sub_type"),
		Balance:         buildAccountColumn(tableName, "balance"),
		StartingBalance: buildAccountColumn(tableName, "starting_balance"),
		CreatedAt:       buildAccountColumn(tableName, "created_at"),
	}
}

type accountColumns struct {
	expr.ColumnsExpr
	tableAlias      string
	ID              accountColumn
	Name            accountColumn
	Type            accountColumn
	SubType         accountColumn
	Balance         accountColumn
	StartingBalance accountColumn
	CreatedAt       accountColumn
}

// Alias returns the current table alias for the columns set.
func (c accountColumns) Alias() string {
	return c.tableAlias
}

// AliasedAs returns a copy of the columns set qualified by tableName.
func (accountColumns) AliasedAs(tableName string) accountColumns {
	return buildAccountColumns(tableName)
}

// Unqualified returns a copy of the columns set without table qualification.
func (c accountColumns) Unqualified() accountColumns {
	return buildAccountColumns("")
}

func buildAccountColumn(alias, name string) accountColumn {
	return accountColumn{
		Expression: psql.Quote(alias, name),
		alias:      alias,
		name:       name,
	}
}

type accountColumn struct {
	psql.Expression
	alias string
	name  string
}

// Name returns the unqualified column name.
func (c accountColumn) Name() string {
	return c.name
}

// ShouldOmitParens prevents automatic parenthesis wrapping in expression builders.
func (c accountColumn) ShouldOmitParens() bool {
	return true
}

// AccountSetter is used for insert/upsert/update operations
// All values are optional, and do not have to be set
// Generated columns are not included
type AccountSetter struct {
	ID              omit.Val[uuid.UUID]       `db:"id,pk" `
	Name            omit.Val[string]          `db:"name" `
	Type            omit.Val[int16]           `db:"type" `
	SubType         omit.Val[string]          `db:"sub_type" `
	Balance         omit.Val[decimal.Decimal] `db:"balance" `
	StartingBalance omit.Val[decimal.Decimal] `db:"starting_balance" `
	CreatedAt       omit.Val[time.Time]       `db:"created_at" `
}

func (s AccountSetter) SetColumns() []string {
	vals := make([]string, 0, 7)
	if s.ID.IsValue() {
		vals = append(vals, "id")
	}
	if s.Name.IsValue() {
		vals = append(vals, "name")
	}
	if s.Type.IsValue() {
		vals = append(vals, "type")
	}
	if s.SubType.IsValue() {
		vals = append(vals, "sub_type")
	}
	if s.Balance.IsValue() {
		vals = append(vals, "balance")
	}
	if s.StartingBalance.IsValue() {
		vals = append(vals, "starting_balance")
	}
	if s.CreatedAt.IsValue() {
		vals = append(vals, "created_at")
	}
	return vals
}

func (s AccountSetter) Overwrite(t *Account) {
	if s.ID.IsValue() {
		t.ID = s.ID.MustGet()
	}
	if s.Name.IsValue() {
		t.Name = s.Name.MustGet()
	}
	if s.Type.IsValue() {
		t.Type = s.Type.MustGet()
	}
	if s.SubType.IsValue() {
		t.SubType = s.SubType.MustGet()
	}
	if s.Balance.IsValue() {
		t.Balance = s.Balance.MustGet()
	}
	if s.StartingBalance.IsValue() {
		t.StartingBalance = s.StartingBalance.MustGet()
	}
	if s.CreatedAt.IsValue() {
		t.CreatedAt = s.CreatedAt.MustGet()
	}
}

func (s *AccountSetter) Apply(q *dialect.InsertQuery) {
	q.AppendHooks(func(ctx context.Context, exec bob.Executor) (context.Context, error) {
		return Accounts.BeforeInsertHooks.RunHooks(ctx, exec, s)
	})

	q.AppendValues(
		bob.ExpressionFunc(func(ctx context.Context, w io.StringWriter, d bob.Dialect, start int) ([]any, error) {
			if s.ID.IsUnset() {
				return psql.Raw("DEFAULT").WriteSQL(ctx, w, d, start)
			}
			return psql.Arg(s.ID.MustGet()).WriteSQL(ctx, w, d, start)
		}), bob.ExpressionFunc(func(ctx context.Context, w io.StringWriter, d bob.Dialect, start int) ([]any, error) {
			if s.Name.IsUnset() {
				return psql.Raw("DEFAULT").WriteSQL(ctx, w, d, start)
			}
			return psql.Arg(s.Name.MustGet()).WriteSQL(ctx, w, d, start)
		}), bob.ExpressionFunc(func(ctx context.Context, w io.StringWriter, d bob.Dialect, start int) ([]any, error) {
			if s.Type.IsUnset() {
				return psql.Raw("DEFAULT").WriteSQL(ctx, w, d, start)
			}
			return psql.Arg(s.Type.MustGet()).WriteSQL(ctx, w, d, start)
		}), bob.ExpressionFunc(func(ctx context.Context, w io.StringWriter, d bob.Dialect, start int) ([]any, error) {
			if s.SubType.IsUnset() {
				return psql.Raw("DEFAULT").WriteSQL(ctx, w, d, start)
			}
			return psql.Arg(s.SubType.MustGet()).WriteSQL(ctx, w, d, start)
		}), bob.ExpressionFunc(func(ctx context.Context, w io.StringWriter, d bob.Dialect, start int) ([]any, error) {
			if s.Balance.IsUnset() {
				return psql.Raw("DEFAULT").WriteSQL(ctx, w, d, start)
			}
			return psql.Arg(s.Balance.MustGet()).WriteSQL(ctx, w, d, start)
		}), bob.ExpressionFunc(func(ctx context.Context, w io.StringWriter, d bob.Dialect, start int) ([]any, error) {
			if s.StartingBalance.IsUnset() {
				return psql.Raw("DEFAULT").WriteSQL(ctx, w, d, start)
			}
			return psql.Arg(s.StartingBalance.MustGet()).WriteSQL(ctx, w, d, start)
		}), bob.ExpressionFunc(func(ctx context.Context, w io.StringWriter, d bob.Dialect, start int) ([]any, error) {
			if s.CreatedAt.IsUnset() {
				return psql.Raw("DEFAULT").WriteSQL(ctx, w, d, start)
			}
			return psql.Arg(s.CreatedAt.MustGet()).WriteSQL(ctx, w, d, start)
		}))
}

func (s AccountSetter) UpdateMod() bob.Mod[*dialect.UpdateQuery] {
	return um.Set(s.Expressions()...)
}

func (s AccountSetter) Expressions(prefix ...string) []bob.Expression {
	exprs := make([]bob.Expression, 0, 7)

	if s.ID.IsValue() {
		exprs = append(exprs, expr.Join{Sep: " = ", Exprs: []bob.Expression{
			psql.Quote(append(prefix, "id")...),
			psql.Arg(s.ID),
		}})
	}

	if s.Name.IsValue() {
		exprs = append(exprs, expr.Join{Sep: " = ", Exprs: []bob.Expression{
			psql.Quote(append(prefix, "name")...),
			psql.Arg(s.Name),
		}})
	}

	if s.Type.IsValue() {
		exprs = append(exprs, expr.Join{Sep: " = ", Exprs: []bob.Expression{
			psql.Quote(append(prefix, "type")...),
			psql.Arg(s.Type),
		}})
	}

	if s.SubType.IsValue() {
		exprs = append(exprs, expr.Join{Sep: " = ", Exprs: []bob.Expression{
			psql.Quote(append(prefix, "sub_type")...),
			psql.Arg(s.SubType),
		}})
	}

	if s.Balance.IsValue() {
		exprs = append(exprs, expr.Join{Sep: " = ", Exprs: []bob.Expression{
			psql.Quote(append(prefix, "balance")...),
			psql.Arg(s.Balance),
		}})
	}

	if s.StartingBalance.IsValue() {
		exprs = append(exprs, expr.Join{Sep: " = ", Exprs: []bob.Expression{
			psql.Quote(append(prefix, "starting_balance")...),
			psql.Arg(s.StartingBalance),
		}})
	}

	if s.CreatedAt.IsValue() {
		exprs = append(exprs, expr.Join{Sep: " = ", Exprs: []bob.Expression{
			psql.Quote(append(prefix, "created_at")...),
			psql.Arg(s.CreatedAt),
		}})
	}

	return exprs
}

// scan.Mapper[*T] without reflection: maps columns to fields by index.
func accountScanMapper(ctx context.Context, cols []string) (scan.BeforeFunc, func(any) (*Account, error)) {
	// resolve the column positions once per query, not per row
	type target struct {
		idx int
		dst func(o *Account) any
	}
	targets := make([]target, 0, 7)
	for i, col := range cols {
		switch col {
		case "id":
			targets = append(targets, target{i, func(o *Account) any { return &o.ID }})
		case "name":
			targets = append(targets, target{i, func(o *Account) any { return &o.Name }})
		case "type":
			targets = append(targets, target{i, func(o *Account) any { return &o.Type }})
		case "sub_type":
			targets = append(targets, target{i, func(o *Account) any { return &o.SubType }})
		case "balance":
			targets = append(targets, target{i, func(o *Account) any { return &o.Balance }})
		case "starting_balance":
			targets = append(targets, target{i, func(o *Account) any { return &o.StartingBalance }})
		case "created_at":
			targets = append(targets, target{i, func(o *Account) any { return &o.CreatedAt }})
		}
	}

	return func(row *scan.Row) (any, error) {
			o := new(Account)
			for _, t := range targets {
				row.ScheduleScanByIndex(t.idx, t.dst(o))
			}
			return o, nil
		}, func(v any) (*Account, error) {
			return v.(*Account), nil
		}
}

// FindAccount retrieves a single record by primary key
// If cols is empty Find will return all columns.
func FindAccount(ctx context.Context, exec bob.Executor, IDPK uuid.UUID, cols ...string) (*Account, error) {
	if len(cols) == 0 {
		return Accounts.Query(
			sm.Where(Accounts.Columns.ID.EQ(psql.Arg(IDPK))),
		).One(ctx, exec)
	}

	return Accounts.Query(
		sm.Where(Accounts.Columns.ID.EQ(psql.Arg(IDPK))),
		sm.Columns(Accounts.Columns.Only(cols...)),
	).One(ctx, exec)
}

// AccountExists checks the presence of a single record by primary key
func AccountExists(ctx context.Context, exec bob.Executor, IDPK uuid.UUID) (bool, error) {
	return Accounts.Query(
		sm.Where(Accounts.Columns.ID.EQ(psql.Arg(IDPK))),
	).Exists(ctx, exec)
}

// AfterQueryHook is called after Account is retrieved from the database
func (o *Account) AfterQueryHook(ctx context.Context, exec bob.Executor, queryType bob.QueryType) error {
	var err error

	switch queryType {
	case bob.QueryTypeSelect:
		ctx, err = Accounts.AfterSelectHooks.RunHooks(ctx, exec, AccountSlice{o})
	case bob.QueryTypeInsert:
		ctx, err = Accounts.AfterInsertHooks.RunHooks(ctx, exec, AccountSlice{o})
	case bob.QueryTypeUpdate:
		ctx, err = Accounts.AfterUpdateHooks.RunHooks(ctx, exec, AccountSlice{o})
	case bob.QueryTypeDelete:
		ctx, err = Accounts.AfterDeleteHooks.RunHooks(ctx, exec, AccountSlice{o})
	case bob.QueryTypeMerge:
		ctx, err = Accounts.AfterMergeHooks.RunHooks(ctx, exec, AccountSlice{o})
	}

	return err
}

// primaryKeyVals returns the primary key values of the Account
func (o *Account) primaryKeyVals() bob.Expression {
	return psql.Arg(o.ID)
}

func (o *Account) pkEQ() dialect.Expression {
	return psql.Quote("accounts", "id").EQ(bob.ExpressionFunc(func(ctx context.Context, w io.StringWriter, d bob.Dialect, start int) ([]any, error) {
		return o.primaryKeyVals().WriteSQL(ctx, w, d, start)
	}))
}

// Update uses an executor to update the Account
func (o *Account) Update(ctx context.Context, exec bob.Executor, s *AccountSetter) error {
	v, err := Accounts.Update(s.UpdateMod(), um.Where(o.pkEQ())).One(ctx, exec)
	if err != nil {
		return err
	}

	o.R = v.R
	*o = *v

	return nil
}

// Delete deletes a single Account record with an executor
func (o *Account) Delete(ctx context.Context, exec bob.Executor) error {
	_, err := Accounts.Delete(dm.Where(o.pkEQ())).Exec(ctx, exec)
	return err
}

// Reload refreshes the Account using the executor
func (o *Account) Reload(ctx context.Context, exec bob.Executor) error {
	o2, err := Accounts.Query(
		sm.Where(Accounts.Columns.ID.EQ(psql.Arg(o.ID))),
	).One(ctx, exec)
	if err != nil {
		return err
	}
	o2.R = o.R
	*o = *o2

	return nil
}

// AfterQueryHook is called after AccountSlice is retrieved from the database
func (o AccountSlice) AfterQueryHook(ctx context.Context, exec bob.Executor, queryType bob.QueryType) error {
	var err error

	switch queryType {
	case bob.QueryTypeSelect:
		ctx, err = Accounts.AfterSelectHooks.RunHooks(ctx, exec, o)
	case bob.QueryTypeInsert:
		ctx, err = Accounts.AfterInsertHooks.RunHooks(ctx, exec, o)
	case bob.QueryTypeUpdate:
		ctx, err = Accounts.AfterUpdateHooks.RunHooks(ctx, exec, o)
	case bob.QueryTypeDelete:
		ctx, err = Accounts.AfterDeleteHooks.RunHooks(ctx, exec, o)
	case bob.QueryTypeMerge:
		ctx, err = Accounts.AfterMergeHooks.RunHooks(ctx, exec, o)
	}

	return err
}

func (o AccountSlice) pkIN() dialect.Expression {
	if len(o) == 0 {
		return psql.Raw("NULL")
	}

	return psql.Quote("accounts", "id").In(bob.ExpressionFunc(func(ctx context.Context, w io.StringWriter, d bob.Dialect, start int) ([]any, error) {
		pkPairs := make([]bob.Expression, len(o))
		for i, row := range o {
			pkPairs[i] = row.primaryKeyVals()
		}
		return bob.ExpressSlice(ctx, w, d, start, pkPairs, "", ", ", "")
	}))
}

// copyMatchingRows finds models in the given slice that have the same primary key
// then it first copies the existing relationships from the old model to the new model
// and then replaces the old model in the slice with the new model
func (o AccountSlice) copyMatchingRows(from ...*Account) {
	fromByPK := make(map[uuid.UUID]*Account, len(from))
	for _, new := range from {
		// keep the first row for each key, like the nested loop did
		if _, ok := fromByPK[new.ID]; !ok {
			fromByPK[new.ID] = new
		}
	}

	for i, old := range o {
		new, ok := fromByPK[old.ID]
		if !ok {
			continue
		}
		new.R = old.R
		o[i] = new
	}
}

// UpdateMod modifies an update query with "WHERE primary_key IN (o...)"
func (o AccountSlice) UpdateMod() bob.Mod[*dialect.UpdateQuery] {
	return bob.ModFunc[*dialect.UpdateQuery](func(q *dialect.UpdateQuery) {
		q.AppendHooks(func(ctx context.Context, exec bob.Executor) (context.Context, error) {
			return Accounts.BeforeUpdateHooks.RunHooks(ctx, exec, o)
		})

		q.AppendLoader(bob.LoaderFunc(func(ctx context.Context, exec bob.Executor, retrieved any) error {
			var err error
			switch retrieved := retrieved.(type) {
			case *Account:
				o.copyMatchingRows(retrieved)
			case []*Account:
				o.copyMatchingRows(retrieved...)
			case AccountSlice:
				o.copyMatchingRows(retrieved...)
			default:
				// If the retrieved value is not a Account or a slice of Account
				// then run the AfterUpdateHooks on the slice
				_, err = Accounts.AfterUpdateHooks.RunHooks(ctx, exec, o)
			}

			return err
		}))

		q.AppendWhere(o.pkIN())
	})
}

// DeleteMod modifies an delete query with "WHERE primary_key IN (o...)"
func (o AccountSlice) DeleteMod() bob.Mod[*dialect.DeleteQuery] {
	return bob.ModFunc[*dialect.DeleteQuery](func(q *dialect.DeleteQuery) {
		q.AppendHooks(func(ctx context.Context, exec bob.Executor) (context.Context, error) {
			return Accounts.BeforeDeleteHooks.RunHooks(ctx, exec, o)
		})

		q.AppendLoader(bob.LoaderFunc(func(ctx context.Context, exec bob.Executor, retrieved any) error {
			var err error
			switch retrieved := retrieved.(type) {
			case *Account:
				o.copyMatchingRows(retrieved)
			case []*Account:
				o.copyMatchingRows(retrieved...)
			case AccountSlice:
				o.copyMatchingRows(retrieved...)
			default:
				// If the retrieved value is not a Account or a slice of Account
				// then run the AfterDeleteHooks on the slice
				_, err = Accounts.AfterDeleteHooks.RunHooks(ctx, exec, o)
			}

			return err
		}))

		q.AppendWhere(o.pkIN())
	})
}

// MergeMod modifies a merge query to run BeforeMergeHooks and AfterMergeHooks
// and updates the slice with the returned rows.
func (o AccountSlice) MergeMod() bob.Mod[*dialect.MergeQuery] {
	return bob.ModFunc[*dialect.MergeQuery](func(q *dialect.MergeQuery) {
		q.AppendHooks(func(ctx context.Context, exec bob.Executor) (context.Context, error) {
			return Accounts.BeforeMergeHooks.RunHooks(ctx, exec, o)
		})

		q.AppendLoader(bob.LoaderFunc(func(ctx context.Context, exec bob.Executor, retrieved any) error {
			var err error
			switch retrieved := retrieved.(type) {
			case *Account:
				o.copyMatchingRows(retrieved)
			case []*Account:
				o.copyMatchingRows(retrieved...)
			case AccountSlice:
				o.copyMatchingRows(retrieved...)
			default:
				// If the retrieved value is not a Account or a slice of Account
				// then run the AfterMergeHooks on the slice
				_, err = Accounts.AfterMergeHooks.RunHooks(ctx, exec, o)
			}

			return err
		}))
	})
}

func (o AccountSlice) UpdateAll(ctx context.Context, exec bob.Executor, vals AccountSetter) error {
	if len(o) == 0 {
		return nil
	}

	_, err := Accounts.Update(vals.UpdateMod(), o.UpdateMod()).All(ctx, exec)
	return err
}

func (o AccountSlice) DeleteAll(ctx context.Context, exec bob.Executor) error {
	if len(o) == 0 {
		return nil
	}

	_, err := Accounts.Delete(o.DeleteMod()).Exec(ctx, exec)
	return err
}

func (o AccountSlice) ReloadAll(ctx context.Context, exec bob.Executor) error {
	if len(o) == 0 {
		return nil
	}

	o2, err := Accounts.Query(sm.Where(o.pkIN())).All(ctx, exec)
	if err != nil {
		return err
	}

	o.copyMatchingRows(o2...)

	return nil
}

// PlaidAccountLinks starts a query for related objects on plaid_account_links
func (o *Account) PlaidAccountLinks(mods ...bob.Mod[*dialect.SelectQuery]) PlaidAccountLinksQuery {
	return PlaidAccountLinks.Query(append(mods,
		sm.Where(PlaidAccountLinks.Columns.AccountID.EQ(psql.Arg(o.ID))),
	)...)
}

func (os AccountSlice) PlaidAccountLinks(mods ...bob.Mod[*dialect.SelectQuery]) PlaidAccountLinksQuery {
	pkID := make(pgtypes.Array[uuid.UUID], 0, len(os))

	for _, o := range os {
		if o == nil {
			continue
		}
		pkID = append(pkID, o.ID)
	}
	PKArgExpr := psql.Any(psql.Cast(psql.Arg(pkID), "uuid[]"))

	return PlaidAccountLinks.Query(append(mods,
		sm.Where(PlaidAccountLinks.Columns.AccountID.EQ(PKArgExpr)),
	)...)
}

// Sync starts a query for related objects on syncs
func (o *Account) Sync(mods ...bob.Mod[*dialect.SelectQuery]) SyncsQuery {
	return Syncs.Query(append(mods,
		sm.Where(Syncs.Columns.AccountID.EQ(psql.Arg(o.ID))),
	)...)
}

func (os AccountSlice) Sync(mods ...bob.Mod[*dialect.SelectQuery]) SyncsQuery {
	pkID := make(pgtypes.Array[uuid.UUID], 0, len(os))

	for _, o := range os {
		if o == nil {
			continue
		}
		pkID = append(pkID, o.ID)
	}
	PKArgExpr := psql.Any(psql.Cast(psql.Arg(pkID), "uuid[]"))

	return Syncs.Query(append(mods,
		sm.Where(Syncs.Columns.AccountID.EQ(PKArgExpr)),
	)...)
}

func insertAccountPlaidAccountLinks0(ctx context.Context, exec bob.Executor, plaidAccountLinks1 []*PlaidAccountLinkSetter, account0 *Account) (PlaidAccountLinkSlice, error) {
	for i := range plaidAccountLinks1 {
		plaidAccountLinks1[i].AccountID = omit.From(account0.ID)
	}

	ret, err := PlaidAccountLinks.Insert(bob.ToMods(plaidAccountLinks1...)).All(ctx, exec)
	if err != nil {
		return ret, fmt.Errorf("insertAccountPlaidAccountLinks0: %w", err)
	}

	return ret, nil
}

func attachAccountPlaidAccountLinks0(ctx context.Context, exec bob.Executor, count int, plaidAccountLinks1 PlaidAccountLinkSlice, account0 *Account) (PlaidAccountLinkSlice, error) {
	setter := &PlaidAccountLinkSetter{
		AccountID: omit.From(account0.ID),
	}

	err := plaidAccountLinks1.UpdateAll(ctx, exec, *setter)
	if err != nil {
		return nil, fmt.Errorf("attachAccountPlaidAccountLinks0: %w", err)
	}

	return plaidAccountLinks1, nil
}

func (account0 *Account) InsertPlaidAccountLinks(ctx context.Context, exec bob.Executor, related ...*PlaidAccountLinkSetter) error {
	if len(related) == 0 {
		return nil
	}

	var err error

	plaidAccountLinks1, err := insertAccountPlaidAccountLinks0(ctx, exec, related, account0)
	if err != nil {
		return err
	}

	account0.R.PlaidAccountLinks = append(account0.R.PlaidAccountLinks, plaidAccountLinks1...)

	for _, rel := range plaidAccountLinks1 {
		rel.R.Account = account0
		rel.R.Loaded.Account = true
	}
	return nil
}

func (account0 *Account) AttachPlaidAccountLinks(ctx context.Context, exec bob.Executor, related ...*PlaidAccountLink) error {
	if len(related) == 0 {
		return nil
	}

	var err error
	plaidAccountLinks1 := PlaidAccountLinkSlice(related)

	_, err = attachAccountPlaidAccountLinks0(ctx, exec, len(related), plaidAccountLinks1, account0)
	if err != nil {
		return err
	}

	account0.R.PlaidAccountLinks = append(account0.R.PlaidAccountLinks, plaidAccountLinks1...)

	for _, rel := range related {
		rel.R.Account = account0
		rel.R.Loaded.Account = true
	}

	return nil
}

func insertAccountSync0(ctx context.Context, exec bob.Executor, sync1 *SyncSetter, account0 *Account) (*Sync, error) {
	sync1.AccountID = omit.From(account0.ID)

	ret, err := Syncs.Insert(sync1).One(ctx, exec)
	if err != nil {
		return ret, fmt.Errorf("insertAccountSync0: %w", err)
	}

	return ret, nil
}

func attachAccountSync0(ctx context.Context, exec bob.Executor, count int, sync1 *Sync, account0 *Account) (*Sync, error) {
	setter := &SyncSetter{
		AccountID: omit.From(account0.ID),
	}

	err := sync1.Update(ctx, exec, setter)
	if err != nil {
		return nil, fmt.Errorf("attachAccountSync0: %w", err)
	}

	return sync1, nil
}

func (account0 *Account) InsertSync(ctx context.Context, exec bob.Executor, related *SyncSetter) error {
	var err error

	sync1, err := insertAccountSync0(ctx, exec, related, account0)
	if err != nil {
		return err
	}

	account0.R.Sync = sync1
	account0.R.Loaded.Sync = true

	sync1.R.Account = account0
	sync1.R.Loaded.Account = true

	return nil
}

func (account0 *Account) AttachSync(ctx context.Context, exec bob.Executor, sync1 *Sync) error {
	var err error

	_, err = attachAccountSync0(ctx, exec, 1, sync1, account0)
	if err != nil {
		return err
	}

	account0.R.Sync = sync1
	account0.R.Loaded.Sync = true

	sync1.R.Account = account0
	sync1.R.Loaded.Account = true

	return nil
}

type accountWhere[Q psql.Filterable] struct {
	cols            accountColumns
	ID              psql.WhereMod[Q, uuid.UUID]
	Name            psql.WhereMod[Q, string]
	Type            psql.WhereMod[Q, int16]
	SubType         psql.WhereMod[Q, string]
	Balance         psql.WhereMod[Q, decimal.Decimal]
	StartingBalance psql.WhereMod[Q, decimal.Decimal]
	CreatedAt       psql.WhereMod[Q, time.Time]
	R               accountWhereR[Q]
}

func (accountWhere[Q]) AliasedAs(alias string) accountWhere[Q] {
	return buildAccountWhere[Q](buildAccountColumns(alias))
}

func buildAccountWhere[Q psql.Filterable](cols accountColumns) accountWhere[Q] {
	return accountWhere[Q]{
		cols:            cols,
		ID:              psql.Where[Q, uuid.UUID](cols.ID.Expression),
		Name:            psql.Where[Q, string](cols.Name.Expression),
		Type:            psql.Where[Q, int16](cols.Type.Expression),
		SubType:         psql.Where[Q, string](cols.SubType.Expression),
		Balance:         psql.Where[Q, decimal.Decimal](cols.Balance.Expression),
		StartingBalance: psql.Where[Q, decimal.Decimal](cols.StartingBalance.Expression),
		CreatedAt:       psql.Where[Q, time.Time](cols.CreatedAt.Expression),
		R:               accountWhereR[Q]{cols: cols},
	}
}

// accountWhereR holds the relationship-based filters of
// accountWhere under the R namespace — mirroring the model's
// R struct — so they cannot collide with column-based filter fields.
type accountWhereR[Q psql.Filterable] struct {
	cols accountColumns
}

// HasPlaidAccountLinks filters parents that have a matching PlaidAccountLinks using a
// correlated EXISTS subquery (semi-join). Unlike an INNER JOIN it does not
// multiply parent rows, so no DISTINCT is needed. The optional filters are
// applied to the subquery (i.e. to PlaidAccountLinks).
func (w accountWhereR[Q]) HasPlaidAccountLinks(filters ...bob.Mod[*dialect.SelectQuery]) mods.Where[Q] {
	q := psql.Select(
		sm.Columns(psql.Raw("1")),
		sm.From(PlaidAccountLinks.NameExpr()),
		sm.Where(PlaidAccountLinks.Columns.AccountID.EQ(w.cols.ID)),
	)
	q.Apply(filters...)
	return mods.Where[Q]{E: psql.Exists(q)}
}

// HasSync filters parents that have a matching Sync using a
// correlated EXISTS subquery (semi-join). Unlike an INNER JOIN it does not
// multiply parent rows, so no DISTINCT is needed. The optional filters are
// applied to the subquery (i.e. to Syncs).
func (w accountWhereR[Q]) HasSync(filters ...bob.Mod[*dialect.SelectQuery]) mods.Where[Q] {
	q := psql.Select(
		sm.Columns(psql.Raw("1")),
		sm.From(Syncs.NameExpr()),
		sm.Where(Syncs.Columns.AccountID.EQ(w.cols.ID)),
	)
	q.Apply(filters...)
	return mods.Where[Q]{E: psql.Exists(q)}
}

// NULL-tolerant scan buffer for accountScanMapperNullable:
// on a LEFT JOIN miss every column comes back NULL, so each field uses the
// nullable version of the column type even when the column itself is NOT NULL.
type accountPreloadBuf struct {
	ID              null.Val[uuid.UUID]
	Name            null.Val[string]
	Type            null.Val[int16]
	SubType         null.Val[string]
	Balance         null.Val[decimal.Decimal]
	StartingBalance null.Val[decimal.Decimal]
	CreatedAt       null.Val[time.Time]
}

// accountScanMapperNullable maps the preloaded account
// columns (prefixed with the runtime join alias) without reflection, while
// keeping the LEFT JOIN semantics of the reflection-based mapper: a row whose
// prefixed columns are all NULL yields nil (no child), and NULL values never
// error, they just leave the zero value in the field.
func accountScanMapperNullable(prefix string) scan.Mapper[*Account] {
	return func(ctx context.Context, cols []string) (scan.BeforeFunc, func(any) (*Account, error)) {
		// resolve the column names once per query, not per row
		type target struct {
			idx int
			dst func(b *accountPreloadBuf) any
		}
		targets := make([]target, 0, 7)
		for i, col := range cols {
			name, ok := strings.CutPrefix(col, prefix)
			if !ok {
				continue
			}
			switch name {
			case "id":
				targets = append(targets, target{i, func(b *accountPreloadBuf) any { return &b.ID }})
			case "name":
				targets = append(targets, target{i, func(b *accountPreloadBuf) any { return &b.Name }})
			case "type":
				targets = append(targets, target{i, func(b *accountPreloadBuf) any { return &b.Type }})
			case "sub_type":
				targets = append(targets, target{i, func(b *accountPreloadBuf) any { return &b.SubType }})
			case "balance":
				targets = append(targets, target{i, func(b *accountPreloadBuf) any { return &b.Balance }})
			case "starting_balance":
				targets = append(targets, target{i, func(b *accountPreloadBuf) any { return &b.StartingBalance }})
			case "created_at":
				targets = append(targets, target{i, func(b *accountPreloadBuf) any { return &b.CreatedAt }})
			}
		}

		// One scratch buffer reused for every row: before -> scan -> after runs
		// synchronously per row, the scheduled columns are fully overwritten each
		// row, and unselected columns stay zero, so a single buffer preserves the
		// per-row NULL semantics without allocating a buffer per parent row. The
		// returned child (o below) is always freshly allocated, so buf never
		// escapes past the after func.
		buf := new(accountPreloadBuf)
		return func(row *scan.Row) (any, error) {
				for _, t := range targets {
					row.ScheduleScanByIndex(t.idx, t.dst(buf))
				}
				return buf, nil
			}, func(link any) (*Account, error) {
				buf := link.(*accountPreloadBuf)

				// Same rule as the reflection mapper's row validator: the child
				// exists only if at least one of its columns is not NULL. Columns
				// not selected by the query are never scanned and stay invalid,
				// so this check also matches when only a subset is selected.
				if !(buf.ID.IsValue()) &&
					!(buf.Name.IsValue()) &&
					!(buf.Type.IsValue()) &&
					!(buf.SubType.IsValue()) &&
					!(buf.Balance.IsValue()) &&
					!(buf.StartingBalance.IsValue()) &&
					!(buf.CreatedAt.IsValue()) {
					return nil, nil
				}

				o := new(Account)
				if buf.ID.IsValue() {
					o.ID = buf.ID.MustGet()
				}
				if buf.Name.IsValue() {
					o.Name = buf.Name.MustGet()
				}
				if buf.Type.IsValue() {
					o.Type = buf.Type.MustGet()
				}
				if buf.SubType.IsValue() {
					o.SubType = buf.SubType.MustGet()
				}
				if buf.Balance.IsValue() {
					o.Balance = buf.Balance.MustGet()
				}
				if buf.StartingBalance.IsValue() {
					o.StartingBalance = buf.StartingBalance.MustGet()
				}
				if buf.CreatedAt.IsValue() {
					o.CreatedAt = buf.CreatedAt.MustGet()
				}
				return o, nil
			}
	}
}

func (o *Account) Preload(name string, retrieved any) error {
	if o == nil {
		return nil
	}

	switch name {
	case "PlaidAccountLinks":
		rels, ok := retrieved.(PlaidAccountLinkSlice)
		if !ok {
			return fmt.Errorf("account cannot load %T as %q", retrieved, name)
		}

		o.R.PlaidAccountLinks = rels
		o.R.Loaded.PlaidAccountLinks = true

		for _, rel := range rels {
			if rel != nil {
				rel.R.Account = o
				rel.R.Loaded.Account = true
			}
		}
		return nil
	case "Sync":
		rel, ok := retrieved.(*Sync)
		if !ok {
			return fmt.Errorf("account cannot load %T as %q", retrieved, name)
		}

		o.R.Sync = rel
		o.R.Loaded.Sync = true

		if rel != nil {
			rel.R.Account = o
			rel.R.Loaded.Account = true
		}
		return nil
	default:
		return fmt.Errorf("account has no relationship %q", name)
	}
}

type accountPreloader struct {
	Sync func(...psql.PreloadOption) psql.Preloader
}

func buildAccountPreloader() accountPreloader {
	return accountPreloader{
		Sync: func(opts ...psql.PreloadOption) psql.Preloader {
			return psql.Preload[*Sync, SyncSlice](psql.PreloadRel{
				Name: "Sync",
				Sides: []psql.PreloadSide{
					{
						From:        Accounts,
						To:          Syncs,
						FromColumns: []string{"id"},
						ToColumns:   []string{"account_id"},
					},
				},
			}, Syncs.Columns.Names(), syncScanMapperNullable, opts...)
		},
	}
}

type accountThenLoader[Q orm.Loadable] struct {
	PlaidAccountLinks func(...bob.Mod[*dialect.SelectQuery]) orm.Loader[Q]
	Sync              func(...bob.Mod[*dialect.SelectQuery]) orm.Loader[Q]
}

func buildAccountThenLoader[Q orm.Loadable]() accountThenLoader[Q] {
	type PlaidAccountLinksLoadInterface interface {
		LoadPlaidAccountLinks(context.Context, bob.Executor, ...bob.Mod[*dialect.SelectQuery]) error
	}
	type SyncLoadInterface interface {
		LoadSync(context.Context, bob.Executor, ...bob.Mod[*dialect.SelectQuery]) error
	}

	return accountThenLoader[Q]{
		PlaidAccountLinks: thenLoadBuilder[Q](
			"PlaidAccountLinks",
			func(ctx context.Context, exec bob.Executor, retrieved PlaidAccountLinksLoadInterface, mods ...bob.Mod[*dialect.SelectQuery]) error {
				return retrieved.LoadPlaidAccountLinks(ctx, exec, mods...)
			},
		),
		Sync: thenLoadBuilder[Q](
			"Sync",
			func(ctx context.Context, exec bob.Executor, retrieved SyncLoadInterface, mods ...bob.Mod[*dialect.SelectQuery]) error {
				return retrieved.LoadSync(ctx, exec, mods...)
			},
		),
	}
}

// LoadPlaidAccountLinks loads the account's PlaidAccountLinks into the .R struct
func (o *Account) LoadPlaidAccountLinks(ctx context.Context, exec bob.Executor, mods ...bob.Mod[*dialect.SelectQuery]) error {
	if o == nil {
		return nil
	}

	// Reset the relationship
	o.R.PlaidAccountLinks = nil
	o.R.Loaded.PlaidAccountLinks = false

	related, err := o.PlaidAccountLinks(mods...).All(ctx, exec)
	if err != nil {
		return err
	}

	for _, rel := range related {
		rel.R.Account = o
		rel.R.Loaded.Account = true
	}

	o.R.PlaidAccountLinks = related
	o.R.Loaded.PlaidAccountLinks = true
	return nil
}

// LoadPlaidAccountLinks loads the account's PlaidAccountLinks into the .R struct
func (os AccountSlice) LoadPlaidAccountLinks(ctx context.Context, exec bob.Executor, mods ...bob.Mod[*dialect.SelectQuery]) error {
	if len(os) == 0 {
		return nil
	}

	plaidAccountLinks, err := os.PlaidAccountLinks(mods...).All(ctx, exec)
	if err != nil {
		return err
	}

	for _, o := range os {
		if o == nil {
			continue
		}

		o.R.PlaidAccountLinks = nil
		o.R.Loaded.PlaidAccountLinks = true
	}
	// O(N+M) stitch via a map keyed by the join column (key -> []parent; was O(N*M)).
	accountByKey := make(map[uuid.UUID][]*Account, len(os))
	for _, o := range os {
		if o == nil {
			continue
		}

		accountByKey[o.ID] = append(accountByKey[o.ID], o)
	}

	for _, rel := range plaidAccountLinks {

		owners, ok := accountByKey[rel.AccountID]
		if !ok {
			continue
		}

		for _, o := range owners {

			rel.R.Account = o
			rel.R.Loaded.Account = true

			o.R.PlaidAccountLinks = append(o.R.PlaidAccountLinks, rel)

		}
	}

	return nil
}

// LoadSync loads the account's Sync into the .R struct
func (o *Account) LoadSync(ctx context.Context, exec bob.Executor, mods ...bob.Mod[*dialect.SelectQuery]) error {
	if o == nil {
		return nil
	}

	// Reset the relationship
	o.R.Sync = nil
	o.R.Loaded.Sync = false

	related, err := o.Sync(mods...).One(ctx, exec)
	if err != nil {
		return err
	}

	related.R.Account = o
	related.R.Loaded.Account = true

	o.R.Sync = related
	o.R.Loaded.Sync = true
	return nil
}

// LoadSync loads the account's Sync into the .R struct
func (os AccountSlice) LoadSync(ctx context.Context, exec bob.Executor, mods ...bob.Mod[*dialect.SelectQuery]) error {
	if len(os) == 0 {
		return nil
	}

	syncs, err := os.Sync(mods...).All(ctx, exec)
	if err != nil {
		return err
	}

	for _, o := range os {
		if o == nil {
			continue
		}

		o.R.Sync = nil
		o.R.Loaded.Sync = true
	}
	// O(N+M) stitch via a map keyed by the join column (key -> []parent; was O(N*M)).
	accountByKey := make(map[uuid.UUID][]*Account, len(os))
	for _, o := range os {
		if o == nil {
			continue
		}

		accountByKey[o.ID] = append(accountByKey[o.ID], o)
	}

	for _, rel := range syncs {

		owners, ok := accountByKey[rel.AccountID]
		if !ok {
			continue
		}

		for _, o := range owners {

			// to-one: keep only the first matching child (matches the previous break)
			if o.R.Sync != nil {
				continue
			}

			rel.R.Account = o
			rel.R.Loaded.Account = true

			o.R.Sync = rel

		}
	}

	return nil
}

// accountC is where relationship counts are stored.
type accountC struct {
	PlaidAccountLinks *int64
}

// PreloadCount sets a count in the C struct by name
func (o *Account) PreloadCount(name string, count int64) error {
	if o == nil {
		return nil
	}

	switch name {
	case "PlaidAccountLinks":
		o.C.PlaidAccountLinks = &count
	}
	return nil
}

type accountCountPreloader struct {
	PlaidAccountLinks func(...bob.Mod[*dialect.SelectQuery]) psql.Preloader
}

func buildAccountCountPreloader() accountCountPreloader {
	return accountCountPreloader{
		PlaidAccountLinks: func(mods ...bob.Mod[*dialect.SelectQuery]) psql.Preloader {
			return countPreloader[*Account]("PlaidAccountLinks", func(parent string) bob.Expression {
				// Build a correlated subquery: (SELECT COUNT(*) FROM related WHERE fk = parent.pk)
				if parent == "" {
					parent = Accounts.Alias()
				}

				subqueryMods := []bob.Mod[*dialect.SelectQuery]{
					sm.Columns(psql.Raw("count(*)")),

					sm.From(PlaidAccountLinks.NameAsExpr()),
					sm.Where(psql.Quote(PlaidAccountLinks.Alias(), "account_id").EQ(psql.Quote(parent, "id"))),
				}
				subqueryMods = append(subqueryMods, mods...)
				return psql.Group(psql.Select(subqueryMods...).Expression)
			})
		},
	}
}

type accountCountThenLoader[Q orm.Loadable] struct {
	PlaidAccountLinks func(...bob.Mod[*dialect.SelectQuery]) orm.Loader[Q]
}

func buildAccountCountThenLoader[Q orm.Loadable]() accountCountThenLoader[Q] {
	type PlaidAccountLinksCountInterface interface {
		LoadCountPlaidAccountLinks(context.Context, bob.Executor, ...bob.Mod[*dialect.SelectQuery]) error
	}

	return accountCountThenLoader[Q]{
		PlaidAccountLinks: countThenLoadBuilder[Q](
			"PlaidAccountLinks",
			func(ctx context.Context, exec bob.Executor, retrieved PlaidAccountLinksCountInterface, mods ...bob.Mod[*dialect.SelectQuery]) error {
				return retrieved.LoadCountPlaidAccountLinks(ctx, exec, mods...)
			},
		),
	}
}

// LoadCountPlaidAccountLinks loads the count of PlaidAccountLinks into the C struct
func (o *Account) LoadCountPlaidAccountLinks(ctx context.Context, exec bob.Executor, mods ...bob.Mod[*dialect.SelectQuery]) error {
	if o == nil {
		return nil
	}

	count, err := o.PlaidAccountLinks(mods...).Count(ctx, exec)
	if err != nil {
		return err
	}

	o.C.PlaidAccountLinks = &count
	return nil
}

// LoadCountPlaidAccountLinks loads the count of PlaidAccountLinks for a slice in a single batch query
func (os AccountSlice) LoadCountPlaidAccountLinks(ctx context.Context, exec bob.Executor, mods ...bob.Mod[*dialect.SelectQuery]) error {
	if len(os) == 0 {
		return nil
	}

	// Build the IN arg expression from parent PKs

	pkID := make(pgtypes.Array[uuid.UUID], 0, len(os))
	for _, o := range os {
		if o == nil {
			continue
		}
		pkID = append(pkID, o.ID)
	}
	PKArgExpr := psql.Any(psql.Cast(psql.Arg(pkID), "uuid[]"))

	// countResult holds one scanned row from the batch count query.
	// FK columns are aliased to the parent PK column names for direct map lookup.
	type countResult struct {
		ID    uuid.UUID
		Count int64
	}

	batchMods := []bob.Mod[*dialect.SelectQuery]{
		// SELECT fk AS parent_pk, count(*)
		sm.Columns(
			PlaidAccountLinks.Columns.AccountID.As("id"),
			psql.Raw("count(*) as count"),
		),
		// Single-hop: FROM related table directly
		sm.From(PlaidAccountLinks.NameAsExpr()),

		// WHERE fk IN (parent PKs) — psql single-column FK uses `= ANY(array)` (see PKArgExpr above)
		sm.Where(PlaidAccountLinks.Columns.AccountID.EQ(PKArgExpr)),
		// GROUP BY fk columns
		sm.GroupBy(PlaidAccountLinks.Columns.AccountID),
	}
	batchMods = append(batchMods, mods...)

	results, err := bob.All(ctx, exec,
		psql.Select(batchMods...),
		scan.StructMapper[countResult](),
	)
	if err != nil {
		return err
	}

	// Single-column FK: direct map lookup
	countMap := make(map[uuid.UUID]int64, len(results))
	for _, r := range results {
		countMap[r.ID] = r.Count
	}
	for _, o := range os {
		if o == nil {
			continue
		}
		count := countMap[o.ID]
		o.C.PlaidAccountLinks = &count
	}

	return nil
}

type accountJoins[Q dialect.Joinable] struct {
	typ               string
	PlaidAccountLinks modAs[Q, plaidAccountLinkColumns]
	Sync              modAs[Q, syncColumns]
}

func (j accountJoins[Q]) aliasedAs(alias string) accountJoins[Q] {
	return buildAccountJoins[Q](buildAccountColumns(alias), j.typ)
}

func buildAccountJoins[Q dialect.Joinable](cols accountColumns, typ string) accountJoins[Q] {
	return accountJoins[Q]{
		typ: typ,
		PlaidAccountLinks: modAs[Q, plaidAccountLinkColumns]{
			c: PlaidAccountLinks.Columns,
			f: func(to plaidAccountLinkColumns) bob.Mod[Q] {
				mods := make(mods.QueryMods[Q], 0, 1)

				{
					mods = append(mods, dialect.Join[Q](typ, PlaidAccountLinks.NameExpr().As(to.Alias())).On(
						to.AccountID.EQ(cols.ID),
					))
				}

				return mods
			},
		},
		Sync: modAs[Q, syncColumns]{
			c: Syncs.Columns,
			f: func(to syncColumns) bob.Mod[Q] {
				mods := make(mods.QueryMods[Q], 0, 1)

				{
					mods = append(mods, dialect.Join[Q](typ, Syncs.NameExpr().As(to.Alias())).On(
						to.AccountID.EQ(cols.ID),
					))
				}

				return mods
			},
		},
	}
}
