// Code generated by BobGen psql v0.42.0. DO NOT EDIT.
// This file is meant to be re-generated in place and/or deleted at any time.

package bobgen

import (
	"context"
	"io"

	"github.com/aarondl/opt/omit"
	"github.com/gofrs/uuid/v5"
	"github.com/shopspring/decimal"
	"github.com/stephenafamo/bob"
	"github.com/stephenafamo/bob/dialect/psql"
	"github.com/stephenafamo/bob/dialect/psql/dialect"
	"github.com/stephenafamo/bob/dialect/psql/dm"
	"github.com/stephenafamo/bob/dialect/psql/sm"
	"github.com/stephenafamo/bob/dialect/psql/um"
	"github.com/stephenafamo/bob/expr"
)

// Account is an object representing the database table.
type Account struct {
	ID      uuid.UUID       `db:"id,pk" `
	Name    string          `db:"name" `
	Type    int16           `db:"type" `
	SubType string          `db:"sub_type" `
	Balance decimal.Decimal `db:"balance" `
}

// AccountSlice is an alias for a slice of pointers to Account.
// This should almost always be used instead of []*Account.
type AccountSlice []*Account

// Accounts contains methods to work with the accounts table
var Accounts = psql.NewTablex[*Account, AccountSlice, *AccountSetter]("", "accounts", buildAccountColumns("accounts"))

// AccountsQuery is a query on the accounts table
type AccountsQuery = *psql.ViewQuery[*Account, AccountSlice]

func buildAccountColumns(alias string) accountColumns {
	return accountColumns{
		ColumnsExpr: expr.NewColumnsExpr(
			"id", "name", "type", "sub_type", "balance",
		).WithParent("accounts"),
		tableAlias: alias,
		ID:         psql.Quote(alias, "id"),
		Name:       psql.Quote(alias, "name"),
		Type:       psql.Quote(alias, "type"),
		SubType:    psql.Quote(alias, "sub_type"),
		Balance:    psql.Quote(alias, "balance"),
	}
}

type accountColumns struct {
	expr.ColumnsExpr
	tableAlias string
	ID         psql.Expression
	Name       psql.Expression
	Type       psql.Expression
	SubType    psql.Expression
	Balance    psql.Expression
}

func (c accountColumns) Alias() string {
	return c.tableAlias
}

func (accountColumns) AliasedAs(alias string) accountColumns {
	return buildAccountColumns(alias)
}

// AccountSetter is used for insert/upsert/update operations
// All values are optional, and do not have to be set
// Generated columns are not included
type AccountSetter struct {
	ID      omit.Val[uuid.UUID]       `db:"id,pk" `
	Name    omit.Val[string]          `db:"name" `
	Type    omit.Val[int16]           `db:"type" `
	SubType omit.Val[string]          `db:"sub_type" `
	Balance omit.Val[decimal.Decimal] `db:"balance" `
}

func (s AccountSetter) SetColumns() []string {
	vals := make([]string, 0, 5)
	if s.ID.IsValue() {
		vals = append(vals, "id")
	}
	if s.Name.IsValue() {
		vals = append(vals, "name")
	}
	if s.Type.IsValue() {
		vals = append(vals, "type")
	}
	if s.SubType.IsValue() {
		vals = append(vals, "sub_type")
	}
	if s.Balance.IsValue() {
		vals = append(vals, "balance")
	}
	return vals
}

func (s AccountSetter) Overwrite(t *Account) {
	if s.ID.IsValue() {
		t.ID = s.ID.MustGet()
	}
	if s.Name.IsValue() {
		t.Name = s.Name.MustGet()
	}
	if s.Type.IsValue() {
		t.Type = s.Type.MustGet()
	}
	if s.SubType.IsValue() {
		t.SubType = s.SubType.MustGet()
	}
	if s.Balance.IsValue() {
		t.Balance = s.Balance.MustGet()
	}
}

func (s *AccountSetter) Apply(q *dialect.InsertQuery) {
	q.AppendHooks(func(ctx context.Context, exec bob.Executor) (context.Context, error) {
		return Accounts.BeforeInsertHooks.RunHooks(ctx, exec, s)
	})

	q.AppendValues(bob.ExpressionFunc(func(ctx context.Context, w io.StringWriter, d bob.Dialect, start int) ([]any, error) {
		vals := make([]bob.Expression, 5)
		if s.ID.IsValue() {
			vals[0] = psql.Arg(s.ID.MustGet())
		} else {
			vals[0] = psql.Raw("DEFAULT")
		}

		if s.Name.IsValue() {
			vals[1] = psql.Arg(s.Name.MustGet())
		} else {
			vals[1] = psql.Raw("DEFAULT")
		}

		if s.Type.IsValue() {
			vals[2] = psql.Arg(s.Type.MustGet())
		} else {
			vals[2] = psql.Raw("DEFAULT")
		}

		if s.SubType.IsValue() {
			vals[3] = psql.Arg(s.SubType.MustGet())
		} else {
			vals[3] = psql.Raw("DEFAULT")
		}

		if s.Balance.IsValue() {
			vals[4] = psql.Arg(s.Balance.MustGet())
		} else {
			vals[4] = psql.Raw("DEFAULT")
		}

		return bob.ExpressSlice(ctx, w, d, start, vals, "", ", ", "")
	}))
}

func (s AccountSetter) UpdateMod() bob.Mod[*dialect.UpdateQuery] {
	return um.Set(s.Expressions()...)
}

func (s AccountSetter) Expressions(prefix ...string) []bob.Expression {
	exprs := make([]bob.Expression, 0, 5)

	if s.ID.IsValue() {
		exprs = append(exprs, expr.Join{Sep: " = ", Exprs: []bob.Expression{
			psql.Quote(append(prefix, "id")...),
			psql.Arg(s.ID),
		}})
	}

	if s.Name.IsValue() {
		exprs = append(exprs, expr.Join{Sep: " = ", Exprs: []bob.Expression{
			psql.Quote(append(prefix, "name")...),
			psql.Arg(s.Name),
		}})
	}

	if s.Type.IsValue() {
		exprs = append(exprs, expr.Join{Sep: " = ", Exprs: []bob.Expression{
			psql.Quote(append(prefix, "type")...),
			psql.Arg(s.Type),
		}})
	}

	if s.SubType.IsValue() {
		exprs = append(exprs, expr.Join{Sep: " = ", Exprs: []bob.Expression{
			psql.Quote(append(prefix, "sub_type")...),
			psql.Arg(s.SubType),
		}})
	}

	if s.Balance.IsValue() {
		exprs = append(exprs, expr.Join{Sep: " = ", Exprs: []bob.Expression{
			psql.Quote(append(prefix, "balance")...),
			psql.Arg(s.Balance),
		}})
	}

	return exprs
}

// FindAccount retrieves a single record by primary key
// If cols is empty Find will return all columns.
func FindAccount(ctx context.Context, exec bob.Executor, IDPK uuid.UUID, cols ...string) (*Account, error) {
	if len(cols) == 0 {
		return Accounts.Query(
			sm.Where(Accounts.Columns.ID.EQ(psql.Arg(IDPK))),
		).One(ctx, exec)
	}

	return Accounts.Query(
		sm.Where(Accounts.Columns.ID.EQ(psql.Arg(IDPK))),
		sm.Columns(Accounts.Columns.Only(cols...)),
	).One(ctx, exec)
}

// AccountExists checks the presence of a single record by primary key
func AccountExists(ctx context.Context, exec bob.Executor, IDPK uuid.UUID) (bool, error) {
	return Accounts.Query(
		sm.Where(Accounts.Columns.ID.EQ(psql.Arg(IDPK))),
	).Exists(ctx, exec)
}

// AfterQueryHook is called after Account is retrieved from the database
func (o *Account) AfterQueryHook(ctx context.Context, exec bob.Executor, queryType bob.QueryType) error {
	var err error

	switch queryType {
	case bob.QueryTypeSelect:
		ctx, err = Accounts.AfterSelectHooks.RunHooks(ctx, exec, AccountSlice{o})
	case bob.QueryTypeInsert:
		ctx, err = Accounts.AfterInsertHooks.RunHooks(ctx, exec, AccountSlice{o})
	case bob.QueryTypeUpdate:
		ctx, err = Accounts.AfterUpdateHooks.RunHooks(ctx, exec, AccountSlice{o})
	case bob.QueryTypeDelete:
		ctx, err = Accounts.AfterDeleteHooks.RunHooks(ctx, exec, AccountSlice{o})
	}

	return err
}

// primaryKeyVals returns the primary key values of the Account
func (o *Account) primaryKeyVals() bob.Expression {
	return psql.Arg(o.ID)
}

func (o *Account) pkEQ() dialect.Expression {
	return psql.Quote("accounts", "id").EQ(bob.ExpressionFunc(func(ctx context.Context, w io.StringWriter, d bob.Dialect, start int) ([]any, error) {
		return o.primaryKeyVals().WriteSQL(ctx, w, d, start)
	}))
}

// Update uses an executor to update the Account
func (o *Account) Update(ctx context.Context, exec bob.Executor, s *AccountSetter) error {
	v, err := Accounts.Update(s.UpdateMod(), um.Where(o.pkEQ())).One(ctx, exec)
	if err != nil {
		return err
	}

	*o = *v

	return nil
}

// Delete deletes a single Account record with an executor
func (o *Account) Delete(ctx context.Context, exec bob.Executor) error {
	_, err := Accounts.Delete(dm.Where(o.pkEQ())).Exec(ctx, exec)
	return err
}

// Reload refreshes the Account using the executor
func (o *Account) Reload(ctx context.Context, exec bob.Executor) error {
	o2, err := Accounts.Query(
		sm.Where(Accounts.Columns.ID.EQ(psql.Arg(o.ID))),
	).One(ctx, exec)
	if err != nil {
		return err
	}

	*o = *o2

	return nil
}

// AfterQueryHook is called after AccountSlice is retrieved from the database
func (o AccountSlice) AfterQueryHook(ctx context.Context, exec bob.Executor, queryType bob.QueryType) error {
	var err error

	switch queryType {
	case bob.QueryTypeSelect:
		ctx, err = Accounts.AfterSelectHooks.RunHooks(ctx, exec, o)
	case bob.QueryTypeInsert:
		ctx, err = Accounts.AfterInsertHooks.RunHooks(ctx, exec, o)
	case bob.QueryTypeUpdate:
		ctx, err = Accounts.AfterUpdateHooks.RunHooks(ctx, exec, o)
	case bob.QueryTypeDelete:
		ctx, err = Accounts.AfterDeleteHooks.RunHooks(ctx, exec, o)
	}

	return err
}

func (o AccountSlice) pkIN() dialect.Expression {
	if len(o) == 0 {
		return psql.Raw("NULL")
	}

	return psql.Quote("accounts", "id").In(bob.ExpressionFunc(func(ctx context.Context, w io.StringWriter, d bob.Dialect, start int) ([]any, error) {
		pkPairs := make([]bob.Expression, len(o))
		for i, row := range o {
			pkPairs[i] = row.primaryKeyVals()
		}
		return bob.ExpressSlice(ctx, w, d, start, pkPairs, "", ", ", "")
	}))
}

// copyMatchingRows finds models in the given slice that have the same primary key
// then it first copies the existing relationships from the old model to the new model
// and then replaces the old model in the slice with the new model
func (o AccountSlice) copyMatchingRows(from ...*Account) {
	for i, old := range o {
		for _, new := range from {
			if new.ID != old.ID {
				continue
			}

			o[i] = new
			break
		}
	}
}

// UpdateMod modifies an update query with "WHERE primary_key IN (o...)"
func (o AccountSlice) UpdateMod() bob.Mod[*dialect.UpdateQuery] {
	return bob.ModFunc[*dialect.UpdateQuery](func(q *dialect.UpdateQuery) {
		q.AppendHooks(func(ctx context.Context, exec bob.Executor) (context.Context, error) {
			return Accounts.BeforeUpdateHooks.RunHooks(ctx, exec, o)
		})

		q.AppendLoader(bob.LoaderFunc(func(ctx context.Context, exec bob.Executor, retrieved any) error {
			var err error
			switch retrieved := retrieved.(type) {
			case *Account:
				o.copyMatchingRows(retrieved)
			case []*Account:
				o.copyMatchingRows(retrieved...)
			case AccountSlice:
				o.copyMatchingRows(retrieved...)
			default:
				// If the retrieved value is not a Account or a slice of Account
				// then run the AfterDeleteHooks on the slice
				_, err = Accounts.AfterDeleteHooks.RunHooks(ctx, exec, o)
			}

			return err
		}))

		q.AppendWhere(o.pkIN())
	})
}

// DeleteMod modifies an delete query with "WHERE primary_key IN (o...)"
func (o AccountSlice) DeleteMod() bob.Mod[*dialect.DeleteQuery] {
	return bob.ModFunc[*dialect.DeleteQuery](func(q *dialect.DeleteQuery) {
		q.AppendHooks(func(ctx context.Context, exec bob.Executor) (context.Context, error) {
			return Accounts.BeforeDeleteHooks.RunHooks(ctx, exec, o)
		})

		q.AppendLoader(bob.LoaderFunc(func(ctx context.Context, exec bob.Executor, retrieved any) error {
			var err error
			switch retrieved := retrieved.(type) {
			case *Account:
				o.copyMatchingRows(retrieved)
			case []*Account:
				o.copyMatchingRows(retrieved...)
			case AccountSlice:
				o.copyMatchingRows(retrieved...)
			default:
				// If the retrieved value is not a Account or a slice of Account
				// then run the AfterDeleteHooks on the slice
				_, err = Accounts.AfterUpdateHooks.RunHooks(ctx, exec, o)
			}

			return err
		}))

		q.AppendWhere(o.pkIN())
	})
}

func (o AccountSlice) UpdateAll(ctx context.Context, exec bob.Executor, vals AccountSetter) error {
	if len(o) == 0 {
		return nil
	}

	_, err := Accounts.Update(vals.UpdateMod(), o.UpdateMod()).All(ctx, exec)
	return err
}

func (o AccountSlice) DeleteAll(ctx context.Context, exec bob.Executor) error {
	if len(o) == 0 {
		return nil
	}

	_, err := Accounts.Delete(o.DeleteMod()).Exec(ctx, exec)
	return err
}

func (o AccountSlice) ReloadAll(ctx context.Context, exec bob.Executor) error {
	if len(o) == 0 {
		return nil
	}

	o2, err := Accounts.Query(sm.Where(o.pkIN())).All(ctx, exec)
	if err != nil {
		return err
	}

	o.copyMatchingRows(o2...)

	return nil
}

type accountWhere[Q psql.Filterable] struct {
	ID      psql.WhereMod[Q, uuid.UUID]
	Name    psql.WhereMod[Q, string]
	Type    psql.WhereMod[Q, int16]
	SubType psql.WhereMod[Q, string]
	Balance psql.WhereMod[Q, decimal.Decimal]
}

func (accountWhere[Q]) AliasedAs(alias string) accountWhere[Q] {
	return buildAccountWhere[Q](buildAccountColumns(alias))
}

func buildAccountWhere[Q psql.Filterable](cols accountColumns) accountWhere[Q] {
	return accountWhere[Q]{
		ID:      psql.Where[Q, uuid.UUID](cols.ID),
		Name:    psql.Where[Q, string](cols.Name),
		Type:    psql.Where[Q, int16](cols.Type),
		SubType: psql.Where[Q, string](cols.SubType),
		Balance: psql.Where[Q, decimal.Decimal](cols.Balance),
	}
}
