// Code generated by BobGen psql v0.42.0. DO NOT EDIT.
// This file is meant to be re-generated in place and/or deleted at any time.

package bobgen

import (
	"context"
	"fmt"
	"io"
	"time"

	"github.com/aarondl/opt/omit"
	"github.com/gofrs/uuid/v5"
	"github.com/shopspring/decimal"
	"github.com/stephenafamo/bob"
	"github.com/stephenafamo/bob/dialect/psql"
	"github.com/stephenafamo/bob/dialect/psql/dialect"
	"github.com/stephenafamo/bob/dialect/psql/dm"
	"github.com/stephenafamo/bob/dialect/psql/sm"
	"github.com/stephenafamo/bob/dialect/psql/um"
	"github.com/stephenafamo/bob/expr"
	"github.com/stephenafamo/bob/mods"
	"github.com/stephenafamo/bob/orm"
	"github.com/stephenafamo/bob/types/pgtypes"
)

// Account is an object representing the database table.
type Account struct {
	ID              uuid.UUID       `db:"id,pk" `
	Name            string          `db:"name" `
	Type            int16           `db:"type" `
	SubType         string          `db:"sub_type" `
	Balance         decimal.Decimal `db:"balance" `
	StartingBalance decimal.Decimal `db:"starting_balance" `
	CreatedAt       time.Time       `db:"created_at" `

	R accountR `db:"-" `
}

// AccountSlice is an alias for a slice of pointers to Account.
// This should almost always be used instead of []*Account.
type AccountSlice []*Account

// Accounts contains methods to work with the accounts table
var Accounts = psql.NewTablex[*Account, AccountSlice, *AccountSetter]("", "accounts", buildAccountColumns("accounts"))

// AccountsQuery is a query on the accounts table
type AccountsQuery = *psql.ViewQuery[*Account, AccountSlice]

// accountR is where relationships are stored.
type accountR struct {
	PlaidAccountLinks PlaidAccountLinkSlice // plaid_account_links.plaid_account_links_account_id_fkey
	Sync              *Sync                 // syncs.syncs_account_id_fkey
}

func buildAccountColumns(alias string) accountColumns {
	return accountColumns{
		ColumnsExpr: expr.NewColumnsExpr(
			"id", "name", "type", "sub_type", "balance", "starting_balance", "created_at",
		).WithParent("accounts"),
		tableAlias:      alias,
		ID:              psql.Quote(alias, "id"),
		Name:            psql.Quote(alias, "name"),
		Type:            psql.Quote(alias, "type"),
		SubType:         psql.Quote(alias, "sub_type"),
		Balance:         psql.Quote(alias, "balance"),
		StartingBalance: psql.Quote(alias, "starting_balance"),
		CreatedAt:       psql.Quote(alias, "created_at"),
	}
}

type accountColumns struct {
	expr.ColumnsExpr
	tableAlias      string
	ID              psql.Expression
	Name            psql.Expression
	Type            psql.Expression
	SubType         psql.Expression
	Balance         psql.Expression
	StartingBalance psql.Expression
	CreatedAt       psql.Expression
}

func (c accountColumns) Alias() string {
	return c.tableAlias
}

func (accountColumns) AliasedAs(alias string) accountColumns {
	return buildAccountColumns(alias)
}

// AccountSetter is used for insert/upsert/update operations
// All values are optional, and do not have to be set
// Generated columns are not included
type AccountSetter struct {
	ID              omit.Val[uuid.UUID]       `db:"id,pk" `
	Name            omit.Val[string]          `db:"name" `
	Type            omit.Val[int16]           `db:"type" `
	SubType         omit.Val[string]          `db:"sub_type" `
	Balance         omit.Val[decimal.Decimal] `db:"balance" `
	StartingBalance omit.Val[decimal.Decimal] `db:"starting_balance" `
	CreatedAt       omit.Val[time.Time]       `db:"created_at" `
}

func (s AccountSetter) SetColumns() []string {
	vals := make([]string, 0, 7)
	if s.ID.IsValue() {
		vals = append(vals, "id")
	}
	if s.Name.IsValue() {
		vals = append(vals, "name")
	}
	if s.Type.IsValue() {
		vals = append(vals, "type")
	}
	if s.SubType.IsValue() {
		vals = append(vals, "sub_type")
	}
	if s.Balance.IsValue() {
		vals = append(vals, "balance")
	}
	if s.StartingBalance.IsValue() {
		vals = append(vals, "starting_balance")
	}
	if s.CreatedAt.IsValue() {
		vals = append(vals, "created_at")
	}
	return vals
}

func (s AccountSetter) Overwrite(t *Account) {
	if s.ID.IsValue() {
		t.ID = s.ID.MustGet()
	}
	if s.Name.IsValue() {
		t.Name = s.Name.MustGet()
	}
	if s.Type.IsValue() {
		t.Type = s.Type.MustGet()
	}
	if s.SubType.IsValue() {
		t.SubType = s.SubType.MustGet()
	}
	if s.Balance.IsValue() {
		t.Balance = s.Balance.MustGet()
	}
	if s.StartingBalance.IsValue() {
		t.StartingBalance = s.StartingBalance.MustGet()
	}
	if s.CreatedAt.IsValue() {
		t.CreatedAt = s.CreatedAt.MustGet()
	}
}

func (s *AccountSetter) Apply(q *dialect.InsertQuery) {
	q.AppendHooks(func(ctx context.Context, exec bob.Executor) (context.Context, error) {
		return Accounts.BeforeInsertHooks.RunHooks(ctx, exec, s)
	})

	q.AppendValues(bob.ExpressionFunc(func(ctx context.Context, w io.StringWriter, d bob.Dialect, start int) ([]any, error) {
		vals := make([]bob.Expression, 7)
		if s.ID.IsValue() {
			vals[0] = psql.Arg(s.ID.MustGet())
		} else {
			vals[0] = psql.Raw("DEFAULT")
		}

		if s.Name.IsValue() {
			vals[1] = psql.Arg(s.Name.MustGet())
		} else {
			vals[1] = psql.Raw("DEFAULT")
		}

		if s.Type.IsValue() {
			vals[2] = psql.Arg(s.Type.MustGet())
		} else {
			vals[2] = psql.Raw("DEFAULT")
		}

		if s.SubType.IsValue() {
			vals[3] = psql.Arg(s.SubType.MustGet())
		} else {
			vals[3] = psql.Raw("DEFAULT")
		}

		if s.Balance.IsValue() {
			vals[4] = psql.Arg(s.Balance.MustGet())
		} else {
			vals[4] = psql.Raw("DEFAULT")
		}

		if s.StartingBalance.IsValue() {
			vals[5] = psql.Arg(s.StartingBalance.MustGet())
		} else {
			vals[5] = psql.Raw("DEFAULT")
		}

		if s.CreatedAt.IsValue() {
			vals[6] = psql.Arg(s.CreatedAt.MustGet())
		} else {
			vals[6] = psql.Raw("DEFAULT")
		}

		return bob.ExpressSlice(ctx, w, d, start, vals, "", ", ", "")
	}))
}

func (s AccountSetter) UpdateMod() bob.Mod[*dialect.UpdateQuery] {
	return um.Set(s.Expressions()...)
}

func (s AccountSetter) Expressions(prefix ...string) []bob.Expression {
	exprs := make([]bob.Expression, 0, 7)

	if s.ID.IsValue() {
		exprs = append(exprs, expr.Join{Sep: " = ", Exprs: []bob.Expression{
			psql.Quote(append(prefix, "id")...),
			psql.Arg(s.ID),
		}})
	}

	if s.Name.IsValue() {
		exprs = append(exprs, expr.Join{Sep: " = ", Exprs: []bob.Expression{
			psql.Quote(append(prefix, "name")...),
			psql.Arg(s.Name),
		}})
	}

	if s.Type.IsValue() {
		exprs = append(exprs, expr.Join{Sep: " = ", Exprs: []bob.Expression{
			psql.Quote(append(prefix, "type")...),
			psql.Arg(s.Type),
		}})
	}

	if s.SubType.IsValue() {
		exprs = append(exprs, expr.Join{Sep: " = ", Exprs: []bob.Expression{
			psql.Quote(append(prefix, "sub_type")...),
			psql.Arg(s.SubType),
		}})
	}

	if s.Balance.IsValue() {
		exprs = append(exprs, expr.Join{Sep: " = ", Exprs: []bob.Expression{
			psql.Quote(append(prefix, "balance")...),
			psql.Arg(s.Balance),
		}})
	}

	if s.StartingBalance.IsValue() {
		exprs = append(exprs, expr.Join{Sep: " = ", Exprs: []bob.Expression{
			psql.Quote(append(prefix, "starting_balance")...),
			psql.Arg(s.StartingBalance),
		}})
	}

	if s.CreatedAt.IsValue() {
		exprs = append(exprs, expr.Join{Sep: " = ", Exprs: []bob.Expression{
			psql.Quote(append(prefix, "created_at")...),
			psql.Arg(s.CreatedAt),
		}})
	}

	return exprs
}

// FindAccount retrieves a single record by primary key
// If cols is empty Find will return all columns.
func FindAccount(ctx context.Context, exec bob.Executor, IDPK uuid.UUID, cols ...string) (*Account, error) {
	if len(cols) == 0 {
		return Accounts.Query(
			sm.Where(Accounts.Columns.ID.EQ(psql.Arg(IDPK))),
		).One(ctx, exec)
	}

	return Accounts.Query(
		sm.Where(Accounts.Columns.ID.EQ(psql.Arg(IDPK))),
		sm.Columns(Accounts.Columns.Only(cols...)),
	).One(ctx, exec)
}

// AccountExists checks the presence of a single record by primary key
func AccountExists(ctx context.Context, exec bob.Executor, IDPK uuid.UUID) (bool, error) {
	return Accounts.Query(
		sm.Where(Accounts.Columns.ID.EQ(psql.Arg(IDPK))),
	).Exists(ctx, exec)
}

// AfterQueryHook is called after Account is retrieved from the database
func (o *Account) AfterQueryHook(ctx context.Context, exec bob.Executor, queryType bob.QueryType) error {
	var err error

	switch queryType {
	case bob.QueryTypeSelect:
		ctx, err = Accounts.AfterSelectHooks.RunHooks(ctx, exec, AccountSlice{o})
	case bob.QueryTypeInsert:
		ctx, err = Accounts.AfterInsertHooks.RunHooks(ctx, exec, AccountSlice{o})
	case bob.QueryTypeUpdate:
		ctx, err = Accounts.AfterUpdateHooks.RunHooks(ctx, exec, AccountSlice{o})
	case bob.QueryTypeDelete:
		ctx, err = Accounts.AfterDeleteHooks.RunHooks(ctx, exec, AccountSlice{o})
	}

	return err
}

// primaryKeyVals returns the primary key values of the Account
func (o *Account) primaryKeyVals() bob.Expression {
	return psql.Arg(o.ID)
}

func (o *Account) pkEQ() dialect.Expression {
	return psql.Quote("accounts", "id").EQ(bob.ExpressionFunc(func(ctx context.Context, w io.StringWriter, d bob.Dialect, start int) ([]any, error) {
		return o.primaryKeyVals().WriteSQL(ctx, w, d, start)
	}))
}

// Update uses an executor to update the Account
func (o *Account) Update(ctx context.Context, exec bob.Executor, s *AccountSetter) error {
	v, err := Accounts.Update(s.UpdateMod(), um.Where(o.pkEQ())).One(ctx, exec)
	if err != nil {
		return err
	}

	o.R = v.R
	*o = *v

	return nil
}

// Delete deletes a single Account record with an executor
func (o *Account) Delete(ctx context.Context, exec bob.Executor) error {
	_, err := Accounts.Delete(dm.Where(o.pkEQ())).Exec(ctx, exec)
	return err
}

// Reload refreshes the Account using the executor
func (o *Account) Reload(ctx context.Context, exec bob.Executor) error {
	o2, err := Accounts.Query(
		sm.Where(Accounts.Columns.ID.EQ(psql.Arg(o.ID))),
	).One(ctx, exec)
	if err != nil {
		return err
	}
	o2.R = o.R
	*o = *o2

	return nil
}

// AfterQueryHook is called after AccountSlice is retrieved from the database
func (o AccountSlice) AfterQueryHook(ctx context.Context, exec bob.Executor, queryType bob.QueryType) error {
	var err error

	switch queryType {
	case bob.QueryTypeSelect:
		ctx, err = Accounts.AfterSelectHooks.RunHooks(ctx, exec, o)
	case bob.QueryTypeInsert:
		ctx, err = Accounts.AfterInsertHooks.RunHooks(ctx, exec, o)
	case bob.QueryTypeUpdate:
		ctx, err = Accounts.AfterUpdateHooks.RunHooks(ctx, exec, o)
	case bob.QueryTypeDelete:
		ctx, err = Accounts.AfterDeleteHooks.RunHooks(ctx, exec, o)
	}

	return err
}

func (o AccountSlice) pkIN() dialect.Expression {
	if len(o) == 0 {
		return psql.Raw("NULL")
	}

	return psql.Quote("accounts", "id").In(bob.ExpressionFunc(func(ctx context.Context, w io.StringWriter, d bob.Dialect, start int) ([]any, error) {
		pkPairs := make([]bob.Expression, len(o))
		for i, row := range o {
			pkPairs[i] = row.primaryKeyVals()
		}
		return bob.ExpressSlice(ctx, w, d, start, pkPairs, "", ", ", "")
	}))
}

// copyMatchingRows finds models in the given slice that have the same primary key
// then it first copies the existing relationships from the old model to the new model
// and then replaces the old model in the slice with the new model
func (o AccountSlice) copyMatchingRows(from ...*Account) {
	for i, old := range o {
		for _, new := range from {
			if new.ID != old.ID {
				continue
			}
			new.R = old.R
			o[i] = new
			break
		}
	}
}

// UpdateMod modifies an update query with "WHERE primary_key IN (o...)"
func (o AccountSlice) UpdateMod() bob.Mod[*dialect.UpdateQuery] {
	return bob.ModFunc[*dialect.UpdateQuery](func(q *dialect.UpdateQuery) {
		q.AppendHooks(func(ctx context.Context, exec bob.Executor) (context.Context, error) {
			return Accounts.BeforeUpdateHooks.RunHooks(ctx, exec, o)
		})

		q.AppendLoader(bob.LoaderFunc(func(ctx context.Context, exec bob.Executor, retrieved any) error {
			var err error
			switch retrieved := retrieved.(type) {
			case *Account:
				o.copyMatchingRows(retrieved)
			case []*Account:
				o.copyMatchingRows(retrieved...)
			case AccountSlice:
				o.copyMatchingRows(retrieved...)
			default:
				// If the retrieved value is not a Account or a slice of Account
				// then run the AfterUpdateHooks on the slice
				_, err = Accounts.AfterUpdateHooks.RunHooks(ctx, exec, o)
			}

			return err
		}))

		q.AppendWhere(o.pkIN())
	})
}

// DeleteMod modifies an delete query with "WHERE primary_key IN (o...)"
func (o AccountSlice) DeleteMod() bob.Mod[*dialect.DeleteQuery] {
	return bob.ModFunc[*dialect.DeleteQuery](func(q *dialect.DeleteQuery) {
		q.AppendHooks(func(ctx context.Context, exec bob.Executor) (context.Context, error) {
			return Accounts.BeforeDeleteHooks.RunHooks(ctx, exec, o)
		})

		q.AppendLoader(bob.LoaderFunc(func(ctx context.Context, exec bob.Executor, retrieved any) error {
			var err error
			switch retrieved := retrieved.(type) {
			case *Account:
				o.copyMatchingRows(retrieved)
			case []*Account:
				o.copyMatchingRows(retrieved...)
			case AccountSlice:
				o.copyMatchingRows(retrieved...)
			default:
				// If the retrieved value is not a Account or a slice of Account
				// then run the AfterDeleteHooks on the slice
				_, err = Accounts.AfterDeleteHooks.RunHooks(ctx, exec, o)
			}

			return err
		}))

		q.AppendWhere(o.pkIN())
	})
}

func (o AccountSlice) UpdateAll(ctx context.Context, exec bob.Executor, vals AccountSetter) error {
	if len(o) == 0 {
		return nil
	}

	_, err := Accounts.Update(vals.UpdateMod(), o.UpdateMod()).All(ctx, exec)
	return err
}

func (o AccountSlice) DeleteAll(ctx context.Context, exec bob.Executor) error {
	if len(o) == 0 {
		return nil
	}

	_, err := Accounts.Delete(o.DeleteMod()).Exec(ctx, exec)
	return err
}

func (o AccountSlice) ReloadAll(ctx context.Context, exec bob.Executor) error {
	if len(o) == 0 {
		return nil
	}

	o2, err := Accounts.Query(sm.Where(o.pkIN())).All(ctx, exec)
	if err != nil {
		return err
	}

	o.copyMatchingRows(o2...)

	return nil
}

// PlaidAccountLinks starts a query for related objects on plaid_account_links
func (o *Account) PlaidAccountLinks(mods ...bob.Mod[*dialect.SelectQuery]) PlaidAccountLinksQuery {
	return PlaidAccountLinks.Query(append(mods,
		sm.Where(PlaidAccountLinks.Columns.AccountID.EQ(psql.Arg(o.ID))),
	)...)
}

func (os AccountSlice) PlaidAccountLinks(mods ...bob.Mod[*dialect.SelectQuery]) PlaidAccountLinksQuery {
	pkID := make(pgtypes.Array[uuid.UUID], 0, len(os))
	for _, o := range os {
		if o == nil {
			continue
		}
		pkID = append(pkID, o.ID)
	}
	PKArgExpr := psql.Select(sm.Columns(
		psql.F("unnest", psql.Cast(psql.Arg(pkID), "uuid[]")),
	))

	return PlaidAccountLinks.Query(append(mods,
		sm.Where(psql.Group(PlaidAccountLinks.Columns.AccountID).OP("IN", PKArgExpr)),
	)...)
}

// Sync starts a query for related objects on syncs
func (o *Account) Sync(mods ...bob.Mod[*dialect.SelectQuery]) SyncsQuery {
	return Syncs.Query(append(mods,
		sm.Where(Syncs.Columns.AccountID.EQ(psql.Arg(o.ID))),
	)...)
}

func (os AccountSlice) Sync(mods ...bob.Mod[*dialect.SelectQuery]) SyncsQuery {
	pkID := make(pgtypes.Array[uuid.UUID], 0, len(os))
	for _, o := range os {
		if o == nil {
			continue
		}
		pkID = append(pkID, o.ID)
	}
	PKArgExpr := psql.Select(sm.Columns(
		psql.F("unnest", psql.Cast(psql.Arg(pkID), "uuid[]")),
	))

	return Syncs.Query(append(mods,
		sm.Where(psql.Group(Syncs.Columns.AccountID).OP("IN", PKArgExpr)),
	)...)
}

func insertAccountPlaidAccountLinks0(ctx context.Context, exec bob.Executor, plaidAccountLinks1 []*PlaidAccountLinkSetter, account0 *Account) (PlaidAccountLinkSlice, error) {
	for i := range plaidAccountLinks1 {
		plaidAccountLinks1[i].AccountID = omit.From(account0.ID)
	}

	ret, err := PlaidAccountLinks.Insert(bob.ToMods(plaidAccountLinks1...)).All(ctx, exec)
	if err != nil {
		return ret, fmt.Errorf("insertAccountPlaidAccountLinks0: %w", err)
	}

	return ret, nil
}

func attachAccountPlaidAccountLinks0(ctx context.Context, exec bob.Executor, count int, plaidAccountLinks1 PlaidAccountLinkSlice, account0 *Account) (PlaidAccountLinkSlice, error) {
	setter := &PlaidAccountLinkSetter{
		AccountID: omit.From(account0.ID),
	}

	err := plaidAccountLinks1.UpdateAll(ctx, exec, *setter)
	if err != nil {
		return nil, fmt.Errorf("attachAccountPlaidAccountLinks0: %w", err)
	}

	return plaidAccountLinks1, nil
}

func (account0 *Account) InsertPlaidAccountLinks(ctx context.Context, exec bob.Executor, related ...*PlaidAccountLinkSetter) error {
	if len(related) == 0 {
		return nil
	}

	var err error

	plaidAccountLinks1, err := insertAccountPlaidAccountLinks0(ctx, exec, related, account0)
	if err != nil {
		return err
	}

	account0.R.PlaidAccountLinks = append(account0.R.PlaidAccountLinks, plaidAccountLinks1...)

	for _, rel := range plaidAccountLinks1 {
		rel.R.Account = account0
	}
	return nil
}

func (account0 *Account) AttachPlaidAccountLinks(ctx context.Context, exec bob.Executor, related ...*PlaidAccountLink) error {
	if len(related) == 0 {
		return nil
	}

	var err error
	plaidAccountLinks1 := PlaidAccountLinkSlice(related)

	_, err = attachAccountPlaidAccountLinks0(ctx, exec, len(related), plaidAccountLinks1, account0)
	if err != nil {
		return err
	}

	account0.R.PlaidAccountLinks = append(account0.R.PlaidAccountLinks, plaidAccountLinks1...)

	for _, rel := range related {
		rel.R.Account = account0
	}

	return nil
}

func insertAccountSync0(ctx context.Context, exec bob.Executor, sync1 *SyncSetter, account0 *Account) (*Sync, error) {
	sync1.AccountID = omit.From(account0.ID)

	ret, err := Syncs.Insert(sync1).One(ctx, exec)
	if err != nil {
		return ret, fmt.Errorf("insertAccountSync0: %w", err)
	}

	return ret, nil
}

func attachAccountSync0(ctx context.Context, exec bob.Executor, count int, sync1 *Sync, account0 *Account) (*Sync, error) {
	setter := &SyncSetter{
		AccountID: omit.From(account0.ID),
	}

	err := sync1.Update(ctx, exec, setter)
	if err != nil {
		return nil, fmt.Errorf("attachAccountSync0: %w", err)
	}

	return sync1, nil
}

func (account0 *Account) InsertSync(ctx context.Context, exec bob.Executor, related *SyncSetter) error {
	var err error

	sync1, err := insertAccountSync0(ctx, exec, related, account0)
	if err != nil {
		return err
	}

	account0.R.Sync = sync1

	sync1.R.Account = account0

	return nil
}

func (account0 *Account) AttachSync(ctx context.Context, exec bob.Executor, sync1 *Sync) error {
	var err error

	_, err = attachAccountSync0(ctx, exec, 1, sync1, account0)
	if err != nil {
		return err
	}

	account0.R.Sync = sync1

	sync1.R.Account = account0

	return nil
}

type accountWhere[Q psql.Filterable] struct {
	ID              psql.WhereMod[Q, uuid.UUID]
	Name            psql.WhereMod[Q, string]
	Type            psql.WhereMod[Q, int16]
	SubType         psql.WhereMod[Q, string]
	Balance         psql.WhereMod[Q, decimal.Decimal]
	StartingBalance psql.WhereMod[Q, decimal.Decimal]
	CreatedAt       psql.WhereMod[Q, time.Time]
}

func (accountWhere[Q]) AliasedAs(alias string) accountWhere[Q] {
	return buildAccountWhere[Q](buildAccountColumns(alias))
}

func buildAccountWhere[Q psql.Filterable](cols accountColumns) accountWhere[Q] {
	return accountWhere[Q]{
		ID:              psql.Where[Q, uuid.UUID](cols.ID),
		Name:            psql.Where[Q, string](cols.Name),
		Type:            psql.Where[Q, int16](cols.Type),
		SubType:         psql.Where[Q, string](cols.SubType),
		Balance:         psql.Where[Q, decimal.Decimal](cols.Balance),
		StartingBalance: psql.Where[Q, decimal.Decimal](cols.StartingBalance),
		CreatedAt:       psql.Where[Q, time.Time](cols.CreatedAt),
	}
}

func (o *Account) Preload(name string, retrieved any) error {
	if o == nil {
		return nil
	}

	switch name {
	case "PlaidAccountLinks":
		rels, ok := retrieved.(PlaidAccountLinkSlice)
		if !ok {
			return fmt.Errorf("account cannot load %T as %q", retrieved, name)
		}

		o.R.PlaidAccountLinks = rels

		for _, rel := range rels {
			if rel != nil {
				rel.R.Account = o
			}
		}
		return nil
	case "Sync":
		rel, ok := retrieved.(*Sync)
		if !ok {
			return fmt.Errorf("account cannot load %T as %q", retrieved, name)
		}

		o.R.Sync = rel

		if rel != nil {
			rel.R.Account = o
		}
		return nil
	default:
		return fmt.Errorf("account has no relationship %q", name)
	}
}

type accountPreloader struct {
	Sync func(...psql.PreloadOption) psql.Preloader
}

func buildAccountPreloader() accountPreloader {
	return accountPreloader{
		Sync: func(opts ...psql.PreloadOption) psql.Preloader {
			return psql.Preload[*Sync, SyncSlice](psql.PreloadRel{
				Name: "Sync",
				Sides: []psql.PreloadSide{
					{
						From:        Accounts,
						To:          Syncs,
						FromColumns: []string{"id"},
						ToColumns:   []string{"account_id"},
					},
				},
			}, Syncs.Columns.Names(), opts...)
		},
	}
}

type accountThenLoader[Q orm.Loadable] struct {
	PlaidAccountLinks func(...bob.Mod[*dialect.SelectQuery]) orm.Loader[Q]
	Sync              func(...bob.Mod[*dialect.SelectQuery]) orm.Loader[Q]
}

func buildAccountThenLoader[Q orm.Loadable]() accountThenLoader[Q] {
	type PlaidAccountLinksLoadInterface interface {
		LoadPlaidAccountLinks(context.Context, bob.Executor, ...bob.Mod[*dialect.SelectQuery]) error
	}
	type SyncLoadInterface interface {
		LoadSync(context.Context, bob.Executor, ...bob.Mod[*dialect.SelectQuery]) error
	}

	return accountThenLoader[Q]{
		PlaidAccountLinks: thenLoadBuilder[Q](
			"PlaidAccountLinks",
			func(ctx context.Context, exec bob.Executor, retrieved PlaidAccountLinksLoadInterface, mods ...bob.Mod[*dialect.SelectQuery]) error {
				return retrieved.LoadPlaidAccountLinks(ctx, exec, mods...)
			},
		),
		Sync: thenLoadBuilder[Q](
			"Sync",
			func(ctx context.Context, exec bob.Executor, retrieved SyncLoadInterface, mods ...bob.Mod[*dialect.SelectQuery]) error {
				return retrieved.LoadSync(ctx, exec, mods...)
			},
		),
	}
}

// LoadPlaidAccountLinks loads the account's PlaidAccountLinks into the .R struct
func (o *Account) LoadPlaidAccountLinks(ctx context.Context, exec bob.Executor, mods ...bob.Mod[*dialect.SelectQuery]) error {
	if o == nil {
		return nil
	}

	// Reset the relationship
	o.R.PlaidAccountLinks = nil

	related, err := o.PlaidAccountLinks(mods...).All(ctx, exec)
	if err != nil {
		return err
	}

	for _, rel := range related {
		rel.R.Account = o
	}

	o.R.PlaidAccountLinks = related
	return nil
}

// LoadPlaidAccountLinks loads the account's PlaidAccountLinks into the .R struct
func (os AccountSlice) LoadPlaidAccountLinks(ctx context.Context, exec bob.Executor, mods ...bob.Mod[*dialect.SelectQuery]) error {
	if len(os) == 0 {
		return nil
	}

	plaidAccountLinks, err := os.PlaidAccountLinks(mods...).All(ctx, exec)
	if err != nil {
		return err
	}

	for _, o := range os {
		if o == nil {
			continue
		}

		o.R.PlaidAccountLinks = nil
	}

	for _, o := range os {
		if o == nil {
			continue
		}

		for _, rel := range plaidAccountLinks {

			if !(o.ID == rel.AccountID) {
				continue
			}

			rel.R.Account = o

			o.R.PlaidAccountLinks = append(o.R.PlaidAccountLinks, rel)
		}
	}

	return nil
}

// LoadSync loads the account's Sync into the .R struct
func (o *Account) LoadSync(ctx context.Context, exec bob.Executor, mods ...bob.Mod[*dialect.SelectQuery]) error {
	if o == nil {
		return nil
	}

	// Reset the relationship
	o.R.Sync = nil

	related, err := o.Sync(mods...).One(ctx, exec)
	if err != nil {
		return err
	}

	related.R.Account = o

	o.R.Sync = related
	return nil
}

// LoadSync loads the account's Sync into the .R struct
func (os AccountSlice) LoadSync(ctx context.Context, exec bob.Executor, mods ...bob.Mod[*dialect.SelectQuery]) error {
	if len(os) == 0 {
		return nil
	}

	syncs, err := os.Sync(mods...).All(ctx, exec)
	if err != nil {
		return err
	}

	for _, o := range os {
		if o == nil {
			continue
		}

		for _, rel := range syncs {

			if !(o.ID == rel.AccountID) {
				continue
			}

			rel.R.Account = o

			o.R.Sync = rel
			break
		}
	}

	return nil
}

type accountJoins[Q dialect.Joinable] struct {
	typ               string
	PlaidAccountLinks modAs[Q, plaidAccountLinkColumns]
	Sync              modAs[Q, syncColumns]
}

func (j accountJoins[Q]) aliasedAs(alias string) accountJoins[Q] {
	return buildAccountJoins[Q](buildAccountColumns(alias), j.typ)
}

func buildAccountJoins[Q dialect.Joinable](cols accountColumns, typ string) accountJoins[Q] {
	return accountJoins[Q]{
		typ: typ,
		PlaidAccountLinks: modAs[Q, plaidAccountLinkColumns]{
			c: PlaidAccountLinks.Columns,
			f: func(to plaidAccountLinkColumns) bob.Mod[Q] {
				mods := make(mods.QueryMods[Q], 0, 1)

				{
					mods = append(mods, dialect.Join[Q](typ, PlaidAccountLinks.Name().As(to.Alias())).On(
						to.AccountID.EQ(cols.ID),
					))
				}

				return mods
			},
		},
		Sync: modAs[Q, syncColumns]{
			c: Syncs.Columns,
			f: func(to syncColumns) bob.Mod[Q] {
				mods := make(mods.QueryMods[Q], 0, 1)

				{
					mods = append(mods, dialect.Join[Q](typ, Syncs.Name().As(to.Alias())).On(
						to.AccountID.EQ(cols.ID),
					))
				}

				return mods
			},
		},
	}
}
