// Code generated by BobGen psql v0.42.0. DO NOT EDIT.
// This file is meant to be re-generated in place and/or deleted at any time.

package bobgen

import (
	"github.com/stephenafamo/bob/clause"
	"github.com/stephenafamo/bob/dialect/psql"
	"github.com/stephenafamo/bob/dialect/psql/dialect"
)

var (
	SelectWhere     = Where[*dialect.SelectQuery]()
	UpdateWhere     = Where[*dialect.UpdateQuery]()
	DeleteWhere     = Where[*dialect.DeleteQuery]()
	OnConflictWhere = Where[*clause.ConflictClause]() // Used in ON CONFLICT DO UPDATE
)

func Where[Q psql.Filterable]() struct {
	Accounts     accountWhere[Q]
	Transactions transactionWhere[Q]
} {
	return struct {
		Accounts     accountWhere[Q]
		Transactions transactionWhere[Q]
	}{
		Accounts:     buildAccountWhere[Q](Accounts.Columns),
		Transactions: buildTransactionWhere[Q](Transactions.Columns),
	}
}
