// Code generated by BobGen psql v0.42.0. DO NOT EDIT.
// This file is meant to be re-generated in place and/or deleted at any time.

package bobgen

import (
	"context"
	"fmt"
	"io"
	"time"

	"github.com/aarondl/opt/omit"
	"github.com/gofrs/uuid/v5"
	"github.com/shopspring/decimal"
	"github.com/stephenafamo/bob"
	"github.com/stephenafamo/bob/dialect/psql"
	"github.com/stephenafamo/bob/dialect/psql/dialect"
	"github.com/stephenafamo/bob/dialect/psql/dm"
	"github.com/stephenafamo/bob/dialect/psql/sm"
	"github.com/stephenafamo/bob/dialect/psql/um"
	"github.com/stephenafamo/bob/expr"
	"github.com/stephenafamo/bob/mods"
	"github.com/stephenafamo/bob/orm"
	"github.com/stephenafamo/bob/types/pgtypes"
)

// Budget is an object representing the database table.
type Budget struct {
	CategoryID uuid.UUID       `db:"category_id,pk" `
	Month      time.Time       `db:"month,pk" `
	Amount     decimal.Decimal `db:"amount" `

	R budgetR `db:"-" `
}

// BudgetSlice is an alias for a slice of pointers to Budget.
// This should almost always be used instead of []*Budget.
type BudgetSlice []*Budget

// Budgets contains methods to work with the budgets table
var Budgets = psql.NewTablex[*Budget, BudgetSlice, *BudgetSetter]("", "budgets", buildBudgetColumns("budgets"))

// BudgetsQuery is a query on the budgets table
type BudgetsQuery = *psql.ViewQuery[*Budget, BudgetSlice]

// budgetR is where relationships are stored.
type budgetR struct {
	Category *Category // budgets.fk_budgets_category
}

func buildBudgetColumns(alias string) budgetColumns {
	return budgetColumns{
		ColumnsExpr: expr.NewColumnsExpr(
			"category_id", "month", "amount",
		).WithParent("budgets"),
		tableAlias: alias,
		CategoryID: psql.Quote(alias, "category_id"),
		Month:      psql.Quote(alias, "month"),
		Amount:     psql.Quote(alias, "amount"),
	}
}

type budgetColumns struct {
	expr.ColumnsExpr
	tableAlias string
	CategoryID psql.Expression
	Month      psql.Expression
	Amount     psql.Expression
}

func (c budgetColumns) Alias() string {
	return c.tableAlias
}

func (budgetColumns) AliasedAs(alias string) budgetColumns {
	return buildBudgetColumns(alias)
}

// BudgetSetter is used for insert/upsert/update operations
// All values are optional, and do not have to be set
// Generated columns are not included
type BudgetSetter struct {
	CategoryID omit.Val[uuid.UUID]       `db:"category_id,pk" `
	Month      omit.Val[time.Time]       `db:"month,pk" `
	Amount     omit.Val[decimal.Decimal] `db:"amount" `
}

func (s BudgetSetter) SetColumns() []string {
	vals := make([]string, 0, 3)
	if s.CategoryID.IsValue() {
		vals = append(vals, "category_id")
	}
	if s.Month.IsValue() {
		vals = append(vals, "month")
	}
	if s.Amount.IsValue() {
		vals = append(vals, "amount")
	}
	return vals
}

func (s BudgetSetter) Overwrite(t *Budget) {
	if s.CategoryID.IsValue() {
		t.CategoryID = s.CategoryID.MustGet()
	}
	if s.Month.IsValue() {
		t.Month = s.Month.MustGet()
	}
	if s.Amount.IsValue() {
		t.Amount = s.Amount.MustGet()
	}
}

func (s *BudgetSetter) Apply(q *dialect.InsertQuery) {
	q.AppendHooks(func(ctx context.Context, exec bob.Executor) (context.Context, error) {
		return Budgets.BeforeInsertHooks.RunHooks(ctx, exec, s)
	})

	q.AppendValues(bob.ExpressionFunc(func(ctx context.Context, w io.StringWriter, d bob.Dialect, start int) ([]any, error) {
		vals := make([]bob.Expression, 3)
		if s.CategoryID.IsValue() {
			vals[0] = psql.Arg(s.CategoryID.MustGet())
		} else {
			vals[0] = psql.Raw("DEFAULT")
		}

		if s.Month.IsValue() {
			vals[1] = psql.Arg(s.Month.MustGet())
		} else {
			vals[1] = psql.Raw("DEFAULT")
		}

		if s.Amount.IsValue() {
			vals[2] = psql.Arg(s.Amount.MustGet())
		} else {
			vals[2] = psql.Raw("DEFAULT")
		}

		return bob.ExpressSlice(ctx, w, d, start, vals, "", ", ", "")
	}))
}

func (s BudgetSetter) UpdateMod() bob.Mod[*dialect.UpdateQuery] {
	return um.Set(s.Expressions()...)
}

func (s BudgetSetter) Expressions(prefix ...string) []bob.Expression {
	exprs := make([]bob.Expression, 0, 3)

	if s.CategoryID.IsValue() {
		exprs = append(exprs, expr.Join{Sep: " = ", Exprs: []bob.Expression{
			psql.Quote(append(prefix, "category_id")...),
			psql.Arg(s.CategoryID),
		}})
	}

	if s.Month.IsValue() {
		exprs = append(exprs, expr.Join{Sep: " = ", Exprs: []bob.Expression{
			psql.Quote(append(prefix, "month")...),
			psql.Arg(s.Month),
		}})
	}

	if s.Amount.IsValue() {
		exprs = append(exprs, expr.Join{Sep: " = ", Exprs: []bob.Expression{
			psql.Quote(append(prefix, "amount")...),
			psql.Arg(s.Amount),
		}})
	}

	return exprs
}

// FindBudget retrieves a single record by primary key
// If cols is empty Find will return all columns.
func FindBudget(ctx context.Context, exec bob.Executor, CategoryIDPK uuid.UUID, MonthPK time.Time, cols ...string) (*Budget, error) {
	if len(cols) == 0 {
		return Budgets.Query(
			sm.Where(Budgets.Columns.CategoryID.EQ(psql.Arg(CategoryIDPK))),
			sm.Where(Budgets.Columns.Month.EQ(psql.Arg(MonthPK))),
		).One(ctx, exec)
	}

	return Budgets.Query(
		sm.Where(Budgets.Columns.CategoryID.EQ(psql.Arg(CategoryIDPK))),
		sm.Where(Budgets.Columns.Month.EQ(psql.Arg(MonthPK))),
		sm.Columns(Budgets.Columns.Only(cols...)),
	).One(ctx, exec)
}

// BudgetExists checks the presence of a single record by primary key
func BudgetExists(ctx context.Context, exec bob.Executor, CategoryIDPK uuid.UUID, MonthPK time.Time) (bool, error) {
	return Budgets.Query(
		sm.Where(Budgets.Columns.CategoryID.EQ(psql.Arg(CategoryIDPK))),
		sm.Where(Budgets.Columns.Month.EQ(psql.Arg(MonthPK))),
	).Exists(ctx, exec)
}

// AfterQueryHook is called after Budget is retrieved from the database
func (o *Budget) AfterQueryHook(ctx context.Context, exec bob.Executor, queryType bob.QueryType) error {
	var err error

	switch queryType {
	case bob.QueryTypeSelect:
		ctx, err = Budgets.AfterSelectHooks.RunHooks(ctx, exec, BudgetSlice{o})
	case bob.QueryTypeInsert:
		ctx, err = Budgets.AfterInsertHooks.RunHooks(ctx, exec, BudgetSlice{o})
	case bob.QueryTypeUpdate:
		ctx, err = Budgets.AfterUpdateHooks.RunHooks(ctx, exec, BudgetSlice{o})
	case bob.QueryTypeDelete:
		ctx, err = Budgets.AfterDeleteHooks.RunHooks(ctx, exec, BudgetSlice{o})
	}

	return err
}

// primaryKeyVals returns the primary key values of the Budget
func (o *Budget) primaryKeyVals() bob.Expression {
	return psql.ArgGroup(
		o.CategoryID,
		o.Month,
	)
}

func (o *Budget) pkEQ() dialect.Expression {
	return psql.Group(psql.Quote("budgets", "category_id"), psql.Quote("budgets", "month")).EQ(bob.ExpressionFunc(func(ctx context.Context, w io.StringWriter, d bob.Dialect, start int) ([]any, error) {
		return o.primaryKeyVals().WriteSQL(ctx, w, d, start)
	}))
}

// Update uses an executor to update the Budget
func (o *Budget) Update(ctx context.Context, exec bob.Executor, s *BudgetSetter) error {
	v, err := Budgets.Update(s.UpdateMod(), um.Where(o.pkEQ())).One(ctx, exec)
	if err != nil {
		return err
	}

	o.R = v.R
	*o = *v

	return nil
}

// Delete deletes a single Budget record with an executor
func (o *Budget) Delete(ctx context.Context, exec bob.Executor) error {
	_, err := Budgets.Delete(dm.Where(o.pkEQ())).Exec(ctx, exec)
	return err
}

// Reload refreshes the Budget using the executor
func (o *Budget) Reload(ctx context.Context, exec bob.Executor) error {
	o2, err := Budgets.Query(
		sm.Where(Budgets.Columns.CategoryID.EQ(psql.Arg(o.CategoryID))),
		sm.Where(Budgets.Columns.Month.EQ(psql.Arg(o.Month))),
	).One(ctx, exec)
	if err != nil {
		return err
	}
	o2.R = o.R
	*o = *o2

	return nil
}

// AfterQueryHook is called after BudgetSlice is retrieved from the database
func (o BudgetSlice) AfterQueryHook(ctx context.Context, exec bob.Executor, queryType bob.QueryType) error {
	var err error

	switch queryType {
	case bob.QueryTypeSelect:
		ctx, err = Budgets.AfterSelectHooks.RunHooks(ctx, exec, o)
	case bob.QueryTypeInsert:
		ctx, err = Budgets.AfterInsertHooks.RunHooks(ctx, exec, o)
	case bob.QueryTypeUpdate:
		ctx, err = Budgets.AfterUpdateHooks.RunHooks(ctx, exec, o)
	case bob.QueryTypeDelete:
		ctx, err = Budgets.AfterDeleteHooks.RunHooks(ctx, exec, o)
	}

	return err
}

func (o BudgetSlice) pkIN() dialect.Expression {
	if len(o) == 0 {
		return psql.Raw("NULL")
	}

	return psql.Group(psql.Quote("budgets", "category_id"), psql.Quote("budgets", "month")).In(bob.ExpressionFunc(func(ctx context.Context, w io.StringWriter, d bob.Dialect, start int) ([]any, error) {
		pkPairs := make([]bob.Expression, len(o))
		for i, row := range o {
			pkPairs[i] = row.primaryKeyVals()
		}
		return bob.ExpressSlice(ctx, w, d, start, pkPairs, "", ", ", "")
	}))
}

// copyMatchingRows finds models in the given slice that have the same primary key
// then it first copies the existing relationships from the old model to the new model
// and then replaces the old model in the slice with the new model
func (o BudgetSlice) copyMatchingRows(from ...*Budget) {
	for i, old := range o {
		for _, new := range from {
			if new.CategoryID != old.CategoryID {
				continue
			}
			if new.Month.Equal(old.Month) {
				continue
			}
			new.R = old.R
			o[i] = new
			break
		}
	}
}

// UpdateMod modifies an update query with "WHERE primary_key IN (o...)"
func (o BudgetSlice) UpdateMod() bob.Mod[*dialect.UpdateQuery] {
	return bob.ModFunc[*dialect.UpdateQuery](func(q *dialect.UpdateQuery) {
		q.AppendHooks(func(ctx context.Context, exec bob.Executor) (context.Context, error) {
			return Budgets.BeforeUpdateHooks.RunHooks(ctx, exec, o)
		})

		q.AppendLoader(bob.LoaderFunc(func(ctx context.Context, exec bob.Executor, retrieved any) error {
			var err error
			switch retrieved := retrieved.(type) {
			case *Budget:
				o.copyMatchingRows(retrieved)
			case []*Budget:
				o.copyMatchingRows(retrieved...)
			case BudgetSlice:
				o.copyMatchingRows(retrieved...)
			default:
				// If the retrieved value is not a Budget or a slice of Budget
				// then run the AfterUpdateHooks on the slice
				_, err = Budgets.AfterUpdateHooks.RunHooks(ctx, exec, o)
			}

			return err
		}))

		q.AppendWhere(o.pkIN())
	})
}

// DeleteMod modifies an delete query with "WHERE primary_key IN (o...)"
func (o BudgetSlice) DeleteMod() bob.Mod[*dialect.DeleteQuery] {
	return bob.ModFunc[*dialect.DeleteQuery](func(q *dialect.DeleteQuery) {
		q.AppendHooks(func(ctx context.Context, exec bob.Executor) (context.Context, error) {
			return Budgets.BeforeDeleteHooks.RunHooks(ctx, exec, o)
		})

		q.AppendLoader(bob.LoaderFunc(func(ctx context.Context, exec bob.Executor, retrieved any) error {
			var err error
			switch retrieved := retrieved.(type) {
			case *Budget:
				o.copyMatchingRows(retrieved)
			case []*Budget:
				o.copyMatchingRows(retrieved...)
			case BudgetSlice:
				o.copyMatchingRows(retrieved...)
			default:
				// If the retrieved value is not a Budget or a slice of Budget
				// then run the AfterDeleteHooks on the slice
				_, err = Budgets.AfterDeleteHooks.RunHooks(ctx, exec, o)
			}

			return err
		}))

		q.AppendWhere(o.pkIN())
	})
}

func (o BudgetSlice) UpdateAll(ctx context.Context, exec bob.Executor, vals BudgetSetter) error {
	if len(o) == 0 {
		return nil
	}

	_, err := Budgets.Update(vals.UpdateMod(), o.UpdateMod()).All(ctx, exec)
	return err
}

func (o BudgetSlice) DeleteAll(ctx context.Context, exec bob.Executor) error {
	if len(o) == 0 {
		return nil
	}

	_, err := Budgets.Delete(o.DeleteMod()).Exec(ctx, exec)
	return err
}

func (o BudgetSlice) ReloadAll(ctx context.Context, exec bob.Executor) error {
	if len(o) == 0 {
		return nil
	}

	o2, err := Budgets.Query(sm.Where(o.pkIN())).All(ctx, exec)
	if err != nil {
		return err
	}

	o.copyMatchingRows(o2...)

	return nil
}

// Category starts a query for related objects on categories
func (o *Budget) Category(mods ...bob.Mod[*dialect.SelectQuery]) CategoriesQuery {
	return Categories.Query(append(mods,
		sm.Where(Categories.Columns.ID.EQ(psql.Arg(o.CategoryID))),
	)...)
}

func (os BudgetSlice) Category(mods ...bob.Mod[*dialect.SelectQuery]) CategoriesQuery {
	pkCategoryID := make(pgtypes.Array[uuid.UUID], 0, len(os))
	for _, o := range os {
		if o == nil {
			continue
		}
		pkCategoryID = append(pkCategoryID, o.CategoryID)
	}
	PKArgExpr := psql.Select(sm.Columns(
		psql.F("unnest", psql.Cast(psql.Arg(pkCategoryID), "uuid[]")),
	))

	return Categories.Query(append(mods,
		sm.Where(psql.Group(Categories.Columns.ID).OP("IN", PKArgExpr)),
	)...)
}

func attachBudgetCategory0(ctx context.Context, exec bob.Executor, count int, budget0 *Budget, category1 *Category) (*Budget, error) {
	setter := &BudgetSetter{
		CategoryID: omit.From(category1.ID),
	}

	err := budget0.Update(ctx, exec, setter)
	if err != nil {
		return nil, fmt.Errorf("attachBudgetCategory0: %w", err)
	}

	return budget0, nil
}

func (budget0 *Budget) InsertCategory(ctx context.Context, exec bob.Executor, related *CategorySetter) error {
	var err error

	category1, err := Categories.Insert(related).One(ctx, exec)
	if err != nil {
		return fmt.Errorf("inserting related objects: %w", err)
	}

	_, err = attachBudgetCategory0(ctx, exec, 1, budget0, category1)
	if err != nil {
		return err
	}

	budget0.R.Category = category1

	category1.R.Budgets = append(category1.R.Budgets, budget0)

	return nil
}

func (budget0 *Budget) AttachCategory(ctx context.Context, exec bob.Executor, category1 *Category) error {
	var err error

	_, err = attachBudgetCategory0(ctx, exec, 1, budget0, category1)
	if err != nil {
		return err
	}

	budget0.R.Category = category1

	category1.R.Budgets = append(category1.R.Budgets, budget0)

	return nil
}

type budgetWhere[Q psql.Filterable] struct {
	CategoryID psql.WhereMod[Q, uuid.UUID]
	Month      psql.WhereMod[Q, time.Time]
	Amount     psql.WhereMod[Q, decimal.Decimal]
}

func (budgetWhere[Q]) AliasedAs(alias string) budgetWhere[Q] {
	return buildBudgetWhere[Q](buildBudgetColumns(alias))
}

func buildBudgetWhere[Q psql.Filterable](cols budgetColumns) budgetWhere[Q] {
	return budgetWhere[Q]{
		CategoryID: psql.Where[Q, uuid.UUID](cols.CategoryID),
		Month:      psql.Where[Q, time.Time](cols.Month),
		Amount:     psql.Where[Q, decimal.Decimal](cols.Amount),
	}
}

func (o *Budget) Preload(name string, retrieved any) error {
	if o == nil {
		return nil
	}

	switch name {
	case "Category":
		rel, ok := retrieved.(*Category)
		if !ok {
			return fmt.Errorf("budget cannot load %T as %q", retrieved, name)
		}

		o.R.Category = rel

		if rel != nil {
			rel.R.Budgets = BudgetSlice{o}
		}
		return nil
	default:
		return fmt.Errorf("budget has no relationship %q", name)
	}
}

type budgetPreloader struct {
	Category func(...psql.PreloadOption) psql.Preloader
}

func buildBudgetPreloader() budgetPreloader {
	return budgetPreloader{
		Category: func(opts ...psql.PreloadOption) psql.Preloader {
			return psql.Preload[*Category, CategorySlice](psql.PreloadRel{
				Name: "Category",
				Sides: []psql.PreloadSide{
					{
						From:        Budgets,
						To:          Categories,
						FromColumns: []string{"category_id"},
						ToColumns:   []string{"id"},
					},
				},
			}, Categories.Columns.Names(), opts...)
		},
	}
}

type budgetThenLoader[Q orm.Loadable] struct {
	Category func(...bob.Mod[*dialect.SelectQuery]) orm.Loader[Q]
}

func buildBudgetThenLoader[Q orm.Loadable]() budgetThenLoader[Q] {
	type CategoryLoadInterface interface {
		LoadCategory(context.Context, bob.Executor, ...bob.Mod[*dialect.SelectQuery]) error
	}

	return budgetThenLoader[Q]{
		Category: thenLoadBuilder[Q](
			"Category",
			func(ctx context.Context, exec bob.Executor, retrieved CategoryLoadInterface, mods ...bob.Mod[*dialect.SelectQuery]) error {
				return retrieved.LoadCategory(ctx, exec, mods...)
			},
		),
	}
}

// LoadCategory loads the budget's Category into the .R struct
func (o *Budget) LoadCategory(ctx context.Context, exec bob.Executor, mods ...bob.Mod[*dialect.SelectQuery]) error {
	if o == nil {
		return nil
	}

	// Reset the relationship
	o.R.Category = nil

	related, err := o.Category(mods...).One(ctx, exec)
	if err != nil {
		return err
	}

	related.R.Budgets = BudgetSlice{o}

	o.R.Category = related
	return nil
}

// LoadCategory loads the budget's Category into the .R struct
func (os BudgetSlice) LoadCategory(ctx context.Context, exec bob.Executor, mods ...bob.Mod[*dialect.SelectQuery]) error {
	if len(os) == 0 {
		return nil
	}

	categories, err := os.Category(mods...).All(ctx, exec)
	if err != nil {
		return err
	}

	for _, o := range os {
		if o == nil {
			continue
		}

		for _, rel := range categories {

			if !(o.CategoryID == rel.ID) {
				continue
			}

			rel.R.Budgets = append(rel.R.Budgets, o)

			o.R.Category = rel
			break
		}
	}

	return nil
}

type budgetJoins[Q dialect.Joinable] struct {
	typ      string
	Category modAs[Q, categoryColumns]
}

func (j budgetJoins[Q]) aliasedAs(alias string) budgetJoins[Q] {
	return buildBudgetJoins[Q](buildBudgetColumns(alias), j.typ)
}

func buildBudgetJoins[Q dialect.Joinable](cols budgetColumns, typ string) budgetJoins[Q] {
	return budgetJoins[Q]{
		typ: typ,
		Category: modAs[Q, categoryColumns]{
			c: Categories.Columns,
			f: func(to categoryColumns) bob.Mod[Q] {
				mods := make(mods.QueryMods[Q], 0, 1)

				{
					mods = append(mods, dialect.Join[Q](typ, Categories.Name().As(to.Alias())).On(
						to.ID.EQ(cols.CategoryID),
					))
				}

				return mods
			},
		},
	}
}
