// Code generated by BobGen psql v0.50.0. DO NOT EDIT.
// This file is meant to be re-generated in place and/or deleted at any time.

package bobgen

import (
	"context"
	"fmt"
	"io"
	"time"

	"github.com/aarondl/opt/omit"
	"github.com/gofrs/uuid/v5"
	"github.com/shopspring/decimal"
	"github.com/stephenafamo/bob"
	"github.com/stephenafamo/bob/dialect/psql"
	"github.com/stephenafamo/bob/dialect/psql/dialect"
	"github.com/stephenafamo/bob/dialect/psql/dm"
	"github.com/stephenafamo/bob/dialect/psql/sm"
	"github.com/stephenafamo/bob/dialect/psql/um"
	"github.com/stephenafamo/bob/expr"
	"github.com/stephenafamo/bob/mods"
	"github.com/stephenafamo/bob/orm"
	"github.com/stephenafamo/bob/types/pgtypes"
	"github.com/stephenafamo/scan"
)

// Budget is an object representing the database table.
type Budget struct {
	CategoryID uuid.UUID       `db:"category_id,pk" `
	Month      time.Time       `db:"month,pk" `
	Amount     decimal.Decimal `db:"amount" `

	R budgetR `db:"-" `
}

// BudgetSlice is an alias for a slice of pointers to Budget.
// This should almost always be used instead of []*Budget.
type BudgetSlice []*Budget

// Budgets contains methods to work with the budgets table
var Budgets = psql.NewTablex[*Budget, BudgetSlice, *BudgetSetter]("", "budgets", buildBudgetColumns("budgets"), budgetScanMapper)

// BudgetsQuery is a query on the budgets table
type BudgetsQuery = *psql.ViewQuery[*Budget, BudgetSlice]

// budgetR is where relationships are stored.
type budgetR struct {
	Category *Category // budgets.fk_budgets_category
	// Loaded reports whether each relationship has been loaded.
	// A relationship's bool is set by Load*, Preload, ThenLoad, factory builds,
	// and to-one Attach/Insert operations. To-many Attach/Insert operations leave it unchanged.
	Loaded budgetRLoaded `db:"-" `
}

// budgetRLoaded tracks which relationships on Budget have been loaded.
type budgetRLoaded struct {
	Category bool // budgets.fk_budgets_category
}

func buildBudgetColumns(tableName string) budgetColumns {
	columnsExpr := expr.NewColumnsExpr(
		"category_id", "month", "amount",
	)

	if tableName != "" {
		columnsExpr = columnsExpr.WithParent(tableName)
	}

	return budgetColumns{
		ColumnsExpr: columnsExpr,
		tableAlias:  tableName,
		CategoryID:  buildBudgetColumn(tableName, "category_id"),
		Month:       buildBudgetColumn(tableName, "month"),
		Amount:      buildBudgetColumn(tableName, "amount"),
	}
}

type budgetColumns struct {
	expr.ColumnsExpr
	tableAlias string
	CategoryID budgetColumn
	Month      budgetColumn
	Amount     budgetColumn
}

// Alias returns the current table alias for the columns set.
func (c budgetColumns) Alias() string {
	return c.tableAlias
}

// AliasedAs returns a copy of the columns set qualified by tableName.
func (budgetColumns) AliasedAs(tableName string) budgetColumns {
	return buildBudgetColumns(tableName)
}

// Unqualified returns a copy of the columns set without table qualification.
func (c budgetColumns) Unqualified() budgetColumns {
	return buildBudgetColumns("")
}

func buildBudgetColumn(alias, name string) budgetColumn {
	return budgetColumn{
		Expression: psql.Quote(alias, name),
		alias:      alias,
		name:       name,
	}
}

type budgetColumn struct {
	psql.Expression
	alias string
	name  string
}

// Name returns the unqualified column name.
func (c budgetColumn) Name() string {
	return c.name
}

// ShouldOmitParens prevents automatic parenthesis wrapping in expression builders.
func (c budgetColumn) ShouldOmitParens() bool {
	return true
}

// BudgetSetter is used for insert/upsert/update operations
// All values are optional, and do not have to be set
// Generated columns are not included
type BudgetSetter struct {
	CategoryID omit.Val[uuid.UUID]       `db:"category_id,pk" `
	Month      omit.Val[time.Time]       `db:"month,pk" `
	Amount     omit.Val[decimal.Decimal] `db:"amount" `
}

func (s BudgetSetter) SetColumns() []string {
	vals := make([]string, 0, 3)
	if s.CategoryID.IsValue() {
		vals = append(vals, "category_id")
	}
	if s.Month.IsValue() {
		vals = append(vals, "month")
	}
	if s.Amount.IsValue() {
		vals = append(vals, "amount")
	}
	return vals
}

func (s BudgetSetter) Overwrite(t *Budget) {
	if s.CategoryID.IsValue() {
		t.CategoryID = s.CategoryID.MustGet()
	}
	if s.Month.IsValue() {
		t.Month = s.Month.MustGet()
	}
	if s.Amount.IsValue() {
		t.Amount = s.Amount.MustGet()
	}
}

func (s *BudgetSetter) Apply(q *dialect.InsertQuery) {
	q.AppendHooks(func(ctx context.Context, exec bob.Executor) (context.Context, error) {
		return Budgets.BeforeInsertHooks.RunHooks(ctx, exec, s)
	})

	q.AppendValues(
		bob.ExpressionFunc(func(ctx context.Context, w io.StringWriter, d bob.Dialect, start int) ([]any, error) {
			if s.CategoryID.IsUnset() {
				return psql.Raw("DEFAULT").WriteSQL(ctx, w, d, start)
			}
			return psql.Arg(s.CategoryID.MustGet()).WriteSQL(ctx, w, d, start)
		}), bob.ExpressionFunc(func(ctx context.Context, w io.StringWriter, d bob.Dialect, start int) ([]any, error) {
			if s.Month.IsUnset() {
				return psql.Raw("DEFAULT").WriteSQL(ctx, w, d, start)
			}
			return psql.Arg(s.Month.MustGet()).WriteSQL(ctx, w, d, start)
		}), bob.ExpressionFunc(func(ctx context.Context, w io.StringWriter, d bob.Dialect, start int) ([]any, error) {
			if s.Amount.IsUnset() {
				return psql.Raw("DEFAULT").WriteSQL(ctx, w, d, start)
			}
			return psql.Arg(s.Amount.MustGet()).WriteSQL(ctx, w, d, start)
		}))
}

func (s BudgetSetter) UpdateMod() bob.Mod[*dialect.UpdateQuery] {
	return um.Set(s.Expressions()...)
}

func (s BudgetSetter) Expressions(prefix ...string) []bob.Expression {
	exprs := make([]bob.Expression, 0, 3)

	if s.CategoryID.IsValue() {
		exprs = append(exprs, expr.Join{Sep: " = ", Exprs: []bob.Expression{
			psql.Quote(append(prefix, "category_id")...),
			psql.Arg(s.CategoryID),
		}})
	}

	if s.Month.IsValue() {
		exprs = append(exprs, expr.Join{Sep: " = ", Exprs: []bob.Expression{
			psql.Quote(append(prefix, "month")...),
			psql.Arg(s.Month),
		}})
	}

	if s.Amount.IsValue() {
		exprs = append(exprs, expr.Join{Sep: " = ", Exprs: []bob.Expression{
			psql.Quote(append(prefix, "amount")...),
			psql.Arg(s.Amount),
		}})
	}

	return exprs
}

// scan.Mapper[*T] without reflection: maps columns to fields by index.
func budgetScanMapper(ctx context.Context, cols []string) (scan.BeforeFunc, func(any) (*Budget, error)) {
	// resolve the column positions once per query, not per row
	type target struct {
		idx int
		dst func(o *Budget) any
	}
	targets := make([]target, 0, 3)
	for i, col := range cols {
		switch col {
		case "category_id":
			targets = append(targets, target{i, func(o *Budget) any { return &o.CategoryID }})
		case "month":
			targets = append(targets, target{i, func(o *Budget) any { return &o.Month }})
		case "amount":
			targets = append(targets, target{i, func(o *Budget) any { return &o.Amount }})
		}
	}

	return func(row *scan.Row) (any, error) {
			o := new(Budget)
			for _, t := range targets {
				row.ScheduleScanByIndex(t.idx, t.dst(o))
			}
			return o, nil
		}, func(v any) (*Budget, error) {
			return v.(*Budget), nil
		}
}

// FindBudget retrieves a single record by primary key
// If cols is empty Find will return all columns.
func FindBudget(ctx context.Context, exec bob.Executor, CategoryIDPK uuid.UUID, MonthPK time.Time, cols ...string) (*Budget, error) {
	if len(cols) == 0 {
		return Budgets.Query(
			sm.Where(Budgets.Columns.CategoryID.EQ(psql.Arg(CategoryIDPK))),
			sm.Where(Budgets.Columns.Month.EQ(psql.Arg(MonthPK))),
		).One(ctx, exec)
	}

	return Budgets.Query(
		sm.Where(Budgets.Columns.CategoryID.EQ(psql.Arg(CategoryIDPK))),
		sm.Where(Budgets.Columns.Month.EQ(psql.Arg(MonthPK))),
		sm.Columns(Budgets.Columns.Only(cols...)),
	).One(ctx, exec)
}

// BudgetExists checks the presence of a single record by primary key
func BudgetExists(ctx context.Context, exec bob.Executor, CategoryIDPK uuid.UUID, MonthPK time.Time) (bool, error) {
	return Budgets.Query(
		sm.Where(Budgets.Columns.CategoryID.EQ(psql.Arg(CategoryIDPK))),
		sm.Where(Budgets.Columns.Month.EQ(psql.Arg(MonthPK))),
	).Exists(ctx, exec)
}

// AfterQueryHook is called after Budget is retrieved from the database
func (o *Budget) AfterQueryHook(ctx context.Context, exec bob.Executor, queryType bob.QueryType) error {
	var err error

	switch queryType {
	case bob.QueryTypeSelect:
		ctx, err = Budgets.AfterSelectHooks.RunHooks(ctx, exec, BudgetSlice{o})
	case bob.QueryTypeInsert:
		ctx, err = Budgets.AfterInsertHooks.RunHooks(ctx, exec, BudgetSlice{o})
	case bob.QueryTypeUpdate:
		ctx, err = Budgets.AfterUpdateHooks.RunHooks(ctx, exec, BudgetSlice{o})
	case bob.QueryTypeDelete:
		ctx, err = Budgets.AfterDeleteHooks.RunHooks(ctx, exec, BudgetSlice{o})
	case bob.QueryTypeMerge:
		ctx, err = Budgets.AfterMergeHooks.RunHooks(ctx, exec, BudgetSlice{o})
	}

	return err
}

// primaryKeyVals returns the primary key values of the Budget
func (o *Budget) primaryKeyVals() bob.Expression {
	return psql.ArgGroup(
		o.CategoryID,
		o.Month,
	)
}

func (o *Budget) pkEQ() dialect.Expression {
	return psql.Group(psql.Quote("budgets", "category_id"), psql.Quote("budgets", "month")).EQ(bob.ExpressionFunc(func(ctx context.Context, w io.StringWriter, d bob.Dialect, start int) ([]any, error) {
		return o.primaryKeyVals().WriteSQL(ctx, w, d, start)
	}))
}

// Update uses an executor to update the Budget
func (o *Budget) Update(ctx context.Context, exec bob.Executor, s *BudgetSetter) error {
	v, err := Budgets.Update(s.UpdateMod(), um.Where(o.pkEQ())).One(ctx, exec)
	if err != nil {
		return err
	}

	o.R = v.R
	*o = *v

	return nil
}

// Delete deletes a single Budget record with an executor
func (o *Budget) Delete(ctx context.Context, exec bob.Executor) error {
	_, err := Budgets.Delete(dm.Where(o.pkEQ())).Exec(ctx, exec)
	return err
}

// Reload refreshes the Budget using the executor
func (o *Budget) Reload(ctx context.Context, exec bob.Executor) error {
	o2, err := Budgets.Query(
		sm.Where(Budgets.Columns.CategoryID.EQ(psql.Arg(o.CategoryID))),
		sm.Where(Budgets.Columns.Month.EQ(psql.Arg(o.Month))),
	).One(ctx, exec)
	if err != nil {
		return err
	}
	o2.R = o.R
	*o = *o2

	return nil
}

// AfterQueryHook is called after BudgetSlice is retrieved from the database
func (o BudgetSlice) AfterQueryHook(ctx context.Context, exec bob.Executor, queryType bob.QueryType) error {
	var err error

	switch queryType {
	case bob.QueryTypeSelect:
		ctx, err = Budgets.AfterSelectHooks.RunHooks(ctx, exec, o)
	case bob.QueryTypeInsert:
		ctx, err = Budgets.AfterInsertHooks.RunHooks(ctx, exec, o)
	case bob.QueryTypeUpdate:
		ctx, err = Budgets.AfterUpdateHooks.RunHooks(ctx, exec, o)
	case bob.QueryTypeDelete:
		ctx, err = Budgets.AfterDeleteHooks.RunHooks(ctx, exec, o)
	case bob.QueryTypeMerge:
		ctx, err = Budgets.AfterMergeHooks.RunHooks(ctx, exec, o)
	}

	return err
}

func (o BudgetSlice) pkIN() dialect.Expression {
	if len(o) == 0 {
		return psql.Raw("NULL")
	}

	return psql.Group(psql.Quote("budgets", "category_id"), psql.Quote("budgets", "month")).In(bob.ExpressionFunc(func(ctx context.Context, w io.StringWriter, d bob.Dialect, start int) ([]any, error) {
		pkPairs := make([]bob.Expression, len(o))
		for i, row := range o {
			pkPairs[i] = row.primaryKeyVals()
		}
		return bob.ExpressSlice(ctx, w, d, start, pkPairs, "", ", ", "")
	}))
}

// copyMatchingRows finds models in the given slice that have the same primary key
// then it first copies the existing relationships from the old model to the new model
// and then replaces the old model in the slice with the new model
func (o BudgetSlice) copyMatchingRows(from ...*Budget) {
	for i, old := range o {
		for _, new := range from {
			if new.CategoryID != old.CategoryID {
				continue
			}
			if new.Month.Equal(old.Month) {
				continue
			}
			new.R = old.R
			o[i] = new
			break
		}
	}
}

// UpdateMod modifies an update query with "WHERE primary_key IN (o...)"
func (o BudgetSlice) UpdateMod() bob.Mod[*dialect.UpdateQuery] {
	return bob.ModFunc[*dialect.UpdateQuery](func(q *dialect.UpdateQuery) {
		q.AppendHooks(func(ctx context.Context, exec bob.Executor) (context.Context, error) {
			return Budgets.BeforeUpdateHooks.RunHooks(ctx, exec, o)
		})

		q.AppendLoader(bob.LoaderFunc(func(ctx context.Context, exec bob.Executor, retrieved any) error {
			var err error
			switch retrieved := retrieved.(type) {
			case *Budget:
				o.copyMatchingRows(retrieved)
			case []*Budget:
				o.copyMatchingRows(retrieved...)
			case BudgetSlice:
				o.copyMatchingRows(retrieved...)
			default:
				// If the retrieved value is not a Budget or a slice of Budget
				// then run the AfterUpdateHooks on the slice
				_, err = Budgets.AfterUpdateHooks.RunHooks(ctx, exec, o)
			}

			return err
		}))

		q.AppendWhere(o.pkIN())
	})
}

// DeleteMod modifies an delete query with "WHERE primary_key IN (o...)"
func (o BudgetSlice) DeleteMod() bob.Mod[*dialect.DeleteQuery] {
	return bob.ModFunc[*dialect.DeleteQuery](func(q *dialect.DeleteQuery) {
		q.AppendHooks(func(ctx context.Context, exec bob.Executor) (context.Context, error) {
			return Budgets.BeforeDeleteHooks.RunHooks(ctx, exec, o)
		})

		q.AppendLoader(bob.LoaderFunc(func(ctx context.Context, exec bob.Executor, retrieved any) error {
			var err error
			switch retrieved := retrieved.(type) {
			case *Budget:
				o.copyMatchingRows(retrieved)
			case []*Budget:
				o.copyMatchingRows(retrieved...)
			case BudgetSlice:
				o.copyMatchingRows(retrieved...)
			default:
				// If the retrieved value is not a Budget or a slice of Budget
				// then run the AfterDeleteHooks on the slice
				_, err = Budgets.AfterDeleteHooks.RunHooks(ctx, exec, o)
			}

			return err
		}))

		q.AppendWhere(o.pkIN())
	})
}

// MergeMod modifies a merge query to run BeforeMergeHooks and AfterMergeHooks
// and updates the slice with the returned rows.
func (o BudgetSlice) MergeMod() bob.Mod[*dialect.MergeQuery] {
	return bob.ModFunc[*dialect.MergeQuery](func(q *dialect.MergeQuery) {
		q.AppendHooks(func(ctx context.Context, exec bob.Executor) (context.Context, error) {
			return Budgets.BeforeMergeHooks.RunHooks(ctx, exec, o)
		})

		q.AppendLoader(bob.LoaderFunc(func(ctx context.Context, exec bob.Executor, retrieved any) error {
			var err error
			switch retrieved := retrieved.(type) {
			case *Budget:
				o.copyMatchingRows(retrieved)
			case []*Budget:
				o.copyMatchingRows(retrieved...)
			case BudgetSlice:
				o.copyMatchingRows(retrieved...)
			default:
				// If the retrieved value is not a Budget or a slice of Budget
				// then run the AfterMergeHooks on the slice
				_, err = Budgets.AfterMergeHooks.RunHooks(ctx, exec, o)
			}

			return err
		}))
	})
}

func (o BudgetSlice) UpdateAll(ctx context.Context, exec bob.Executor, vals BudgetSetter) error {
	if len(o) == 0 {
		return nil
	}

	_, err := Budgets.Update(vals.UpdateMod(), o.UpdateMod()).All(ctx, exec)
	return err
}

func (o BudgetSlice) DeleteAll(ctx context.Context, exec bob.Executor) error {
	if len(o) == 0 {
		return nil
	}

	_, err := Budgets.Delete(o.DeleteMod()).Exec(ctx, exec)
	return err
}

func (o BudgetSlice) ReloadAll(ctx context.Context, exec bob.Executor) error {
	if len(o) == 0 {
		return nil
	}

	o2, err := Budgets.Query(sm.Where(o.pkIN())).All(ctx, exec)
	if err != nil {
		return err
	}

	o.copyMatchingRows(o2...)

	return nil
}

// Category starts a query for related objects on categories
func (o *Budget) Category(mods ...bob.Mod[*dialect.SelectQuery]) CategoriesQuery {
	return Categories.Query(append(mods,
		sm.Where(Categories.Columns.ID.EQ(psql.Arg(o.CategoryID))),
	)...)
}

func (os BudgetSlice) Category(mods ...bob.Mod[*dialect.SelectQuery]) CategoriesQuery {
	pkCategoryID := make(pgtypes.Array[uuid.UUID], 0, len(os))

	// the array is only a filter (semi-join), so duplicate keys can be
	// dropped before they are sent over the wire
	seenCategoryID := make(map[uuid.UUID]struct{}, len(os))
	for _, o := range os {
		if o == nil {
			continue
		}
		if _, ok := seenCategoryID[o.CategoryID]; ok {
			continue
		}
		seenCategoryID[o.CategoryID] = struct{}{}
		pkCategoryID = append(pkCategoryID, o.CategoryID)
	}
	PKArgExpr := psql.Any(psql.Cast(psql.Arg(pkCategoryID), "uuid[]"))

	return Categories.Query(append(mods,
		sm.Where(Categories.Columns.ID.EQ(PKArgExpr)),
	)...)
}

func attachBudgetCategory0(ctx context.Context, exec bob.Executor, count int, budget0 *Budget, category1 *Category) (*Budget, error) {
	setter := &BudgetSetter{
		CategoryID: omit.From(category1.ID),
	}

	err := budget0.Update(ctx, exec, setter)
	if err != nil {
		return nil, fmt.Errorf("attachBudgetCategory0: %w", err)
	}

	return budget0, nil
}

func (budget0 *Budget) InsertCategory(ctx context.Context, exec bob.Executor, related *CategorySetter) error {
	var err error

	category1, err := Categories.Insert(related).One(ctx, exec)
	if err != nil {
		return fmt.Errorf("inserting related objects: %w", err)
	}

	_, err = attachBudgetCategory0(ctx, exec, 1, budget0, category1)
	if err != nil {
		return err
	}

	budget0.R.Category = category1
	budget0.R.Loaded.Category = true

	category1.R.Budgets = append(category1.R.Budgets, budget0)

	return nil
}

func (budget0 *Budget) AttachCategory(ctx context.Context, exec bob.Executor, category1 *Category) error {
	var err error

	_, err = attachBudgetCategory0(ctx, exec, 1, budget0, category1)
	if err != nil {
		return err
	}

	budget0.R.Category = category1
	budget0.R.Loaded.Category = true

	category1.R.Budgets = append(category1.R.Budgets, budget0)

	return nil
}

type budgetWhere[Q psql.Filterable] struct {
	cols       budgetColumns
	CategoryID psql.WhereMod[Q, uuid.UUID]
	Month      psql.WhereMod[Q, time.Time]
	Amount     psql.WhereMod[Q, decimal.Decimal]
	R          budgetWhereR[Q]
}

func (budgetWhere[Q]) AliasedAs(alias string) budgetWhere[Q] {
	return buildBudgetWhere[Q](buildBudgetColumns(alias))
}

func buildBudgetWhere[Q psql.Filterable](cols budgetColumns) budgetWhere[Q] {
	return budgetWhere[Q]{
		cols:       cols,
		CategoryID: psql.Where[Q, uuid.UUID](cols.CategoryID.Expression),
		Month:      psql.Where[Q, time.Time](cols.Month.Expression),
		Amount:     psql.Where[Q, decimal.Decimal](cols.Amount.Expression),
		R:          budgetWhereR[Q]{cols: cols},
	}
}

// budgetWhereR holds the relationship-based filters of
// budgetWhere under the R namespace — mirroring the model's
// R struct — so they cannot collide with column-based filter fields.
type budgetWhereR[Q psql.Filterable] struct {
	cols budgetColumns
}

// HasCategory filters parents that have a matching Category using a
// correlated EXISTS subquery (semi-join). Unlike an INNER JOIN it does not
// multiply parent rows, so no DISTINCT is needed. The optional filters are
// applied to the subquery (i.e. to Categories).
func (w budgetWhereR[Q]) HasCategory(filters ...bob.Mod[*dialect.SelectQuery]) mods.Where[Q] {
	q := psql.Select(
		sm.Columns(psql.Raw("1")),
		sm.From(Categories.NameExpr()),
		sm.Where(Categories.Columns.ID.EQ(w.cols.CategoryID)),
	)
	q.Apply(filters...)
	return mods.Where[Q]{E: psql.Exists(q)}
}

func (o *Budget) Preload(name string, retrieved any) error {
	if o == nil {
		return nil
	}

	switch name {
	case "Category":
		rel, ok := retrieved.(*Category)
		if !ok {
			return fmt.Errorf("budget cannot load %T as %q", retrieved, name)
		}

		o.R.Category = rel
		o.R.Loaded.Category = true

		if rel != nil {
			rel.R.Budgets = BudgetSlice{o}
		}
		return nil
	default:
		return fmt.Errorf("budget has no relationship %q", name)
	}
}

type budgetPreloader struct {
	Category func(...psql.PreloadOption) psql.Preloader
}

func buildBudgetPreloader() budgetPreloader {
	return budgetPreloader{
		Category: func(opts ...psql.PreloadOption) psql.Preloader {
			return psql.Preload[*Category, CategorySlice](psql.PreloadRel{
				Name: "Category",
				Sides: []psql.PreloadSide{
					{
						From:        Budgets,
						To:          Categories,
						FromColumns: []string{"category_id"},
						ToColumns:   []string{"id"},
					},
				},
			}, Categories.Columns.Names(), categoryScanMapperNullable, opts...)
		},
	}
}

type budgetThenLoader[Q orm.Loadable] struct {
	Category func(...bob.Mod[*dialect.SelectQuery]) orm.Loader[Q]
}

func buildBudgetThenLoader[Q orm.Loadable]() budgetThenLoader[Q] {
	type CategoryLoadInterface interface {
		LoadCategory(context.Context, bob.Executor, ...bob.Mod[*dialect.SelectQuery]) error
	}

	return budgetThenLoader[Q]{
		Category: thenLoadBuilder[Q](
			"Category",
			func(ctx context.Context, exec bob.Executor, retrieved CategoryLoadInterface, mods ...bob.Mod[*dialect.SelectQuery]) error {
				return retrieved.LoadCategory(ctx, exec, mods...)
			},
		),
	}
}

// LoadCategory loads the budget's Category into the .R struct
func (o *Budget) LoadCategory(ctx context.Context, exec bob.Executor, mods ...bob.Mod[*dialect.SelectQuery]) error {
	if o == nil {
		return nil
	}

	// Reset the relationship
	o.R.Category = nil
	o.R.Loaded.Category = false

	related, err := o.Category(mods...).One(ctx, exec)
	if err != nil {
		return err
	}

	related.R.Budgets = BudgetSlice{o}

	o.R.Category = related
	o.R.Loaded.Category = true
	return nil
}

// LoadCategory loads the budget's Category into the .R struct
func (os BudgetSlice) LoadCategory(ctx context.Context, exec bob.Executor, mods ...bob.Mod[*dialect.SelectQuery]) error {
	if len(os) == 0 {
		return nil
	}

	categories, err := os.Category(mods...).All(ctx, exec)
	if err != nil {
		return err
	}

	for _, o := range os {
		if o == nil {
			continue
		}

		o.R.Category = nil
		o.R.Loaded.Category = true
	}
	// O(N+M) stitch via a map keyed by the join column (key -> []parent; was O(N*M)).
	budgetByKey := make(map[uuid.UUID][]*Budget, len(os))
	for _, o := range os {
		if o == nil {
			continue
		}

		budgetByKey[o.CategoryID] = append(budgetByKey[o.CategoryID], o)
	}

	for _, rel := range categories {

		owners, ok := budgetByKey[rel.ID]
		if !ok {
			continue
		}

		for _, o := range owners {

			// to-one: keep only the first matching child (matches the previous break)
			if o.R.Category != nil {
				continue
			}

			rel.R.Budgets = append(rel.R.Budgets, o)

			o.R.Category = rel

		}
	}

	return nil
}

type budgetJoins[Q dialect.Joinable] struct {
	typ      string
	Category modAs[Q, categoryColumns]
}

func (j budgetJoins[Q]) aliasedAs(alias string) budgetJoins[Q] {
	return buildBudgetJoins[Q](buildBudgetColumns(alias), j.typ)
}

func buildBudgetJoins[Q dialect.Joinable](cols budgetColumns, typ string) budgetJoins[Q] {
	return budgetJoins[Q]{
		typ: typ,
		Category: modAs[Q, categoryColumns]{
			c: Categories.Columns,
			f: func(to categoryColumns) bob.Mod[Q] {
				mods := make(mods.QueryMods[Q], 0, 1)

				{
					mods = append(mods, dialect.Join[Q](typ, Categories.NameExpr().As(to.Alias())).On(
						to.ID.EQ(cols.CategoryID),
					))
				}

				return mods
			},
		},
	}
}
