// Code generated by BobGen psql v0.50.0. DO NOT EDIT.
// This file is meant to be re-generated in place and/or deleted at any time.

package bobgen

import (
	"context"
	"fmt"
	"io"
	"strings"
	"time"

	"github.com/aarondl/opt/null"
	"github.com/aarondl/opt/omit"
	"github.com/aarondl/opt/omitnull"
	"github.com/gofrs/uuid/v5"
	"github.com/stephenafamo/bob"
	"github.com/stephenafamo/bob/dialect/psql"
	"github.com/stephenafamo/bob/dialect/psql/dialect"
	"github.com/stephenafamo/bob/dialect/psql/dm"
	"github.com/stephenafamo/bob/dialect/psql/sm"
	"github.com/stephenafamo/bob/dialect/psql/um"
	"github.com/stephenafamo/bob/expr"
	"github.com/stephenafamo/bob/mods"
	"github.com/stephenafamo/bob/orm"
	"github.com/stephenafamo/bob/types/pgtypes"
	"github.com/stephenafamo/scan"
)

// Category is an object representing the database table.
type Category struct {
	ID               uuid.UUID           `db:"id,pk" `
	Name             string              `db:"name" `
	IsGroup          bool                `db:"is_group" `
	ParentID         null.Val[uuid.UUID] `db:"parent_id" `
	ShouldBeBudgeted bool                `db:"should_be_budgeted" `
	IsDisabled       bool                `db:"is_disabled" `
	CategoryType     int16               `db:"category_type" `
	CreatedAt        time.Time           `db:"created_at" `

	R categoryR `db:"-" `

	C categoryC `db:"-" `
}

// CategorySlice is an alias for a slice of pointers to Category.
// This should almost always be used instead of []*Category.
type CategorySlice []*Category

// Categories contains methods to work with the categories table
var Categories = psql.NewTablex[*Category, CategorySlice, *CategorySetter]("", "categories", buildCategoryColumns("categories"), categoryScanMapper)

// CategoriesQuery is a query on the categories table
type CategoriesQuery = *psql.ViewQuery[*Category, CategorySlice]

// categoryR is where relationships are stored.
type categoryR struct {
	Budgets        BudgetSlice      // budgets.fk_budgets_category
	Parent         *Category        // categories.fk_categories_parent
	ReverseParents CategorySlice    // categories.fk_categories_parent__self_join_reverse
	Transactions   TransactionSlice // transactions.fk_transactions_category_id
	// Loaded reports whether each relationship has been loaded.
	// A relationship's bool is set by Load*, Preload, ThenLoad, factory builds,
	// and to-one Attach/Insert operations. To-many Attach/Insert operations leave it unchanged.
	Loaded categoryRLoaded `db:"-" `
}

// categoryRLoaded tracks which relationships on Category have been loaded.
type categoryRLoaded struct {
	Budgets        bool // budgets.fk_budgets_category
	Parent         bool // categories.fk_categories_parent
	ReverseParents bool // categories.fk_categories_parent__self_join_reverse
	Transactions   bool // transactions.fk_transactions_category_id
}

func buildCategoryColumns(tableName string) categoryColumns {
	columnsExpr := expr.NewColumnsExpr(
		"id", "name", "is_group", "parent_id", "should_be_budgeted", "is_disabled", "category_type", "created_at",
	)

	if tableName != "" {
		columnsExpr = columnsExpr.WithParent(tableName)
	}

	return categoryColumns{
		ColumnsExpr:      columnsExpr,
		tableAlias:       tableName,
		ID:               buildCategoryColumn(tableName, "id"),
		Name:             buildCategoryColumn(tableName, "name"),
		IsGroup:          buildCategoryColumn(tableName, "is_group"),
		ParentID:         buildCategoryColumn(tableName, "parent_id"),
		ShouldBeBudgeted: buildCategoryColumn(tableName, "should_be_budgeted"),
		IsDisabled:       buildCategoryColumn(tableName, "is_disabled"),
		CategoryType:     buildCategoryColumn(tableName, "category_type"),
		CreatedAt:        buildCategoryColumn(tableName, "created_at"),
	}
}

type categoryColumns struct {
	expr.ColumnsExpr
	tableAlias       string
	ID               categoryColumn
	Name             categoryColumn
	IsGroup          categoryColumn
	ParentID         categoryColumn
	ShouldBeBudgeted categoryColumn
	IsDisabled       categoryColumn
	CategoryType     categoryColumn
	CreatedAt        categoryColumn
}

// Alias returns the current table alias for the columns set.
func (c categoryColumns) Alias() string {
	return c.tableAlias
}

// AliasedAs returns a copy of the columns set qualified by tableName.
func (categoryColumns) AliasedAs(tableName string) categoryColumns {
	return buildCategoryColumns(tableName)
}

// Unqualified returns a copy of the columns set without table qualification.
func (c categoryColumns) Unqualified() categoryColumns {
	return buildCategoryColumns("")
}

func buildCategoryColumn(alias, name string) categoryColumn {
	return categoryColumn{
		Expression: psql.Quote(alias, name),
		alias:      alias,
		name:       name,
	}
}

type categoryColumn struct {
	psql.Expression
	alias string
	name  string
}

// Name returns the unqualified column name.
func (c categoryColumn) Name() string {
	return c.name
}

// ShouldOmitParens prevents automatic parenthesis wrapping in expression builders.
func (c categoryColumn) ShouldOmitParens() bool {
	return true
}

// CategorySetter is used for insert/upsert/update operations
// All values are optional, and do not have to be set
// Generated columns are not included
type CategorySetter struct {
	ID               omit.Val[uuid.UUID]     `db:"id,pk" `
	Name             omit.Val[string]        `db:"name" `
	IsGroup          omit.Val[bool]          `db:"is_group" `
	ParentID         omitnull.Val[uuid.UUID] `db:"parent_id" `
	ShouldBeBudgeted omit.Val[bool]          `db:"should_be_budgeted" `
	IsDisabled       omit.Val[bool]          `db:"is_disabled" `
	CategoryType     omit.Val[int16]         `db:"category_type" `
	CreatedAt        omit.Val[time.Time]     `db:"created_at" `
}

func (s CategorySetter) SetColumns() []string {
	vals := make([]string, 0, 8)
	if s.ID.IsValue() {
		vals = append(vals, "id")
	}
	if s.Name.IsValue() {
		vals = append(vals, "name")
	}
	if s.IsGroup.IsValue() {
		vals = append(vals, "is_group")
	}
	if s.ParentID.IsValue() || s.ParentID.IsNull() {
		vals = append(vals, "parent_id")
	}
	if s.ShouldBeBudgeted.IsValue() {
		vals = append(vals, "should_be_budgeted")
	}
	if s.IsDisabled.IsValue() {
		vals = append(vals, "is_disabled")
	}
	if s.CategoryType.IsValue() {
		vals = append(vals, "category_type")
	}
	if s.CreatedAt.IsValue() {
		vals = append(vals, "created_at")
	}
	return vals
}

func (s CategorySetter) Overwrite(t *Category) {
	if s.ID.IsValue() {
		t.ID = s.ID.MustGet()
	}
	if s.Name.IsValue() {
		t.Name = s.Name.MustGet()
	}
	if s.IsGroup.IsValue() {
		t.IsGroup = s.IsGroup.MustGet()
	}
	if s.ParentID.IsValue() || s.ParentID.IsNull() {
		t.ParentID = s.ParentID.MustGetNull()
	}
	if s.ShouldBeBudgeted.IsValue() {
		t.ShouldBeBudgeted = s.ShouldBeBudgeted.MustGet()
	}
	if s.IsDisabled.IsValue() {
		t.IsDisabled = s.IsDisabled.MustGet()
	}
	if s.CategoryType.IsValue() {
		t.CategoryType = s.CategoryType.MustGet()
	}
	if s.CreatedAt.IsValue() {
		t.CreatedAt = s.CreatedAt.MustGet()
	}
}

func (s *CategorySetter) Apply(q *dialect.InsertQuery) {
	q.AppendHooks(func(ctx context.Context, exec bob.Executor) (context.Context, error) {
		return Categories.BeforeInsertHooks.RunHooks(ctx, exec, s)
	})

	q.AppendValues(
		bob.ExpressionFunc(func(ctx context.Context, w io.StringWriter, d bob.Dialect, start int) ([]any, error) {
			if s.ID.IsUnset() {
				return psql.Raw("DEFAULT").WriteSQL(ctx, w, d, start)
			}
			return psql.Arg(s.ID.MustGet()).WriteSQL(ctx, w, d, start)
		}), bob.ExpressionFunc(func(ctx context.Context, w io.StringWriter, d bob.Dialect, start int) ([]any, error) {
			if s.Name.IsUnset() {
				return psql.Raw("DEFAULT").WriteSQL(ctx, w, d, start)
			}
			return psql.Arg(s.Name.MustGet()).WriteSQL(ctx, w, d, start)
		}), bob.ExpressionFunc(func(ctx context.Context, w io.StringWriter, d bob.Dialect, start int) ([]any, error) {
			if s.IsGroup.IsUnset() {
				return psql.Raw("DEFAULT").WriteSQL(ctx, w, d, start)
			}
			return psql.Arg(s.IsGroup.MustGet()).WriteSQL(ctx, w, d, start)
		}), bob.ExpressionFunc(func(ctx context.Context, w io.StringWriter, d bob.Dialect, start int) ([]any, error) {
			if s.ParentID.IsUnset() {
				return psql.Raw("DEFAULT").WriteSQL(ctx, w, d, start)
			}
			return psql.Arg(s.ParentID.MustGetNull()).WriteSQL(ctx, w, d, start)
		}), bob.ExpressionFunc(func(ctx context.Context, w io.StringWriter, d bob.Dialect, start int) ([]any, error) {
			if s.ShouldBeBudgeted.IsUnset() {
				return psql.Raw("DEFAULT").WriteSQL(ctx, w, d, start)
			}
			return psql.Arg(s.ShouldBeBudgeted.MustGet()).WriteSQL(ctx, w, d, start)
		}), bob.ExpressionFunc(func(ctx context.Context, w io.StringWriter, d bob.Dialect, start int) ([]any, error) {
			if s.IsDisabled.IsUnset() {
				return psql.Raw("DEFAULT").WriteSQL(ctx, w, d, start)
			}
			return psql.Arg(s.IsDisabled.MustGet()).WriteSQL(ctx, w, d, start)
		}), bob.ExpressionFunc(func(ctx context.Context, w io.StringWriter, d bob.Dialect, start int) ([]any, error) {
			if s.CategoryType.IsUnset() {
				return psql.Raw("DEFAULT").WriteSQL(ctx, w, d, start)
			}
			return psql.Arg(s.CategoryType.MustGet()).WriteSQL(ctx, w, d, start)
		}), bob.ExpressionFunc(func(ctx context.Context, w io.StringWriter, d bob.Dialect, start int) ([]any, error) {
			if s.CreatedAt.IsUnset() {
				return psql.Raw("DEFAULT").WriteSQL(ctx, w, d, start)
			}
			return psql.Arg(s.CreatedAt.MustGet()).WriteSQL(ctx, w, d, start)
		}))
}

func (s CategorySetter) UpdateMod() bob.Mod[*dialect.UpdateQuery] {
	return um.Set(s.Expressions()...)
}

func (s CategorySetter) Expressions(prefix ...string) []bob.Expression {
	exprs := make([]bob.Expression, 0, 8)

	if s.ID.IsValue() {
		exprs = append(exprs, expr.Join{Sep: " = ", Exprs: []bob.Expression{
			psql.Quote(append(prefix, "id")...),
			psql.Arg(s.ID),
		}})
	}

	if s.Name.IsValue() {
		exprs = append(exprs, expr.Join{Sep: " = ", Exprs: []bob.Expression{
			psql.Quote(append(prefix, "name")...),
			psql.Arg(s.Name),
		}})
	}

	if s.IsGroup.IsValue() {
		exprs = append(exprs, expr.Join{Sep: " = ", Exprs: []bob.Expression{
			psql.Quote(append(prefix, "is_group")...),
			psql.Arg(s.IsGroup),
		}})
	}

	if s.ParentID.IsValue() || s.ParentID.IsNull() {
		exprs = append(exprs, expr.Join{Sep: " = ", Exprs: []bob.Expression{
			psql.Quote(append(prefix, "parent_id")...),
			psql.Arg(s.ParentID),
		}})
	}

	if s.ShouldBeBudgeted.IsValue() {
		exprs = append(exprs, expr.Join{Sep: " = ", Exprs: []bob.Expression{
			psql.Quote(append(prefix, "should_be_budgeted")...),
			psql.Arg(s.ShouldBeBudgeted),
		}})
	}

	if s.IsDisabled.IsValue() {
		exprs = append(exprs, expr.Join{Sep: " = ", Exprs: []bob.Expression{
			psql.Quote(append(prefix, "is_disabled")...),
			psql.Arg(s.IsDisabled),
		}})
	}

	if s.CategoryType.IsValue() {
		exprs = append(exprs, expr.Join{Sep: " = ", Exprs: []bob.Expression{
			psql.Quote(append(prefix, "category_type")...),
			psql.Arg(s.CategoryType),
		}})
	}

	if s.CreatedAt.IsValue() {
		exprs = append(exprs, expr.Join{Sep: " = ", Exprs: []bob.Expression{
			psql.Quote(append(prefix, "created_at")...),
			psql.Arg(s.CreatedAt),
		}})
	}

	return exprs
}

// scan.Mapper[*T] without reflection: maps columns to fields by index.
func categoryScanMapper(ctx context.Context, cols []string) (scan.BeforeFunc, func(any) (*Category, error)) {
	// resolve the column positions once per query, not per row
	type target struct {
		idx int
		dst func(o *Category) any
	}
	targets := make([]target, 0, 8)
	for i, col := range cols {
		switch col {
		case "id":
			targets = append(targets, target{i, func(o *Category) any { return &o.ID }})
		case "name":
			targets = append(targets, target{i, func(o *Category) any { return &o.Name }})
		case "is_group":
			targets = append(targets, target{i, func(o *Category) any { return &o.IsGroup }})
		case "parent_id":
			targets = append(targets, target{i, func(o *Category) any { return &o.ParentID }})
		case "should_be_budgeted":
			targets = append(targets, target{i, func(o *Category) any { return &o.ShouldBeBudgeted }})
		case "is_disabled":
			targets = append(targets, target{i, func(o *Category) any { return &o.IsDisabled }})
		case "category_type":
			targets = append(targets, target{i, func(o *Category) any { return &o.CategoryType }})
		case "created_at":
			targets = append(targets, target{i, func(o *Category) any { return &o.CreatedAt }})
		}
	}

	return func(row *scan.Row) (any, error) {
			o := new(Category)
			for _, t := range targets {
				row.ScheduleScanByIndex(t.idx, t.dst(o))
			}
			return o, nil
		}, func(v any) (*Category, error) {
			return v.(*Category), nil
		}
}

// FindCategory retrieves a single record by primary key
// If cols is empty Find will return all columns.
func FindCategory(ctx context.Context, exec bob.Executor, IDPK uuid.UUID, cols ...string) (*Category, error) {
	if len(cols) == 0 {
		return Categories.Query(
			sm.Where(Categories.Columns.ID.EQ(psql.Arg(IDPK))),
		).One(ctx, exec)
	}

	return Categories.Query(
		sm.Where(Categories.Columns.ID.EQ(psql.Arg(IDPK))),
		sm.Columns(Categories.Columns.Only(cols...)),
	).One(ctx, exec)
}

// CategoryExists checks the presence of a single record by primary key
func CategoryExists(ctx context.Context, exec bob.Executor, IDPK uuid.UUID) (bool, error) {
	return Categories.Query(
		sm.Where(Categories.Columns.ID.EQ(psql.Arg(IDPK))),
	).Exists(ctx, exec)
}

// AfterQueryHook is called after Category is retrieved from the database
func (o *Category) AfterQueryHook(ctx context.Context, exec bob.Executor, queryType bob.QueryType) error {
	var err error

	switch queryType {
	case bob.QueryTypeSelect:
		ctx, err = Categories.AfterSelectHooks.RunHooks(ctx, exec, CategorySlice{o})
	case bob.QueryTypeInsert:
		ctx, err = Categories.AfterInsertHooks.RunHooks(ctx, exec, CategorySlice{o})
	case bob.QueryTypeUpdate:
		ctx, err = Categories.AfterUpdateHooks.RunHooks(ctx, exec, CategorySlice{o})
	case bob.QueryTypeDelete:
		ctx, err = Categories.AfterDeleteHooks.RunHooks(ctx, exec, CategorySlice{o})
	case bob.QueryTypeMerge:
		ctx, err = Categories.AfterMergeHooks.RunHooks(ctx, exec, CategorySlice{o})
	}

	return err
}

// primaryKeyVals returns the primary key values of the Category
func (o *Category) primaryKeyVals() bob.Expression {
	return psql.Arg(o.ID)
}

func (o *Category) pkEQ() dialect.Expression {
	return psql.Quote("categories", "id").EQ(bob.ExpressionFunc(func(ctx context.Context, w io.StringWriter, d bob.Dialect, start int) ([]any, error) {
		return o.primaryKeyVals().WriteSQL(ctx, w, d, start)
	}))
}

// Update uses an executor to update the Category
func (o *Category) Update(ctx context.Context, exec bob.Executor, s *CategorySetter) error {
	v, err := Categories.Update(s.UpdateMod(), um.Where(o.pkEQ())).One(ctx, exec)
	if err != nil {
		return err
	}

	o.R = v.R
	*o = *v

	return nil
}

// Delete deletes a single Category record with an executor
func (o *Category) Delete(ctx context.Context, exec bob.Executor) error {
	_, err := Categories.Delete(dm.Where(o.pkEQ())).Exec(ctx, exec)
	return err
}

// Reload refreshes the Category using the executor
func (o *Category) Reload(ctx context.Context, exec bob.Executor) error {
	o2, err := Categories.Query(
		sm.Where(Categories.Columns.ID.EQ(psql.Arg(o.ID))),
	).One(ctx, exec)
	if err != nil {
		return err
	}
	o2.R = o.R
	*o = *o2

	return nil
}

// AfterQueryHook is called after CategorySlice is retrieved from the database
func (o CategorySlice) AfterQueryHook(ctx context.Context, exec bob.Executor, queryType bob.QueryType) error {
	var err error

	switch queryType {
	case bob.QueryTypeSelect:
		ctx, err = Categories.AfterSelectHooks.RunHooks(ctx, exec, o)
	case bob.QueryTypeInsert:
		ctx, err = Categories.AfterInsertHooks.RunHooks(ctx, exec, o)
	case bob.QueryTypeUpdate:
		ctx, err = Categories.AfterUpdateHooks.RunHooks(ctx, exec, o)
	case bob.QueryTypeDelete:
		ctx, err = Categories.AfterDeleteHooks.RunHooks(ctx, exec, o)
	case bob.QueryTypeMerge:
		ctx, err = Categories.AfterMergeHooks.RunHooks(ctx, exec, o)
	}

	return err
}

func (o CategorySlice) pkIN() dialect.Expression {
	if len(o) == 0 {
		return psql.Raw("NULL")
	}

	return psql.Quote("categories", "id").In(bob.ExpressionFunc(func(ctx context.Context, w io.StringWriter, d bob.Dialect, start int) ([]any, error) {
		pkPairs := make([]bob.Expression, len(o))
		for i, row := range o {
			pkPairs[i] = row.primaryKeyVals()
		}
		return bob.ExpressSlice(ctx, w, d, start, pkPairs, "", ", ", "")
	}))
}

// copyMatchingRows finds models in the given slice that have the same primary key
// then it first copies the existing relationships from the old model to the new model
// and then replaces the old model in the slice with the new model
func (o CategorySlice) copyMatchingRows(from ...*Category) {
	fromByPK := make(map[uuid.UUID]*Category, len(from))
	for _, new := range from {
		// keep the first row for each key, like the nested loop did
		if _, ok := fromByPK[new.ID]; !ok {
			fromByPK[new.ID] = new
		}
	}

	for i, old := range o {
		new, ok := fromByPK[old.ID]
		if !ok {
			continue
		}
		new.R = old.R
		o[i] = new
	}
}

// UpdateMod modifies an update query with "WHERE primary_key IN (o...)"
func (o CategorySlice) UpdateMod() bob.Mod[*dialect.UpdateQuery] {
	return bob.ModFunc[*dialect.UpdateQuery](func(q *dialect.UpdateQuery) {
		q.AppendHooks(func(ctx context.Context, exec bob.Executor) (context.Context, error) {
			return Categories.BeforeUpdateHooks.RunHooks(ctx, exec, o)
		})

		q.AppendLoader(bob.LoaderFunc(func(ctx context.Context, exec bob.Executor, retrieved any) error {
			var err error
			switch retrieved := retrieved.(type) {
			case *Category:
				o.copyMatchingRows(retrieved)
			case []*Category:
				o.copyMatchingRows(retrieved...)
			case CategorySlice:
				o.copyMatchingRows(retrieved...)
			default:
				// If the retrieved value is not a Category or a slice of Category
				// then run the AfterUpdateHooks on the slice
				_, err = Categories.AfterUpdateHooks.RunHooks(ctx, exec, o)
			}

			return err
		}))

		q.AppendWhere(o.pkIN())
	})
}

// DeleteMod modifies an delete query with "WHERE primary_key IN (o...)"
func (o CategorySlice) DeleteMod() bob.Mod[*dialect.DeleteQuery] {
	return bob.ModFunc[*dialect.DeleteQuery](func(q *dialect.DeleteQuery) {
		q.AppendHooks(func(ctx context.Context, exec bob.Executor) (context.Context, error) {
			return Categories.BeforeDeleteHooks.RunHooks(ctx, exec, o)
		})

		q.AppendLoader(bob.LoaderFunc(func(ctx context.Context, exec bob.Executor, retrieved any) error {
			var err error
			switch retrieved := retrieved.(type) {
			case *Category:
				o.copyMatchingRows(retrieved)
			case []*Category:
				o.copyMatchingRows(retrieved...)
			case CategorySlice:
				o.copyMatchingRows(retrieved...)
			default:
				// If the retrieved value is not a Category or a slice of Category
				// then run the AfterDeleteHooks on the slice
				_, err = Categories.AfterDeleteHooks.RunHooks(ctx, exec, o)
			}

			return err
		}))

		q.AppendWhere(o.pkIN())
	})
}

// MergeMod modifies a merge query to run BeforeMergeHooks and AfterMergeHooks
// and updates the slice with the returned rows.
func (o CategorySlice) MergeMod() bob.Mod[*dialect.MergeQuery] {
	return bob.ModFunc[*dialect.MergeQuery](func(q *dialect.MergeQuery) {
		q.AppendHooks(func(ctx context.Context, exec bob.Executor) (context.Context, error) {
			return Categories.BeforeMergeHooks.RunHooks(ctx, exec, o)
		})

		q.AppendLoader(bob.LoaderFunc(func(ctx context.Context, exec bob.Executor, retrieved any) error {
			var err error
			switch retrieved := retrieved.(type) {
			case *Category:
				o.copyMatchingRows(retrieved)
			case []*Category:
				o.copyMatchingRows(retrieved...)
			case CategorySlice:
				o.copyMatchingRows(retrieved...)
			default:
				// If the retrieved value is not a Category or a slice of Category
				// then run the AfterMergeHooks on the slice
				_, err = Categories.AfterMergeHooks.RunHooks(ctx, exec, o)
			}

			return err
		}))
	})
}

func (o CategorySlice) UpdateAll(ctx context.Context, exec bob.Executor, vals CategorySetter) error {
	if len(o) == 0 {
		return nil
	}

	_, err := Categories.Update(vals.UpdateMod(), o.UpdateMod()).All(ctx, exec)
	return err
}

func (o CategorySlice) DeleteAll(ctx context.Context, exec bob.Executor) error {
	if len(o) == 0 {
		return nil
	}

	_, err := Categories.Delete(o.DeleteMod()).Exec(ctx, exec)
	return err
}

func (o CategorySlice) ReloadAll(ctx context.Context, exec bob.Executor) error {
	if len(o) == 0 {
		return nil
	}

	o2, err := Categories.Query(sm.Where(o.pkIN())).All(ctx, exec)
	if err != nil {
		return err
	}

	o.copyMatchingRows(o2...)

	return nil
}

// Budgets starts a query for related objects on budgets
func (o *Category) Budgets(mods ...bob.Mod[*dialect.SelectQuery]) BudgetsQuery {
	return Budgets.Query(append(mods,
		sm.Where(Budgets.Columns.CategoryID.EQ(psql.Arg(o.ID))),
	)...)
}

func (os CategorySlice) Budgets(mods ...bob.Mod[*dialect.SelectQuery]) BudgetsQuery {
	pkID := make(pgtypes.Array[uuid.UUID], 0, len(os))

	for _, o := range os {
		if o == nil {
			continue
		}
		pkID = append(pkID, o.ID)
	}
	PKArgExpr := psql.Any(psql.Cast(psql.Arg(pkID), "uuid[]"))

	return Budgets.Query(append(mods,
		sm.Where(Budgets.Columns.CategoryID.EQ(PKArgExpr)),
	)...)
}

// Parent starts a query for related objects on categories
func (o *Category) Parent(mods ...bob.Mod[*dialect.SelectQuery]) CategoriesQuery {
	return Categories.Query(append(mods,
		sm.Where(Categories.Columns.ID.EQ(psql.Arg(o.ParentID))),
	)...)
}

func (os CategorySlice) Parent(mods ...bob.Mod[*dialect.SelectQuery]) CategoriesQuery {
	pkParentID := make(pgtypes.Array[null.Val[uuid.UUID]], 0, len(os))

	// the array is only a filter (semi-join), so duplicate keys can be
	// dropped before they are sent over the wire
	seenParentID := make(map[null.Val[uuid.UUID]]struct{}, len(os))
	for _, o := range os {
		if o == nil {
			continue
		}
		if _, ok := seenParentID[o.ParentID]; ok {
			continue
		}
		seenParentID[o.ParentID] = struct{}{}
		pkParentID = append(pkParentID, o.ParentID)
	}
	PKArgExpr := psql.Any(psql.Cast(psql.Arg(pkParentID), "uuid[]"))

	return Categories.Query(append(mods,
		sm.Where(Categories.Columns.ID.EQ(PKArgExpr)),
	)...)
}

// ReverseParents starts a query for related objects on categories
func (o *Category) ReverseParents(mods ...bob.Mod[*dialect.SelectQuery]) CategoriesQuery {
	return Categories.Query(append(mods,
		sm.Where(Categories.Columns.ParentID.EQ(psql.Arg(o.ID))),
	)...)
}

func (os CategorySlice) ReverseParents(mods ...bob.Mod[*dialect.SelectQuery]) CategoriesQuery {
	pkID := make(pgtypes.Array[uuid.UUID], 0, len(os))

	for _, o := range os {
		if o == nil {
			continue
		}
		pkID = append(pkID, o.ID)
	}
	PKArgExpr := psql.Any(psql.Cast(psql.Arg(pkID), "uuid[]"))

	return Categories.Query(append(mods,
		sm.Where(Categories.Columns.ParentID.EQ(PKArgExpr)),
	)...)
}

// Transactions starts a query for related objects on transactions
func (o *Category) Transactions(mods ...bob.Mod[*dialect.SelectQuery]) TransactionsQuery {
	return Transactions.Query(append(mods,
		sm.Where(Transactions.Columns.CategoryID.EQ(psql.Arg(o.ID))),
	)...)
}

func (os CategorySlice) Transactions(mods ...bob.Mod[*dialect.SelectQuery]) TransactionsQuery {
	pkID := make(pgtypes.Array[uuid.UUID], 0, len(os))

	for _, o := range os {
		if o == nil {
			continue
		}
		pkID = append(pkID, o.ID)
	}
	PKArgExpr := psql.Any(psql.Cast(psql.Arg(pkID), "uuid[]"))

	return Transactions.Query(append(mods,
		sm.Where(Transactions.Columns.CategoryID.EQ(PKArgExpr)),
	)...)
}

func insertCategoryBudgets0(ctx context.Context, exec bob.Executor, budgets1 []*BudgetSetter, category0 *Category) (BudgetSlice, error) {
	for i := range budgets1 {
		budgets1[i].CategoryID = omit.From(category0.ID)
	}

	ret, err := Budgets.Insert(bob.ToMods(budgets1...)).All(ctx, exec)
	if err != nil {
		return ret, fmt.Errorf("insertCategoryBudgets0: %w", err)
	}

	return ret, nil
}

func attachCategoryBudgets0(ctx context.Context, exec bob.Executor, count int, budgets1 BudgetSlice, category0 *Category) (BudgetSlice, error) {
	setter := &BudgetSetter{
		CategoryID: omit.From(category0.ID),
	}

	err := budgets1.UpdateAll(ctx, exec, *setter)
	if err != nil {
		return nil, fmt.Errorf("attachCategoryBudgets0: %w", err)
	}

	return budgets1, nil
}

func (category0 *Category) InsertBudgets(ctx context.Context, exec bob.Executor, related ...*BudgetSetter) error {
	if len(related) == 0 {
		return nil
	}

	var err error

	budgets1, err := insertCategoryBudgets0(ctx, exec, related, category0)
	if err != nil {
		return err
	}

	category0.R.Budgets = append(category0.R.Budgets, budgets1...)

	for _, rel := range budgets1 {
		rel.R.Category = category0
		rel.R.Loaded.Category = true
	}
	return nil
}

func (category0 *Category) AttachBudgets(ctx context.Context, exec bob.Executor, related ...*Budget) error {
	if len(related) == 0 {
		return nil
	}

	var err error
	budgets1 := BudgetSlice(related)

	_, err = attachCategoryBudgets0(ctx, exec, len(related), budgets1, category0)
	if err != nil {
		return err
	}

	category0.R.Budgets = append(category0.R.Budgets, budgets1...)

	for _, rel := range related {
		rel.R.Category = category0
		rel.R.Loaded.Category = true
	}

	return nil
}

func attachCategoryParent0(ctx context.Context, exec bob.Executor, count int, category0 *Category, category1 *Category) (*Category, error) {
	setter := &CategorySetter{
		ParentID: omitnull.From(category1.ID),
	}

	err := category0.Update(ctx, exec, setter)
	if err != nil {
		return nil, fmt.Errorf("attachCategoryParent0: %w", err)
	}

	return category0, nil
}

func (category0 *Category) InsertParent(ctx context.Context, exec bob.Executor, related *CategorySetter) error {
	var err error

	category1, err := Categories.Insert(related).One(ctx, exec)
	if err != nil {
		return fmt.Errorf("inserting related objects: %w", err)
	}

	_, err = attachCategoryParent0(ctx, exec, 1, category0, category1)
	if err != nil {
		return err
	}

	category0.R.Parent = category1
	category0.R.Loaded.Parent = true

	category1.R.ReverseParents = append(category1.R.ReverseParents, category0)

	return nil
}

func (category0 *Category) AttachParent(ctx context.Context, exec bob.Executor, category1 *Category) error {
	var err error

	_, err = attachCategoryParent0(ctx, exec, 1, category0, category1)
	if err != nil {
		return err
	}

	category0.R.Parent = category1
	category0.R.Loaded.Parent = true

	category1.R.ReverseParents = append(category1.R.ReverseParents, category0)

	return nil
}

func insertCategoryReverseParents0(ctx context.Context, exec bob.Executor, categories1 []*CategorySetter, category0 *Category) (CategorySlice, error) {
	for i := range categories1 {
		categories1[i].ParentID = omitnull.From(category0.ID)
	}

	ret, err := Categories.Insert(bob.ToMods(categories1...)).All(ctx, exec)
	if err != nil {
		return ret, fmt.Errorf("insertCategoryReverseParents0: %w", err)
	}

	return ret, nil
}

func attachCategoryReverseParents0(ctx context.Context, exec bob.Executor, count int, categories1 CategorySlice, category0 *Category) (CategorySlice, error) {
	setter := &CategorySetter{
		ParentID: omitnull.From(category0.ID),
	}

	err := categories1.UpdateAll(ctx, exec, *setter)
	if err != nil {
		return nil, fmt.Errorf("attachCategoryReverseParents0: %w", err)
	}

	return categories1, nil
}

func (category0 *Category) InsertReverseParents(ctx context.Context, exec bob.Executor, related ...*CategorySetter) error {
	if len(related) == 0 {
		return nil
	}

	var err error

	categories1, err := insertCategoryReverseParents0(ctx, exec, related, category0)
	if err != nil {
		return err
	}

	category0.R.ReverseParents = append(category0.R.ReverseParents, categories1...)

	for _, rel := range categories1 {
		rel.R.Parent = category0
		rel.R.Loaded.Parent = true
	}
	return nil
}

func (category0 *Category) AttachReverseParents(ctx context.Context, exec bob.Executor, related ...*Category) error {
	if len(related) == 0 {
		return nil
	}

	var err error
	categories1 := CategorySlice(related)

	_, err = attachCategoryReverseParents0(ctx, exec, len(related), categories1, category0)
	if err != nil {
		return err
	}

	category0.R.ReverseParents = append(category0.R.ReverseParents, categories1...)

	for _, rel := range related {
		rel.R.Parent = category0
		rel.R.Loaded.Parent = true
	}

	return nil
}

func insertCategoryTransactions0(ctx context.Context, exec bob.Executor, transactions1 []*TransactionSetter, category0 *Category) (TransactionSlice, error) {
	for i := range transactions1 {
		transactions1[i].CategoryID = omitnull.From(category0.ID)
	}

	ret, err := Transactions.Insert(bob.ToMods(transactions1...)).All(ctx, exec)
	if err != nil {
		return ret, fmt.Errorf("insertCategoryTransactions0: %w", err)
	}

	return ret, nil
}

func attachCategoryTransactions0(ctx context.Context, exec bob.Executor, count int, transactions1 TransactionSlice, category0 *Category) (TransactionSlice, error) {
	setter := &TransactionSetter{
		CategoryID: omitnull.From(category0.ID),
	}

	err := transactions1.UpdateAll(ctx, exec, *setter)
	if err != nil {
		return nil, fmt.Errorf("attachCategoryTransactions0: %w", err)
	}

	return transactions1, nil
}

func (category0 *Category) InsertTransactions(ctx context.Context, exec bob.Executor, related ...*TransactionSetter) error {
	if len(related) == 0 {
		return nil
	}

	var err error

	transactions1, err := insertCategoryTransactions0(ctx, exec, related, category0)
	if err != nil {
		return err
	}

	category0.R.Transactions = append(category0.R.Transactions, transactions1...)

	for _, rel := range transactions1 {
		rel.R.Category = category0
		rel.R.Loaded.Category = true
	}
	return nil
}

func (category0 *Category) AttachTransactions(ctx context.Context, exec bob.Executor, related ...*Transaction) error {
	if len(related) == 0 {
		return nil
	}

	var err error
	transactions1 := TransactionSlice(related)

	_, err = attachCategoryTransactions0(ctx, exec, len(related), transactions1, category0)
	if err != nil {
		return err
	}

	category0.R.Transactions = append(category0.R.Transactions, transactions1...)

	for _, rel := range related {
		rel.R.Category = category0
		rel.R.Loaded.Category = true
	}

	return nil
}

type categoryWhere[Q psql.Filterable] struct {
	cols             categoryColumns
	ID               psql.WhereMod[Q, uuid.UUID]
	Name             psql.WhereMod[Q, string]
	IsGroup          psql.WhereMod[Q, bool]
	ParentID         psql.WhereNullMod[Q, uuid.UUID]
	ShouldBeBudgeted psql.WhereMod[Q, bool]
	IsDisabled       psql.WhereMod[Q, bool]
	CategoryType     psql.WhereMod[Q, int16]
	CreatedAt        psql.WhereMod[Q, time.Time]
	R                categoryWhereR[Q]
}

func (categoryWhere[Q]) AliasedAs(alias string) categoryWhere[Q] {
	return buildCategoryWhere[Q](buildCategoryColumns(alias))
}

func buildCategoryWhere[Q psql.Filterable](cols categoryColumns) categoryWhere[Q] {
	return categoryWhere[Q]{
		cols:             cols,
		ID:               psql.Where[Q, uuid.UUID](cols.ID.Expression),
		Name:             psql.Where[Q, string](cols.Name.Expression),
		IsGroup:          psql.Where[Q, bool](cols.IsGroup.Expression),
		ParentID:         psql.WhereNull[Q, uuid.UUID](cols.ParentID.Expression),
		ShouldBeBudgeted: psql.Where[Q, bool](cols.ShouldBeBudgeted.Expression),
		IsDisabled:       psql.Where[Q, bool](cols.IsDisabled.Expression),
		CategoryType:     psql.Where[Q, int16](cols.CategoryType.Expression),
		CreatedAt:        psql.Where[Q, time.Time](cols.CreatedAt.Expression),
		R:                categoryWhereR[Q]{cols: cols},
	}
}

// categoryWhereR holds the relationship-based filters of
// categoryWhere under the R namespace — mirroring the model's
// R struct — so they cannot collide with column-based filter fields.
type categoryWhereR[Q psql.Filterable] struct {
	cols categoryColumns
}

// HasBudgets filters parents that have a matching Budgets using a
// correlated EXISTS subquery (semi-join). Unlike an INNER JOIN it does not
// multiply parent rows, so no DISTINCT is needed. The optional filters are
// applied to the subquery (i.e. to Budgets).
func (w categoryWhereR[Q]) HasBudgets(filters ...bob.Mod[*dialect.SelectQuery]) mods.Where[Q] {
	q := psql.Select(
		sm.Columns(psql.Raw("1")),
		sm.From(Budgets.NameExpr()),
		sm.Where(Budgets.Columns.CategoryID.EQ(w.cols.ID)),
	)
	q.Apply(filters...)
	return mods.Where[Q]{E: psql.Exists(q)}
}

// HasParent filters parents that have a matching Parent using a
// correlated EXISTS subquery (semi-join). Unlike an INNER JOIN it does not
// multiply parent rows, so no DISTINCT is needed. The optional filters are
// applied to the subquery (i.e. to Categories).
func (w categoryWhereR[Q]) HasParent(filters ...bob.Mod[*dialect.SelectQuery]) mods.Where[Q] {
	// self-referential relation: alias the subquery table so the correlation
	// columns still reference the parent row rather than the subquery's own row.
	relTbl := Categories.Columns.AliasedAs("Parent")
	q := psql.Select(
		sm.Columns(psql.Raw("1")),
		sm.From(Categories.NameExpr().As("Parent")),
		sm.Where(relTbl.ID.EQ(w.cols.ParentID)),
	)
	q.Apply(filters...)
	return mods.Where[Q]{E: psql.Exists(q)}
}

// HasReverseParents filters parents that have a matching ReverseParents using a
// correlated EXISTS subquery (semi-join). Unlike an INNER JOIN it does not
// multiply parent rows, so no DISTINCT is needed. The optional filters are
// applied to the subquery (i.e. to Categories).
func (w categoryWhereR[Q]) HasReverseParents(filters ...bob.Mod[*dialect.SelectQuery]) mods.Where[Q] {
	// self-referential relation: alias the subquery table so the correlation
	// columns still reference the parent row rather than the subquery's own row.
	relTbl := Categories.Columns.AliasedAs("ReverseParents")
	q := psql.Select(
		sm.Columns(psql.Raw("1")),
		sm.From(Categories.NameExpr().As("ReverseParents")),
		sm.Where(relTbl.ParentID.EQ(w.cols.ID)),
	)
	q.Apply(filters...)
	return mods.Where[Q]{E: psql.Exists(q)}
}

// HasTransactions filters parents that have a matching Transactions using a
// correlated EXISTS subquery (semi-join). Unlike an INNER JOIN it does not
// multiply parent rows, so no DISTINCT is needed. The optional filters are
// applied to the subquery (i.e. to Transactions).
func (w categoryWhereR[Q]) HasTransactions(filters ...bob.Mod[*dialect.SelectQuery]) mods.Where[Q] {
	q := psql.Select(
		sm.Columns(psql.Raw("1")),
		sm.From(Transactions.NameExpr()),
		sm.Where(Transactions.Columns.CategoryID.EQ(w.cols.ID)),
	)
	q.Apply(filters...)
	return mods.Where[Q]{E: psql.Exists(q)}
}

// NULL-tolerant scan buffer for categoryScanMapperNullable:
// on a LEFT JOIN miss every column comes back NULL, so each field uses the
// nullable version of the column type even when the column itself is NOT NULL.
type categoryPreloadBuf struct {
	ID               null.Val[uuid.UUID]
	Name             null.Val[string]
	IsGroup          null.Val[bool]
	ParentID         null.Val[uuid.UUID]
	ShouldBeBudgeted null.Val[bool]
	IsDisabled       null.Val[bool]
	CategoryType     null.Val[int16]
	CreatedAt        null.Val[time.Time]
}

// categoryScanMapperNullable maps the preloaded category
// columns (prefixed with the runtime join alias) without reflection, while
// keeping the LEFT JOIN semantics of the reflection-based mapper: a row whose
// prefixed columns are all NULL yields nil (no child), and NULL values never
// error, they just leave the zero value in the field.
func categoryScanMapperNullable(prefix string) scan.Mapper[*Category] {
	return func(ctx context.Context, cols []string) (scan.BeforeFunc, func(any) (*Category, error)) {
		// resolve the column names once per query, not per row
		type target struct {
			idx int
			dst func(b *categoryPreloadBuf) any
		}
		targets := make([]target, 0, 8)
		for i, col := range cols {
			name, ok := strings.CutPrefix(col, prefix)
			if !ok {
				continue
			}
			switch name {
			case "id":
				targets = append(targets, target{i, func(b *categoryPreloadBuf) any { return &b.ID }})
			case "name":
				targets = append(targets, target{i, func(b *categoryPreloadBuf) any { return &b.Name }})
			case "is_group":
				targets = append(targets, target{i, func(b *categoryPreloadBuf) any { return &b.IsGroup }})
			case "parent_id":
				targets = append(targets, target{i, func(b *categoryPreloadBuf) any { return &b.ParentID }})
			case "should_be_budgeted":
				targets = append(targets, target{i, func(b *categoryPreloadBuf) any { return &b.ShouldBeBudgeted }})
			case "is_disabled":
				targets = append(targets, target{i, func(b *categoryPreloadBuf) any { return &b.IsDisabled }})
			case "category_type":
				targets = append(targets, target{i, func(b *categoryPreloadBuf) any { return &b.CategoryType }})
			case "created_at":
				targets = append(targets, target{i, func(b *categoryPreloadBuf) any { return &b.CreatedAt }})
			}
		}

		// One scratch buffer reused for every row: before -> scan -> after runs
		// synchronously per row, the scheduled columns are fully overwritten each
		// row, and unselected columns stay zero, so a single buffer preserves the
		// per-row NULL semantics without allocating a buffer per parent row. The
		// returned child (o below) is always freshly allocated, so buf never
		// escapes past the after func.
		buf := new(categoryPreloadBuf)
		return func(row *scan.Row) (any, error) {
				for _, t := range targets {
					row.ScheduleScanByIndex(t.idx, t.dst(buf))
				}
				return buf, nil
			}, func(link any) (*Category, error) {
				buf := link.(*categoryPreloadBuf)

				// Same rule as the reflection mapper's row validator: the child
				// exists only if at least one of its columns is not NULL. Columns
				// not selected by the query are never scanned and stay invalid,
				// so this check also matches when only a subset is selected.
				if !(buf.ID.IsValue()) &&
					!(buf.Name.IsValue()) &&
					!(buf.IsGroup.IsValue()) &&
					!(buf.ParentID.IsValue()) &&
					!(buf.ShouldBeBudgeted.IsValue()) &&
					!(buf.IsDisabled.IsValue()) &&
					!(buf.CategoryType.IsValue()) &&
					!(buf.CreatedAt.IsValue()) {
					return nil, nil
				}

				o := new(Category)
				if buf.ID.IsValue() {
					o.ID = buf.ID.MustGet()
				}
				if buf.Name.IsValue() {
					o.Name = buf.Name.MustGet()
				}
				if buf.IsGroup.IsValue() {
					o.IsGroup = buf.IsGroup.MustGet()
				}
				o.ParentID = buf.ParentID
				if buf.ShouldBeBudgeted.IsValue() {
					o.ShouldBeBudgeted = buf.ShouldBeBudgeted.MustGet()
				}
				if buf.IsDisabled.IsValue() {
					o.IsDisabled = buf.IsDisabled.MustGet()
				}
				if buf.CategoryType.IsValue() {
					o.CategoryType = buf.CategoryType.MustGet()
				}
				if buf.CreatedAt.IsValue() {
					o.CreatedAt = buf.CreatedAt.MustGet()
				}
				return o, nil
			}
	}
}

func (o *Category) Preload(name string, retrieved any) error {
	if o == nil {
		return nil
	}

	switch name {
	case "Budgets":
		rels, ok := retrieved.(BudgetSlice)
		if !ok {
			return fmt.Errorf("category cannot load %T as %q", retrieved, name)
		}

		o.R.Budgets = rels
		o.R.Loaded.Budgets = true

		for _, rel := range rels {
			if rel != nil {
				rel.R.Category = o
				rel.R.Loaded.Category = true
			}
		}
		return nil
	case "Parent":
		rel, ok := retrieved.(*Category)
		if !ok {
			return fmt.Errorf("category cannot load %T as %q", retrieved, name)
		}

		o.R.Parent = rel
		o.R.Loaded.Parent = true

		if rel != nil {
			rel.R.ReverseParents = CategorySlice{o}
		}
		return nil
	case "ReverseParents":
		rels, ok := retrieved.(CategorySlice)
		if !ok {
			return fmt.Errorf("category cannot load %T as %q", retrieved, name)
		}

		o.R.ReverseParents = rels
		o.R.Loaded.ReverseParents = true

		for _, rel := range rels {
			if rel != nil {
				rel.R.Parent = o
				rel.R.Loaded.Parent = true
			}
		}
		return nil
	case "Transactions":
		rels, ok := retrieved.(TransactionSlice)
		if !ok {
			return fmt.Errorf("category cannot load %T as %q", retrieved, name)
		}

		o.R.Transactions = rels
		o.R.Loaded.Transactions = true

		for _, rel := range rels {
			if rel != nil {
				rel.R.Category = o
				rel.R.Loaded.Category = true
			}
		}
		return nil
	default:
		return fmt.Errorf("category has no relationship %q", name)
	}
}

type categoryPreloader struct {
	Parent func(...psql.PreloadOption) psql.Preloader
}

func buildCategoryPreloader() categoryPreloader {
	return categoryPreloader{
		Parent: func(opts ...psql.PreloadOption) psql.Preloader {
			return psql.Preload[*Category, CategorySlice](psql.PreloadRel{
				Name: "Parent",
				Sides: []psql.PreloadSide{
					{
						From:        Categories,
						To:          Categories,
						FromColumns: []string{"parent_id"},
						ToColumns:   []string{"id"},
					},
				},
			}, Categories.Columns.Names(), categoryScanMapperNullable, opts...)
		},
	}
}

type categoryThenLoader[Q orm.Loadable] struct {
	Budgets        func(...bob.Mod[*dialect.SelectQuery]) orm.Loader[Q]
	Parent         func(...bob.Mod[*dialect.SelectQuery]) orm.Loader[Q]
	ReverseParents func(...bob.Mod[*dialect.SelectQuery]) orm.Loader[Q]
	Transactions   func(...bob.Mod[*dialect.SelectQuery]) orm.Loader[Q]
}

func buildCategoryThenLoader[Q orm.Loadable]() categoryThenLoader[Q] {
	type BudgetsLoadInterface interface {
		LoadBudgets(context.Context, bob.Executor, ...bob.Mod[*dialect.SelectQuery]) error
	}
	type ParentLoadInterface interface {
		LoadParent(context.Context, bob.Executor, ...bob.Mod[*dialect.SelectQuery]) error
	}
	type ReverseParentsLoadInterface interface {
		LoadReverseParents(context.Context, bob.Executor, ...bob.Mod[*dialect.SelectQuery]) error
	}
	type TransactionsLoadInterface interface {
		LoadTransactions(context.Context, bob.Executor, ...bob.Mod[*dialect.SelectQuery]) error
	}

	return categoryThenLoader[Q]{
		Budgets: thenLoadBuilder[Q](
			"Budgets",
			func(ctx context.Context, exec bob.Executor, retrieved BudgetsLoadInterface, mods ...bob.Mod[*dialect.SelectQuery]) error {
				return retrieved.LoadBudgets(ctx, exec, mods...)
			},
		),
		Parent: thenLoadBuilder[Q](
			"Parent",
			func(ctx context.Context, exec bob.Executor, retrieved ParentLoadInterface, mods ...bob.Mod[*dialect.SelectQuery]) error {
				return retrieved.LoadParent(ctx, exec, mods...)
			},
		),
		ReverseParents: thenLoadBuilder[Q](
			"ReverseParents",
			func(ctx context.Context, exec bob.Executor, retrieved ReverseParentsLoadInterface, mods ...bob.Mod[*dialect.SelectQuery]) error {
				return retrieved.LoadReverseParents(ctx, exec, mods...)
			},
		),
		Transactions: thenLoadBuilder[Q](
			"Transactions",
			func(ctx context.Context, exec bob.Executor, retrieved TransactionsLoadInterface, mods ...bob.Mod[*dialect.SelectQuery]) error {
				return retrieved.LoadTransactions(ctx, exec, mods...)
			},
		),
	}
}

// LoadBudgets loads the category's Budgets into the .R struct
func (o *Category) LoadBudgets(ctx context.Context, exec bob.Executor, mods ...bob.Mod[*dialect.SelectQuery]) error {
	if o == nil {
		return nil
	}

	// Reset the relationship
	o.R.Budgets = nil
	o.R.Loaded.Budgets = false

	related, err := o.Budgets(mods...).All(ctx, exec)
	if err != nil {
		return err
	}

	for _, rel := range related {
		rel.R.Category = o
		rel.R.Loaded.Category = true
	}

	o.R.Budgets = related
	o.R.Loaded.Budgets = true
	return nil
}

// LoadBudgets loads the category's Budgets into the .R struct
func (os CategorySlice) LoadBudgets(ctx context.Context, exec bob.Executor, mods ...bob.Mod[*dialect.SelectQuery]) error {
	if len(os) == 0 {
		return nil
	}

	budgets, err := os.Budgets(mods...).All(ctx, exec)
	if err != nil {
		return err
	}

	for _, o := range os {
		if o == nil {
			continue
		}

		o.R.Budgets = nil
		o.R.Loaded.Budgets = true
	}
	// O(N+M) stitch via a map keyed by the join column (key -> []parent; was O(N*M)).
	categoryByKey := make(map[uuid.UUID][]*Category, len(os))
	for _, o := range os {
		if o == nil {
			continue
		}

		categoryByKey[o.ID] = append(categoryByKey[o.ID], o)
	}

	for _, rel := range budgets {

		owners, ok := categoryByKey[rel.CategoryID]
		if !ok {
			continue
		}

		for _, o := range owners {

			rel.R.Category = o
			rel.R.Loaded.Category = true

			o.R.Budgets = append(o.R.Budgets, rel)

		}
	}

	return nil
}

// LoadParent loads the category's Parent into the .R struct
func (o *Category) LoadParent(ctx context.Context, exec bob.Executor, mods ...bob.Mod[*dialect.SelectQuery]) error {
	if o == nil {
		return nil
	}

	// Reset the relationship
	o.R.Parent = nil
	o.R.Loaded.Parent = false

	related, err := o.Parent(mods...).One(ctx, exec)
	if err != nil {
		return err
	}

	related.R.ReverseParents = CategorySlice{o}

	o.R.Parent = related
	o.R.Loaded.Parent = true
	return nil
}

// LoadParent loads the category's Parent into the .R struct
func (os CategorySlice) LoadParent(ctx context.Context, exec bob.Executor, mods ...bob.Mod[*dialect.SelectQuery]) error {
	if len(os) == 0 {
		return nil
	}

	categories, err := os.Parent(mods...).All(ctx, exec)
	if err != nil {
		return err
	}

	for _, o := range os {
		if o == nil {
			continue
		}

		o.R.Parent = nil
		o.R.Loaded.Parent = true
	}
	// O(N+M) stitch via a map keyed by the join column (key -> []parent; was O(N*M)).
	categoryByKey := make(map[uuid.UUID][]*Category, len(os))
	for _, o := range os {
		if o == nil {
			continue
		}

		// NULL never matches any row in SQL, so don't add it to the map
		if !o.ParentID.IsValue() {
			continue
		}

		categoryByKey[o.ParentID.MustGet()] = append(categoryByKey[o.ParentID.MustGet()], o)
	}

	for _, rel := range categories {

		owners, ok := categoryByKey[rel.ID]
		if !ok {
			continue
		}

		for _, o := range owners {

			// to-one: keep only the first matching child (matches the previous break)
			if o.R.Parent != nil {
				continue
			}

			rel.R.ReverseParents = append(rel.R.ReverseParents, o)

			o.R.Parent = rel

		}
	}

	return nil
}

// LoadReverseParents loads the category's ReverseParents into the .R struct
func (o *Category) LoadReverseParents(ctx context.Context, exec bob.Executor, mods ...bob.Mod[*dialect.SelectQuery]) error {
	if o == nil {
		return nil
	}

	// Reset the relationship
	o.R.ReverseParents = nil
	o.R.Loaded.ReverseParents = false

	related, err := o.ReverseParents(mods...).All(ctx, exec)
	if err != nil {
		return err
	}

	for _, rel := range related {
		rel.R.Parent = o
		rel.R.Loaded.Parent = true
	}

	o.R.ReverseParents = related
	o.R.Loaded.ReverseParents = true
	return nil
}

// LoadReverseParents loads the category's ReverseParents into the .R struct
func (os CategorySlice) LoadReverseParents(ctx context.Context, exec bob.Executor, mods ...bob.Mod[*dialect.SelectQuery]) error {
	if len(os) == 0 {
		return nil
	}

	categories, err := os.ReverseParents(mods...).All(ctx, exec)
	if err != nil {
		return err
	}

	for _, o := range os {
		if o == nil {
			continue
		}

		o.R.ReverseParents = nil
		o.R.Loaded.ReverseParents = true
	}
	// O(N+M) stitch via a map keyed by the join column (key -> []parent; was O(N*M)).
	categoryByKey := make(map[uuid.UUID][]*Category, len(os))
	for _, o := range os {
		if o == nil {
			continue
		}

		categoryByKey[o.ID] = append(categoryByKey[o.ID], o)
	}

	for _, rel := range categories {

		if !rel.ParentID.IsValue() {
			continue
		}

		owners, ok := categoryByKey[rel.ParentID.MustGet()]
		if !ok {
			continue
		}

		for _, o := range owners {

			rel.R.Parent = o
			rel.R.Loaded.Parent = true

			o.R.ReverseParents = append(o.R.ReverseParents, rel)

		}
	}

	return nil
}

// LoadTransactions loads the category's Transactions into the .R struct
func (o *Category) LoadTransactions(ctx context.Context, exec bob.Executor, mods ...bob.Mod[*dialect.SelectQuery]) error {
	if o == nil {
		return nil
	}

	// Reset the relationship
	o.R.Transactions = nil
	o.R.Loaded.Transactions = false

	related, err := o.Transactions(mods...).All(ctx, exec)
	if err != nil {
		return err
	}

	for _, rel := range related {
		rel.R.Category = o
		rel.R.Loaded.Category = true
	}

	o.R.Transactions = related
	o.R.Loaded.Transactions = true
	return nil
}

// LoadTransactions loads the category's Transactions into the .R struct
func (os CategorySlice) LoadTransactions(ctx context.Context, exec bob.Executor, mods ...bob.Mod[*dialect.SelectQuery]) error {
	if len(os) == 0 {
		return nil
	}

	transactions, err := os.Transactions(mods...).All(ctx, exec)
	if err != nil {
		return err
	}

	for _, o := range os {
		if o == nil {
			continue
		}

		o.R.Transactions = nil
		o.R.Loaded.Transactions = true
	}
	// O(N+M) stitch via a map keyed by the join column (key -> []parent; was O(N*M)).
	categoryByKey := make(map[uuid.UUID][]*Category, len(os))
	for _, o := range os {
		if o == nil {
			continue
		}

		categoryByKey[o.ID] = append(categoryByKey[o.ID], o)
	}

	for _, rel := range transactions {

		if !rel.CategoryID.IsValue() {
			continue
		}

		owners, ok := categoryByKey[rel.CategoryID.MustGet()]
		if !ok {
			continue
		}

		for _, o := range owners {

			rel.R.Category = o
			rel.R.Loaded.Category = true

			o.R.Transactions = append(o.R.Transactions, rel)

		}
	}

	return nil
}

// categoryC is where relationship counts are stored.
type categoryC struct {
	Budgets        *int64
	ReverseParents *int64
	Transactions   *int64
}

// PreloadCount sets a count in the C struct by name
func (o *Category) PreloadCount(name string, count int64) error {
	if o == nil {
		return nil
	}

	switch name {
	case "Budgets":
		o.C.Budgets = &count
	case "ReverseParents":
		o.C.ReverseParents = &count
	case "Transactions":
		o.C.Transactions = &count
	}
	return nil
}

type categoryCountPreloader struct {
	Budgets        func(...bob.Mod[*dialect.SelectQuery]) psql.Preloader
	ReverseParents func(...bob.Mod[*dialect.SelectQuery]) psql.Preloader
	Transactions   func(...bob.Mod[*dialect.SelectQuery]) psql.Preloader
}

func buildCategoryCountPreloader() categoryCountPreloader {
	return categoryCountPreloader{
		Budgets: func(mods ...bob.Mod[*dialect.SelectQuery]) psql.Preloader {
			return countPreloader[*Category]("Budgets", func(parent string) bob.Expression {
				// Build a correlated subquery: (SELECT COUNT(*) FROM related WHERE fk = parent.pk)
				if parent == "" {
					parent = Categories.Alias()
				}

				subqueryMods := []bob.Mod[*dialect.SelectQuery]{
					sm.Columns(psql.Raw("count(*)")),

					sm.From(Budgets.NameAsExpr()),
					sm.Where(psql.Quote(Budgets.Alias(), "category_id").EQ(psql.Quote(parent, "id"))),
				}
				subqueryMods = append(subqueryMods, mods...)
				return psql.Group(psql.Select(subqueryMods...).Expression)
			})
		},
		ReverseParents: func(mods ...bob.Mod[*dialect.SelectQuery]) psql.Preloader {
			return countPreloader[*Category]("ReverseParents", func(parent string) bob.Expression {
				// Build a correlated subquery: (SELECT COUNT(*) FROM related WHERE fk = parent.pk)
				if parent == "" {
					parent = Categories.Alias()
				}

				subqueryMods := []bob.Mod[*dialect.SelectQuery]{
					sm.Columns(psql.Raw("count(*)")),

					sm.From(Categories.NameAsExpr()),
					sm.Where(psql.Quote(Categories.Alias(), "parent_id").EQ(psql.Quote(parent, "id"))),
				}
				subqueryMods = append(subqueryMods, mods...)
				return psql.Group(psql.Select(subqueryMods...).Expression)
			})
		},
		Transactions: func(mods ...bob.Mod[*dialect.SelectQuery]) psql.Preloader {
			return countPreloader[*Category]("Transactions", func(parent string) bob.Expression {
				// Build a correlated subquery: (SELECT COUNT(*) FROM related WHERE fk = parent.pk)
				if parent == "" {
					parent = Categories.Alias()
				}

				subqueryMods := []bob.Mod[*dialect.SelectQuery]{
					sm.Columns(psql.Raw("count(*)")),

					sm.From(Transactions.NameAsExpr()),
					sm.Where(psql.Quote(Transactions.Alias(), "category_id").EQ(psql.Quote(parent, "id"))),
				}
				subqueryMods = append(subqueryMods, mods...)
				return psql.Group(psql.Select(subqueryMods...).Expression)
			})
		},
	}
}

type categoryCountThenLoader[Q orm.Loadable] struct {
	Budgets        func(...bob.Mod[*dialect.SelectQuery]) orm.Loader[Q]
	ReverseParents func(...bob.Mod[*dialect.SelectQuery]) orm.Loader[Q]
	Transactions   func(...bob.Mod[*dialect.SelectQuery]) orm.Loader[Q]
}

func buildCategoryCountThenLoader[Q orm.Loadable]() categoryCountThenLoader[Q] {
	type BudgetsCountInterface interface {
		LoadCountBudgets(context.Context, bob.Executor, ...bob.Mod[*dialect.SelectQuery]) error
	}
	type ReverseParentsCountInterface interface {
		LoadCountReverseParents(context.Context, bob.Executor, ...bob.Mod[*dialect.SelectQuery]) error
	}
	type TransactionsCountInterface interface {
		LoadCountTransactions(context.Context, bob.Executor, ...bob.Mod[*dialect.SelectQuery]) error
	}

	return categoryCountThenLoader[Q]{
		Budgets: countThenLoadBuilder[Q](
			"Budgets",
			func(ctx context.Context, exec bob.Executor, retrieved BudgetsCountInterface, mods ...bob.Mod[*dialect.SelectQuery]) error {
				return retrieved.LoadCountBudgets(ctx, exec, mods...)
			},
		),
		ReverseParents: countThenLoadBuilder[Q](
			"ReverseParents",
			func(ctx context.Context, exec bob.Executor, retrieved ReverseParentsCountInterface, mods ...bob.Mod[*dialect.SelectQuery]) error {
				return retrieved.LoadCountReverseParents(ctx, exec, mods...)
			},
		),
		Transactions: countThenLoadBuilder[Q](
			"Transactions",
			func(ctx context.Context, exec bob.Executor, retrieved TransactionsCountInterface, mods ...bob.Mod[*dialect.SelectQuery]) error {
				return retrieved.LoadCountTransactions(ctx, exec, mods...)
			},
		),
	}
}

// LoadCountBudgets loads the count of Budgets into the C struct
func (o *Category) LoadCountBudgets(ctx context.Context, exec bob.Executor, mods ...bob.Mod[*dialect.SelectQuery]) error {
	if o == nil {
		return nil
	}

	count, err := o.Budgets(mods...).Count(ctx, exec)
	if err != nil {
		return err
	}

	o.C.Budgets = &count
	return nil
}

// LoadCountBudgets loads the count of Budgets for a slice in a single batch query
func (os CategorySlice) LoadCountBudgets(ctx context.Context, exec bob.Executor, mods ...bob.Mod[*dialect.SelectQuery]) error {
	if len(os) == 0 {
		return nil
	}

	// Build the IN arg expression from parent PKs

	pkID := make(pgtypes.Array[uuid.UUID], 0, len(os))
	for _, o := range os {
		if o == nil {
			continue
		}
		pkID = append(pkID, o.ID)
	}
	PKArgExpr := psql.Any(psql.Cast(psql.Arg(pkID), "uuid[]"))

	// countResult holds one scanned row from the batch count query.
	// FK columns are aliased to the parent PK column names for direct map lookup.
	type countResult struct {
		ID    uuid.UUID
		Count int64
	}

	batchMods := []bob.Mod[*dialect.SelectQuery]{
		// SELECT fk AS parent_pk, count(*)
		sm.Columns(
			Budgets.Columns.CategoryID.As("id"),
			psql.Raw("count(*) as count"),
		),
		// Single-hop: FROM related table directly
		sm.From(Budgets.NameAsExpr()),

		// WHERE fk IN (parent PKs) — psql single-column FK uses `= ANY(array)` (see PKArgExpr above)
		sm.Where(Budgets.Columns.CategoryID.EQ(PKArgExpr)),
		// GROUP BY fk columns
		sm.GroupBy(Budgets.Columns.CategoryID),
	}
	batchMods = append(batchMods, mods...)

	results, err := bob.All(ctx, exec,
		psql.Select(batchMods...),
		scan.StructMapper[countResult](),
	)
	if err != nil {
		return err
	}

	// Single-column FK: direct map lookup
	countMap := make(map[uuid.UUID]int64, len(results))
	for _, r := range results {
		countMap[r.ID] = r.Count
	}
	for _, o := range os {
		if o == nil {
			continue
		}
		count := countMap[o.ID]
		o.C.Budgets = &count
	}

	return nil
}

// LoadCountReverseParents loads the count of ReverseParents into the C struct
func (o *Category) LoadCountReverseParents(ctx context.Context, exec bob.Executor, mods ...bob.Mod[*dialect.SelectQuery]) error {
	if o == nil {
		return nil
	}

	count, err := o.ReverseParents(mods...).Count(ctx, exec)
	if err != nil {
		return err
	}

	o.C.ReverseParents = &count
	return nil
}

// LoadCountReverseParents loads the count of ReverseParents for a slice in a single batch query
func (os CategorySlice) LoadCountReverseParents(ctx context.Context, exec bob.Executor, mods ...bob.Mod[*dialect.SelectQuery]) error {
	if len(os) == 0 {
		return nil
	}

	// Build the IN arg expression from parent PKs

	pkID := make(pgtypes.Array[uuid.UUID], 0, len(os))
	for _, o := range os {
		if o == nil {
			continue
		}
		pkID = append(pkID, o.ID)
	}
	PKArgExpr := psql.Any(psql.Cast(psql.Arg(pkID), "uuid[]"))

	// countResult holds one scanned row from the batch count query.
	// FK columns are aliased to the parent PK column names for direct map lookup.
	type countResult struct {
		ID    uuid.UUID
		Count int64
	}

	batchMods := []bob.Mod[*dialect.SelectQuery]{
		// SELECT fk AS parent_pk, count(*)
		sm.Columns(
			Categories.Columns.ParentID.As("id"),
			psql.Raw("count(*) as count"),
		),
		// Single-hop: FROM related table directly
		sm.From(Categories.NameAsExpr()),

		// WHERE fk IN (parent PKs) — psql single-column FK uses `= ANY(array)` (see PKArgExpr above)
		sm.Where(Categories.Columns.ParentID.EQ(PKArgExpr)),
		// GROUP BY fk columns
		sm.GroupBy(Categories.Columns.ParentID),
	}
	batchMods = append(batchMods, mods...)

	results, err := bob.All(ctx, exec,
		psql.Select(batchMods...),
		scan.StructMapper[countResult](),
	)
	if err != nil {
		return err
	}

	// Single-column FK: direct map lookup
	countMap := make(map[uuid.UUID]int64, len(results))
	for _, r := range results {
		countMap[r.ID] = r.Count
	}
	for _, o := range os {
		if o == nil {
			continue
		}
		count := countMap[o.ID]
		o.C.ReverseParents = &count
	}

	return nil
}

// LoadCountTransactions loads the count of Transactions into the C struct
func (o *Category) LoadCountTransactions(ctx context.Context, exec bob.Executor, mods ...bob.Mod[*dialect.SelectQuery]) error {
	if o == nil {
		return nil
	}

	count, err := o.Transactions(mods...).Count(ctx, exec)
	if err != nil {
		return err
	}

	o.C.Transactions = &count
	return nil
}

// LoadCountTransactions loads the count of Transactions for a slice in a single batch query
func (os CategorySlice) LoadCountTransactions(ctx context.Context, exec bob.Executor, mods ...bob.Mod[*dialect.SelectQuery]) error {
	if len(os) == 0 {
		return nil
	}

	// Build the IN arg expression from parent PKs

	pkID := make(pgtypes.Array[uuid.UUID], 0, len(os))
	for _, o := range os {
		if o == nil {
			continue
		}
		pkID = append(pkID, o.ID)
	}
	PKArgExpr := psql.Any(psql.Cast(psql.Arg(pkID), "uuid[]"))

	// countResult holds one scanned row from the batch count query.
	// FK columns are aliased to the parent PK column names for direct map lookup.
	type countResult struct {
		ID    uuid.UUID
		Count int64
	}

	batchMods := []bob.Mod[*dialect.SelectQuery]{
		// SELECT fk AS parent_pk, count(*)
		sm.Columns(
			Transactions.Columns.CategoryID.As("id"),
			psql.Raw("count(*) as count"),
		),
		// Single-hop: FROM related table directly
		sm.From(Transactions.NameAsExpr()),

		// WHERE fk IN (parent PKs) — psql single-column FK uses `= ANY(array)` (see PKArgExpr above)
		sm.Where(Transactions.Columns.CategoryID.EQ(PKArgExpr)),
		// GROUP BY fk columns
		sm.GroupBy(Transactions.Columns.CategoryID),
	}
	batchMods = append(batchMods, mods...)

	results, err := bob.All(ctx, exec,
		psql.Select(batchMods...),
		scan.StructMapper[countResult](),
	)
	if err != nil {
		return err
	}

	// Single-column FK: direct map lookup
	countMap := make(map[uuid.UUID]int64, len(results))
	for _, r := range results {
		countMap[r.ID] = r.Count
	}
	for _, o := range os {
		if o == nil {
			continue
		}
		count := countMap[o.ID]
		o.C.Transactions = &count
	}

	return nil
}

type categoryJoins[Q dialect.Joinable] struct {
	typ            string
	Budgets        modAs[Q, budgetColumns]
	Parent         modAs[Q, categoryColumns]
	ReverseParents modAs[Q, categoryColumns]
	Transactions   modAs[Q, transactionColumns]
}

func (j categoryJoins[Q]) aliasedAs(alias string) categoryJoins[Q] {
	return buildCategoryJoins[Q](buildCategoryColumns(alias), j.typ)
}

func buildCategoryJoins[Q dialect.Joinable](cols categoryColumns, typ string) categoryJoins[Q] {
	return categoryJoins[Q]{
		typ: typ,
		Budgets: modAs[Q, budgetColumns]{
			c: Budgets.Columns,
			f: func(to budgetColumns) bob.Mod[Q] {
				mods := make(mods.QueryMods[Q], 0, 1)

				{
					mods = append(mods, dialect.Join[Q](typ, Budgets.NameExpr().As(to.Alias())).On(
						to.CategoryID.EQ(cols.ID),
					))
				}

				return mods
			},
		},
		Parent: modAs[Q, categoryColumns]{
			c: Categories.Columns,
			f: func(to categoryColumns) bob.Mod[Q] {
				mods := make(mods.QueryMods[Q], 0, 1)

				{
					mods = append(mods, dialect.Join[Q](typ, Categories.NameExpr().As(to.Alias())).On(
						to.ID.EQ(cols.ParentID),
					))
				}

				return mods
			},
		},
		ReverseParents: modAs[Q, categoryColumns]{
			c: Categories.Columns,
			f: func(to categoryColumns) bob.Mod[Q] {
				mods := make(mods.QueryMods[Q], 0, 1)

				{
					mods = append(mods, dialect.Join[Q](typ, Categories.NameExpr().As(to.Alias())).On(
						to.ParentID.EQ(cols.ID),
					))
				}

				return mods
			},
		},
		Transactions: modAs[Q, transactionColumns]{
			c: Transactions.Columns,
			f: func(to transactionColumns) bob.Mod[Q] {
				mods := make(mods.QueryMods[Q], 0, 1)

				{
					mods = append(mods, dialect.Join[Q](typ, Transactions.NameExpr().As(to.Alias())).On(
						to.CategoryID.EQ(cols.ID),
					))
				}

				return mods
			},
		},
	}
}
