// Code generated by BobGen psql v0.42.0. DO NOT EDIT.
// This file is meant to be re-generated in place and/or deleted at any time.

package bobgen

import (
	"context"
	"fmt"
	"io"
	"time"

	"github.com/aarondl/opt/null"
	"github.com/aarondl/opt/omit"
	"github.com/aarondl/opt/omitnull"
	"github.com/gofrs/uuid/v5"
	"github.com/stephenafamo/bob"
	"github.com/stephenafamo/bob/dialect/psql"
	"github.com/stephenafamo/bob/dialect/psql/dialect"
	"github.com/stephenafamo/bob/dialect/psql/dm"
	"github.com/stephenafamo/bob/dialect/psql/sm"
	"github.com/stephenafamo/bob/dialect/psql/um"
	"github.com/stephenafamo/bob/expr"
	"github.com/stephenafamo/bob/mods"
	"github.com/stephenafamo/bob/orm"
	"github.com/stephenafamo/bob/types/pgtypes"
)

// Category is an object representing the database table.
type Category struct {
	ID               uuid.UUID           `db:"id,pk" `
	Name             string              `db:"name" `
	IsGroup          bool                `db:"is_group" `
	ParentID         null.Val[uuid.UUID] `db:"parent_id" `
	ShouldBeBudgeted bool                `db:"should_be_budgeted" `
	IsDisabled       bool                `db:"is_disabled" `
	CategoryType     int16               `db:"category_type" `
	CreatedAt        time.Time           `db:"created_at" `

	R categoryR `db:"-" `
}

// CategorySlice is an alias for a slice of pointers to Category.
// This should almost always be used instead of []*Category.
type CategorySlice []*Category

// Categories contains methods to work with the categories table
var Categories = psql.NewTablex[*Category, CategorySlice, *CategorySetter]("", "categories", buildCategoryColumns("categories"))

// CategoriesQuery is a query on the categories table
type CategoriesQuery = *psql.ViewQuery[*Category, CategorySlice]

// categoryR is where relationships are stored.
type categoryR struct {
	Parent         *Category        // categories.fk_categories_parent
	ReverseParents CategorySlice    // categories.fk_categories_parent__self_join_reverse
	Transactions   TransactionSlice // transactions.fk_transactions_category_id
}

func buildCategoryColumns(alias string) categoryColumns {
	return categoryColumns{
		ColumnsExpr: expr.NewColumnsExpr(
			"id", "name", "is_group", "parent_id", "should_be_budgeted", "is_disabled", "category_type", "created_at",
		).WithParent("categories"),
		tableAlias:       alias,
		ID:               psql.Quote(alias, "id"),
		Name:             psql.Quote(alias, "name"),
		IsGroup:          psql.Quote(alias, "is_group"),
		ParentID:         psql.Quote(alias, "parent_id"),
		ShouldBeBudgeted: psql.Quote(alias, "should_be_budgeted"),
		IsDisabled:       psql.Quote(alias, "is_disabled"),
		CategoryType:     psql.Quote(alias, "category_type"),
		CreatedAt:        psql.Quote(alias, "created_at"),
	}
}

type categoryColumns struct {
	expr.ColumnsExpr
	tableAlias       string
	ID               psql.Expression
	Name             psql.Expression
	IsGroup          psql.Expression
	ParentID         psql.Expression
	ShouldBeBudgeted psql.Expression
	IsDisabled       psql.Expression
	CategoryType     psql.Expression
	CreatedAt        psql.Expression
}

func (c categoryColumns) Alias() string {
	return c.tableAlias
}

func (categoryColumns) AliasedAs(alias string) categoryColumns {
	return buildCategoryColumns(alias)
}

// CategorySetter is used for insert/upsert/update operations
// All values are optional, and do not have to be set
// Generated columns are not included
type CategorySetter struct {
	ID               omit.Val[uuid.UUID]     `db:"id,pk" `
	Name             omit.Val[string]        `db:"name" `
	IsGroup          omit.Val[bool]          `db:"is_group" `
	ParentID         omitnull.Val[uuid.UUID] `db:"parent_id" `
	ShouldBeBudgeted omit.Val[bool]          `db:"should_be_budgeted" `
	IsDisabled       omit.Val[bool]          `db:"is_disabled" `
	CategoryType     omit.Val[int16]         `db:"category_type" `
	CreatedAt        omit.Val[time.Time]     `db:"created_at" `
}

func (s CategorySetter) SetColumns() []string {
	vals := make([]string, 0, 8)
	if s.ID.IsValue() {
		vals = append(vals, "id")
	}
	if s.Name.IsValue() {
		vals = append(vals, "name")
	}
	if s.IsGroup.IsValue() {
		vals = append(vals, "is_group")
	}
	if !s.ParentID.IsUnset() {
		vals = append(vals, "parent_id")
	}
	if s.ShouldBeBudgeted.IsValue() {
		vals = append(vals, "should_be_budgeted")
	}
	if s.IsDisabled.IsValue() {
		vals = append(vals, "is_disabled")
	}
	if s.CategoryType.IsValue() {
		vals = append(vals, "category_type")
	}
	if s.CreatedAt.IsValue() {
		vals = append(vals, "created_at")
	}
	return vals
}

func (s CategorySetter) Overwrite(t *Category) {
	if s.ID.IsValue() {
		t.ID = s.ID.MustGet()
	}
	if s.Name.IsValue() {
		t.Name = s.Name.MustGet()
	}
	if s.IsGroup.IsValue() {
		t.IsGroup = s.IsGroup.MustGet()
	}
	if !s.ParentID.IsUnset() {
		t.ParentID = s.ParentID.MustGetNull()
	}
	if s.ShouldBeBudgeted.IsValue() {
		t.ShouldBeBudgeted = s.ShouldBeBudgeted.MustGet()
	}
	if s.IsDisabled.IsValue() {
		t.IsDisabled = s.IsDisabled.MustGet()
	}
	if s.CategoryType.IsValue() {
		t.CategoryType = s.CategoryType.MustGet()
	}
	if s.CreatedAt.IsValue() {
		t.CreatedAt = s.CreatedAt.MustGet()
	}
}

func (s *CategorySetter) Apply(q *dialect.InsertQuery) {
	q.AppendHooks(func(ctx context.Context, exec bob.Executor) (context.Context, error) {
		return Categories.BeforeInsertHooks.RunHooks(ctx, exec, s)
	})

	q.AppendValues(bob.ExpressionFunc(func(ctx context.Context, w io.StringWriter, d bob.Dialect, start int) ([]any, error) {
		vals := make([]bob.Expression, 8)
		if s.ID.IsValue() {
			vals[0] = psql.Arg(s.ID.MustGet())
		} else {
			vals[0] = psql.Raw("DEFAULT")
		}

		if s.Name.IsValue() {
			vals[1] = psql.Arg(s.Name.MustGet())
		} else {
			vals[1] = psql.Raw("DEFAULT")
		}

		if s.IsGroup.IsValue() {
			vals[2] = psql.Arg(s.IsGroup.MustGet())
		} else {
			vals[2] = psql.Raw("DEFAULT")
		}

		if !s.ParentID.IsUnset() {
			vals[3] = psql.Arg(s.ParentID.MustGetNull())
		} else {
			vals[3] = psql.Raw("DEFAULT")
		}

		if s.ShouldBeBudgeted.IsValue() {
			vals[4] = psql.Arg(s.ShouldBeBudgeted.MustGet())
		} else {
			vals[4] = psql.Raw("DEFAULT")
		}

		if s.IsDisabled.IsValue() {
			vals[5] = psql.Arg(s.IsDisabled.MustGet())
		} else {
			vals[5] = psql.Raw("DEFAULT")
		}

		if s.CategoryType.IsValue() {
			vals[6] = psql.Arg(s.CategoryType.MustGet())
		} else {
			vals[6] = psql.Raw("DEFAULT")
		}

		if s.CreatedAt.IsValue() {
			vals[7] = psql.Arg(s.CreatedAt.MustGet())
		} else {
			vals[7] = psql.Raw("DEFAULT")
		}

		return bob.ExpressSlice(ctx, w, d, start, vals, "", ", ", "")
	}))
}

func (s CategorySetter) UpdateMod() bob.Mod[*dialect.UpdateQuery] {
	return um.Set(s.Expressions()...)
}

func (s CategorySetter) Expressions(prefix ...string) []bob.Expression {
	exprs := make([]bob.Expression, 0, 8)

	if s.ID.IsValue() {
		exprs = append(exprs, expr.Join{Sep: " = ", Exprs: []bob.Expression{
			psql.Quote(append(prefix, "id")...),
			psql.Arg(s.ID),
		}})
	}

	if s.Name.IsValue() {
		exprs = append(exprs, expr.Join{Sep: " = ", Exprs: []bob.Expression{
			psql.Quote(append(prefix, "name")...),
			psql.Arg(s.Name),
		}})
	}

	if s.IsGroup.IsValue() {
		exprs = append(exprs, expr.Join{Sep: " = ", Exprs: []bob.Expression{
			psql.Quote(append(prefix, "is_group")...),
			psql.Arg(s.IsGroup),
		}})
	}

	if !s.ParentID.IsUnset() {
		exprs = append(exprs, expr.Join{Sep: " = ", Exprs: []bob.Expression{
			psql.Quote(append(prefix, "parent_id")...),
			psql.Arg(s.ParentID),
		}})
	}

	if s.ShouldBeBudgeted.IsValue() {
		exprs = append(exprs, expr.Join{Sep: " = ", Exprs: []bob.Expression{
			psql.Quote(append(prefix, "should_be_budgeted")...),
			psql.Arg(s.ShouldBeBudgeted),
		}})
	}

	if s.IsDisabled.IsValue() {
		exprs = append(exprs, expr.Join{Sep: " = ", Exprs: []bob.Expression{
			psql.Quote(append(prefix, "is_disabled")...),
			psql.Arg(s.IsDisabled),
		}})
	}

	if s.CategoryType.IsValue() {
		exprs = append(exprs, expr.Join{Sep: " = ", Exprs: []bob.Expression{
			psql.Quote(append(prefix, "category_type")...),
			psql.Arg(s.CategoryType),
		}})
	}

	if s.CreatedAt.IsValue() {
		exprs = append(exprs, expr.Join{Sep: " = ", Exprs: []bob.Expression{
			psql.Quote(append(prefix, "created_at")...),
			psql.Arg(s.CreatedAt),
		}})
	}

	return exprs
}

// FindCategory retrieves a single record by primary key
// If cols is empty Find will return all columns.
func FindCategory(ctx context.Context, exec bob.Executor, IDPK uuid.UUID, cols ...string) (*Category, error) {
	if len(cols) == 0 {
		return Categories.Query(
			sm.Where(Categories.Columns.ID.EQ(psql.Arg(IDPK))),
		).One(ctx, exec)
	}

	return Categories.Query(
		sm.Where(Categories.Columns.ID.EQ(psql.Arg(IDPK))),
		sm.Columns(Categories.Columns.Only(cols...)),
	).One(ctx, exec)
}

// CategoryExists checks the presence of a single record by primary key
func CategoryExists(ctx context.Context, exec bob.Executor, IDPK uuid.UUID) (bool, error) {
	return Categories.Query(
		sm.Where(Categories.Columns.ID.EQ(psql.Arg(IDPK))),
	).Exists(ctx, exec)
}

// AfterQueryHook is called after Category is retrieved from the database
func (o *Category) AfterQueryHook(ctx context.Context, exec bob.Executor, queryType bob.QueryType) error {
	var err error

	switch queryType {
	case bob.QueryTypeSelect:
		ctx, err = Categories.AfterSelectHooks.RunHooks(ctx, exec, CategorySlice{o})
	case bob.QueryTypeInsert:
		ctx, err = Categories.AfterInsertHooks.RunHooks(ctx, exec, CategorySlice{o})
	case bob.QueryTypeUpdate:
		ctx, err = Categories.AfterUpdateHooks.RunHooks(ctx, exec, CategorySlice{o})
	case bob.QueryTypeDelete:
		ctx, err = Categories.AfterDeleteHooks.RunHooks(ctx, exec, CategorySlice{o})
	}

	return err
}

// primaryKeyVals returns the primary key values of the Category
func (o *Category) primaryKeyVals() bob.Expression {
	return psql.Arg(o.ID)
}

func (o *Category) pkEQ() dialect.Expression {
	return psql.Quote("categories", "id").EQ(bob.ExpressionFunc(func(ctx context.Context, w io.StringWriter, d bob.Dialect, start int) ([]any, error) {
		return o.primaryKeyVals().WriteSQL(ctx, w, d, start)
	}))
}

// Update uses an executor to update the Category
func (o *Category) Update(ctx context.Context, exec bob.Executor, s *CategorySetter) error {
	v, err := Categories.Update(s.UpdateMod(), um.Where(o.pkEQ())).One(ctx, exec)
	if err != nil {
		return err
	}

	o.R = v.R
	*o = *v

	return nil
}

// Delete deletes a single Category record with an executor
func (o *Category) Delete(ctx context.Context, exec bob.Executor) error {
	_, err := Categories.Delete(dm.Where(o.pkEQ())).Exec(ctx, exec)
	return err
}

// Reload refreshes the Category using the executor
func (o *Category) Reload(ctx context.Context, exec bob.Executor) error {
	o2, err := Categories.Query(
		sm.Where(Categories.Columns.ID.EQ(psql.Arg(o.ID))),
	).One(ctx, exec)
	if err != nil {
		return err
	}
	o2.R = o.R
	*o = *o2

	return nil
}

// AfterQueryHook is called after CategorySlice is retrieved from the database
func (o CategorySlice) AfterQueryHook(ctx context.Context, exec bob.Executor, queryType bob.QueryType) error {
	var err error

	switch queryType {
	case bob.QueryTypeSelect:
		ctx, err = Categories.AfterSelectHooks.RunHooks(ctx, exec, o)
	case bob.QueryTypeInsert:
		ctx, err = Categories.AfterInsertHooks.RunHooks(ctx, exec, o)
	case bob.QueryTypeUpdate:
		ctx, err = Categories.AfterUpdateHooks.RunHooks(ctx, exec, o)
	case bob.QueryTypeDelete:
		ctx, err = Categories.AfterDeleteHooks.RunHooks(ctx, exec, o)
	}

	return err
}

func (o CategorySlice) pkIN() dialect.Expression {
	if len(o) == 0 {
		return psql.Raw("NULL")
	}

	return psql.Quote("categories", "id").In(bob.ExpressionFunc(func(ctx context.Context, w io.StringWriter, d bob.Dialect, start int) ([]any, error) {
		pkPairs := make([]bob.Expression, len(o))
		for i, row := range o {
			pkPairs[i] = row.primaryKeyVals()
		}
		return bob.ExpressSlice(ctx, w, d, start, pkPairs, "", ", ", "")
	}))
}

// copyMatchingRows finds models in the given slice that have the same primary key
// then it first copies the existing relationships from the old model to the new model
// and then replaces the old model in the slice with the new model
func (o CategorySlice) copyMatchingRows(from ...*Category) {
	for i, old := range o {
		for _, new := range from {
			if new.ID != old.ID {
				continue
			}
			new.R = old.R
			o[i] = new
			break
		}
	}
}

// UpdateMod modifies an update query with "WHERE primary_key IN (o...)"
func (o CategorySlice) UpdateMod() bob.Mod[*dialect.UpdateQuery] {
	return bob.ModFunc[*dialect.UpdateQuery](func(q *dialect.UpdateQuery) {
		q.AppendHooks(func(ctx context.Context, exec bob.Executor) (context.Context, error) {
			return Categories.BeforeUpdateHooks.RunHooks(ctx, exec, o)
		})

		q.AppendLoader(bob.LoaderFunc(func(ctx context.Context, exec bob.Executor, retrieved any) error {
			var err error
			switch retrieved := retrieved.(type) {
			case *Category:
				o.copyMatchingRows(retrieved)
			case []*Category:
				o.copyMatchingRows(retrieved...)
			case CategorySlice:
				o.copyMatchingRows(retrieved...)
			default:
				// If the retrieved value is not a Category or a slice of Category
				// then run the AfterUpdateHooks on the slice
				_, err = Categories.AfterUpdateHooks.RunHooks(ctx, exec, o)
			}

			return err
		}))

		q.AppendWhere(o.pkIN())
	})
}

// DeleteMod modifies an delete query with "WHERE primary_key IN (o...)"
func (o CategorySlice) DeleteMod() bob.Mod[*dialect.DeleteQuery] {
	return bob.ModFunc[*dialect.DeleteQuery](func(q *dialect.DeleteQuery) {
		q.AppendHooks(func(ctx context.Context, exec bob.Executor) (context.Context, error) {
			return Categories.BeforeDeleteHooks.RunHooks(ctx, exec, o)
		})

		q.AppendLoader(bob.LoaderFunc(func(ctx context.Context, exec bob.Executor, retrieved any) error {
			var err error
			switch retrieved := retrieved.(type) {
			case *Category:
				o.copyMatchingRows(retrieved)
			case []*Category:
				o.copyMatchingRows(retrieved...)
			case CategorySlice:
				o.copyMatchingRows(retrieved...)
			default:
				// If the retrieved value is not a Category or a slice of Category
				// then run the AfterDeleteHooks on the slice
				_, err = Categories.AfterDeleteHooks.RunHooks(ctx, exec, o)
			}

			return err
		}))

		q.AppendWhere(o.pkIN())
	})
}

func (o CategorySlice) UpdateAll(ctx context.Context, exec bob.Executor, vals CategorySetter) error {
	if len(o) == 0 {
		return nil
	}

	_, err := Categories.Update(vals.UpdateMod(), o.UpdateMod()).All(ctx, exec)
	return err
}

func (o CategorySlice) DeleteAll(ctx context.Context, exec bob.Executor) error {
	if len(o) == 0 {
		return nil
	}

	_, err := Categories.Delete(o.DeleteMod()).Exec(ctx, exec)
	return err
}

func (o CategorySlice) ReloadAll(ctx context.Context, exec bob.Executor) error {
	if len(o) == 0 {
		return nil
	}

	o2, err := Categories.Query(sm.Where(o.pkIN())).All(ctx, exec)
	if err != nil {
		return err
	}

	o.copyMatchingRows(o2...)

	return nil
}

// Parent starts a query for related objects on categories
func (o *Category) Parent(mods ...bob.Mod[*dialect.SelectQuery]) CategoriesQuery {
	return Categories.Query(append(mods,
		sm.Where(Categories.Columns.ID.EQ(psql.Arg(o.ParentID))),
	)...)
}

func (os CategorySlice) Parent(mods ...bob.Mod[*dialect.SelectQuery]) CategoriesQuery {
	pkParentID := make(pgtypes.Array[null.Val[uuid.UUID]], 0, len(os))
	for _, o := range os {
		if o == nil {
			continue
		}
		pkParentID = append(pkParentID, o.ParentID)
	}
	PKArgExpr := psql.Select(sm.Columns(
		psql.F("unnest", psql.Cast(psql.Arg(pkParentID), "uuid[]")),
	))

	return Categories.Query(append(mods,
		sm.Where(psql.Group(Categories.Columns.ID).OP("IN", PKArgExpr)),
	)...)
}

// ReverseParents starts a query for related objects on categories
func (o *Category) ReverseParents(mods ...bob.Mod[*dialect.SelectQuery]) CategoriesQuery {
	return Categories.Query(append(mods,
		sm.Where(Categories.Columns.ParentID.EQ(psql.Arg(o.ID))),
	)...)
}

func (os CategorySlice) ReverseParents(mods ...bob.Mod[*dialect.SelectQuery]) CategoriesQuery {
	pkID := make(pgtypes.Array[uuid.UUID], 0, len(os))
	for _, o := range os {
		if o == nil {
			continue
		}
		pkID = append(pkID, o.ID)
	}
	PKArgExpr := psql.Select(sm.Columns(
		psql.F("unnest", psql.Cast(psql.Arg(pkID), "uuid[]")),
	))

	return Categories.Query(append(mods,
		sm.Where(psql.Group(Categories.Columns.ParentID).OP("IN", PKArgExpr)),
	)...)
}

// Transactions starts a query for related objects on transactions
func (o *Category) Transactions(mods ...bob.Mod[*dialect.SelectQuery]) TransactionsQuery {
	return Transactions.Query(append(mods,
		sm.Where(Transactions.Columns.CategoryID.EQ(psql.Arg(o.ID))),
	)...)
}

func (os CategorySlice) Transactions(mods ...bob.Mod[*dialect.SelectQuery]) TransactionsQuery {
	pkID := make(pgtypes.Array[uuid.UUID], 0, len(os))
	for _, o := range os {
		if o == nil {
			continue
		}
		pkID = append(pkID, o.ID)
	}
	PKArgExpr := psql.Select(sm.Columns(
		psql.F("unnest", psql.Cast(psql.Arg(pkID), "uuid[]")),
	))

	return Transactions.Query(append(mods,
		sm.Where(psql.Group(Transactions.Columns.CategoryID).OP("IN", PKArgExpr)),
	)...)
}

func attachCategoryParent0(ctx context.Context, exec bob.Executor, count int, category0 *Category, category1 *Category) (*Category, error) {
	setter := &CategorySetter{
		ParentID: omitnull.From(category1.ID),
	}

	err := category0.Update(ctx, exec, setter)
	if err != nil {
		return nil, fmt.Errorf("attachCategoryParent0: %w", err)
	}

	return category0, nil
}

func (category0 *Category) InsertParent(ctx context.Context, exec bob.Executor, related *CategorySetter) error {
	var err error

	category1, err := Categories.Insert(related).One(ctx, exec)
	if err != nil {
		return fmt.Errorf("inserting related objects: %w", err)
	}

	_, err = attachCategoryParent0(ctx, exec, 1, category0, category1)
	if err != nil {
		return err
	}

	category0.R.Parent = category1

	category1.R.Parent = category0

	return nil
}

func (category0 *Category) AttachParent(ctx context.Context, exec bob.Executor, category1 *Category) error {
	var err error

	_, err = attachCategoryParent0(ctx, exec, 1, category0, category1)
	if err != nil {
		return err
	}

	category0.R.Parent = category1

	category1.R.Parent = category0

	return nil
}

func insertCategoryReverseParents0(ctx context.Context, exec bob.Executor, categories1 []*CategorySetter, category0 *Category) (CategorySlice, error) {
	for i := range categories1 {
		categories1[i].ParentID = omitnull.From(category0.ID)
	}

	ret, err := Categories.Insert(bob.ToMods(categories1...)).All(ctx, exec)
	if err != nil {
		return ret, fmt.Errorf("insertCategoryReverseParents0: %w", err)
	}

	return ret, nil
}

func attachCategoryReverseParents0(ctx context.Context, exec bob.Executor, count int, categories1 CategorySlice, category0 *Category) (CategorySlice, error) {
	setter := &CategorySetter{
		ParentID: omitnull.From(category0.ID),
	}

	err := categories1.UpdateAll(ctx, exec, *setter)
	if err != nil {
		return nil, fmt.Errorf("attachCategoryReverseParents0: %w", err)
	}

	return categories1, nil
}

func (category0 *Category) InsertReverseParents(ctx context.Context, exec bob.Executor, related ...*CategorySetter) error {
	if len(related) == 0 {
		return nil
	}

	var err error

	categories1, err := insertCategoryReverseParents0(ctx, exec, related, category0)
	if err != nil {
		return err
	}

	category0.R.ReverseParents = append(category0.R.ReverseParents, categories1...)

	for _, rel := range categories1 {
		rel.R.ReverseParents = append(rel.R.ReverseParents, category0)
	}
	return nil
}

func (category0 *Category) AttachReverseParents(ctx context.Context, exec bob.Executor, related ...*Category) error {
	if len(related) == 0 {
		return nil
	}

	var err error
	categories1 := CategorySlice(related)

	_, err = attachCategoryReverseParents0(ctx, exec, len(related), categories1, category0)
	if err != nil {
		return err
	}

	category0.R.ReverseParents = append(category0.R.ReverseParents, categories1...)

	for _, rel := range related {
		rel.R.ReverseParents = append(rel.R.ReverseParents, category0)
	}

	return nil
}

func insertCategoryTransactions0(ctx context.Context, exec bob.Executor, transactions1 []*TransactionSetter, category0 *Category) (TransactionSlice, error) {
	for i := range transactions1 {
		transactions1[i].CategoryID = omit.From(category0.ID)
	}

	ret, err := Transactions.Insert(bob.ToMods(transactions1...)).All(ctx, exec)
	if err != nil {
		return ret, fmt.Errorf("insertCategoryTransactions0: %w", err)
	}

	return ret, nil
}

func attachCategoryTransactions0(ctx context.Context, exec bob.Executor, count int, transactions1 TransactionSlice, category0 *Category) (TransactionSlice, error) {
	setter := &TransactionSetter{
		CategoryID: omit.From(category0.ID),
	}

	err := transactions1.UpdateAll(ctx, exec, *setter)
	if err != nil {
		return nil, fmt.Errorf("attachCategoryTransactions0: %w", err)
	}

	return transactions1, nil
}

func (category0 *Category) InsertTransactions(ctx context.Context, exec bob.Executor, related ...*TransactionSetter) error {
	if len(related) == 0 {
		return nil
	}

	var err error

	transactions1, err := insertCategoryTransactions0(ctx, exec, related, category0)
	if err != nil {
		return err
	}

	category0.R.Transactions = append(category0.R.Transactions, transactions1...)

	for _, rel := range transactions1 {
		_ = rel // Transaction in this package has no R.Category field
	}
	return nil
}

func (category0 *Category) AttachTransactions(ctx context.Context, exec bob.Executor, related ...*Transaction) error {
	if len(related) == 0 {
		return nil
	}

	var err error
	transactions1 := TransactionSlice(related)

	_, err = attachCategoryTransactions0(ctx, exec, len(related), transactions1, category0)
	if err != nil {
		return err
	}

	category0.R.Transactions = append(category0.R.Transactions, transactions1...)

	for _, rel := range related {
		_ = rel // Transaction in this package has no R.Category field
	}

	return nil
}

type categoryWhere[Q psql.Filterable] struct {
	ID               psql.WhereMod[Q, uuid.UUID]
	Name             psql.WhereMod[Q, string]
	IsGroup          psql.WhereMod[Q, bool]
	ParentID         psql.WhereNullMod[Q, uuid.UUID]
	ShouldBeBudgeted psql.WhereMod[Q, bool]
	IsDisabled       psql.WhereMod[Q, bool]
	CategoryType     psql.WhereMod[Q, int16]
	CreatedAt        psql.WhereMod[Q, time.Time]
}

func (categoryWhere[Q]) AliasedAs(alias string) categoryWhere[Q] {
	return buildCategoryWhere[Q](buildCategoryColumns(alias))
}

func buildCategoryWhere[Q psql.Filterable](cols categoryColumns) categoryWhere[Q] {
	return categoryWhere[Q]{
		ID:               psql.Where[Q, uuid.UUID](cols.ID),
		Name:             psql.Where[Q, string](cols.Name),
		IsGroup:          psql.Where[Q, bool](cols.IsGroup),
		ParentID:         psql.WhereNull[Q, uuid.UUID](cols.ParentID),
		ShouldBeBudgeted: psql.Where[Q, bool](cols.ShouldBeBudgeted),
		IsDisabled:       psql.Where[Q, bool](cols.IsDisabled),
		CategoryType:     psql.Where[Q, int16](cols.CategoryType),
		CreatedAt:        psql.Where[Q, time.Time](cols.CreatedAt),
	}
}

func (o *Category) Preload(name string, retrieved any) error {
	if o == nil {
		return nil
	}

	switch name {
	case "Parent":
		rel, ok := retrieved.(*Category)
		if !ok {
			return fmt.Errorf("category cannot load %T as %q", retrieved, name)
		}

		o.R.Parent = rel

		if rel != nil {
			rel.R.Parent = o
		}
		return nil
	case "ReverseParents":
		rels, ok := retrieved.(CategorySlice)
		if !ok {
			return fmt.Errorf("category cannot load %T as %q", retrieved, name)
		}

		o.R.ReverseParents = rels

		for _, rel := range rels {
			if rel != nil {
				rel.R.ReverseParents = CategorySlice{o}
			}
		}
		return nil
	case "Transactions":
		rels, ok := retrieved.(TransactionSlice)
		if !ok {
			return fmt.Errorf("category cannot load %T as %q", retrieved, name)
		}

		o.R.Transactions = rels

		for _, rel := range rels {
			if rel != nil {
				_ = rel // Transaction in this package has no R.Category field
			}
		}
		return nil
	default:
		return fmt.Errorf("category has no relationship %q", name)
	}
}

type categoryPreloader struct {
	Parent func(...psql.PreloadOption) psql.Preloader
}

func buildCategoryPreloader() categoryPreloader {
	return categoryPreloader{
		Parent: func(opts ...psql.PreloadOption) psql.Preloader {
			return psql.Preload[*Category, CategorySlice](psql.PreloadRel{
				Name: "Parent",
				Sides: []psql.PreloadSide{
					{
						From:        Categories,
						To:          Categories,
						FromColumns: []string{"parent_id"},
						ToColumns:   []string{"id"},
					},
				},
			}, Categories.Columns.Names(), opts...)
		},
	}
}

type categoryThenLoader[Q orm.Loadable] struct {
	Parent         func(...bob.Mod[*dialect.SelectQuery]) orm.Loader[Q]
	ReverseParents func(...bob.Mod[*dialect.SelectQuery]) orm.Loader[Q]
	Transactions   func(...bob.Mod[*dialect.SelectQuery]) orm.Loader[Q]
}

func buildCategoryThenLoader[Q orm.Loadable]() categoryThenLoader[Q] {
	type ParentLoadInterface interface {
		LoadParent(context.Context, bob.Executor, ...bob.Mod[*dialect.SelectQuery]) error
	}
	type ReverseParentsLoadInterface interface {
		LoadReverseParents(context.Context, bob.Executor, ...bob.Mod[*dialect.SelectQuery]) error
	}
	type TransactionsLoadInterface interface {
		LoadTransactions(context.Context, bob.Executor, ...bob.Mod[*dialect.SelectQuery]) error
	}

	return categoryThenLoader[Q]{
		Parent: thenLoadBuilder[Q](
			"Parent",
			func(ctx context.Context, exec bob.Executor, retrieved ParentLoadInterface, mods ...bob.Mod[*dialect.SelectQuery]) error {
				return retrieved.LoadParent(ctx, exec, mods...)
			},
		),
		ReverseParents: thenLoadBuilder[Q](
			"ReverseParents",
			func(ctx context.Context, exec bob.Executor, retrieved ReverseParentsLoadInterface, mods ...bob.Mod[*dialect.SelectQuery]) error {
				return retrieved.LoadReverseParents(ctx, exec, mods...)
			},
		),
		Transactions: thenLoadBuilder[Q](
			"Transactions",
			func(ctx context.Context, exec bob.Executor, retrieved TransactionsLoadInterface, mods ...bob.Mod[*dialect.SelectQuery]) error {
				return retrieved.LoadTransactions(ctx, exec, mods...)
			},
		),
	}
}

// LoadParent loads the category's Parent into the .R struct
func (o *Category) LoadParent(ctx context.Context, exec bob.Executor, mods ...bob.Mod[*dialect.SelectQuery]) error {
	if o == nil {
		return nil
	}

	// Reset the relationship
	o.R.Parent = nil

	related, err := o.Parent(mods...).One(ctx, exec)
	if err != nil {
		return err
	}

	related.R.Parent = o

	o.R.Parent = related
	return nil
}

// LoadParent loads the category's Parent into the .R struct
func (os CategorySlice) LoadParent(ctx context.Context, exec bob.Executor, mods ...bob.Mod[*dialect.SelectQuery]) error {
	if len(os) == 0 {
		return nil
	}

	categories, err := os.Parent(mods...).All(ctx, exec)
	if err != nil {
		return err
	}

	for _, o := range os {
		if o == nil {
			continue
		}

		for _, rel := range categories {
			if !o.ParentID.IsValue() {
				continue
			}

			if !(o.ParentID.IsValue() && o.ParentID.MustGet() == rel.ID) {
				continue
			}

			rel.R.Parent = o

			o.R.Parent = rel
			break
		}
	}

	return nil
}

// LoadReverseParents loads the category's ReverseParents into the .R struct
func (o *Category) LoadReverseParents(ctx context.Context, exec bob.Executor, mods ...bob.Mod[*dialect.SelectQuery]) error {
	if o == nil {
		return nil
	}

	// Reset the relationship
	o.R.ReverseParents = nil

	related, err := o.ReverseParents(mods...).All(ctx, exec)
	if err != nil {
		return err
	}

	for _, rel := range related {
		rel.R.ReverseParents = CategorySlice{o}
	}

	o.R.ReverseParents = related
	return nil
}

// LoadReverseParents loads the category's ReverseParents into the .R struct
func (os CategorySlice) LoadReverseParents(ctx context.Context, exec bob.Executor, mods ...bob.Mod[*dialect.SelectQuery]) error {
	if len(os) == 0 {
		return nil
	}

	categories, err := os.ReverseParents(mods...).All(ctx, exec)
	if err != nil {
		return err
	}

	for _, o := range os {
		if o == nil {
			continue
		}

		o.R.ReverseParents = nil
	}

	for _, o := range os {
		if o == nil {
			continue
		}

		for _, rel := range categories {

			if !rel.ParentID.IsValue() {
				continue
			}
			if !(rel.ParentID.IsValue() && o.ID == rel.ParentID.MustGet()) {
				continue
			}

			rel.R.ReverseParents = append(rel.R.ReverseParents, o)

			o.R.ReverseParents = append(o.R.ReverseParents, rel)
		}
	}

	return nil
}

// LoadTransactions loads the category's Transactions into the .R struct
func (o *Category) LoadTransactions(ctx context.Context, exec bob.Executor, mods ...bob.Mod[*dialect.SelectQuery]) error {
	if o == nil {
		return nil
	}

	// Reset the relationship
	o.R.Transactions = nil

	related, err := o.Transactions(mods...).All(ctx, exec)
	if err != nil {
		return err
	}

	for _, rel := range related {
		_ = rel // Transaction in this package has no R.Category field
	}

	o.R.Transactions = related
	return nil
}

// LoadTransactions loads the category's Transactions into the .R struct
func (os CategorySlice) LoadTransactions(ctx context.Context, exec bob.Executor, mods ...bob.Mod[*dialect.SelectQuery]) error {
	if len(os) == 0 {
		return nil
	}

	transactions, err := os.Transactions(mods...).All(ctx, exec)
	if err != nil {
		return err
	}

	for _, o := range os {
		if o == nil {
			continue
		}

		o.R.Transactions = nil
	}

	for _, o := range os {
		if o == nil {
			continue
		}

		for _, rel := range transactions {

			if !(o.ID == rel.CategoryID) {
				continue
			}

			_ = rel // Transaction in this package has no R.Category field

			o.R.Transactions = append(o.R.Transactions, rel)
		}
	}

	return nil
}

type categoryJoins[Q dialect.Joinable] struct {
	typ            string
	Parent         modAs[Q, categoryColumns]
	ReverseParents modAs[Q, categoryColumns]
	Transactions   modAs[Q, transactionColumns]
}

func (j categoryJoins[Q]) aliasedAs(alias string) categoryJoins[Q] {
	return buildCategoryJoins[Q](buildCategoryColumns(alias), j.typ)
}

func buildCategoryJoins[Q dialect.Joinable](cols categoryColumns, typ string) categoryJoins[Q] {
	return categoryJoins[Q]{
		typ: typ,
		Parent: modAs[Q, categoryColumns]{
			c: Categories.Columns,
			f: func(to categoryColumns) bob.Mod[Q] {
				mods := make(mods.QueryMods[Q], 0, 1)

				{
					mods = append(mods, dialect.Join[Q](typ, Categories.Name().As(to.Alias())).On(
						to.ID.EQ(cols.ParentID),
					))
				}

				return mods
			},
		},
		ReverseParents: modAs[Q, categoryColumns]{
			c: Categories.Columns,
			f: func(to categoryColumns) bob.Mod[Q] {
				mods := make(mods.QueryMods[Q], 0, 1)

				{
					mods = append(mods, dialect.Join[Q](typ, Categories.Name().As(to.Alias())).On(
						to.ParentID.EQ(cols.ID),
					))
				}

				return mods
			},
		},
		Transactions: modAs[Q, transactionColumns]{
			c: Transactions.Columns,
			f: func(to transactionColumns) bob.Mod[Q] {
				mods := make(mods.QueryMods[Q], 0, 1)

				{
					mods = append(mods, dialect.Join[Q](typ, Transactions.Name().As(to.Alias())).On(
						to.CategoryID.EQ(cols.ID),
					))
				}

				return mods
			},
		},
	}
}
