// Code generated by BobGen psql v0.50.0. DO NOT EDIT.
// This file is meant to be re-generated in place and/or deleted at any time.

package bobgen

import (
	"context"
	"fmt"
	"io"

	"github.com/aarondl/opt/omit"
	"github.com/gofrs/uuid/v5"
	"github.com/stephenafamo/bob"
	"github.com/stephenafamo/bob/dialect/psql"
	"github.com/stephenafamo/bob/dialect/psql/dialect"
	"github.com/stephenafamo/bob/dialect/psql/dm"
	"github.com/stephenafamo/bob/dialect/psql/sm"
	"github.com/stephenafamo/bob/dialect/psql/um"
	"github.com/stephenafamo/bob/expr"
	"github.com/stephenafamo/bob/mods"
	"github.com/stephenafamo/bob/orm"
	"github.com/stephenafamo/bob/types/pgtypes"
	"github.com/stephenafamo/scan"
)

// PlaidTransactionLink is an object representing the database table.
type PlaidTransactionLink struct {
	PlaidTransactionID string    `db:"plaid_transaction_id,pk" `
	TransactionID      uuid.UUID `db:"transaction_id" `
	PlaidAccountID     string    `db:"plaid_account_id" `

	R plaidTransactionLinkR `db:"-" `
}

// PlaidTransactionLinkSlice is an alias for a slice of pointers to PlaidTransactionLink.
// This should almost always be used instead of []*PlaidTransactionLink.
type PlaidTransactionLinkSlice []*PlaidTransactionLink

// PlaidTransactionLinks contains methods to work with the plaid_transaction_links table
var PlaidTransactionLinks = psql.NewTablex[*PlaidTransactionLink, PlaidTransactionLinkSlice, *PlaidTransactionLinkSetter]("", "plaid_transaction_links", buildPlaidTransactionLinkColumns("plaid_transaction_links"), plaidTransactionLinkScanMapper)

// PlaidTransactionLinksQuery is a query on the plaid_transaction_links table
type PlaidTransactionLinksQuery = *psql.ViewQuery[*PlaidTransactionLink, PlaidTransactionLinkSlice]

// plaidTransactionLinkR is where relationships are stored.
type plaidTransactionLinkR struct {
	Transaction *Transaction // plaid_transaction_links.plaid_transaction_links_transaction_id_fkey
	// Loaded reports whether each relationship has been loaded.
	// A relationship's bool is set by Load*, Preload, ThenLoad, factory builds,
	// and to-one Attach/Insert operations. To-many Attach/Insert operations leave it unchanged.
	Loaded plaidTransactionLinkRLoaded `db:"-" `
}

// plaidTransactionLinkRLoaded tracks which relationships on PlaidTransactionLink have been loaded.
type plaidTransactionLinkRLoaded struct {
	Transaction bool // plaid_transaction_links.plaid_transaction_links_transaction_id_fkey
}

func buildPlaidTransactionLinkColumns(tableName string) plaidTransactionLinkColumns {
	columnsExpr := expr.NewColumnsExpr(
		"plaid_transaction_id", "transaction_id", "plaid_account_id",
	)

	if tableName != "" {
		columnsExpr = columnsExpr.WithParent(tableName)
	}

	return plaidTransactionLinkColumns{
		ColumnsExpr:        columnsExpr,
		tableAlias:         tableName,
		PlaidTransactionID: buildPlaidTransactionLinkColumn(tableName, "plaid_transaction_id"),
		TransactionID:      buildPlaidTransactionLinkColumn(tableName, "transaction_id"),
		PlaidAccountID:     buildPlaidTransactionLinkColumn(tableName, "plaid_account_id"),
	}
}

type plaidTransactionLinkColumns struct {
	expr.ColumnsExpr
	tableAlias         string
	PlaidTransactionID plaidTransactionLinkColumn
	TransactionID      plaidTransactionLinkColumn
	PlaidAccountID     plaidTransactionLinkColumn
}

// Alias returns the current table alias for the columns set.
func (c plaidTransactionLinkColumns) Alias() string {
	return c.tableAlias
}

// AliasedAs returns a copy of the columns set qualified by tableName.
func (plaidTransactionLinkColumns) AliasedAs(tableName string) plaidTransactionLinkColumns {
	return buildPlaidTransactionLinkColumns(tableName)
}

// Unqualified returns a copy of the columns set without table qualification.
func (c plaidTransactionLinkColumns) Unqualified() plaidTransactionLinkColumns {
	return buildPlaidTransactionLinkColumns("")
}

func buildPlaidTransactionLinkColumn(alias, name string) plaidTransactionLinkColumn {
	return plaidTransactionLinkColumn{
		Expression: psql.Quote(alias, name),
		alias:      alias,
		name:       name,
	}
}

type plaidTransactionLinkColumn struct {
	psql.Expression
	alias string
	name  string
}

// Name returns the unqualified column name.
func (c plaidTransactionLinkColumn) Name() string {
	return c.name
}

// ShouldOmitParens prevents automatic parenthesis wrapping in expression builders.
func (c plaidTransactionLinkColumn) ShouldOmitParens() bool {
	return true
}

// PlaidTransactionLinkSetter is used for insert/upsert/update operations
// All values are optional, and do not have to be set
// Generated columns are not included
type PlaidTransactionLinkSetter struct {
	PlaidTransactionID omit.Val[string]    `db:"plaid_transaction_id,pk" `
	TransactionID      omit.Val[uuid.UUID] `db:"transaction_id" `
	PlaidAccountID     omit.Val[string]    `db:"plaid_account_id" `
}

func (s PlaidTransactionLinkSetter) SetColumns() []string {
	vals := make([]string, 0, 3)
	if s.PlaidTransactionID.IsValue() {
		vals = append(vals, "plaid_transaction_id")
	}
	if s.TransactionID.IsValue() {
		vals = append(vals, "transaction_id")
	}
	if s.PlaidAccountID.IsValue() {
		vals = append(vals, "plaid_account_id")
	}
	return vals
}

func (s PlaidTransactionLinkSetter) Overwrite(t *PlaidTransactionLink) {
	if s.PlaidTransactionID.IsValue() {
		t.PlaidTransactionID = s.PlaidTransactionID.MustGet()
	}
	if s.TransactionID.IsValue() {
		t.TransactionID = s.TransactionID.MustGet()
	}
	if s.PlaidAccountID.IsValue() {
		t.PlaidAccountID = s.PlaidAccountID.MustGet()
	}
}

func (s *PlaidTransactionLinkSetter) Apply(q *dialect.InsertQuery) {
	q.AppendHooks(func(ctx context.Context, exec bob.Executor) (context.Context, error) {
		return PlaidTransactionLinks.BeforeInsertHooks.RunHooks(ctx, exec, s)
	})

	q.AppendValues(
		bob.ExpressionFunc(func(ctx context.Context, w io.StringWriter, d bob.Dialect, start int) ([]any, error) {
			if s.PlaidTransactionID.IsUnset() {
				return psql.Raw("DEFAULT").WriteSQL(ctx, w, d, start)
			}
			return psql.Arg(s.PlaidTransactionID.MustGet()).WriteSQL(ctx, w, d, start)
		}), bob.ExpressionFunc(func(ctx context.Context, w io.StringWriter, d bob.Dialect, start int) ([]any, error) {
			if s.TransactionID.IsUnset() {
				return psql.Raw("DEFAULT").WriteSQL(ctx, w, d, start)
			}
			return psql.Arg(s.TransactionID.MustGet()).WriteSQL(ctx, w, d, start)
		}), bob.ExpressionFunc(func(ctx context.Context, w io.StringWriter, d bob.Dialect, start int) ([]any, error) {
			if s.PlaidAccountID.IsUnset() {
				return psql.Raw("DEFAULT").WriteSQL(ctx, w, d, start)
			}
			return psql.Arg(s.PlaidAccountID.MustGet()).WriteSQL(ctx, w, d, start)
		}))
}

func (s PlaidTransactionLinkSetter) UpdateMod() bob.Mod[*dialect.UpdateQuery] {
	return um.Set(s.Expressions()...)
}

func (s PlaidTransactionLinkSetter) Expressions(prefix ...string) []bob.Expression {
	exprs := make([]bob.Expression, 0, 3)

	if s.PlaidTransactionID.IsValue() {
		exprs = append(exprs, expr.Join{Sep: " = ", Exprs: []bob.Expression{
			psql.Quote(append(prefix, "plaid_transaction_id")...),
			psql.Arg(s.PlaidTransactionID),
		}})
	}

	if s.TransactionID.IsValue() {
		exprs = append(exprs, expr.Join{Sep: " = ", Exprs: []bob.Expression{
			psql.Quote(append(prefix, "transaction_id")...),
			psql.Arg(s.TransactionID),
		}})
	}

	if s.PlaidAccountID.IsValue() {
		exprs = append(exprs, expr.Join{Sep: " = ", Exprs: []bob.Expression{
			psql.Quote(append(prefix, "plaid_account_id")...),
			psql.Arg(s.PlaidAccountID),
		}})
	}

	return exprs
}

// scan.Mapper[*T] without reflection: maps columns to fields by index.
func plaidTransactionLinkScanMapper(ctx context.Context, cols []string) (scan.BeforeFunc, func(any) (*PlaidTransactionLink, error)) {
	// resolve the column positions once per query, not per row
	type target struct {
		idx int
		dst func(o *PlaidTransactionLink) any
	}
	targets := make([]target, 0, 3)
	for i, col := range cols {
		switch col {
		case "plaid_transaction_id":
			targets = append(targets, target{i, func(o *PlaidTransactionLink) any { return &o.PlaidTransactionID }})
		case "transaction_id":
			targets = append(targets, target{i, func(o *PlaidTransactionLink) any { return &o.TransactionID }})
		case "plaid_account_id":
			targets = append(targets, target{i, func(o *PlaidTransactionLink) any { return &o.PlaidAccountID }})
		}
	}

	return func(row *scan.Row) (any, error) {
			o := new(PlaidTransactionLink)
			for _, t := range targets {
				row.ScheduleScanByIndex(t.idx, t.dst(o))
			}
			return o, nil
		}, func(v any) (*PlaidTransactionLink, error) {
			return v.(*PlaidTransactionLink), nil
		}
}

// FindPlaidTransactionLink retrieves a single record by primary key
// If cols is empty Find will return all columns.
func FindPlaidTransactionLink(ctx context.Context, exec bob.Executor, PlaidTransactionIDPK string, cols ...string) (*PlaidTransactionLink, error) {
	if len(cols) == 0 {
		return PlaidTransactionLinks.Query(
			sm.Where(PlaidTransactionLinks.Columns.PlaidTransactionID.EQ(psql.Arg(PlaidTransactionIDPK))),
		).One(ctx, exec)
	}

	return PlaidTransactionLinks.Query(
		sm.Where(PlaidTransactionLinks.Columns.PlaidTransactionID.EQ(psql.Arg(PlaidTransactionIDPK))),
		sm.Columns(PlaidTransactionLinks.Columns.Only(cols...)),
	).One(ctx, exec)
}

// PlaidTransactionLinkExists checks the presence of a single record by primary key
func PlaidTransactionLinkExists(ctx context.Context, exec bob.Executor, PlaidTransactionIDPK string) (bool, error) {
	return PlaidTransactionLinks.Query(
		sm.Where(PlaidTransactionLinks.Columns.PlaidTransactionID.EQ(psql.Arg(PlaidTransactionIDPK))),
	).Exists(ctx, exec)
}

// AfterQueryHook is called after PlaidTransactionLink is retrieved from the database
func (o *PlaidTransactionLink) AfterQueryHook(ctx context.Context, exec bob.Executor, queryType bob.QueryType) error {
	var err error

	switch queryType {
	case bob.QueryTypeSelect:
		ctx, err = PlaidTransactionLinks.AfterSelectHooks.RunHooks(ctx, exec, PlaidTransactionLinkSlice{o})
	case bob.QueryTypeInsert:
		ctx, err = PlaidTransactionLinks.AfterInsertHooks.RunHooks(ctx, exec, PlaidTransactionLinkSlice{o})
	case bob.QueryTypeUpdate:
		ctx, err = PlaidTransactionLinks.AfterUpdateHooks.RunHooks(ctx, exec, PlaidTransactionLinkSlice{o})
	case bob.QueryTypeDelete:
		ctx, err = PlaidTransactionLinks.AfterDeleteHooks.RunHooks(ctx, exec, PlaidTransactionLinkSlice{o})
	case bob.QueryTypeMerge:
		ctx, err = PlaidTransactionLinks.AfterMergeHooks.RunHooks(ctx, exec, PlaidTransactionLinkSlice{o})
	}

	return err
}

// primaryKeyVals returns the primary key values of the PlaidTransactionLink
func (o *PlaidTransactionLink) primaryKeyVals() bob.Expression {
	return psql.Arg(o.PlaidTransactionID)
}

func (o *PlaidTransactionLink) pkEQ() dialect.Expression {
	return psql.Quote("plaid_transaction_links", "plaid_transaction_id").EQ(bob.ExpressionFunc(func(ctx context.Context, w io.StringWriter, d bob.Dialect, start int) ([]any, error) {
		return o.primaryKeyVals().WriteSQL(ctx, w, d, start)
	}))
}

// Update uses an executor to update the PlaidTransactionLink
func (o *PlaidTransactionLink) Update(ctx context.Context, exec bob.Executor, s *PlaidTransactionLinkSetter) error {
	v, err := PlaidTransactionLinks.Update(s.UpdateMod(), um.Where(o.pkEQ())).One(ctx, exec)
	if err != nil {
		return err
	}

	o.R = v.R
	*o = *v

	return nil
}

// Delete deletes a single PlaidTransactionLink record with an executor
func (o *PlaidTransactionLink) Delete(ctx context.Context, exec bob.Executor) error {
	_, err := PlaidTransactionLinks.Delete(dm.Where(o.pkEQ())).Exec(ctx, exec)
	return err
}

// Reload refreshes the PlaidTransactionLink using the executor
func (o *PlaidTransactionLink) Reload(ctx context.Context, exec bob.Executor) error {
	o2, err := PlaidTransactionLinks.Query(
		sm.Where(PlaidTransactionLinks.Columns.PlaidTransactionID.EQ(psql.Arg(o.PlaidTransactionID))),
	).One(ctx, exec)
	if err != nil {
		return err
	}
	o2.R = o.R
	*o = *o2

	return nil
}

// AfterQueryHook is called after PlaidTransactionLinkSlice is retrieved from the database
func (o PlaidTransactionLinkSlice) AfterQueryHook(ctx context.Context, exec bob.Executor, queryType bob.QueryType) error {
	var err error

	switch queryType {
	case bob.QueryTypeSelect:
		ctx, err = PlaidTransactionLinks.AfterSelectHooks.RunHooks(ctx, exec, o)
	case bob.QueryTypeInsert:
		ctx, err = PlaidTransactionLinks.AfterInsertHooks.RunHooks(ctx, exec, o)
	case bob.QueryTypeUpdate:
		ctx, err = PlaidTransactionLinks.AfterUpdateHooks.RunHooks(ctx, exec, o)
	case bob.QueryTypeDelete:
		ctx, err = PlaidTransactionLinks.AfterDeleteHooks.RunHooks(ctx, exec, o)
	case bob.QueryTypeMerge:
		ctx, err = PlaidTransactionLinks.AfterMergeHooks.RunHooks(ctx, exec, o)
	}

	return err
}

func (o PlaidTransactionLinkSlice) pkIN() dialect.Expression {
	if len(o) == 0 {
		return psql.Raw("NULL")
	}

	return psql.Quote("plaid_transaction_links", "plaid_transaction_id").In(bob.ExpressionFunc(func(ctx context.Context, w io.StringWriter, d bob.Dialect, start int) ([]any, error) {
		pkPairs := make([]bob.Expression, len(o))
		for i, row := range o {
			pkPairs[i] = row.primaryKeyVals()
		}
		return bob.ExpressSlice(ctx, w, d, start, pkPairs, "", ", ", "")
	}))
}

// copyMatchingRows finds models in the given slice that have the same primary key
// then it first copies the existing relationships from the old model to the new model
// and then replaces the old model in the slice with the new model
func (o PlaidTransactionLinkSlice) copyMatchingRows(from ...*PlaidTransactionLink) {
	fromByPK := make(map[string]*PlaidTransactionLink, len(from))
	for _, new := range from {
		// keep the first row for each key, like the nested loop did
		if _, ok := fromByPK[new.PlaidTransactionID]; !ok {
			fromByPK[new.PlaidTransactionID] = new
		}
	}

	for i, old := range o {
		new, ok := fromByPK[old.PlaidTransactionID]
		if !ok {
			continue
		}
		new.R = old.R
		o[i] = new
	}
}

// UpdateMod modifies an update query with "WHERE primary_key IN (o...)"
func (o PlaidTransactionLinkSlice) UpdateMod() bob.Mod[*dialect.UpdateQuery] {
	return bob.ModFunc[*dialect.UpdateQuery](func(q *dialect.UpdateQuery) {
		q.AppendHooks(func(ctx context.Context, exec bob.Executor) (context.Context, error) {
			return PlaidTransactionLinks.BeforeUpdateHooks.RunHooks(ctx, exec, o)
		})

		q.AppendLoader(bob.LoaderFunc(func(ctx context.Context, exec bob.Executor, retrieved any) error {
			var err error
			switch retrieved := retrieved.(type) {
			case *PlaidTransactionLink:
				o.copyMatchingRows(retrieved)
			case []*PlaidTransactionLink:
				o.copyMatchingRows(retrieved...)
			case PlaidTransactionLinkSlice:
				o.copyMatchingRows(retrieved...)
			default:
				// If the retrieved value is not a PlaidTransactionLink or a slice of PlaidTransactionLink
				// then run the AfterUpdateHooks on the slice
				_, err = PlaidTransactionLinks.AfterUpdateHooks.RunHooks(ctx, exec, o)
			}

			return err
		}))

		q.AppendWhere(o.pkIN())
	})
}

// DeleteMod modifies an delete query with "WHERE primary_key IN (o...)"
func (o PlaidTransactionLinkSlice) DeleteMod() bob.Mod[*dialect.DeleteQuery] {
	return bob.ModFunc[*dialect.DeleteQuery](func(q *dialect.DeleteQuery) {
		q.AppendHooks(func(ctx context.Context, exec bob.Executor) (context.Context, error) {
			return PlaidTransactionLinks.BeforeDeleteHooks.RunHooks(ctx, exec, o)
		})

		q.AppendLoader(bob.LoaderFunc(func(ctx context.Context, exec bob.Executor, retrieved any) error {
			var err error
			switch retrieved := retrieved.(type) {
			case *PlaidTransactionLink:
				o.copyMatchingRows(retrieved)
			case []*PlaidTransactionLink:
				o.copyMatchingRows(retrieved...)
			case PlaidTransactionLinkSlice:
				o.copyMatchingRows(retrieved...)
			default:
				// If the retrieved value is not a PlaidTransactionLink or a slice of PlaidTransactionLink
				// then run the AfterDeleteHooks on the slice
				_, err = PlaidTransactionLinks.AfterDeleteHooks.RunHooks(ctx, exec, o)
			}

			return err
		}))

		q.AppendWhere(o.pkIN())
	})
}

// MergeMod modifies a merge query to run BeforeMergeHooks and AfterMergeHooks
// and updates the slice with the returned rows.
func (o PlaidTransactionLinkSlice) MergeMod() bob.Mod[*dialect.MergeQuery] {
	return bob.ModFunc[*dialect.MergeQuery](func(q *dialect.MergeQuery) {
		q.AppendHooks(func(ctx context.Context, exec bob.Executor) (context.Context, error) {
			return PlaidTransactionLinks.BeforeMergeHooks.RunHooks(ctx, exec, o)
		})

		q.AppendLoader(bob.LoaderFunc(func(ctx context.Context, exec bob.Executor, retrieved any) error {
			var err error
			switch retrieved := retrieved.(type) {
			case *PlaidTransactionLink:
				o.copyMatchingRows(retrieved)
			case []*PlaidTransactionLink:
				o.copyMatchingRows(retrieved...)
			case PlaidTransactionLinkSlice:
				o.copyMatchingRows(retrieved...)
			default:
				// If the retrieved value is not a PlaidTransactionLink or a slice of PlaidTransactionLink
				// then run the AfterMergeHooks on the slice
				_, err = PlaidTransactionLinks.AfterMergeHooks.RunHooks(ctx, exec, o)
			}

			return err
		}))
	})
}

func (o PlaidTransactionLinkSlice) UpdateAll(ctx context.Context, exec bob.Executor, vals PlaidTransactionLinkSetter) error {
	if len(o) == 0 {
		return nil
	}

	_, err := PlaidTransactionLinks.Update(vals.UpdateMod(), o.UpdateMod()).All(ctx, exec)
	return err
}

func (o PlaidTransactionLinkSlice) DeleteAll(ctx context.Context, exec bob.Executor) error {
	if len(o) == 0 {
		return nil
	}

	_, err := PlaidTransactionLinks.Delete(o.DeleteMod()).Exec(ctx, exec)
	return err
}

func (o PlaidTransactionLinkSlice) ReloadAll(ctx context.Context, exec bob.Executor) error {
	if len(o) == 0 {
		return nil
	}

	o2, err := PlaidTransactionLinks.Query(sm.Where(o.pkIN())).All(ctx, exec)
	if err != nil {
		return err
	}

	o.copyMatchingRows(o2...)

	return nil
}

// Transaction starts a query for related objects on transactions
func (o *PlaidTransactionLink) Transaction(mods ...bob.Mod[*dialect.SelectQuery]) TransactionsQuery {
	return Transactions.Query(append(mods,
		sm.Where(Transactions.Columns.ID.EQ(psql.Arg(o.TransactionID))),
	)...)
}

func (os PlaidTransactionLinkSlice) Transaction(mods ...bob.Mod[*dialect.SelectQuery]) TransactionsQuery {
	pkTransactionID := make(pgtypes.Array[uuid.UUID], 0, len(os))

	// the array is only a filter (semi-join), so duplicate keys can be
	// dropped before they are sent over the wire
	seenTransactionID := make(map[uuid.UUID]struct{}, len(os))
	for _, o := range os {
		if o == nil {
			continue
		}
		if _, ok := seenTransactionID[o.TransactionID]; ok {
			continue
		}
		seenTransactionID[o.TransactionID] = struct{}{}
		pkTransactionID = append(pkTransactionID, o.TransactionID)
	}
	PKArgExpr := psql.Any(psql.Cast(psql.Arg(pkTransactionID), "uuid[]"))

	return Transactions.Query(append(mods,
		sm.Where(Transactions.Columns.ID.EQ(PKArgExpr)),
	)...)
}

func attachPlaidTransactionLinkTransaction0(ctx context.Context, exec bob.Executor, count int, plaidTransactionLink0 *PlaidTransactionLink, transaction1 *Transaction) (*PlaidTransactionLink, error) {
	setter := &PlaidTransactionLinkSetter{
		TransactionID: omit.From(transaction1.ID),
	}

	err := plaidTransactionLink0.Update(ctx, exec, setter)
	if err != nil {
		return nil, fmt.Errorf("attachPlaidTransactionLinkTransaction0: %w", err)
	}

	return plaidTransactionLink0, nil
}

func (plaidTransactionLink0 *PlaidTransactionLink) InsertTransaction(ctx context.Context, exec bob.Executor, related *TransactionSetter) error {
	var err error

	transaction1, err := Transactions.Insert(related).One(ctx, exec)
	if err != nil {
		return fmt.Errorf("inserting related objects: %w", err)
	}

	_, err = attachPlaidTransactionLinkTransaction0(ctx, exec, 1, plaidTransactionLink0, transaction1)
	if err != nil {
		return err
	}

	plaidTransactionLink0.R.Transaction = transaction1
	plaidTransactionLink0.R.Loaded.Transaction = true

	transaction1.R.PlaidTransactionLinks = append(transaction1.R.PlaidTransactionLinks, plaidTransactionLink0)

	return nil
}

func (plaidTransactionLink0 *PlaidTransactionLink) AttachTransaction(ctx context.Context, exec bob.Executor, transaction1 *Transaction) error {
	var err error

	_, err = attachPlaidTransactionLinkTransaction0(ctx, exec, 1, plaidTransactionLink0, transaction1)
	if err != nil {
		return err
	}

	plaidTransactionLink0.R.Transaction = transaction1
	plaidTransactionLink0.R.Loaded.Transaction = true

	transaction1.R.PlaidTransactionLinks = append(transaction1.R.PlaidTransactionLinks, plaidTransactionLink0)

	return nil
}

type plaidTransactionLinkWhere[Q psql.Filterable] struct {
	cols               plaidTransactionLinkColumns
	PlaidTransactionID psql.WhereMod[Q, string]
	TransactionID      psql.WhereMod[Q, uuid.UUID]
	PlaidAccountID     psql.WhereMod[Q, string]
	R                  plaidTransactionLinkWhereR[Q]
}

func (plaidTransactionLinkWhere[Q]) AliasedAs(alias string) plaidTransactionLinkWhere[Q] {
	return buildPlaidTransactionLinkWhere[Q](buildPlaidTransactionLinkColumns(alias))
}

func buildPlaidTransactionLinkWhere[Q psql.Filterable](cols plaidTransactionLinkColumns) plaidTransactionLinkWhere[Q] {
	return plaidTransactionLinkWhere[Q]{
		cols:               cols,
		PlaidTransactionID: psql.Where[Q, string](cols.PlaidTransactionID.Expression),
		TransactionID:      psql.Where[Q, uuid.UUID](cols.TransactionID.Expression),
		PlaidAccountID:     psql.Where[Q, string](cols.PlaidAccountID.Expression),
		R:                  plaidTransactionLinkWhereR[Q]{cols: cols},
	}
}

// plaidTransactionLinkWhereR holds the relationship-based filters of
// plaidTransactionLinkWhere under the R namespace — mirroring the model's
// R struct — so they cannot collide with column-based filter fields.
type plaidTransactionLinkWhereR[Q psql.Filterable] struct {
	cols plaidTransactionLinkColumns
}

// HasTransaction filters parents that have a matching Transaction using a
// correlated EXISTS subquery (semi-join). Unlike an INNER JOIN it does not
// multiply parent rows, so no DISTINCT is needed. The optional filters are
// applied to the subquery (i.e. to Transactions).
func (w plaidTransactionLinkWhereR[Q]) HasTransaction(filters ...bob.Mod[*dialect.SelectQuery]) mods.Where[Q] {
	q := psql.Select(
		sm.Columns(psql.Raw("1")),
		sm.From(Transactions.NameExpr()),
		sm.Where(Transactions.Columns.ID.EQ(w.cols.TransactionID)),
	)
	q.Apply(filters...)
	return mods.Where[Q]{E: psql.Exists(q)}
}

func (o *PlaidTransactionLink) Preload(name string, retrieved any) error {
	if o == nil {
		return nil
	}

	switch name {
	case "Transaction":
		rel, ok := retrieved.(*Transaction)
		if !ok {
			return fmt.Errorf("plaidTransactionLink cannot load %T as %q", retrieved, name)
		}

		o.R.Transaction = rel
		o.R.Loaded.Transaction = true

		if rel != nil {
			rel.R.PlaidTransactionLinks = PlaidTransactionLinkSlice{o}
		}
		return nil
	default:
		return fmt.Errorf("plaidTransactionLink has no relationship %q", name)
	}
}

type plaidTransactionLinkPreloader struct {
	Transaction func(...psql.PreloadOption) psql.Preloader
}

func buildPlaidTransactionLinkPreloader() plaidTransactionLinkPreloader {
	return plaidTransactionLinkPreloader{
		Transaction: func(opts ...psql.PreloadOption) psql.Preloader {
			return psql.Preload[*Transaction, TransactionSlice](psql.PreloadRel{
				Name: "Transaction",
				Sides: []psql.PreloadSide{
					{
						From:        PlaidTransactionLinks,
						To:          Transactions,
						FromColumns: []string{"transaction_id"},
						ToColumns:   []string{"id"},
					},
				},
			}, Transactions.Columns.Names(), transactionScanMapperNullable, opts...)
		},
	}
}

type plaidTransactionLinkThenLoader[Q orm.Loadable] struct {
	Transaction func(...bob.Mod[*dialect.SelectQuery]) orm.Loader[Q]
}

func buildPlaidTransactionLinkThenLoader[Q orm.Loadable]() plaidTransactionLinkThenLoader[Q] {
	type TransactionLoadInterface interface {
		LoadTransaction(context.Context, bob.Executor, ...bob.Mod[*dialect.SelectQuery]) error
	}

	return plaidTransactionLinkThenLoader[Q]{
		Transaction: thenLoadBuilder[Q](
			"Transaction",
			func(ctx context.Context, exec bob.Executor, retrieved TransactionLoadInterface, mods ...bob.Mod[*dialect.SelectQuery]) error {
				return retrieved.LoadTransaction(ctx, exec, mods...)
			},
		),
	}
}

// LoadTransaction loads the plaidTransactionLink's Transaction into the .R struct
func (o *PlaidTransactionLink) LoadTransaction(ctx context.Context, exec bob.Executor, mods ...bob.Mod[*dialect.SelectQuery]) error {
	if o == nil {
		return nil
	}

	// Reset the relationship
	o.R.Transaction = nil
	o.R.Loaded.Transaction = false

	related, err := o.Transaction(mods...).One(ctx, exec)
	if err != nil {
		return err
	}

	related.R.PlaidTransactionLinks = PlaidTransactionLinkSlice{o}

	o.R.Transaction = related
	o.R.Loaded.Transaction = true
	return nil
}

// LoadTransaction loads the plaidTransactionLink's Transaction into the .R struct
func (os PlaidTransactionLinkSlice) LoadTransaction(ctx context.Context, exec bob.Executor, mods ...bob.Mod[*dialect.SelectQuery]) error {
	if len(os) == 0 {
		return nil
	}

	transactions, err := os.Transaction(mods...).All(ctx, exec)
	if err != nil {
		return err
	}

	for _, o := range os {
		if o == nil {
			continue
		}

		o.R.Transaction = nil
		o.R.Loaded.Transaction = true
	}
	// O(N+M) stitch via a map keyed by the join column (key -> []parent; was O(N*M)).
	plaidTransactionLinkByKey := make(map[uuid.UUID][]*PlaidTransactionLink, len(os))
	for _, o := range os {
		if o == nil {
			continue
		}

		plaidTransactionLinkByKey[o.TransactionID] = append(plaidTransactionLinkByKey[o.TransactionID], o)
	}

	for _, rel := range transactions {

		owners, ok := plaidTransactionLinkByKey[rel.ID]
		if !ok {
			continue
		}

		for _, o := range owners {

			// to-one: keep only the first matching child (matches the previous break)
			if o.R.Transaction != nil {
				continue
			}

			rel.R.PlaidTransactionLinks = append(rel.R.PlaidTransactionLinks, o)

			o.R.Transaction = rel

		}
	}

	return nil
}

type plaidTransactionLinkJoins[Q dialect.Joinable] struct {
	typ         string
	Transaction modAs[Q, transactionColumns]
}

func (j plaidTransactionLinkJoins[Q]) aliasedAs(alias string) plaidTransactionLinkJoins[Q] {
	return buildPlaidTransactionLinkJoins[Q](buildPlaidTransactionLinkColumns(alias), j.typ)
}

func buildPlaidTransactionLinkJoins[Q dialect.Joinable](cols plaidTransactionLinkColumns, typ string) plaidTransactionLinkJoins[Q] {
	return plaidTransactionLinkJoins[Q]{
		typ: typ,
		Transaction: modAs[Q, transactionColumns]{
			c: Transactions.Columns,
			f: func(to transactionColumns) bob.Mod[Q] {
				mods := make(mods.QueryMods[Q], 0, 1)

				{
					mods = append(mods, dialect.Join[Q](typ, Transactions.NameExpr().As(to.Alias())).On(
						to.ID.EQ(cols.TransactionID),
					))
				}

				return mods
			},
		},
	}
}
