// Code generated by BobGen psql v0.42.0. DO NOT EDIT.
// This file is meant to be re-generated in place and/or deleted at any time.

package bobgen

import (
	"context"
	"fmt"
	"io"
	"time"

	"github.com/aarondl/opt/omit"
	"github.com/gofrs/uuid/v5"
	"github.com/stephenafamo/bob"
	"github.com/stephenafamo/bob/dialect/psql"
	"github.com/stephenafamo/bob/dialect/psql/dialect"
	"github.com/stephenafamo/bob/dialect/psql/dm"
	"github.com/stephenafamo/bob/dialect/psql/sm"
	"github.com/stephenafamo/bob/dialect/psql/um"
	"github.com/stephenafamo/bob/expr"
	"github.com/stephenafamo/bob/mods"
	"github.com/stephenafamo/bob/orm"
	"github.com/stephenafamo/bob/types/pgtypes"
)

// PlaidItem is an object representing the database table.
type PlaidItem struct {
	ID              uuid.UUID `db:"id,pk" `
	AccessToken     string    `db:"access_token" `
	PlaidItemID     string    `db:"plaid_item_id" `
	InstitutionID   string    `db:"institution_id" `
	InstitutionName string    `db:"institution_name" `
	Cursor          string    `db:"cursor" `
	CreatedAt       time.Time `db:"created_at" `

	R plaidItemR `db:"-" `
}

// PlaidItemSlice is an alias for a slice of pointers to PlaidItem.
// This should almost always be used instead of []*PlaidItem.
type PlaidItemSlice []*PlaidItem

// PlaidItems contains methods to work with the plaid_items table
var PlaidItems = psql.NewTablex[*PlaidItem, PlaidItemSlice, *PlaidItemSetter]("", "plaid_items", buildPlaidItemColumns("plaid_items"))

// PlaidItemsQuery is a query on the plaid_items table
type PlaidItemsQuery = *psql.ViewQuery[*PlaidItem, PlaidItemSlice]

// plaidItemR is where relationships are stored.
type plaidItemR struct {
	PlaidAccountLinks PlaidAccountLinkSlice // plaid_account_links.plaid_account_links_plaid_item_id_fkey
}

func buildPlaidItemColumns(alias string) plaidItemColumns {
	return plaidItemColumns{
		ColumnsExpr: expr.NewColumnsExpr(
			"id", "access_token", "plaid_item_id", "institution_id", "institution_name", "cursor", "created_at",
		).WithParent("plaid_items"),
		tableAlias:      alias,
		ID:              psql.Quote(alias, "id"),
		AccessToken:     psql.Quote(alias, "access_token"),
		PlaidItemID:     psql.Quote(alias, "plaid_item_id"),
		InstitutionID:   psql.Quote(alias, "institution_id"),
		InstitutionName: psql.Quote(alias, "institution_name"),
		Cursor:          psql.Quote(alias, "cursor"),
		CreatedAt:       psql.Quote(alias, "created_at"),
	}
}

type plaidItemColumns struct {
	expr.ColumnsExpr
	tableAlias      string
	ID              psql.Expression
	AccessToken     psql.Expression
	PlaidItemID     psql.Expression
	InstitutionID   psql.Expression
	InstitutionName psql.Expression
	Cursor          psql.Expression
	CreatedAt       psql.Expression
}

func (c plaidItemColumns) Alias() string {
	return c.tableAlias
}

func (plaidItemColumns) AliasedAs(alias string) plaidItemColumns {
	return buildPlaidItemColumns(alias)
}

// PlaidItemSetter is used for insert/upsert/update operations
// All values are optional, and do not have to be set
// Generated columns are not included
type PlaidItemSetter struct {
	ID              omit.Val[uuid.UUID] `db:"id,pk" `
	AccessToken     omit.Val[string]    `db:"access_token" `
	PlaidItemID     omit.Val[string]    `db:"plaid_item_id" `
	InstitutionID   omit.Val[string]    `db:"institution_id" `
	InstitutionName omit.Val[string]    `db:"institution_name" `
	Cursor          omit.Val[string]    `db:"cursor" `
	CreatedAt       omit.Val[time.Time] `db:"created_at" `
}

func (s PlaidItemSetter) SetColumns() []string {
	vals := make([]string, 0, 7)
	if s.ID.IsValue() {
		vals = append(vals, "id")
	}
	if s.AccessToken.IsValue() {
		vals = append(vals, "access_token")
	}
	if s.PlaidItemID.IsValue() {
		vals = append(vals, "plaid_item_id")
	}
	if s.InstitutionID.IsValue() {
		vals = append(vals, "institution_id")
	}
	if s.InstitutionName.IsValue() {
		vals = append(vals, "institution_name")
	}
	if s.Cursor.IsValue() {
		vals = append(vals, "cursor")
	}
	if s.CreatedAt.IsValue() {
		vals = append(vals, "created_at")
	}
	return vals
}

func (s PlaidItemSetter) Overwrite(t *PlaidItem) {
	if s.ID.IsValue() {
		t.ID = s.ID.MustGet()
	}
	if s.AccessToken.IsValue() {
		t.AccessToken = s.AccessToken.MustGet()
	}
	if s.PlaidItemID.IsValue() {
		t.PlaidItemID = s.PlaidItemID.MustGet()
	}
	if s.InstitutionID.IsValue() {
		t.InstitutionID = s.InstitutionID.MustGet()
	}
	if s.InstitutionName.IsValue() {
		t.InstitutionName = s.InstitutionName.MustGet()
	}
	if s.Cursor.IsValue() {
		t.Cursor = s.Cursor.MustGet()
	}
	if s.CreatedAt.IsValue() {
		t.CreatedAt = s.CreatedAt.MustGet()
	}
}

func (s *PlaidItemSetter) Apply(q *dialect.InsertQuery) {
	q.AppendHooks(func(ctx context.Context, exec bob.Executor) (context.Context, error) {
		return PlaidItems.BeforeInsertHooks.RunHooks(ctx, exec, s)
	})

	q.AppendValues(bob.ExpressionFunc(func(ctx context.Context, w io.StringWriter, d bob.Dialect, start int) ([]any, error) {
		vals := make([]bob.Expression, 7)
		if s.ID.IsValue() {
			vals[0] = psql.Arg(s.ID.MustGet())
		} else {
			vals[0] = psql.Raw("DEFAULT")
		}

		if s.AccessToken.IsValue() {
			vals[1] = psql.Arg(s.AccessToken.MustGet())
		} else {
			vals[1] = psql.Raw("DEFAULT")
		}

		if s.PlaidItemID.IsValue() {
			vals[2] = psql.Arg(s.PlaidItemID.MustGet())
		} else {
			vals[2] = psql.Raw("DEFAULT")
		}

		if s.InstitutionID.IsValue() {
			vals[3] = psql.Arg(s.InstitutionID.MustGet())
		} else {
			vals[3] = psql.Raw("DEFAULT")
		}

		if s.InstitutionName.IsValue() {
			vals[4] = psql.Arg(s.InstitutionName.MustGet())
		} else {
			vals[4] = psql.Raw("DEFAULT")
		}

		if s.Cursor.IsValue() {
			vals[5] = psql.Arg(s.Cursor.MustGet())
		} else {
			vals[5] = psql.Raw("DEFAULT")
		}

		if s.CreatedAt.IsValue() {
			vals[6] = psql.Arg(s.CreatedAt.MustGet())
		} else {
			vals[6] = psql.Raw("DEFAULT")
		}

		return bob.ExpressSlice(ctx, w, d, start, vals, "", ", ", "")
	}))
}

func (s PlaidItemSetter) UpdateMod() bob.Mod[*dialect.UpdateQuery] {
	return um.Set(s.Expressions()...)
}

func (s PlaidItemSetter) Expressions(prefix ...string) []bob.Expression {
	exprs := make([]bob.Expression, 0, 7)

	if s.ID.IsValue() {
		exprs = append(exprs, expr.Join{Sep: " = ", Exprs: []bob.Expression{
			psql.Quote(append(prefix, "id")...),
			psql.Arg(s.ID),
		}})
	}

	if s.AccessToken.IsValue() {
		exprs = append(exprs, expr.Join{Sep: " = ", Exprs: []bob.Expression{
			psql.Quote(append(prefix, "access_token")...),
			psql.Arg(s.AccessToken),
		}})
	}

	if s.PlaidItemID.IsValue() {
		exprs = append(exprs, expr.Join{Sep: " = ", Exprs: []bob.Expression{
			psql.Quote(append(prefix, "plaid_item_id")...),
			psql.Arg(s.PlaidItemID),
		}})
	}

	if s.InstitutionID.IsValue() {
		exprs = append(exprs, expr.Join{Sep: " = ", Exprs: []bob.Expression{
			psql.Quote(append(prefix, "institution_id")...),
			psql.Arg(s.InstitutionID),
		}})
	}

	if s.InstitutionName.IsValue() {
		exprs = append(exprs, expr.Join{Sep: " = ", Exprs: []bob.Expression{
			psql.Quote(append(prefix, "institution_name")...),
			psql.Arg(s.InstitutionName),
		}})
	}

	if s.Cursor.IsValue() {
		exprs = append(exprs, expr.Join{Sep: " = ", Exprs: []bob.Expression{
			psql.Quote(append(prefix, "cursor")...),
			psql.Arg(s.Cursor),
		}})
	}

	if s.CreatedAt.IsValue() {
		exprs = append(exprs, expr.Join{Sep: " = ", Exprs: []bob.Expression{
			psql.Quote(append(prefix, "created_at")...),
			psql.Arg(s.CreatedAt),
		}})
	}

	return exprs
}

// FindPlaidItem retrieves a single record by primary key
// If cols is empty Find will return all columns.
func FindPlaidItem(ctx context.Context, exec bob.Executor, IDPK uuid.UUID, cols ...string) (*PlaidItem, error) {
	if len(cols) == 0 {
		return PlaidItems.Query(
			sm.Where(PlaidItems.Columns.ID.EQ(psql.Arg(IDPK))),
		).One(ctx, exec)
	}

	return PlaidItems.Query(
		sm.Where(PlaidItems.Columns.ID.EQ(psql.Arg(IDPK))),
		sm.Columns(PlaidItems.Columns.Only(cols...)),
	).One(ctx, exec)
}

// PlaidItemExists checks the presence of a single record by primary key
func PlaidItemExists(ctx context.Context, exec bob.Executor, IDPK uuid.UUID) (bool, error) {
	return PlaidItems.Query(
		sm.Where(PlaidItems.Columns.ID.EQ(psql.Arg(IDPK))),
	).Exists(ctx, exec)
}

// AfterQueryHook is called after PlaidItem is retrieved from the database
func (o *PlaidItem) AfterQueryHook(ctx context.Context, exec bob.Executor, queryType bob.QueryType) error {
	var err error

	switch queryType {
	case bob.QueryTypeSelect:
		ctx, err = PlaidItems.AfterSelectHooks.RunHooks(ctx, exec, PlaidItemSlice{o})
	case bob.QueryTypeInsert:
		ctx, err = PlaidItems.AfterInsertHooks.RunHooks(ctx, exec, PlaidItemSlice{o})
	case bob.QueryTypeUpdate:
		ctx, err = PlaidItems.AfterUpdateHooks.RunHooks(ctx, exec, PlaidItemSlice{o})
	case bob.QueryTypeDelete:
		ctx, err = PlaidItems.AfterDeleteHooks.RunHooks(ctx, exec, PlaidItemSlice{o})
	}

	return err
}

// primaryKeyVals returns the primary key values of the PlaidItem
func (o *PlaidItem) primaryKeyVals() bob.Expression {
	return psql.Arg(o.ID)
}

func (o *PlaidItem) pkEQ() dialect.Expression {
	return psql.Quote("plaid_items", "id").EQ(bob.ExpressionFunc(func(ctx context.Context, w io.StringWriter, d bob.Dialect, start int) ([]any, error) {
		return o.primaryKeyVals().WriteSQL(ctx, w, d, start)
	}))
}

// Update uses an executor to update the PlaidItem
func (o *PlaidItem) Update(ctx context.Context, exec bob.Executor, s *PlaidItemSetter) error {
	v, err := PlaidItems.Update(s.UpdateMod(), um.Where(o.pkEQ())).One(ctx, exec)
	if err != nil {
		return err
	}

	o.R = v.R
	*o = *v

	return nil
}

// Delete deletes a single PlaidItem record with an executor
func (o *PlaidItem) Delete(ctx context.Context, exec bob.Executor) error {
	_, err := PlaidItems.Delete(dm.Where(o.pkEQ())).Exec(ctx, exec)
	return err
}

// Reload refreshes the PlaidItem using the executor
func (o *PlaidItem) Reload(ctx context.Context, exec bob.Executor) error {
	o2, err := PlaidItems.Query(
		sm.Where(PlaidItems.Columns.ID.EQ(psql.Arg(o.ID))),
	).One(ctx, exec)
	if err != nil {
		return err
	}
	o2.R = o.R
	*o = *o2

	return nil
}

// AfterQueryHook is called after PlaidItemSlice is retrieved from the database
func (o PlaidItemSlice) AfterQueryHook(ctx context.Context, exec bob.Executor, queryType bob.QueryType) error {
	var err error

	switch queryType {
	case bob.QueryTypeSelect:
		ctx, err = PlaidItems.AfterSelectHooks.RunHooks(ctx, exec, o)
	case bob.QueryTypeInsert:
		ctx, err = PlaidItems.AfterInsertHooks.RunHooks(ctx, exec, o)
	case bob.QueryTypeUpdate:
		ctx, err = PlaidItems.AfterUpdateHooks.RunHooks(ctx, exec, o)
	case bob.QueryTypeDelete:
		ctx, err = PlaidItems.AfterDeleteHooks.RunHooks(ctx, exec, o)
	}

	return err
}

func (o PlaidItemSlice) pkIN() dialect.Expression {
	if len(o) == 0 {
		return psql.Raw("NULL")
	}

	return psql.Quote("plaid_items", "id").In(bob.ExpressionFunc(func(ctx context.Context, w io.StringWriter, d bob.Dialect, start int) ([]any, error) {
		pkPairs := make([]bob.Expression, len(o))
		for i, row := range o {
			pkPairs[i] = row.primaryKeyVals()
		}
		return bob.ExpressSlice(ctx, w, d, start, pkPairs, "", ", ", "")
	}))
}

// copyMatchingRows finds models in the given slice that have the same primary key
// then it first copies the existing relationships from the old model to the new model
// and then replaces the old model in the slice with the new model
func (o PlaidItemSlice) copyMatchingRows(from ...*PlaidItem) {
	for i, old := range o {
		for _, new := range from {
			if new.ID != old.ID {
				continue
			}
			new.R = old.R
			o[i] = new
			break
		}
	}
}

// UpdateMod modifies an update query with "WHERE primary_key IN (o...)"
func (o PlaidItemSlice) UpdateMod() bob.Mod[*dialect.UpdateQuery] {
	return bob.ModFunc[*dialect.UpdateQuery](func(q *dialect.UpdateQuery) {
		q.AppendHooks(func(ctx context.Context, exec bob.Executor) (context.Context, error) {
			return PlaidItems.BeforeUpdateHooks.RunHooks(ctx, exec, o)
		})

		q.AppendLoader(bob.LoaderFunc(func(ctx context.Context, exec bob.Executor, retrieved any) error {
			var err error
			switch retrieved := retrieved.(type) {
			case *PlaidItem:
				o.copyMatchingRows(retrieved)
			case []*PlaidItem:
				o.copyMatchingRows(retrieved...)
			case PlaidItemSlice:
				o.copyMatchingRows(retrieved...)
			default:
				// If the retrieved value is not a PlaidItem or a slice of PlaidItem
				// then run the AfterUpdateHooks on the slice
				_, err = PlaidItems.AfterUpdateHooks.RunHooks(ctx, exec, o)
			}

			return err
		}))

		q.AppendWhere(o.pkIN())
	})
}

// DeleteMod modifies an delete query with "WHERE primary_key IN (o...)"
func (o PlaidItemSlice) DeleteMod() bob.Mod[*dialect.DeleteQuery] {
	return bob.ModFunc[*dialect.DeleteQuery](func(q *dialect.DeleteQuery) {
		q.AppendHooks(func(ctx context.Context, exec bob.Executor) (context.Context, error) {
			return PlaidItems.BeforeDeleteHooks.RunHooks(ctx, exec, o)
		})

		q.AppendLoader(bob.LoaderFunc(func(ctx context.Context, exec bob.Executor, retrieved any) error {
			var err error
			switch retrieved := retrieved.(type) {
			case *PlaidItem:
				o.copyMatchingRows(retrieved)
			case []*PlaidItem:
				o.copyMatchingRows(retrieved...)
			case PlaidItemSlice:
				o.copyMatchingRows(retrieved...)
			default:
				// If the retrieved value is not a PlaidItem or a slice of PlaidItem
				// then run the AfterDeleteHooks on the slice
				_, err = PlaidItems.AfterDeleteHooks.RunHooks(ctx, exec, o)
			}

			return err
		}))

		q.AppendWhere(o.pkIN())
	})
}

func (o PlaidItemSlice) UpdateAll(ctx context.Context, exec bob.Executor, vals PlaidItemSetter) error {
	if len(o) == 0 {
		return nil
	}

	_, err := PlaidItems.Update(vals.UpdateMod(), o.UpdateMod()).All(ctx, exec)
	return err
}

func (o PlaidItemSlice) DeleteAll(ctx context.Context, exec bob.Executor) error {
	if len(o) == 0 {
		return nil
	}

	_, err := PlaidItems.Delete(o.DeleteMod()).Exec(ctx, exec)
	return err
}

func (o PlaidItemSlice) ReloadAll(ctx context.Context, exec bob.Executor) error {
	if len(o) == 0 {
		return nil
	}

	o2, err := PlaidItems.Query(sm.Where(o.pkIN())).All(ctx, exec)
	if err != nil {
		return err
	}

	o.copyMatchingRows(o2...)

	return nil
}

// PlaidAccountLinks starts a query for related objects on plaid_account_links
func (o *PlaidItem) PlaidAccountLinks(mods ...bob.Mod[*dialect.SelectQuery]) PlaidAccountLinksQuery {
	return PlaidAccountLinks.Query(append(mods,
		sm.Where(PlaidAccountLinks.Columns.PlaidItemID.EQ(psql.Arg(o.ID))),
	)...)
}

func (os PlaidItemSlice) PlaidAccountLinks(mods ...bob.Mod[*dialect.SelectQuery]) PlaidAccountLinksQuery {
	pkID := make(pgtypes.Array[uuid.UUID], 0, len(os))
	for _, o := range os {
		if o == nil {
			continue
		}
		pkID = append(pkID, o.ID)
	}
	PKArgExpr := psql.Select(sm.Columns(
		psql.F("unnest", psql.Cast(psql.Arg(pkID), "uuid[]")),
	))

	return PlaidAccountLinks.Query(append(mods,
		sm.Where(psql.Group(PlaidAccountLinks.Columns.PlaidItemID).OP("IN", PKArgExpr)),
	)...)
}

func insertPlaidItemPlaidAccountLinks0(ctx context.Context, exec bob.Executor, plaidAccountLinks1 []*PlaidAccountLinkSetter, plaidItem0 *PlaidItem) (PlaidAccountLinkSlice, error) {
	for i := range plaidAccountLinks1 {
		plaidAccountLinks1[i].PlaidItemID = omit.From(plaidItem0.ID)
	}

	ret, err := PlaidAccountLinks.Insert(bob.ToMods(plaidAccountLinks1...)).All(ctx, exec)
	if err != nil {
		return ret, fmt.Errorf("insertPlaidItemPlaidAccountLinks0: %w", err)
	}

	return ret, nil
}

func attachPlaidItemPlaidAccountLinks0(ctx context.Context, exec bob.Executor, count int, plaidAccountLinks1 PlaidAccountLinkSlice, plaidItem0 *PlaidItem) (PlaidAccountLinkSlice, error) {
	setter := &PlaidAccountLinkSetter{
		PlaidItemID: omit.From(plaidItem0.ID),
	}

	err := plaidAccountLinks1.UpdateAll(ctx, exec, *setter)
	if err != nil {
		return nil, fmt.Errorf("attachPlaidItemPlaidAccountLinks0: %w", err)
	}

	return plaidAccountLinks1, nil
}

func (plaidItem0 *PlaidItem) InsertPlaidAccountLinks(ctx context.Context, exec bob.Executor, related ...*PlaidAccountLinkSetter) error {
	if len(related) == 0 {
		return nil
	}

	var err error

	plaidAccountLinks1, err := insertPlaidItemPlaidAccountLinks0(ctx, exec, related, plaidItem0)
	if err != nil {
		return err
	}

	plaidItem0.R.PlaidAccountLinks = append(plaidItem0.R.PlaidAccountLinks, plaidAccountLinks1...)

	for _, rel := range plaidAccountLinks1 {
		rel.R.PlaidItem = plaidItem0
	}
	return nil
}

func (plaidItem0 *PlaidItem) AttachPlaidAccountLinks(ctx context.Context, exec bob.Executor, related ...*PlaidAccountLink) error {
	if len(related) == 0 {
		return nil
	}

	var err error
	plaidAccountLinks1 := PlaidAccountLinkSlice(related)

	_, err = attachPlaidItemPlaidAccountLinks0(ctx, exec, len(related), plaidAccountLinks1, plaidItem0)
	if err != nil {
		return err
	}

	plaidItem0.R.PlaidAccountLinks = append(plaidItem0.R.PlaidAccountLinks, plaidAccountLinks1...)

	for _, rel := range related {
		rel.R.PlaidItem = plaidItem0
	}

	return nil
}

type plaidItemWhere[Q psql.Filterable] struct {
	ID              psql.WhereMod[Q, uuid.UUID]
	AccessToken     psql.WhereMod[Q, string]
	PlaidItemID     psql.WhereMod[Q, string]
	InstitutionID   psql.WhereMod[Q, string]
	InstitutionName psql.WhereMod[Q, string]
	Cursor          psql.WhereMod[Q, string]
	CreatedAt       psql.WhereMod[Q, time.Time]
}

func (plaidItemWhere[Q]) AliasedAs(alias string) plaidItemWhere[Q] {
	return buildPlaidItemWhere[Q](buildPlaidItemColumns(alias))
}

func buildPlaidItemWhere[Q psql.Filterable](cols plaidItemColumns) plaidItemWhere[Q] {
	return plaidItemWhere[Q]{
		ID:              psql.Where[Q, uuid.UUID](cols.ID),
		AccessToken:     psql.Where[Q, string](cols.AccessToken),
		PlaidItemID:     psql.Where[Q, string](cols.PlaidItemID),
		InstitutionID:   psql.Where[Q, string](cols.InstitutionID),
		InstitutionName: psql.Where[Q, string](cols.InstitutionName),
		Cursor:          psql.Where[Q, string](cols.Cursor),
		CreatedAt:       psql.Where[Q, time.Time](cols.CreatedAt),
	}
}

func (o *PlaidItem) Preload(name string, retrieved any) error {
	if o == nil {
		return nil
	}

	switch name {
	case "PlaidAccountLinks":
		rels, ok := retrieved.(PlaidAccountLinkSlice)
		if !ok {
			return fmt.Errorf("plaidItem cannot load %T as %q", retrieved, name)
		}

		o.R.PlaidAccountLinks = rels

		for _, rel := range rels {
			if rel != nil {
				rel.R.PlaidItem = o
			}
		}
		return nil
	default:
		return fmt.Errorf("plaidItem has no relationship %q", name)
	}
}

type plaidItemPreloader struct{}

func buildPlaidItemPreloader() plaidItemPreloader {
	return plaidItemPreloader{}
}

type plaidItemThenLoader[Q orm.Loadable] struct {
	PlaidAccountLinks func(...bob.Mod[*dialect.SelectQuery]) orm.Loader[Q]
}

func buildPlaidItemThenLoader[Q orm.Loadable]() plaidItemThenLoader[Q] {
	type PlaidAccountLinksLoadInterface interface {
		LoadPlaidAccountLinks(context.Context, bob.Executor, ...bob.Mod[*dialect.SelectQuery]) error
	}

	return plaidItemThenLoader[Q]{
		PlaidAccountLinks: thenLoadBuilder[Q](
			"PlaidAccountLinks",
			func(ctx context.Context, exec bob.Executor, retrieved PlaidAccountLinksLoadInterface, mods ...bob.Mod[*dialect.SelectQuery]) error {
				return retrieved.LoadPlaidAccountLinks(ctx, exec, mods...)
			},
		),
	}
}

// LoadPlaidAccountLinks loads the plaidItem's PlaidAccountLinks into the .R struct
func (o *PlaidItem) LoadPlaidAccountLinks(ctx context.Context, exec bob.Executor, mods ...bob.Mod[*dialect.SelectQuery]) error {
	if o == nil {
		return nil
	}

	// Reset the relationship
	o.R.PlaidAccountLinks = nil

	related, err := o.PlaidAccountLinks(mods...).All(ctx, exec)
	if err != nil {
		return err
	}

	for _, rel := range related {
		rel.R.PlaidItem = o
	}

	o.R.PlaidAccountLinks = related
	return nil
}

// LoadPlaidAccountLinks loads the plaidItem's PlaidAccountLinks into the .R struct
func (os PlaidItemSlice) LoadPlaidAccountLinks(ctx context.Context, exec bob.Executor, mods ...bob.Mod[*dialect.SelectQuery]) error {
	if len(os) == 0 {
		return nil
	}

	plaidAccountLinks, err := os.PlaidAccountLinks(mods...).All(ctx, exec)
	if err != nil {
		return err
	}

	for _, o := range os {
		if o == nil {
			continue
		}

		o.R.PlaidAccountLinks = nil
	}

	for _, o := range os {
		if o == nil {
			continue
		}

		for _, rel := range plaidAccountLinks {

			if !(o.ID == rel.PlaidItemID) {
				continue
			}

			rel.R.PlaidItem = o

			o.R.PlaidAccountLinks = append(o.R.PlaidAccountLinks, rel)
		}
	}

	return nil
}

type plaidItemJoins[Q dialect.Joinable] struct {
	typ               string
	PlaidAccountLinks modAs[Q, plaidAccountLinkColumns]
}

func (j plaidItemJoins[Q]) aliasedAs(alias string) plaidItemJoins[Q] {
	return buildPlaidItemJoins[Q](buildPlaidItemColumns(alias), j.typ)
}

func buildPlaidItemJoins[Q dialect.Joinable](cols plaidItemColumns, typ string) plaidItemJoins[Q] {
	return plaidItemJoins[Q]{
		typ: typ,
		PlaidAccountLinks: modAs[Q, plaidAccountLinkColumns]{
			c: PlaidAccountLinks.Columns,
			f: func(to plaidAccountLinkColumns) bob.Mod[Q] {
				mods := make(mods.QueryMods[Q], 0, 1)

				{
					mods = append(mods, dialect.Join[Q](typ, PlaidAccountLinks.Name().As(to.Alias())).On(
						to.PlaidItemID.EQ(cols.ID),
					))
				}

				return mods
			},
		},
	}
}
