// Code generated by BobGen psql v0.50.0. DO NOT EDIT.
// This file is meant to be re-generated in place and/or deleted at any time.

package bobgen

import (
	"context"
	"fmt"
	"io"
	"strings"
	"time"

	"github.com/aarondl/opt/null"
	"github.com/aarondl/opt/omit"
	"github.com/aarondl/opt/omitnull"
	"github.com/gofrs/uuid/v5"
	"github.com/shopspring/decimal"
	"github.com/stephenafamo/bob"
	"github.com/stephenafamo/bob/dialect/psql"
	"github.com/stephenafamo/bob/dialect/psql/dialect"
	"github.com/stephenafamo/bob/dialect/psql/dm"
	"github.com/stephenafamo/bob/dialect/psql/sm"
	"github.com/stephenafamo/bob/dialect/psql/um"
	"github.com/stephenafamo/bob/expr"
	"github.com/stephenafamo/bob/mods"
	"github.com/stephenafamo/bob/orm"
	"github.com/stephenafamo/bob/types/pgtypes"
	"github.com/stephenafamo/scan"
)

// Transaction is an object representing the database table.
type Transaction struct {
	ID              uuid.UUID           `db:"id,pk" `
	AccountID       uuid.UUID           `db:"account_id" `
	CategoryID      null.Val[uuid.UUID] `db:"category_id" `
	Amount          decimal.Decimal     `db:"amount" `
	TransactionName string              `db:"transaction_name" `
	TransactionDate time.Time           `db:"transaction_date" `
	CreatedAt       time.Time           `db:"created_at" `
	MerchantName    null.Val[string]    `db:"merchant_name" `

	R transactionR `db:"-" `

	C transactionC `db:"-" `
}

// TransactionSlice is an alias for a slice of pointers to Transaction.
// This should almost always be used instead of []*Transaction.
type TransactionSlice []*Transaction

// Transactions contains methods to work with the transactions table
var Transactions = psql.NewTablex[*Transaction, TransactionSlice, *TransactionSetter]("", "transactions", buildTransactionColumns("transactions"), transactionScanMapper)

// TransactionsQuery is a query on the transactions table
type TransactionsQuery = *psql.ViewQuery[*Transaction, TransactionSlice]

// transactionR is where relationships are stored.
type transactionR struct {
	PlaidTransactionLinks PlaidTransactionLinkSlice // plaid_transaction_links.plaid_transaction_links_transaction_id_fkey
	Account               *Account                  // transactions.fk_transactions_account_id
	Category              *Category                 // transactions.fk_transactions_category_id
	// Loaded reports whether each relationship has been loaded.
	// A relationship's bool is set by Load*, Preload, ThenLoad, factory builds,
	// and to-one Attach/Insert operations. To-many Attach/Insert operations leave it unchanged.
	Loaded transactionRLoaded `db:"-" `
}

// transactionRLoaded tracks which relationships on Transaction have been loaded.
type transactionRLoaded struct {
	PlaidTransactionLinks bool // plaid_transaction_links.plaid_transaction_links_transaction_id_fkey
	Account               bool // transactions.fk_transactions_account_id
	Category              bool // transactions.fk_transactions_category_id
}

func buildTransactionColumns(tableName string) transactionColumns {
	columnsExpr := expr.NewColumnsExpr(
		"id", "account_id", "category_id", "amount", "transaction_name", "transaction_date", "created_at", "merchant_name",
	)

	if tableName != "" {
		columnsExpr = columnsExpr.WithParent(tableName)
	}

	return transactionColumns{
		ColumnsExpr:     columnsExpr,
		tableAlias:      tableName,
		ID:              buildTransactionColumn(tableName, "id"),
		AccountID:       buildTransactionColumn(tableName, "account_id"),
		CategoryID:      buildTransactionColumn(tableName, "category_id"),
		Amount:          buildTransactionColumn(tableName, "amount"),
		TransactionName: buildTransactionColumn(tableName, "transaction_name"),
		TransactionDate: buildTransactionColumn(tableName, "transaction_date"),
		CreatedAt:       buildTransactionColumn(tableName, "created_at"),
		MerchantName:    buildTransactionColumn(tableName, "merchant_name"),
	}
}

type transactionColumns struct {
	expr.ColumnsExpr
	tableAlias      string
	ID              transactionColumn
	AccountID       transactionColumn
	CategoryID      transactionColumn
	Amount          transactionColumn
	TransactionName transactionColumn
	TransactionDate transactionColumn
	CreatedAt       transactionColumn
	MerchantName    transactionColumn
}

// Alias returns the current table alias for the columns set.
func (c transactionColumns) Alias() string {
	return c.tableAlias
}

// AliasedAs returns a copy of the columns set qualified by tableName.
func (transactionColumns) AliasedAs(tableName string) transactionColumns {
	return buildTransactionColumns(tableName)
}

// Unqualified returns a copy of the columns set without table qualification.
func (c transactionColumns) Unqualified() transactionColumns {
	return buildTransactionColumns("")
}

func buildTransactionColumn(alias, name string) transactionColumn {
	return transactionColumn{
		Expression: psql.Quote(alias, name),
		alias:      alias,
		name:       name,
	}
}

type transactionColumn struct {
	psql.Expression
	alias string
	name  string
}

// Name returns the unqualified column name.
func (c transactionColumn) Name() string {
	return c.name
}

// ShouldOmitParens prevents automatic parenthesis wrapping in expression builders.
func (c transactionColumn) ShouldOmitParens() bool {
	return true
}

// TransactionSetter is used for insert/upsert/update operations
// All values are optional, and do not have to be set
// Generated columns are not included
type TransactionSetter struct {
	ID              omit.Val[uuid.UUID]       `db:"id,pk" `
	AccountID       omit.Val[uuid.UUID]       `db:"account_id" `
	CategoryID      omitnull.Val[uuid.UUID]   `db:"category_id" `
	Amount          omit.Val[decimal.Decimal] `db:"amount" `
	TransactionName omit.Val[string]          `db:"transaction_name" `
	TransactionDate omit.Val[time.Time]       `db:"transaction_date" `
	CreatedAt       omit.Val[time.Time]       `db:"created_at" `
	MerchantName    omitnull.Val[string]      `db:"merchant_name" `
}

func (s TransactionSetter) SetColumns() []string {
	vals := make([]string, 0, 8)
	if s.ID.IsValue() {
		vals = append(vals, "id")
	}
	if s.AccountID.IsValue() {
		vals = append(vals, "account_id")
	}
	if s.CategoryID.IsValue() || s.CategoryID.IsNull() {
		vals = append(vals, "category_id")
	}
	if s.Amount.IsValue() {
		vals = append(vals, "amount")
	}
	if s.TransactionName.IsValue() {
		vals = append(vals, "transaction_name")
	}
	if s.TransactionDate.IsValue() {
		vals = append(vals, "transaction_date")
	}
	if s.CreatedAt.IsValue() {
		vals = append(vals, "created_at")
	}
	if s.MerchantName.IsValue() || s.MerchantName.IsNull() {
		vals = append(vals, "merchant_name")
	}
	return vals
}

func (s TransactionSetter) Overwrite(t *Transaction) {
	if s.ID.IsValue() {
		t.ID = s.ID.MustGet()
	}
	if s.AccountID.IsValue() {
		t.AccountID = s.AccountID.MustGet()
	}
	if s.CategoryID.IsValue() || s.CategoryID.IsNull() {
		t.CategoryID = s.CategoryID.MustGetNull()
	}
	if s.Amount.IsValue() {
		t.Amount = s.Amount.MustGet()
	}
	if s.TransactionName.IsValue() {
		t.TransactionName = s.TransactionName.MustGet()
	}
	if s.TransactionDate.IsValue() {
		t.TransactionDate = s.TransactionDate.MustGet()
	}
	if s.CreatedAt.IsValue() {
		t.CreatedAt = s.CreatedAt.MustGet()
	}
	if s.MerchantName.IsValue() || s.MerchantName.IsNull() {
		t.MerchantName = s.MerchantName.MustGetNull()
	}
}

func (s *TransactionSetter) Apply(q *dialect.InsertQuery) {
	q.AppendHooks(func(ctx context.Context, exec bob.Executor) (context.Context, error) {
		return Transactions.BeforeInsertHooks.RunHooks(ctx, exec, s)
	})

	q.AppendValues(
		bob.ExpressionFunc(func(ctx context.Context, w io.StringWriter, d bob.Dialect, start int) ([]any, error) {
			if s.ID.IsUnset() {
				return psql.Raw("DEFAULT").WriteSQL(ctx, w, d, start)
			}
			return psql.Arg(s.ID.MustGet()).WriteSQL(ctx, w, d, start)
		}), bob.ExpressionFunc(func(ctx context.Context, w io.StringWriter, d bob.Dialect, start int) ([]any, error) {
			if s.AccountID.IsUnset() {
				return psql.Raw("DEFAULT").WriteSQL(ctx, w, d, start)
			}
			return psql.Arg(s.AccountID.MustGet()).WriteSQL(ctx, w, d, start)
		}), bob.ExpressionFunc(func(ctx context.Context, w io.StringWriter, d bob.Dialect, start int) ([]any, error) {
			if s.CategoryID.IsUnset() {
				return psql.Raw("DEFAULT").WriteSQL(ctx, w, d, start)
			}
			return psql.Arg(s.CategoryID.MustGetNull()).WriteSQL(ctx, w, d, start)
		}), bob.ExpressionFunc(func(ctx context.Context, w io.StringWriter, d bob.Dialect, start int) ([]any, error) {
			if s.Amount.IsUnset() {
				return psql.Raw("DEFAULT").WriteSQL(ctx, w, d, start)
			}
			return psql.Arg(s.Amount.MustGet()).WriteSQL(ctx, w, d, start)
		}), bob.ExpressionFunc(func(ctx context.Context, w io.StringWriter, d bob.Dialect, start int) ([]any, error) {
			if s.TransactionName.IsUnset() {
				return psql.Raw("DEFAULT").WriteSQL(ctx, w, d, start)
			}
			return psql.Arg(s.TransactionName.MustGet()).WriteSQL(ctx, w, d, start)
		}), bob.ExpressionFunc(func(ctx context.Context, w io.StringWriter, d bob.Dialect, start int) ([]any, error) {
			if s.TransactionDate.IsUnset() {
				return psql.Raw("DEFAULT").WriteSQL(ctx, w, d, start)
			}
			return psql.Arg(s.TransactionDate.MustGet()).WriteSQL(ctx, w, d, start)
		}), bob.ExpressionFunc(func(ctx context.Context, w io.StringWriter, d bob.Dialect, start int) ([]any, error) {
			if s.CreatedAt.IsUnset() {
				return psql.Raw("DEFAULT").WriteSQL(ctx, w, d, start)
			}
			return psql.Arg(s.CreatedAt.MustGet()).WriteSQL(ctx, w, d, start)
		}), bob.ExpressionFunc(func(ctx context.Context, w io.StringWriter, d bob.Dialect, start int) ([]any, error) {
			if s.MerchantName.IsUnset() {
				return psql.Raw("DEFAULT").WriteSQL(ctx, w, d, start)
			}
			return psql.Arg(s.MerchantName.MustGetNull()).WriteSQL(ctx, w, d, start)
		}))
}

func (s TransactionSetter) UpdateMod() bob.Mod[*dialect.UpdateQuery] {
	return um.Set(s.Expressions()...)
}

func (s TransactionSetter) Expressions(prefix ...string) []bob.Expression {
	exprs := make([]bob.Expression, 0, 8)

	if s.ID.IsValue() {
		exprs = append(exprs, expr.Join{Sep: " = ", Exprs: []bob.Expression{
			psql.Quote(append(prefix, "id")...),
			psql.Arg(s.ID),
		}})
	}

	if s.AccountID.IsValue() {
		exprs = append(exprs, expr.Join{Sep: " = ", Exprs: []bob.Expression{
			psql.Quote(append(prefix, "account_id")...),
			psql.Arg(s.AccountID),
		}})
	}

	if s.CategoryID.IsValue() || s.CategoryID.IsNull() {
		exprs = append(exprs, expr.Join{Sep: " = ", Exprs: []bob.Expression{
			psql.Quote(append(prefix, "category_id")...),
			psql.Arg(s.CategoryID),
		}})
	}

	if s.Amount.IsValue() {
		exprs = append(exprs, expr.Join{Sep: " = ", Exprs: []bob.Expression{
			psql.Quote(append(prefix, "amount")...),
			psql.Arg(s.Amount),
		}})
	}

	if s.TransactionName.IsValue() {
		exprs = append(exprs, expr.Join{Sep: " = ", Exprs: []bob.Expression{
			psql.Quote(append(prefix, "transaction_name")...),
			psql.Arg(s.TransactionName),
		}})
	}

	if s.TransactionDate.IsValue() {
		exprs = append(exprs, expr.Join{Sep: " = ", Exprs: []bob.Expression{
			psql.Quote(append(prefix, "transaction_date")...),
			psql.Arg(s.TransactionDate),
		}})
	}

	if s.CreatedAt.IsValue() {
		exprs = append(exprs, expr.Join{Sep: " = ", Exprs: []bob.Expression{
			psql.Quote(append(prefix, "created_at")...),
			psql.Arg(s.CreatedAt),
		}})
	}

	if s.MerchantName.IsValue() || s.MerchantName.IsNull() {
		exprs = append(exprs, expr.Join{Sep: " = ", Exprs: []bob.Expression{
			psql.Quote(append(prefix, "merchant_name")...),
			psql.Arg(s.MerchantName),
		}})
	}

	return exprs
}

// scan.Mapper[*T] without reflection: maps columns to fields by index.
func transactionScanMapper(ctx context.Context, cols []string) (scan.BeforeFunc, func(any) (*Transaction, error)) {
	// resolve the column positions once per query, not per row
	type target struct {
		idx int
		dst func(o *Transaction) any
	}
	targets := make([]target, 0, 8)
	for i, col := range cols {
		switch col {
		case "id":
			targets = append(targets, target{i, func(o *Transaction) any { return &o.ID }})
		case "account_id":
			targets = append(targets, target{i, func(o *Transaction) any { return &o.AccountID }})
		case "category_id":
			targets = append(targets, target{i, func(o *Transaction) any { return &o.CategoryID }})
		case "amount":
			targets = append(targets, target{i, func(o *Transaction) any { return &o.Amount }})
		case "transaction_name":
			targets = append(targets, target{i, func(o *Transaction) any { return &o.TransactionName }})
		case "transaction_date":
			targets = append(targets, target{i, func(o *Transaction) any { return &o.TransactionDate }})
		case "created_at":
			targets = append(targets, target{i, func(o *Transaction) any { return &o.CreatedAt }})
		case "merchant_name":
			targets = append(targets, target{i, func(o *Transaction) any { return &o.MerchantName }})
		}
	}

	return func(row *scan.Row) (any, error) {
			o := new(Transaction)
			for _, t := range targets {
				row.ScheduleScanByIndex(t.idx, t.dst(o))
			}
			return o, nil
		}, func(v any) (*Transaction, error) {
			return v.(*Transaction), nil
		}
}

// FindTransaction retrieves a single record by primary key
// If cols is empty Find will return all columns.
func FindTransaction(ctx context.Context, exec bob.Executor, IDPK uuid.UUID, cols ...string) (*Transaction, error) {
	if len(cols) == 0 {
		return Transactions.Query(
			sm.Where(Transactions.Columns.ID.EQ(psql.Arg(IDPK))),
		).One(ctx, exec)
	}

	return Transactions.Query(
		sm.Where(Transactions.Columns.ID.EQ(psql.Arg(IDPK))),
		sm.Columns(Transactions.Columns.Only(cols...)),
	).One(ctx, exec)
}

// TransactionExists checks the presence of a single record by primary key
func TransactionExists(ctx context.Context, exec bob.Executor, IDPK uuid.UUID) (bool, error) {
	return Transactions.Query(
		sm.Where(Transactions.Columns.ID.EQ(psql.Arg(IDPK))),
	).Exists(ctx, exec)
}

// AfterQueryHook is called after Transaction is retrieved from the database
func (o *Transaction) AfterQueryHook(ctx context.Context, exec bob.Executor, queryType bob.QueryType) error {
	var err error

	switch queryType {
	case bob.QueryTypeSelect:
		ctx, err = Transactions.AfterSelectHooks.RunHooks(ctx, exec, TransactionSlice{o})
	case bob.QueryTypeInsert:
		ctx, err = Transactions.AfterInsertHooks.RunHooks(ctx, exec, TransactionSlice{o})
	case bob.QueryTypeUpdate:
		ctx, err = Transactions.AfterUpdateHooks.RunHooks(ctx, exec, TransactionSlice{o})
	case bob.QueryTypeDelete:
		ctx, err = Transactions.AfterDeleteHooks.RunHooks(ctx, exec, TransactionSlice{o})
	case bob.QueryTypeMerge:
		ctx, err = Transactions.AfterMergeHooks.RunHooks(ctx, exec, TransactionSlice{o})
	}

	return err
}

// primaryKeyVals returns the primary key values of the Transaction
func (o *Transaction) primaryKeyVals() bob.Expression {
	return psql.Arg(o.ID)
}

func (o *Transaction) pkEQ() dialect.Expression {
	return psql.Quote("transactions", "id").EQ(bob.ExpressionFunc(func(ctx context.Context, w io.StringWriter, d bob.Dialect, start int) ([]any, error) {
		return o.primaryKeyVals().WriteSQL(ctx, w, d, start)
	}))
}

// Update uses an executor to update the Transaction
func (o *Transaction) Update(ctx context.Context, exec bob.Executor, s *TransactionSetter) error {
	v, err := Transactions.Update(s.UpdateMod(), um.Where(o.pkEQ())).One(ctx, exec)
	if err != nil {
		return err
	}

	o.R = v.R
	*o = *v

	return nil
}

// Delete deletes a single Transaction record with an executor
func (o *Transaction) Delete(ctx context.Context, exec bob.Executor) error {
	_, err := Transactions.Delete(dm.Where(o.pkEQ())).Exec(ctx, exec)
	return err
}

// Reload refreshes the Transaction using the executor
func (o *Transaction) Reload(ctx context.Context, exec bob.Executor) error {
	o2, err := Transactions.Query(
		sm.Where(Transactions.Columns.ID.EQ(psql.Arg(o.ID))),
	).One(ctx, exec)
	if err != nil {
		return err
	}
	o2.R = o.R
	*o = *o2

	return nil
}

// AfterQueryHook is called after TransactionSlice is retrieved from the database
func (o TransactionSlice) AfterQueryHook(ctx context.Context, exec bob.Executor, queryType bob.QueryType) error {
	var err error

	switch queryType {
	case bob.QueryTypeSelect:
		ctx, err = Transactions.AfterSelectHooks.RunHooks(ctx, exec, o)
	case bob.QueryTypeInsert:
		ctx, err = Transactions.AfterInsertHooks.RunHooks(ctx, exec, o)
	case bob.QueryTypeUpdate:
		ctx, err = Transactions.AfterUpdateHooks.RunHooks(ctx, exec, o)
	case bob.QueryTypeDelete:
		ctx, err = Transactions.AfterDeleteHooks.RunHooks(ctx, exec, o)
	case bob.QueryTypeMerge:
		ctx, err = Transactions.AfterMergeHooks.RunHooks(ctx, exec, o)
	}

	return err
}

func (o TransactionSlice) pkIN() dialect.Expression {
	if len(o) == 0 {
		return psql.Raw("NULL")
	}

	return psql.Quote("transactions", "id").In(bob.ExpressionFunc(func(ctx context.Context, w io.StringWriter, d bob.Dialect, start int) ([]any, error) {
		pkPairs := make([]bob.Expression, len(o))
		for i, row := range o {
			pkPairs[i] = row.primaryKeyVals()
		}
		return bob.ExpressSlice(ctx, w, d, start, pkPairs, "", ", ", "")
	}))
}

// copyMatchingRows finds models in the given slice that have the same primary key
// then it first copies the existing relationships from the old model to the new model
// and then replaces the old model in the slice with the new model
func (o TransactionSlice) copyMatchingRows(from ...*Transaction) {
	fromByPK := make(map[uuid.UUID]*Transaction, len(from))
	for _, new := range from {
		// keep the first row for each key, like the nested loop did
		if _, ok := fromByPK[new.ID]; !ok {
			fromByPK[new.ID] = new
		}
	}

	for i, old := range o {
		new, ok := fromByPK[old.ID]
		if !ok {
			continue
		}
		new.R = old.R
		o[i] = new
	}
}

// UpdateMod modifies an update query with "WHERE primary_key IN (o...)"
func (o TransactionSlice) UpdateMod() bob.Mod[*dialect.UpdateQuery] {
	return bob.ModFunc[*dialect.UpdateQuery](func(q *dialect.UpdateQuery) {
		q.AppendHooks(func(ctx context.Context, exec bob.Executor) (context.Context, error) {
			return Transactions.BeforeUpdateHooks.RunHooks(ctx, exec, o)
		})

		q.AppendLoader(bob.LoaderFunc(func(ctx context.Context, exec bob.Executor, retrieved any) error {
			var err error
			switch retrieved := retrieved.(type) {
			case *Transaction:
				o.copyMatchingRows(retrieved)
			case []*Transaction:
				o.copyMatchingRows(retrieved...)
			case TransactionSlice:
				o.copyMatchingRows(retrieved...)
			default:
				// If the retrieved value is not a Transaction or a slice of Transaction
				// then run the AfterUpdateHooks on the slice
				_, err = Transactions.AfterUpdateHooks.RunHooks(ctx, exec, o)
			}

			return err
		}))

		q.AppendWhere(o.pkIN())
	})
}

// DeleteMod modifies an delete query with "WHERE primary_key IN (o...)"
func (o TransactionSlice) DeleteMod() bob.Mod[*dialect.DeleteQuery] {
	return bob.ModFunc[*dialect.DeleteQuery](func(q *dialect.DeleteQuery) {
		q.AppendHooks(func(ctx context.Context, exec bob.Executor) (context.Context, error) {
			return Transactions.BeforeDeleteHooks.RunHooks(ctx, exec, o)
		})

		q.AppendLoader(bob.LoaderFunc(func(ctx context.Context, exec bob.Executor, retrieved any) error {
			var err error
			switch retrieved := retrieved.(type) {
			case *Transaction:
				o.copyMatchingRows(retrieved)
			case []*Transaction:
				o.copyMatchingRows(retrieved...)
			case TransactionSlice:
				o.copyMatchingRows(retrieved...)
			default:
				// If the retrieved value is not a Transaction or a slice of Transaction
				// then run the AfterDeleteHooks on the slice
				_, err = Transactions.AfterDeleteHooks.RunHooks(ctx, exec, o)
			}

			return err
		}))

		q.AppendWhere(o.pkIN())
	})
}

// MergeMod modifies a merge query to run BeforeMergeHooks and AfterMergeHooks
// and updates the slice with the returned rows.
func (o TransactionSlice) MergeMod() bob.Mod[*dialect.MergeQuery] {
	return bob.ModFunc[*dialect.MergeQuery](func(q *dialect.MergeQuery) {
		q.AppendHooks(func(ctx context.Context, exec bob.Executor) (context.Context, error) {
			return Transactions.BeforeMergeHooks.RunHooks(ctx, exec, o)
		})

		q.AppendLoader(bob.LoaderFunc(func(ctx context.Context, exec bob.Executor, retrieved any) error {
			var err error
			switch retrieved := retrieved.(type) {
			case *Transaction:
				o.copyMatchingRows(retrieved)
			case []*Transaction:
				o.copyMatchingRows(retrieved...)
			case TransactionSlice:
				o.copyMatchingRows(retrieved...)
			default:
				// If the retrieved value is not a Transaction or a slice of Transaction
				// then run the AfterMergeHooks on the slice
				_, err = Transactions.AfterMergeHooks.RunHooks(ctx, exec, o)
			}

			return err
		}))
	})
}

func (o TransactionSlice) UpdateAll(ctx context.Context, exec bob.Executor, vals TransactionSetter) error {
	if len(o) == 0 {
		return nil
	}

	_, err := Transactions.Update(vals.UpdateMod(), o.UpdateMod()).All(ctx, exec)
	return err
}

func (o TransactionSlice) DeleteAll(ctx context.Context, exec bob.Executor) error {
	if len(o) == 0 {
		return nil
	}

	_, err := Transactions.Delete(o.DeleteMod()).Exec(ctx, exec)
	return err
}

func (o TransactionSlice) ReloadAll(ctx context.Context, exec bob.Executor) error {
	if len(o) == 0 {
		return nil
	}

	o2, err := Transactions.Query(sm.Where(o.pkIN())).All(ctx, exec)
	if err != nil {
		return err
	}

	o.copyMatchingRows(o2...)

	return nil
}

// PlaidTransactionLinks starts a query for related objects on plaid_transaction_links
func (o *Transaction) PlaidTransactionLinks(mods ...bob.Mod[*dialect.SelectQuery]) PlaidTransactionLinksQuery {
	return PlaidTransactionLinks.Query(append(mods,
		sm.Where(PlaidTransactionLinks.Columns.TransactionID.EQ(psql.Arg(o.ID))),
	)...)
}

func (os TransactionSlice) PlaidTransactionLinks(mods ...bob.Mod[*dialect.SelectQuery]) PlaidTransactionLinksQuery {
	pkID := make(pgtypes.Array[uuid.UUID], 0, len(os))

	for _, o := range os {
		if o == nil {
			continue
		}
		pkID = append(pkID, o.ID)
	}
	PKArgExpr := psql.Any(psql.Cast(psql.Arg(pkID), "uuid[]"))

	return PlaidTransactionLinks.Query(append(mods,
		sm.Where(PlaidTransactionLinks.Columns.TransactionID.EQ(PKArgExpr)),
	)...)
}

// Account starts a query for related objects on accounts
func (o *Transaction) Account(mods ...bob.Mod[*dialect.SelectQuery]) AccountsQuery {
	return Accounts.Query(append(mods,
		sm.Where(Accounts.Columns.ID.EQ(psql.Arg(o.AccountID))),
	)...)
}

func (os TransactionSlice) Account(mods ...bob.Mod[*dialect.SelectQuery]) AccountsQuery {
	pkAccountID := make(pgtypes.Array[uuid.UUID], 0, len(os))

	// the array is only a filter (semi-join), so duplicate keys can be
	// dropped before they are sent over the wire
	seenAccountID := make(map[uuid.UUID]struct{}, len(os))
	for _, o := range os {
		if o == nil {
			continue
		}
		if _, ok := seenAccountID[o.AccountID]; ok {
			continue
		}
		seenAccountID[o.AccountID] = struct{}{}
		pkAccountID = append(pkAccountID, o.AccountID)
	}
	PKArgExpr := psql.Any(psql.Cast(psql.Arg(pkAccountID), "uuid[]"))

	return Accounts.Query(append(mods,
		sm.Where(Accounts.Columns.ID.EQ(PKArgExpr)),
	)...)
}

// Category starts a query for related objects on categories
func (o *Transaction) Category(mods ...bob.Mod[*dialect.SelectQuery]) CategoriesQuery {
	return Categories.Query(append(mods,
		sm.Where(Categories.Columns.ID.EQ(psql.Arg(o.CategoryID))),
	)...)
}

func (os TransactionSlice) Category(mods ...bob.Mod[*dialect.SelectQuery]) CategoriesQuery {
	pkCategoryID := make(pgtypes.Array[null.Val[uuid.UUID]], 0, len(os))

	// the array is only a filter (semi-join), so duplicate keys can be
	// dropped before they are sent over the wire
	seenCategoryID := make(map[null.Val[uuid.UUID]]struct{}, len(os))
	for _, o := range os {
		if o == nil {
			continue
		}
		if _, ok := seenCategoryID[o.CategoryID]; ok {
			continue
		}
		seenCategoryID[o.CategoryID] = struct{}{}
		pkCategoryID = append(pkCategoryID, o.CategoryID)
	}
	PKArgExpr := psql.Any(psql.Cast(psql.Arg(pkCategoryID), "uuid[]"))

	return Categories.Query(append(mods,
		sm.Where(Categories.Columns.ID.EQ(PKArgExpr)),
	)...)
}

func insertTransactionPlaidTransactionLinks0(ctx context.Context, exec bob.Executor, plaidTransactionLinks1 []*PlaidTransactionLinkSetter, transaction0 *Transaction) (PlaidTransactionLinkSlice, error) {
	for i := range plaidTransactionLinks1 {
		plaidTransactionLinks1[i].TransactionID = omit.From(transaction0.ID)
	}

	ret, err := PlaidTransactionLinks.Insert(bob.ToMods(plaidTransactionLinks1...)).All(ctx, exec)
	if err != nil {
		return ret, fmt.Errorf("insertTransactionPlaidTransactionLinks0: %w", err)
	}

	return ret, nil
}

func attachTransactionPlaidTransactionLinks0(ctx context.Context, exec bob.Executor, count int, plaidTransactionLinks1 PlaidTransactionLinkSlice, transaction0 *Transaction) (PlaidTransactionLinkSlice, error) {
	setter := &PlaidTransactionLinkSetter{
		TransactionID: omit.From(transaction0.ID),
	}

	err := plaidTransactionLinks1.UpdateAll(ctx, exec, *setter)
	if err != nil {
		return nil, fmt.Errorf("attachTransactionPlaidTransactionLinks0: %w", err)
	}

	return plaidTransactionLinks1, nil
}

func (transaction0 *Transaction) InsertPlaidTransactionLinks(ctx context.Context, exec bob.Executor, related ...*PlaidTransactionLinkSetter) error {
	if len(related) == 0 {
		return nil
	}

	var err error

	plaidTransactionLinks1, err := insertTransactionPlaidTransactionLinks0(ctx, exec, related, transaction0)
	if err != nil {
		return err
	}

	transaction0.R.PlaidTransactionLinks = append(transaction0.R.PlaidTransactionLinks, plaidTransactionLinks1...)

	for _, rel := range plaidTransactionLinks1 {
		rel.R.Transaction = transaction0
		rel.R.Loaded.Transaction = true
	}
	return nil
}

func (transaction0 *Transaction) AttachPlaidTransactionLinks(ctx context.Context, exec bob.Executor, related ...*PlaidTransactionLink) error {
	if len(related) == 0 {
		return nil
	}

	var err error
	plaidTransactionLinks1 := PlaidTransactionLinkSlice(related)

	_, err = attachTransactionPlaidTransactionLinks0(ctx, exec, len(related), plaidTransactionLinks1, transaction0)
	if err != nil {
		return err
	}

	transaction0.R.PlaidTransactionLinks = append(transaction0.R.PlaidTransactionLinks, plaidTransactionLinks1...)

	for _, rel := range related {
		rel.R.Transaction = transaction0
		rel.R.Loaded.Transaction = true
	}

	return nil
}

func attachTransactionAccount0(ctx context.Context, exec bob.Executor, count int, transaction0 *Transaction, account1 *Account) (*Transaction, error) {
	setter := &TransactionSetter{
		AccountID: omit.From(account1.ID),
	}

	err := transaction0.Update(ctx, exec, setter)
	if err != nil {
		return nil, fmt.Errorf("attachTransactionAccount0: %w", err)
	}

	return transaction0, nil
}

func (transaction0 *Transaction) InsertAccount(ctx context.Context, exec bob.Executor, related *AccountSetter) error {
	var err error

	account1, err := Accounts.Insert(related).One(ctx, exec)
	if err != nil {
		return fmt.Errorf("inserting related objects: %w", err)
	}

	_, err = attachTransactionAccount0(ctx, exec, 1, transaction0, account1)
	if err != nil {
		return err
	}

	transaction0.R.Account = account1
	transaction0.R.Loaded.Account = true

	account1.R.Transactions = append(account1.R.Transactions, transaction0)

	return nil
}

func (transaction0 *Transaction) AttachAccount(ctx context.Context, exec bob.Executor, account1 *Account) error {
	var err error

	_, err = attachTransactionAccount0(ctx, exec, 1, transaction0, account1)
	if err != nil {
		return err
	}

	transaction0.R.Account = account1
	transaction0.R.Loaded.Account = true

	account1.R.Transactions = append(account1.R.Transactions, transaction0)

	return nil
}

func attachTransactionCategory0(ctx context.Context, exec bob.Executor, count int, transaction0 *Transaction, category1 *Category) (*Transaction, error) {
	setter := &TransactionSetter{
		CategoryID: omitnull.From(category1.ID),
	}

	err := transaction0.Update(ctx, exec, setter)
	if err != nil {
		return nil, fmt.Errorf("attachTransactionCategory0: %w", err)
	}

	return transaction0, nil
}

func (transaction0 *Transaction) InsertCategory(ctx context.Context, exec bob.Executor, related *CategorySetter) error {
	var err error

	category1, err := Categories.Insert(related).One(ctx, exec)
	if err != nil {
		return fmt.Errorf("inserting related objects: %w", err)
	}

	_, err = attachTransactionCategory0(ctx, exec, 1, transaction0, category1)
	if err != nil {
		return err
	}

	transaction0.R.Category = category1
	transaction0.R.Loaded.Category = true

	category1.R.Transactions = append(category1.R.Transactions, transaction0)

	return nil
}

func (transaction0 *Transaction) AttachCategory(ctx context.Context, exec bob.Executor, category1 *Category) error {
	var err error

	_, err = attachTransactionCategory0(ctx, exec, 1, transaction0, category1)
	if err != nil {
		return err
	}

	transaction0.R.Category = category1
	transaction0.R.Loaded.Category = true

	category1.R.Transactions = append(category1.R.Transactions, transaction0)

	return nil
}

type transactionWhere[Q psql.Filterable] struct {
	cols            transactionColumns
	ID              psql.WhereMod[Q, uuid.UUID]
	AccountID       psql.WhereMod[Q, uuid.UUID]
	CategoryID      psql.WhereNullMod[Q, uuid.UUID]
	Amount          psql.WhereMod[Q, decimal.Decimal]
	TransactionName psql.WhereMod[Q, string]
	TransactionDate psql.WhereMod[Q, time.Time]
	CreatedAt       psql.WhereMod[Q, time.Time]
	MerchantName    psql.WhereNullMod[Q, string]
	R               transactionWhereR[Q]
}

func (transactionWhere[Q]) AliasedAs(alias string) transactionWhere[Q] {
	return buildTransactionWhere[Q](buildTransactionColumns(alias))
}

func buildTransactionWhere[Q psql.Filterable](cols transactionColumns) transactionWhere[Q] {
	return transactionWhere[Q]{
		cols:            cols,
		ID:              psql.Where[Q, uuid.UUID](cols.ID.Expression),
		AccountID:       psql.Where[Q, uuid.UUID](cols.AccountID.Expression),
		CategoryID:      psql.WhereNull[Q, uuid.UUID](cols.CategoryID.Expression),
		Amount:          psql.Where[Q, decimal.Decimal](cols.Amount.Expression),
		TransactionName: psql.Where[Q, string](cols.TransactionName.Expression),
		TransactionDate: psql.Where[Q, time.Time](cols.TransactionDate.Expression),
		CreatedAt:       psql.Where[Q, time.Time](cols.CreatedAt.Expression),
		MerchantName:    psql.WhereNull[Q, string](cols.MerchantName.Expression),
		R:               transactionWhereR[Q]{cols: cols},
	}
}

// transactionWhereR holds the relationship-based filters of
// transactionWhere under the R namespace — mirroring the model's
// R struct — so they cannot collide with column-based filter fields.
type transactionWhereR[Q psql.Filterable] struct {
	cols transactionColumns
}

// HasPlaidTransactionLinks filters parents that have a matching PlaidTransactionLinks using a
// correlated EXISTS subquery (semi-join). Unlike an INNER JOIN it does not
// multiply parent rows, so no DISTINCT is needed. The optional filters are
// applied to the subquery (i.e. to PlaidTransactionLinks).
func (w transactionWhereR[Q]) HasPlaidTransactionLinks(filters ...bob.Mod[*dialect.SelectQuery]) mods.Where[Q] {
	q := psql.Select(
		sm.Columns(psql.Raw("1")),
		sm.From(PlaidTransactionLinks.NameExpr()),
		sm.Where(PlaidTransactionLinks.Columns.TransactionID.EQ(w.cols.ID)),
	)
	q.Apply(filters...)
	return mods.Where[Q]{E: psql.Exists(q)}
}

// HasAccount filters parents that have a matching Account using a
// correlated EXISTS subquery (semi-join). Unlike an INNER JOIN it does not
// multiply parent rows, so no DISTINCT is needed. The optional filters are
// applied to the subquery (i.e. to Accounts).
func (w transactionWhereR[Q]) HasAccount(filters ...bob.Mod[*dialect.SelectQuery]) mods.Where[Q] {
	q := psql.Select(
		sm.Columns(psql.Raw("1")),
		sm.From(Accounts.NameExpr()),
		sm.Where(Accounts.Columns.ID.EQ(w.cols.AccountID)),
	)
	q.Apply(filters...)
	return mods.Where[Q]{E: psql.Exists(q)}
}

// HasCategory filters parents that have a matching Category using a
// correlated EXISTS subquery (semi-join). Unlike an INNER JOIN it does not
// multiply parent rows, so no DISTINCT is needed. The optional filters are
// applied to the subquery (i.e. to Categories).
func (w transactionWhereR[Q]) HasCategory(filters ...bob.Mod[*dialect.SelectQuery]) mods.Where[Q] {
	q := psql.Select(
		sm.Columns(psql.Raw("1")),
		sm.From(Categories.NameExpr()),
		sm.Where(Categories.Columns.ID.EQ(w.cols.CategoryID)),
	)
	q.Apply(filters...)
	return mods.Where[Q]{E: psql.Exists(q)}
}

// NULL-tolerant scan buffer for transactionScanMapperNullable:
// on a LEFT JOIN miss every column comes back NULL, so each field uses the
// nullable version of the column type even when the column itself is NOT NULL.
type transactionPreloadBuf struct {
	ID              null.Val[uuid.UUID]
	AccountID       null.Val[uuid.UUID]
	CategoryID      null.Val[uuid.UUID]
	Amount          null.Val[decimal.Decimal]
	TransactionName null.Val[string]
	TransactionDate null.Val[time.Time]
	CreatedAt       null.Val[time.Time]
	MerchantName    null.Val[string]
}

// transactionScanMapperNullable maps the preloaded transaction
// columns (prefixed with the runtime join alias) without reflection, while
// keeping the LEFT JOIN semantics of the reflection-based mapper: a row whose
// prefixed columns are all NULL yields nil (no child), and NULL values never
// error, they just leave the zero value in the field.
func transactionScanMapperNullable(prefix string) scan.Mapper[*Transaction] {
	return func(ctx context.Context, cols []string) (scan.BeforeFunc, func(any) (*Transaction, error)) {
		// resolve the column names once per query, not per row
		type target struct {
			idx int
			dst func(b *transactionPreloadBuf) any
		}
		targets := make([]target, 0, 8)
		for i, col := range cols {
			name, ok := strings.CutPrefix(col, prefix)
			if !ok {
				continue
			}
			switch name {
			case "id":
				targets = append(targets, target{i, func(b *transactionPreloadBuf) any { return &b.ID }})
			case "account_id":
				targets = append(targets, target{i, func(b *transactionPreloadBuf) any { return &b.AccountID }})
			case "category_id":
				targets = append(targets, target{i, func(b *transactionPreloadBuf) any { return &b.CategoryID }})
			case "amount":
				targets = append(targets, target{i, func(b *transactionPreloadBuf) any { return &b.Amount }})
			case "transaction_name":
				targets = append(targets, target{i, func(b *transactionPreloadBuf) any { return &b.TransactionName }})
			case "transaction_date":
				targets = append(targets, target{i, func(b *transactionPreloadBuf) any { return &b.TransactionDate }})
			case "created_at":
				targets = append(targets, target{i, func(b *transactionPreloadBuf) any { return &b.CreatedAt }})
			case "merchant_name":
				targets = append(targets, target{i, func(b *transactionPreloadBuf) any { return &b.MerchantName }})
			}
		}

		// One scratch buffer reused for every row: before -> scan -> after runs
		// synchronously per row, the scheduled columns are fully overwritten each
		// row, and unselected columns stay zero, so a single buffer preserves the
		// per-row NULL semantics without allocating a buffer per parent row. The
		// returned child (o below) is always freshly allocated, so buf never
		// escapes past the after func.
		buf := new(transactionPreloadBuf)
		return func(row *scan.Row) (any, error) {
				for _, t := range targets {
					row.ScheduleScanByIndex(t.idx, t.dst(buf))
				}
				return buf, nil
			}, func(link any) (*Transaction, error) {
				buf := link.(*transactionPreloadBuf)

				// Same rule as the reflection mapper's row validator: the child
				// exists only if at least one of its columns is not NULL. Columns
				// not selected by the query are never scanned and stay invalid,
				// so this check also matches when only a subset is selected.
				if !(buf.ID.IsValue()) &&
					!(buf.AccountID.IsValue()) &&
					!(buf.CategoryID.IsValue()) &&
					!(buf.Amount.IsValue()) &&
					!(buf.TransactionName.IsValue()) &&
					!(buf.TransactionDate.IsValue()) &&
					!(buf.CreatedAt.IsValue()) &&
					!(buf.MerchantName.IsValue()) {
					return nil, nil
				}

				o := new(Transaction)
				if buf.ID.IsValue() {
					o.ID = buf.ID.MustGet()
				}
				if buf.AccountID.IsValue() {
					o.AccountID = buf.AccountID.MustGet()
				}
				o.CategoryID = buf.CategoryID
				if buf.Amount.IsValue() {
					o.Amount = buf.Amount.MustGet()
				}
				if buf.TransactionName.IsValue() {
					o.TransactionName = buf.TransactionName.MustGet()
				}
				if buf.TransactionDate.IsValue() {
					o.TransactionDate = buf.TransactionDate.MustGet()
				}
				if buf.CreatedAt.IsValue() {
					o.CreatedAt = buf.CreatedAt.MustGet()
				}
				o.MerchantName = buf.MerchantName
				return o, nil
			}
	}
}

func (o *Transaction) Preload(name string, retrieved any) error {
	if o == nil {
		return nil
	}

	switch name {
	case "PlaidTransactionLinks":
		rels, ok := retrieved.(PlaidTransactionLinkSlice)
		if !ok {
			return fmt.Errorf("transaction cannot load %T as %q", retrieved, name)
		}

		o.R.PlaidTransactionLinks = rels
		o.R.Loaded.PlaidTransactionLinks = true

		for _, rel := range rels {
			if rel != nil {
				rel.R.Transaction = o
				rel.R.Loaded.Transaction = true
			}
		}
		return nil
	case "Account":
		rel, ok := retrieved.(*Account)
		if !ok {
			return fmt.Errorf("transaction cannot load %T as %q", retrieved, name)
		}

		o.R.Account = rel
		o.R.Loaded.Account = true

		if rel != nil {
			rel.R.Transactions = TransactionSlice{o}
		}
		return nil
	case "Category":
		rel, ok := retrieved.(*Category)
		if !ok {
			return fmt.Errorf("transaction cannot load %T as %q", retrieved, name)
		}

		o.R.Category = rel
		o.R.Loaded.Category = true

		if rel != nil {
			rel.R.Transactions = TransactionSlice{o}
		}
		return nil
	default:
		return fmt.Errorf("transaction has no relationship %q", name)
	}
}

type transactionPreloader struct {
	Account  func(...psql.PreloadOption) psql.Preloader
	Category func(...psql.PreloadOption) psql.Preloader
}

func buildTransactionPreloader() transactionPreloader {
	return transactionPreloader{
		Account: func(opts ...psql.PreloadOption) psql.Preloader {
			return psql.Preload[*Account, AccountSlice](psql.PreloadRel{
				Name: "Account",
				Sides: []psql.PreloadSide{
					{
						From:        Transactions,
						To:          Accounts,
						FromColumns: []string{"account_id"},
						ToColumns:   []string{"id"},
					},
				},
			}, Accounts.Columns.Names(), accountScanMapperNullable, opts...)
		},
		Category: func(opts ...psql.PreloadOption) psql.Preloader {
			return psql.Preload[*Category, CategorySlice](psql.PreloadRel{
				Name: "Category",
				Sides: []psql.PreloadSide{
					{
						From:        Transactions,
						To:          Categories,
						FromColumns: []string{"category_id"},
						ToColumns:   []string{"id"},
					},
				},
			}, Categories.Columns.Names(), categoryScanMapperNullable, opts...)
		},
	}
}

type transactionThenLoader[Q orm.Loadable] struct {
	PlaidTransactionLinks func(...bob.Mod[*dialect.SelectQuery]) orm.Loader[Q]
	Account               func(...bob.Mod[*dialect.SelectQuery]) orm.Loader[Q]
	Category              func(...bob.Mod[*dialect.SelectQuery]) orm.Loader[Q]
}

func buildTransactionThenLoader[Q orm.Loadable]() transactionThenLoader[Q] {
	type PlaidTransactionLinksLoadInterface interface {
		LoadPlaidTransactionLinks(context.Context, bob.Executor, ...bob.Mod[*dialect.SelectQuery]) error
	}
	type AccountLoadInterface interface {
		LoadAccount(context.Context, bob.Executor, ...bob.Mod[*dialect.SelectQuery]) error
	}
	type CategoryLoadInterface interface {
		LoadCategory(context.Context, bob.Executor, ...bob.Mod[*dialect.SelectQuery]) error
	}

	return transactionThenLoader[Q]{
		PlaidTransactionLinks: thenLoadBuilder[Q](
			"PlaidTransactionLinks",
			func(ctx context.Context, exec bob.Executor, retrieved PlaidTransactionLinksLoadInterface, mods ...bob.Mod[*dialect.SelectQuery]) error {
				return retrieved.LoadPlaidTransactionLinks(ctx, exec, mods...)
			},
		),
		Account: thenLoadBuilder[Q](
			"Account",
			func(ctx context.Context, exec bob.Executor, retrieved AccountLoadInterface, mods ...bob.Mod[*dialect.SelectQuery]) error {
				return retrieved.LoadAccount(ctx, exec, mods...)
			},
		),
		Category: thenLoadBuilder[Q](
			"Category",
			func(ctx context.Context, exec bob.Executor, retrieved CategoryLoadInterface, mods ...bob.Mod[*dialect.SelectQuery]) error {
				return retrieved.LoadCategory(ctx, exec, mods...)
			},
		),
	}
}

// LoadPlaidTransactionLinks loads the transaction's PlaidTransactionLinks into the .R struct
func (o *Transaction) LoadPlaidTransactionLinks(ctx context.Context, exec bob.Executor, mods ...bob.Mod[*dialect.SelectQuery]) error {
	if o == nil {
		return nil
	}

	// Reset the relationship
	o.R.PlaidTransactionLinks = nil
	o.R.Loaded.PlaidTransactionLinks = false

	related, err := o.PlaidTransactionLinks(mods...).All(ctx, exec)
	if err != nil {
		return err
	}

	for _, rel := range related {
		rel.R.Transaction = o
		rel.R.Loaded.Transaction = true
	}

	o.R.PlaidTransactionLinks = related
	o.R.Loaded.PlaidTransactionLinks = true
	return nil
}

// LoadPlaidTransactionLinks loads the transaction's PlaidTransactionLinks into the .R struct
func (os TransactionSlice) LoadPlaidTransactionLinks(ctx context.Context, exec bob.Executor, mods ...bob.Mod[*dialect.SelectQuery]) error {
	if len(os) == 0 {
		return nil
	}

	plaidTransactionLinks, err := os.PlaidTransactionLinks(mods...).All(ctx, exec)
	if err != nil {
		return err
	}

	for _, o := range os {
		if o == nil {
			continue
		}

		o.R.PlaidTransactionLinks = nil
		o.R.Loaded.PlaidTransactionLinks = true
	}
	// O(N+M) stitch via a map keyed by the join column (key -> []parent; was O(N*M)).
	transactionByKey := make(map[uuid.UUID][]*Transaction, len(os))
	for _, o := range os {
		if o == nil {
			continue
		}

		transactionByKey[o.ID] = append(transactionByKey[o.ID], o)
	}

	for _, rel := range plaidTransactionLinks {

		owners, ok := transactionByKey[rel.TransactionID]
		if !ok {
			continue
		}

		for _, o := range owners {

			rel.R.Transaction = o
			rel.R.Loaded.Transaction = true

			o.R.PlaidTransactionLinks = append(o.R.PlaidTransactionLinks, rel)

		}
	}

	return nil
}

// LoadAccount loads the transaction's Account into the .R struct
func (o *Transaction) LoadAccount(ctx context.Context, exec bob.Executor, mods ...bob.Mod[*dialect.SelectQuery]) error {
	if o == nil {
		return nil
	}

	// Reset the relationship
	o.R.Account = nil
	o.R.Loaded.Account = false

	related, err := o.Account(mods...).One(ctx, exec)
	if err != nil {
		return err
	}

	related.R.Transactions = TransactionSlice{o}

	o.R.Account = related
	o.R.Loaded.Account = true
	return nil
}

// LoadAccount loads the transaction's Account into the .R struct
func (os TransactionSlice) LoadAccount(ctx context.Context, exec bob.Executor, mods ...bob.Mod[*dialect.SelectQuery]) error {
	if len(os) == 0 {
		return nil
	}

	accounts, err := os.Account(mods...).All(ctx, exec)
	if err != nil {
		return err
	}

	for _, o := range os {
		if o == nil {
			continue
		}

		o.R.Account = nil
		o.R.Loaded.Account = true
	}
	// O(N+M) stitch via a map keyed by the join column (key -> []parent; was O(N*M)).
	transactionByKey := make(map[uuid.UUID][]*Transaction, len(os))
	for _, o := range os {
		if o == nil {
			continue
		}

		transactionByKey[o.AccountID] = append(transactionByKey[o.AccountID], o)
	}

	for _, rel := range accounts {

		owners, ok := transactionByKey[rel.ID]
		if !ok {
			continue
		}

		for _, o := range owners {

			// to-one: keep only the first matching child (matches the previous break)
			if o.R.Account != nil {
				continue
			}

			rel.R.Transactions = append(rel.R.Transactions, o)

			o.R.Account = rel

		}
	}

	return nil
}

// LoadCategory loads the transaction's Category into the .R struct
func (o *Transaction) LoadCategory(ctx context.Context, exec bob.Executor, mods ...bob.Mod[*dialect.SelectQuery]) error {
	if o == nil {
		return nil
	}

	// Reset the relationship
	o.R.Category = nil
	o.R.Loaded.Category = false

	related, err := o.Category(mods...).One(ctx, exec)
	if err != nil {
		return err
	}

	related.R.Transactions = TransactionSlice{o}

	o.R.Category = related
	o.R.Loaded.Category = true
	return nil
}

// LoadCategory loads the transaction's Category into the .R struct
func (os TransactionSlice) LoadCategory(ctx context.Context, exec bob.Executor, mods ...bob.Mod[*dialect.SelectQuery]) error {
	if len(os) == 0 {
		return nil
	}

	categories, err := os.Category(mods...).All(ctx, exec)
	if err != nil {
		return err
	}

	for _, o := range os {
		if o == nil {
			continue
		}

		o.R.Category = nil
		o.R.Loaded.Category = true
	}
	// O(N+M) stitch via a map keyed by the join column (key -> []parent; was O(N*M)).
	transactionByKey := make(map[uuid.UUID][]*Transaction, len(os))
	for _, o := range os {
		if o == nil {
			continue
		}

		// NULL never matches any row in SQL, so don't add it to the map
		if !o.CategoryID.IsValue() {
			continue
		}

		transactionByKey[o.CategoryID.MustGet()] = append(transactionByKey[o.CategoryID.MustGet()], o)
	}

	for _, rel := range categories {

		owners, ok := transactionByKey[rel.ID]
		if !ok {
			continue
		}

		for _, o := range owners {

			// to-one: keep only the first matching child (matches the previous break)
			if o.R.Category != nil {
				continue
			}

			rel.R.Transactions = append(rel.R.Transactions, o)

			o.R.Category = rel

		}
	}

	return nil
}

// transactionC is where relationship counts are stored.
type transactionC struct {
	PlaidTransactionLinks *int64
}

// PreloadCount sets a count in the C struct by name
func (o *Transaction) PreloadCount(name string, count int64) error {
	if o == nil {
		return nil
	}

	switch name {
	case "PlaidTransactionLinks":
		o.C.PlaidTransactionLinks = &count
	}
	return nil
}

type transactionCountPreloader struct {
	PlaidTransactionLinks func(...bob.Mod[*dialect.SelectQuery]) psql.Preloader
}

func buildTransactionCountPreloader() transactionCountPreloader {
	return transactionCountPreloader{
		PlaidTransactionLinks: func(mods ...bob.Mod[*dialect.SelectQuery]) psql.Preloader {
			return countPreloader[*Transaction]("PlaidTransactionLinks", func(parent string) bob.Expression {
				// Build a correlated subquery: (SELECT COUNT(*) FROM related WHERE fk = parent.pk)
				if parent == "" {
					parent = Transactions.Alias()
				}

				subqueryMods := []bob.Mod[*dialect.SelectQuery]{
					sm.Columns(psql.Raw("count(*)")),

					sm.From(PlaidTransactionLinks.NameAsExpr()),
					sm.Where(psql.Quote(PlaidTransactionLinks.Alias(), "transaction_id").EQ(psql.Quote(parent, "id"))),
				}
				subqueryMods = append(subqueryMods, mods...)
				return psql.Group(psql.Select(subqueryMods...).Expression)
			})
		},
	}
}

type transactionCountThenLoader[Q orm.Loadable] struct {
	PlaidTransactionLinks func(...bob.Mod[*dialect.SelectQuery]) orm.Loader[Q]
}

func buildTransactionCountThenLoader[Q orm.Loadable]() transactionCountThenLoader[Q] {
	type PlaidTransactionLinksCountInterface interface {
		LoadCountPlaidTransactionLinks(context.Context, bob.Executor, ...bob.Mod[*dialect.SelectQuery]) error
	}

	return transactionCountThenLoader[Q]{
		PlaidTransactionLinks: countThenLoadBuilder[Q](
			"PlaidTransactionLinks",
			func(ctx context.Context, exec bob.Executor, retrieved PlaidTransactionLinksCountInterface, mods ...bob.Mod[*dialect.SelectQuery]) error {
				return retrieved.LoadCountPlaidTransactionLinks(ctx, exec, mods...)
			},
		),
	}
}

// LoadCountPlaidTransactionLinks loads the count of PlaidTransactionLinks into the C struct
func (o *Transaction) LoadCountPlaidTransactionLinks(ctx context.Context, exec bob.Executor, mods ...bob.Mod[*dialect.SelectQuery]) error {
	if o == nil {
		return nil
	}

	count, err := o.PlaidTransactionLinks(mods...).Count(ctx, exec)
	if err != nil {
		return err
	}

	o.C.PlaidTransactionLinks = &count
	return nil
}

// LoadCountPlaidTransactionLinks loads the count of PlaidTransactionLinks for a slice in a single batch query
func (os TransactionSlice) LoadCountPlaidTransactionLinks(ctx context.Context, exec bob.Executor, mods ...bob.Mod[*dialect.SelectQuery]) error {
	if len(os) == 0 {
		return nil
	}

	// Build the IN arg expression from parent PKs

	pkID := make(pgtypes.Array[uuid.UUID], 0, len(os))
	for _, o := range os {
		if o == nil {
			continue
		}
		pkID = append(pkID, o.ID)
	}
	PKArgExpr := psql.Any(psql.Cast(psql.Arg(pkID), "uuid[]"))

	// countResult holds one scanned row from the batch count query.
	// FK columns are aliased to the parent PK column names for direct map lookup.
	type countResult struct {
		ID    uuid.UUID
		Count int64
	}

	batchMods := []bob.Mod[*dialect.SelectQuery]{
		// SELECT fk AS parent_pk, count(*)
		sm.Columns(
			PlaidTransactionLinks.Columns.TransactionID.As("id"),
			psql.Raw("count(*) as count"),
		),
		// Single-hop: FROM related table directly
		sm.From(PlaidTransactionLinks.NameAsExpr()),

		// WHERE fk IN (parent PKs) — psql single-column FK uses `= ANY(array)` (see PKArgExpr above)
		sm.Where(PlaidTransactionLinks.Columns.TransactionID.EQ(PKArgExpr)),
		// GROUP BY fk columns
		sm.GroupBy(PlaidTransactionLinks.Columns.TransactionID),
	}
	batchMods = append(batchMods, mods...)

	results, err := bob.All(ctx, exec,
		psql.Select(batchMods...),
		scan.StructMapper[countResult](),
	)
	if err != nil {
		return err
	}

	// Single-column FK: direct map lookup
	countMap := make(map[uuid.UUID]int64, len(results))
	for _, r := range results {
		countMap[r.ID] = r.Count
	}
	for _, o := range os {
		if o == nil {
			continue
		}
		count := countMap[o.ID]
		o.C.PlaidTransactionLinks = &count
	}

	return nil
}

type transactionJoins[Q dialect.Joinable] struct {
	typ                   string
	PlaidTransactionLinks modAs[Q, plaidTransactionLinkColumns]
	Account               modAs[Q, accountColumns]
	Category              modAs[Q, categoryColumns]
}

func (j transactionJoins[Q]) aliasedAs(alias string) transactionJoins[Q] {
	return buildTransactionJoins[Q](buildTransactionColumns(alias), j.typ)
}

func buildTransactionJoins[Q dialect.Joinable](cols transactionColumns, typ string) transactionJoins[Q] {
	return transactionJoins[Q]{
		typ: typ,
		PlaidTransactionLinks: modAs[Q, plaidTransactionLinkColumns]{
			c: PlaidTransactionLinks.Columns,
			f: func(to plaidTransactionLinkColumns) bob.Mod[Q] {
				mods := make(mods.QueryMods[Q], 0, 1)

				{
					mods = append(mods, dialect.Join[Q](typ, PlaidTransactionLinks.NameExpr().As(to.Alias())).On(
						to.TransactionID.EQ(cols.ID),
					))
				}

				return mods
			},
		},
		Account: modAs[Q, accountColumns]{
			c: Accounts.Columns,
			f: func(to accountColumns) bob.Mod[Q] {
				mods := make(mods.QueryMods[Q], 0, 1)

				{
					mods = append(mods, dialect.Join[Q](typ, Accounts.NameExpr().As(to.Alias())).On(
						to.ID.EQ(cols.AccountID),
					))
				}

				return mods
			},
		},
		Category: modAs[Q, categoryColumns]{
			c: Categories.Columns,
			f: func(to categoryColumns) bob.Mod[Q] {
				mods := make(mods.QueryMods[Q], 0, 1)

				{
					mods = append(mods, dialect.Join[Q](typ, Categories.NameExpr().As(to.Alias())).On(
						to.ID.EQ(cols.CategoryID),
					))
				}

				return mods
			},
		},
	}
}
