// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package transaction

import (
	"context"

	"github.com/gofrs/uuid/v5"
	mock "github.com/stretchr/testify/mock"
)

// NewMockITransactionTable creates a new instance of MockITransactionTable. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockITransactionTable(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockITransactionTable {
	if helper, ok := t.(interface{ Helper() }); ok {
		helper.Helper()
	}

	mock := &MockITransactionTable{}
	mock.Mock.Test(t)

	t.Cleanup(func() {
		if helper, ok := t.(interface{ Helper() }); ok {
			helper.Helper()
		}
		mock.AssertExpectations(t)
	})

	return mock
}

// MockITransactionTable is an autogenerated mock type for the ITransactionTable type
type MockITransactionTable struct {
	mock.Mock
}

type MockITransactionTable_Expecter struct {
	mock *mock.Mock
}

func (_m *MockITransactionTable) EXPECT() *MockITransactionTable_Expecter {
	return &MockITransactionTable_Expecter{mock: &_m.Mock}
}

// FindByID provides a mock function for the type MockITransactionTable
func (_mock *MockITransactionTable) FindByID(ctx context.Context, id uuid.UUID) (*Transaction, error) {
	ret := _mock.Called(ctx, id)

	if len(ret) == 0 {
		panic("no return value specified for FindByID")
	}

	var r0 *Transaction
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, uuid.UUID) (*Transaction, error)); ok {
		return returnFunc(ctx, id)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, uuid.UUID) *Transaction); ok {
		r0 = returnFunc(ctx, id)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*Transaction)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, uuid.UUID) error); ok {
		r1 = returnFunc(ctx, id)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockITransactionTable_FindByID_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'FindByID'
type MockITransactionTable_FindByID_Call struct {
	*mock.Call
}

// FindByID is a helper method to define mock.On call
//   - ctx context.Context
//   - id uuid.UUID
func (_e *MockITransactionTable_Expecter) FindByID(ctx any, id any) *MockITransactionTable_FindByID_Call {
	return &MockITransactionTable_FindByID_Call{Call: _e.mock.On("FindByID", ctx, id)}
}

func (_c *MockITransactionTable_FindByID_Call) Run(run func(ctx context.Context, id uuid.UUID)) *MockITransactionTable_FindByID_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 uuid.UUID
		if args[1] != nil {
			arg1 = args[1].(uuid.UUID)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockITransactionTable_FindByID_Call) Return(transaction *Transaction, err error) *MockITransactionTable_FindByID_Call {
	_c.Call.Return(transaction, err)
	return _c
}

func (_c *MockITransactionTable_FindByID_Call) RunAndReturn(run func(ctx context.Context, id uuid.UUID) (*Transaction, error)) *MockITransactionTable_FindByID_Call {
	_c.Call.Return(run)
	return _c
}

// Insert provides a mock function for the type MockITransactionTable
func (_mock *MockITransactionTable) Insert(ctx context.Context, create *TransactionCreate) (uuid.UUID, error) {
	ret := _mock.Called(ctx, create)

	if len(ret) == 0 {
		panic("no return value specified for Insert")
	}

	var r0 uuid.UUID
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, *TransactionCreate) (uuid.UUID, error)); ok {
		return returnFunc(ctx, create)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, *TransactionCreate) uuid.UUID); ok {
		r0 = returnFunc(ctx, create)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(uuid.UUID)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, *TransactionCreate) error); ok {
		r1 = returnFunc(ctx, create)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockITransactionTable_Insert_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Insert'
type MockITransactionTable_Insert_Call struct {
	*mock.Call
}

// Insert is a helper method to define mock.On call
//   - ctx context.Context
//   - create *TransactionCreate
func (_e *MockITransactionTable_Expecter) Insert(ctx any, create any) *MockITransactionTable_Insert_Call {
	return &MockITransactionTable_Insert_Call{Call: _e.mock.On("Insert", ctx, create)}
}

func (_c *MockITransactionTable_Insert_Call) Run(run func(ctx context.Context, create *TransactionCreate)) *MockITransactionTable_Insert_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 *TransactionCreate
		if args[1] != nil {
			arg1 = args[1].(*TransactionCreate)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockITransactionTable_Insert_Call) Return(uUID uuid.UUID, err error) *MockITransactionTable_Insert_Call {
	_c.Call.Return(uUID, err)
	return _c
}

func (_c *MockITransactionTable_Insert_Call) RunAndReturn(run func(ctx context.Context, create *TransactionCreate) (uuid.UUID, error)) *MockITransactionTable_Insert_Call {
	_c.Call.Return(run)
	return _c
}

// List provides a mock function for the type MockITransactionTable
func (_mock *MockITransactionTable) List(ctx context.Context, filter *TransactionFilter) ([]*Transaction, error) {
	ret := _mock.Called(ctx, filter)

	if len(ret) == 0 {
		panic("no return value specified for List")
	}

	var r0 []*Transaction
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, *TransactionFilter) ([]*Transaction, error)); ok {
		return returnFunc(ctx, filter)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, *TransactionFilter) []*Transaction); ok {
		r0 = returnFunc(ctx, filter)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]*Transaction)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, *TransactionFilter) error); ok {
		r1 = returnFunc(ctx, filter)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockITransactionTable_List_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'List'
type MockITransactionTable_List_Call struct {
	*mock.Call
}

// List is a helper method to define mock.On call
//   - ctx context.Context
//   - filter *TransactionFilter
func (_e *MockITransactionTable_Expecter) List(ctx any, filter any) *MockITransactionTable_List_Call {
	return &MockITransactionTable_List_Call{Call: _e.mock.On("List", ctx, filter)}
}

func (_c *MockITransactionTable_List_Call) Run(run func(ctx context.Context, filter *TransactionFilter)) *MockITransactionTable_List_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 *TransactionFilter
		if args[1] != nil {
			arg1 = args[1].(*TransactionFilter)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockITransactionTable_List_Call) Return(transactions []*Transaction, err error) *MockITransactionTable_List_Call {
	_c.Call.Return(transactions, err)
	return _c
}

func (_c *MockITransactionTable_List_Call) RunAndReturn(run func(ctx context.Context, filter *TransactionFilter) ([]*Transaction, error)) *MockITransactionTable_List_Call {
	_c.Call.Return(run)
	return _c
}
