// Code generated by BobGen psql v0.42.0. DO NOT EDIT.
// This file is meant to be re-generated in place and/or deleted at any time.

package dbinfo

import "github.com/aarondl/opt/null"

var PlaidItems = Table[
	plaidItemColumns,
	plaidItemIndexes,
	plaidItemForeignKeys,
	plaidItemUniques,
	plaidItemChecks,
]{
	Schema: "",
	Name:   "plaid_items",
	Columns: plaidItemColumns{
		ID: column{
			Name:      "id",
			DBType:    "uuid",
			Default:   "uuid_generate_v4()",
			Comment:   "",
			Nullable:  false,
			Generated: false,
			AutoIncr:  false,
		},
		AccessToken: column{
			Name:      "access_token",
			DBType:    "text",
			Default:   "",
			Comment:   "",
			Nullable:  false,
			Generated: false,
			AutoIncr:  false,
		},
		PlaidItemID: column{
			Name:      "plaid_item_id",
			DBType:    "text",
			Default:   "",
			Comment:   "",
			Nullable:  false,
			Generated: false,
			AutoIncr:  false,
		},
		InstitutionID: column{
			Name:      "institution_id",
			DBType:    "text",
			Default:   "",
			Comment:   "",
			Nullable:  false,
			Generated: false,
			AutoIncr:  false,
		},
		InstitutionName: column{
			Name:      "institution_name",
			DBType:    "text",
			Default:   "",
			Comment:   "",
			Nullable:  false,
			Generated: false,
			AutoIncr:  false,
		},
		Cursor: column{
			Name:      "cursor",
			DBType:    "text",
			Default:   "''::text",
			Comment:   "",
			Nullable:  false,
			Generated: false,
			AutoIncr:  false,
		},
		CreatedAt: column{
			Name:      "created_at",
			DBType:    "timestamp with time zone",
			Default:   "now()",
			Comment:   "",
			Nullable:  false,
			Generated: false,
			AutoIncr:  false,
		},
	},
	Indexes: plaidItemIndexes{
		PlaidItemsPkey: index{
			Type: "btree",
			Name: "plaid_items_pkey",
			Columns: []indexColumn{
				{
					Name:         "id",
					Desc:         null.FromCond(false, true),
					IsExpression: false,
				},
			},
			Unique:        true,
			Comment:       "",
			NullsFirst:    []bool{false},
			NullsDistinct: false,
			Where:         "",
			Include:       []string{},
		},
		PlaidItemsPlaidItemIDKey: index{
			Type: "btree",
			Name: "plaid_items_plaid_item_id_key",
			Columns: []indexColumn{
				{
					Name:         "plaid_item_id",
					Desc:         null.FromCond(false, true),
					IsExpression: false,
				},
			},
			Unique:        true,
			Comment:       "",
			NullsFirst:    []bool{false},
			NullsDistinct: false,
			Where:         "",
			Include:       []string{},
		},
	},
	PrimaryKey: &constraint{
		Name:    "plaid_items_pkey",
		Columns: []string{"id"},
		Comment: "",
	},

	Uniques: plaidItemUniques{
		PlaidItemsPlaidItemIDKey: constraint{
			Name:    "plaid_items_plaid_item_id_key",
			Columns: []string{"plaid_item_id"},
			Comment: "",
		},
	},

	Comment: "",
}

type plaidItemColumns struct {
	ID              column
	AccessToken     column
	PlaidItemID     column
	InstitutionID   column
	InstitutionName column
	Cursor          column
	CreatedAt       column
}

func (c plaidItemColumns) AsSlice() []column {
	return []column{
		c.ID, c.AccessToken, c.PlaidItemID, c.InstitutionID, c.InstitutionName, c.Cursor, c.CreatedAt,
	}
}

type plaidItemIndexes struct {
	PlaidItemsPkey           index
	PlaidItemsPlaidItemIDKey index
}

func (i plaidItemIndexes) AsSlice() []index {
	return []index{
		i.PlaidItemsPkey, i.PlaidItemsPlaidItemIDKey,
	}
}

type plaidItemForeignKeys struct{}

func (f plaidItemForeignKeys) AsSlice() []foreignKey {
	return []foreignKey{}
}

type plaidItemUniques struct {
	PlaidItemsPlaidItemIDKey constraint
}

func (u plaidItemUniques) AsSlice() []constraint {
	return []constraint{
		u.PlaidItemsPlaidItemIDKey,
	}
}

type plaidItemChecks struct{}

func (c plaidItemChecks) AsSlice() []check {
	return []check{}
}
