// Code generated by BobGen psql v0.42.0. DO NOT EDIT.
// This file is meant to be re-generated in place and/or deleted at any time.

package dbinfo

import "github.com/aarondl/opt/null"

var PlaidAccountLinks = Table[
	plaidAccountLinkColumns,
	plaidAccountLinkIndexes,
	plaidAccountLinkForeignKeys,
	plaidAccountLinkUniques,
	plaidAccountLinkChecks,
]{
	Schema: "",
	Name:   "plaid_account_links",
	Columns: plaidAccountLinkColumns{
		PlaidAccountID: column{
			Name:      "plaid_account_id",
			DBType:    "text",
			Default:   "",
			Comment:   "",
			Nullable:  false,
			Generated: false,
			AutoIncr:  false,
		},
		AccountID: column{
			Name:      "account_id",
			DBType:    "uuid",
			Default:   "",
			Comment:   "",
			Nullable:  false,
			Generated: false,
			AutoIncr:  false,
		},
		PlaidItemID: column{
			Name:      "plaid_item_id",
			DBType:    "uuid",
			Default:   "",
			Comment:   "",
			Nullable:  false,
			Generated: false,
			AutoIncr:  false,
		},
	},
	Indexes: plaidAccountLinkIndexes{
		PlaidAccountLinksPkey: index{
			Type: "btree",
			Name: "plaid_account_links_pkey",
			Columns: []indexColumn{
				{
					Name:         "plaid_account_id",
					Desc:         null.FromCond(false, true),
					IsExpression: false,
				},
			},
			Unique:        true,
			Comment:       "",
			NullsFirst:    []bool{false},
			NullsDistinct: false,
			Where:         "",
			Include:       []string{},
		},
		IdxPlaidAccountLinksAccountID: index{
			Type: "btree",
			Name: "idx_plaid_account_links_account_id",
			Columns: []indexColumn{
				{
					Name:         "account_id",
					Desc:         null.FromCond(false, true),
					IsExpression: false,
				},
			},
			Unique:        false,
			Comment:       "",
			NullsFirst:    []bool{false},
			NullsDistinct: false,
			Where:         "",
			Include:       []string{},
		},
		IdxPlaidAccountLinksPlaidItemID: index{
			Type: "btree",
			Name: "idx_plaid_account_links_plaid_item_id",
			Columns: []indexColumn{
				{
					Name:         "plaid_item_id",
					Desc:         null.FromCond(false, true),
					IsExpression: false,
				},
			},
			Unique:        false,
			Comment:       "",
			NullsFirst:    []bool{false},
			NullsDistinct: false,
			Where:         "",
			Include:       []string{},
		},
	},
	PrimaryKey: &constraint{
		Name:    "plaid_account_links_pkey",
		Columns: []string{"plaid_account_id"},
		Comment: "",
	},
	ForeignKeys: plaidAccountLinkForeignKeys{
		PlaidAccountLinksPlaidAccountLinksAccountIDFkey: foreignKey{
			constraint: constraint{
				Name:    "plaid_account_links.plaid_account_links_account_id_fkey",
				Columns: []string{"account_id"},
				Comment: "",
			},
			ForeignTable:   "accounts",
			ForeignColumns: []string{"id"},
		},
		PlaidAccountLinksPlaidAccountLinksPlaidItemIDFkey: foreignKey{
			constraint: constraint{
				Name:    "plaid_account_links.plaid_account_links_plaid_item_id_fkey",
				Columns: []string{"plaid_item_id"},
				Comment: "",
			},
			ForeignTable:   "plaid_items",
			ForeignColumns: []string{"id"},
		},
	},

	Comment: "",
}

type plaidAccountLinkColumns struct {
	PlaidAccountID column
	AccountID      column
	PlaidItemID    column
}

func (c plaidAccountLinkColumns) AsSlice() []column {
	return []column{
		c.PlaidAccountID, c.AccountID, c.PlaidItemID,
	}
}

type plaidAccountLinkIndexes struct {
	PlaidAccountLinksPkey           index
	IdxPlaidAccountLinksAccountID   index
	IdxPlaidAccountLinksPlaidItemID index
}

func (i plaidAccountLinkIndexes) AsSlice() []index {
	return []index{
		i.PlaidAccountLinksPkey, i.IdxPlaidAccountLinksAccountID, i.IdxPlaidAccountLinksPlaidItemID,
	}
}

type plaidAccountLinkForeignKeys struct {
	PlaidAccountLinksPlaidAccountLinksAccountIDFkey   foreignKey
	PlaidAccountLinksPlaidAccountLinksPlaidItemIDFkey foreignKey
}

func (f plaidAccountLinkForeignKeys) AsSlice() []foreignKey {
	return []foreignKey{
		f.PlaidAccountLinksPlaidAccountLinksAccountIDFkey, f.PlaidAccountLinksPlaidAccountLinksPlaidItemIDFkey,
	}
}

type plaidAccountLinkUniques struct{}

func (u plaidAccountLinkUniques) AsSlice() []constraint {
	return []constraint{}
}

type plaidAccountLinkChecks struct{}

func (c plaidAccountLinkChecks) AsSlice() []check {
	return []check{}
}
