// Code generated by BobGen psql v0.42.0. DO NOT EDIT.
// This file is meant to be re-generated in place and/or deleted at any time.

package dbinfo

import "github.com/aarondl/opt/null"

var PlaidTransactionLinks = Table[
	plaidTransactionLinkColumns,
	plaidTransactionLinkIndexes,
	plaidTransactionLinkForeignKeys,
	plaidTransactionLinkUniques,
	plaidTransactionLinkChecks,
]{
	Schema: "",
	Name:   "plaid_transaction_links",
	Columns: plaidTransactionLinkColumns{
		PlaidTransactionID: column{
			Name:      "plaid_transaction_id",
			DBType:    "text",
			Default:   "",
			Comment:   "",
			Nullable:  false,
			Generated: false,
			AutoIncr:  false,
		},
		TransactionID: column{
			Name:      "transaction_id",
			DBType:    "uuid",
			Default:   "",
			Comment:   "",
			Nullable:  false,
			Generated: false,
			AutoIncr:  false,
		},
		PlaidAccountID: column{
			Name:      "plaid_account_id",
			DBType:    "text",
			Default:   "",
			Comment:   "",
			Nullable:  false,
			Generated: false,
			AutoIncr:  false,
		},
	},
	Indexes: plaidTransactionLinkIndexes{
		PlaidTransactionLinksPkey: index{
			Type: "btree",
			Name: "plaid_transaction_links_pkey",
			Columns: []indexColumn{
				{
					Name:         "plaid_transaction_id",
					Desc:         null.FromCond(false, true),
					IsExpression: false,
				},
			},
			Unique:        true,
			Comment:       "",
			NullsFirst:    []bool{false},
			NullsDistinct: false,
			Where:         "",
			Include:       []string{},
		},
		IdxPlaidTransactionLinksTransactionID: index{
			Type: "btree",
			Name: "idx_plaid_transaction_links_transaction_id",
			Columns: []indexColumn{
				{
					Name:         "transaction_id",
					Desc:         null.FromCond(false, true),
					IsExpression: false,
				},
			},
			Unique:        false,
			Comment:       "",
			NullsFirst:    []bool{false},
			NullsDistinct: false,
			Where:         "",
			Include:       []string{},
		},
	},
	PrimaryKey: &constraint{
		Name:    "plaid_transaction_links_pkey",
		Columns: []string{"plaid_transaction_id"},
		Comment: "",
	},
	ForeignKeys: plaidTransactionLinkForeignKeys{
		PlaidTransactionLinksPlaidTransactionLinksTransactionIDFkey: foreignKey{
			constraint: constraint{
				Name:    "plaid_transaction_links.plaid_transaction_links_transaction_id_fkey",
				Columns: []string{"transaction_id"},
				Comment: "",
			},
			ForeignTable:   "transactions",
			ForeignColumns: []string{"id"},
		},
	},

	Comment: "",
}

type plaidTransactionLinkColumns struct {
	PlaidTransactionID column
	TransactionID      column
	PlaidAccountID     column
}

func (c plaidTransactionLinkColumns) AsSlice() []column {
	return []column{
		c.PlaidTransactionID, c.TransactionID, c.PlaidAccountID,
	}
}

type plaidTransactionLinkIndexes struct {
	PlaidTransactionLinksPkey             index
	IdxPlaidTransactionLinksTransactionID index
}

func (i plaidTransactionLinkIndexes) AsSlice() []index {
	return []index{
		i.PlaidTransactionLinksPkey, i.IdxPlaidTransactionLinksTransactionID,
	}
}

type plaidTransactionLinkForeignKeys struct {
	PlaidTransactionLinksPlaidTransactionLinksTransactionIDFkey foreignKey
}

func (f plaidTransactionLinkForeignKeys) AsSlice() []foreignKey {
	return []foreignKey{
		f.PlaidTransactionLinksPlaidTransactionLinksTransactionIDFkey,
	}
}

type plaidTransactionLinkUniques struct{}

func (u plaidTransactionLinkUniques) AsSlice() []constraint {
	return []constraint{}
}

type plaidTransactionLinkChecks struct{}

func (c plaidTransactionLinkChecks) AsSlice() []check {
	return []check{}
}
