// Code generated by BobGen psql v0.42.0. DO NOT EDIT.
// This file is meant to be re-generated in place and/or deleted at any time.

package dbinfo

import "github.com/aarondl/opt/null"

var Syncs = Table[
	syncColumns,
	syncIndexes,
	syncForeignKeys,
	syncUniques,
	syncChecks,
]{
	Schema: "",
	Name:   "syncs",
	Columns: syncColumns{
		AccountID: column{
			Name:      "account_id",
			DBType:    "uuid",
			Default:   "",
			Comment:   "",
			Nullable:  false,
			Generated: false,
			AutoIncr:  false,
		},
		SyncType: column{
			Name:      "sync_type",
			DBType:    "smallint",
			Default:   "",
			Comment:   "",
			Nullable:  false,
			Generated: false,
			AutoIncr:  false,
		},
		CreatedAt: column{
			Name:      "created_at",
			DBType:    "timestamp with time zone",
			Default:   "now()",
			Comment:   "",
			Nullable:  false,
			Generated: false,
			AutoIncr:  false,
		},
		UpdatedAt: column{
			Name:      "updated_at",
			DBType:    "timestamp with time zone",
			Default:   "now()",
			Comment:   "",
			Nullable:  false,
			Generated: false,
			AutoIncr:  false,
		},
	},
	Indexes: syncIndexes{
		SyncsPkey: index{
			Type: "btree",
			Name: "syncs_pkey",
			Columns: []indexColumn{
				{
					Name:         "account_id",
					Desc:         null.FromCond(false, true),
					IsExpression: false,
				},
			},
			Unique:        true,
			Comment:       "",
			NullsFirst:    []bool{false},
			NullsDistinct: false,
			Where:         "",
			Include:       []string{},
		},
		IdxSyncsSyncType: index{
			Type: "btree",
			Name: "idx_syncs_sync_type",
			Columns: []indexColumn{
				{
					Name:         "sync_type",
					Desc:         null.FromCond(false, true),
					IsExpression: false,
				},
			},
			Unique:        false,
			Comment:       "",
			NullsFirst:    []bool{false},
			NullsDistinct: false,
			Where:         "",
			Include:       []string{},
		},
	},
	PrimaryKey: &constraint{
		Name:    "syncs_pkey",
		Columns: []string{"account_id"},
		Comment: "",
	},
	ForeignKeys: syncForeignKeys{
		SyncsSyncsAccountIDFkey: foreignKey{
			constraint: constraint{
				Name:    "syncs.syncs_account_id_fkey",
				Columns: []string{"account_id"},
				Comment: "",
			},
			ForeignTable:   "accounts",
			ForeignColumns: []string{"id"},
		},
	},

	Comment: "",
}

type syncColumns struct {
	AccountID column
	SyncType  column
	CreatedAt column
	UpdatedAt column
}

func (c syncColumns) AsSlice() []column {
	return []column{
		c.AccountID, c.SyncType, c.CreatedAt, c.UpdatedAt,
	}
}

type syncIndexes struct {
	SyncsPkey        index
	IdxSyncsSyncType index
}

func (i syncIndexes) AsSlice() []index {
	return []index{
		i.SyncsPkey, i.IdxSyncsSyncType,
	}
}

type syncForeignKeys struct {
	SyncsSyncsAccountIDFkey foreignKey
}

func (f syncForeignKeys) AsSlice() []foreignKey {
	return []foreignKey{
		f.SyncsSyncsAccountIDFkey,
	}
}

type syncUniques struct{}

func (u syncUniques) AsSlice() []constraint {
	return []constraint{}
}

type syncChecks struct{}

func (c syncChecks) AsSlice() []check {
	return []check{}
}
