// Code generated by BobGen psql v0.42.0. DO NOT EDIT.
// This file is meant to be re-generated in place and/or deleted at any time.

package dbinfo

import "github.com/aarondl/opt/null"

var Transactions = Table[
	transactionColumns,
	transactionIndexes,
	transactionForeignKeys,
	transactionUniques,
	transactionChecks,
]{
	Schema: "",
	Name:   "transactions",
	Columns: transactionColumns{
		ID: column{
			Name:      "id",
			DBType:    "uuid",
			Default:   "uuid_generate_v4()",
			Comment:   "",
			Nullable:  false,
			Generated: false,
			AutoIncr:  false,
		},
		AccountID: column{
			Name:      "account_id",
			DBType:    "uuid",
			Default:   "",
			Comment:   "",
			Nullable:  false,
			Generated: false,
			AutoIncr:  false,
		},
		CategoryID: column{
			Name:      "category_id",
			DBType:    "uuid",
			Default:   "",
			Comment:   "",
			Nullable:  false,
			Generated: false,
			AutoIncr:  false,
		},
		Amount: column{
			Name:      "amount",
			DBType:    "numeric",
			Default:   "",
			Comment:   "",
			Nullable:  false,
			Generated: false,
			AutoIncr:  false,
		},
		TransactionName: column{
			Name:      "transaction_name",
			DBType:    "text",
			Default:   "",
			Comment:   "",
			Nullable:  false,
			Generated: false,
			AutoIncr:  false,
		},
		TransactionDate: column{
			Name:      "transaction_date",
			DBType:    "timestamp with time zone",
			Default:   "now()",
			Comment:   "",
			Nullable:  false,
			Generated: false,
			AutoIncr:  false,
		},
		CreatedAt: column{
			Name:      "created_at",
			DBType:    "timestamp with time zone",
			Default:   "now()",
			Comment:   "",
			Nullable:  false,
			Generated: false,
			AutoIncr:  false,
		},
	},
	Indexes: transactionIndexes{
		TransactionsPkey: index{
			Type: "btree",
			Name: "transactions_pkey",
			Columns: []indexColumn{
				{
					Name:         "id",
					Desc:         null.FromCond(false, true),
					IsExpression: false,
				},
			},
			Unique:        true,
			Comment:       "",
			NullsFirst:    []bool{false},
			NullsDistinct: false,
			Where:         "",
			Include:       []string{},
		},
	},
	PrimaryKey: &constraint{
		Name:    "transactions_pkey",
		Columns: []string{"id"},
		Comment: "",
	},

	Comment: "",
}

type transactionColumns struct {
	ID              column
	AccountID       column
	CategoryID      column
	Amount          column
	TransactionName column
	TransactionDate column
	CreatedAt       column
}

func (c transactionColumns) AsSlice() []column {
	return []column{
		c.ID, c.AccountID, c.CategoryID, c.Amount, c.TransactionName, c.TransactionDate, c.CreatedAt,
	}
}

type transactionIndexes struct {
	TransactionsPkey index
}

func (i transactionIndexes) AsSlice() []index {
	return []index{
		i.TransactionsPkey,
	}
}

type transactionForeignKeys struct{}

func (f transactionForeignKeys) AsSlice() []foreignKey {
	return []foreignKey{}
}

type transactionUniques struct{}

func (u transactionUniques) AsSlice() []constraint {
	return []constraint{}
}

type transactionChecks struct{}

func (c transactionChecks) AsSlice() []check {
	return []check{}
}
