// Code generated by mockery v2.53.6. DO NOT EDIT.

package actions

import (
	context "context"

	storage "github.com/carson-networks/budget-server/internal/storage"
	mock "github.com/stretchr/testify/mock"
)

// MockIAction is an autogenerated mock type for the IAction type
type MockIAction struct {
	mock.Mock
}

type MockIAction_Expecter struct {
	mock *mock.Mock
}

func (_m *MockIAction) EXPECT() *MockIAction_Expecter {
	return &MockIAction_Expecter{mock: &_m.Mock}
}

// Perform provides a mock function with given fields: ctx, writer
func (_m *MockIAction) Perform(ctx context.Context, writer *storage.Writer) error {
	ret := _m.Called(ctx, writer)

	if len(ret) == 0 {
		panic("no return value specified for Perform")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, *storage.Writer) error); ok {
		r0 = rf(ctx, writer)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockIAction_Perform_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Perform'
type MockIAction_Perform_Call struct {
	*mock.Call
}

// Perform is a helper method to define mock.On call
//   - ctx context.Context
//   - writer *storage.Writer
func (_e *MockIAction_Expecter) Perform(ctx interface{}, writer interface{}) *MockIAction_Perform_Call {
	return &MockIAction_Perform_Call{Call: _e.mock.On("Perform", ctx, writer)}
}

func (_c *MockIAction_Perform_Call) Run(run func(ctx context.Context, writer *storage.Writer)) *MockIAction_Perform_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(*storage.Writer))
	})
	return _c
}

func (_c *MockIAction_Perform_Call) Return(_a0 error) *MockIAction_Perform_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockIAction_Perform_Call) RunAndReturn(run func(context.Context, *storage.Writer) error) *MockIAction_Perform_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockIAction creates a new instance of MockIAction. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockIAction(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockIAction {
	mock := &MockIAction{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
