name: Run Tests

on:
  push:

jobs:
  test:
    name: Run all Go tests
    runs-on: ubuntu-latest

    services:
      postgres:
        image: postgres:18
        env:
          POSTGRES_PASSWORD: postgres
        ports:
          - 5432:5432
        options: >-
          --health-cmd "pg_isready -U postgres"
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5

    env:
      BUDGET_TEST_DATABASE_URL: postgres://postgres:postgres@localhost:5432/postgres?sslmode=disable

    steps:
      - name: Check out the repo
        uses: actions/checkout@v6.0.2

      - name: Set up Go
        uses: actions/setup-go@v6.3.0
        with:
          go-version-file: .tool-versions
          cache: true

      - name: Run tests
        run: go test ./...
